;--------------------------------------------------------------------------------------------
;  Copyright (c) Fantaise Software. All rights reserved.
;  Dual licensed under the GPL and Fantaisie Software licenses.
;  See LICENSE and LICENSE-FANTAISIE in the project root for license information.
;--------------------------------------------------------------------------------------------



;
; Gather some build information to include in the IDE About box (for better debugging)
; Crossplatform
;

CompilerIf #PB_Compiler_OS = #PB_OS_Windows
  #Compiler    = "Compilers/PBCompiler.exe"
  #VersionFlag = "/VERSION"
  #Subversion  = "svn.exe"
CompilerElse
  #Compiler    = "/compilers/pbcompiler"
  #VersionFlag = "--version"
  #Subversion  = "svn"
CompilerEndIf

Global SvnBranch$, SvnRevision$

OpenConsole()

Procedure.s GetCompilerVersion()
  Version$ = ""

  Compiler$ = GetEnvironmentVariable("PUREBASIC_HOME")
  If Right(Compiler$, 1) <> "/"
    Compiler$ + "/"
  EndIf
  Compiler$ + #Compiler
  
  compiler = RunProgram(Compiler$, #VersionFlag, "", #PB_Program_Open|#PB_Program_Read|#PB_Program_Hide)
  If compiler
    Version$ = ReadProgramString(compiler)
    
    ; purge any remaining output
    While ProgramRunning(compiler)
      ReadProgramString(compiler)
    Wend
    CloseProgram(compiler)
  EndIf  
  
  ; Cut the copyright notice
  Version$ = StringField(Version$, 1, ")") + ")"

  ProcedureReturn Version$
EndProcedure

;- Start
;
BuildDirectory$ = ProgramParameter()
If Right(BuildDirectory$, 1) <> "/"
  BuildDirectory$ + "/"
EndIf

Compiler$ = GetCompilerVersion()
Version$ = Trim(StringField(Compiler$, 1, "(")) ; remove "(Windows - x86)"
Version$ = Right(Version$, Len(Version$) - 10)  ; remove "PureBasic "

;- Write output
;
If CreateFile(0, BuildDirectory$+"BuildInfo.pb")
  WriteStringN(0, "; Autogenerated by makebuildinfo.pb")
  WriteStringN(0, ";")
  
  WriteStringN(0, "#BUILDINFO_Branch   = "+Chr(34)+SvnBranch$+Chr(34))  
  WriteStringN(0, "#BUILDINFO_Revision = "+Chr(34)+SvnRevision$+Chr(34))
  WriteStringN(0, "#BUILDINFO_Compiler = "+Chr(34)+Compiler$+Chr(34)) 
  WriteStringN(0, "#BUILDINFO_Version  = "+Chr(34)+Version$+Chr(34))
  WriteStringN(0, "#BUILDINFO_User     = "+Chr(34)+UserName()+Chr(34))
  
  CloseFile(0)
  End 0 ; success
  
Else
  PrintN("makebuildinfo - could not write output file!")
  End 1 ; failure
  
EndIf


  
