Enumeration   ; GConvertError
  #G_CONVERT_ERROR_NO_CONVERSION
  #G_CONVERT_ERROR_ILLEGAL_SEQUENCE
  #G_CONVERT_ERROR_FAILED
  #G_CONVERT_ERROR_PARTIAL_INPUT
  #G_CONVERT_ERROR_BAD_URI
  #G_CONVERT_ERROR_NOT_ABSOLUTE_PATH
EndEnumeration

