Enumeration   ; GFileError
  #G_FILE_ERROR_EXIST
  #G_FILE_ERROR_ISDIR
  #G_FILE_ERROR_ACCES
  #G_FILE_ERROR_NAMETOOLONG
  #G_FILE_ERROR_NOENT
  #G_FILE_ERROR_NOTDIR
  #G_FILE_ERROR_NXIO
  #G_FILE_ERROR_NODEV
  #G_FILE_ERROR_ROFS
  #G_FILE_ERROR_TXTBSY
  #G_FILE_ERROR_FAULT
  #G_FILE_ERROR_LOOP
  #G_FILE_ERROR_NOSPC
  #G_FILE_ERROR_NOMEM
  #G_FILE_ERROR_MFILE
  #G_FILE_ERROR_NFILE
  #G_FILE_ERROR_BADF
  #G_FILE_ERROR_INVAL
  #G_FILE_ERROR_PIPE
  #G_FILE_ERROR_AGAIN
  #G_FILE_ERROR_INTR
  #G_FILE_ERROR_IO
  #G_FILE_ERROR_PERM
  #G_FILE_ERROR_NOSYS
  #G_FILE_ERROR_FAILED
EndEnumeration

Enumeration   ; GFileTest
  #G_FILE_TEST_IS_REGULAR = 1<<0
  #G_FILE_TEST_IS_SYMLINK = 1<<1
  #G_FILE_TEST_IS_DIR = 1<<2
  #G_FILE_TEST_IS_EXECUTABLE = 1<<3
  #G_FILE_TEST_EXISTS = 1<<4
EndEnumeration

