Enumeration   ; GKeyFileError
  #G_KEY_FILE_ERROR_UNKNOWN_ENCODING
  #G_KEY_FILE_ERROR_PARSE
  #G_KEY_FILE_ERROR_NOT_FOUND
  #G_KEY_FILE_ERROR_KEY_NOT_FOUND
  #G_KEY_FILE_ERROR_GROUP_NOT_FOUND
  #G_KEY_FILE_ERROR_INVALID_VALUE
EndEnumeration

Enumeration   ; GKeyFileFlags
  #G_KEY_FILE_NONE = 0
  #G_KEY_FILE_KEEP_COMMENTS = 1<<0
  #G_KEY_FILE_KEEP_TRANSLATIONS = 1<<1
EndEnumeration

