Enumeration   ; GUnicodeType
  #G_UNICODE_CONTROL
  #G_UNICODE_FORMAT
  #G_UNICODE_UNASSIGNED
  #G_UNICODE_PRIVATE_USE
  #G_UNICODE_SURROGATE
  #G_UNICODE_LOWERCASE_LETTER
  #G_UNICODE_MODIFIER_LETTER
  #G_UNICODE_OTHER_LETTER
  #G_UNICODE_TITLECASE_LETTER
  #G_UNICODE_UPPERCASE_LETTER
  #G_UNICODE_COMBINING_MARK
  #G_UNICODE_ENCLOSING_MARK
  #G_UNICODE_NON_SPACING_MARK
  #G_UNICODE_DECIMAL_NUMBER
  #G_UNICODE_LETTER_NUMBER
  #G_UNICODE_OTHER_NUMBER
  #G_UNICODE_CONNECT_PUNCTUATION
  #G_UNICODE_DASH_PUNCTUATION
  #G_UNICODE_CLOSE_PUNCTUATION
  #G_UNICODE_FINAL_PUNCTUATION
  #G_UNICODE_INITIAL_PUNCTUATION
  #G_UNICODE_OTHER_PUNCTUATION
  #G_UNICODE_OPEN_PUNCTUATION
  #G_UNICODE_CURRENCY_SYMBOL
  #G_UNICODE_MODIFIER_SYMBOL
  #G_UNICODE_MATH_SYMBOL
  #G_UNICODE_OTHER_SYMBOL
  #G_UNICODE_LINE_SEPARATOR
  #G_UNICODE_PARAGRAPH_SEPARATOR
  #G_UNICODE_SPACE_SEPARATOR
EndEnumeration

Enumeration   ; GUnicodeBreakType
  #G_UNICODE_BREAK_MANDATORY
  #G_UNICODE_BREAK_CARRIAGE_RETURN
  #G_UNICODE_BREAK_LINE_FEED
  #G_UNICODE_BREAK_COMBINING_MARK
  #G_UNICODE_BREAK_SURROGATE
  #G_UNICODE_BREAK_ZERO_WIDTH_SPACE
  #G_UNICODE_BREAK_INSEPARABLE
  #G_UNICODE_BREAK_NON_BREAKING_GLUE
  #G_UNICODE_BREAK_CONTINGENT
  #G_UNICODE_BREAK_SPACE
  #G_UNICODE_BREAK_AFTER
  #G_UNICODE_BREAK_BEFORE
  #G_UNICODE_BREAK_BEFORE_AND_AFTER
  #G_UNICODE_BREAK_HYPHEN
  #G_UNICODE_BREAK_NON_STARTER
  #G_UNICODE_BREAK_OPEN_PUNCTUATION
  #G_UNICODE_BREAK_CLOSE_PUNCTUATION
  #G_UNICODE_BREAK_QUOTATION
  #G_UNICODE_BREAK_EXCLAMATION
  #G_UNICODE_BREAK_IDEOGRAPHIC
  #G_UNICODE_BREAK_NUMERIC
  #G_UNICODE_BREAK_INFIX_SEPARATOR
  #G_UNICODE_BREAK_SYMBOL
  #G_UNICODE_BREAK_ALPHABETIC
  #G_UNICODE_BREAK_PREFIX
  #G_UNICODE_BREAK_POSTFIX
  #G_UNICODE_BREAK_COMPLEX_CONTEXT
  #G_UNICODE_BREAK_AMBIGUOUS
  #G_UNICODE_BREAK_UNKNOWN
  #G_UNICODE_BREAK_NEXT_LINE
  #G_UNICODE_BREAK_WORD_JOINER
EndEnumeration

Enumeration   ; GNormalizeMode
  #G_NORMALIZE_DEFAULT
  #G_NORMALIZE_NFD = #G_NORMALIZE_DEFAULT
  #G_NORMALIZE_DEFAULT_COMPOSE
  #G_NORMALIZE_NFC = #G_NORMALIZE_DEFAULT_COMPOSE
  #G_NORMALIZE_ALL
  #G_NORMALIZE_NFKD = #G_NORMALIZE_ALL
  #G_NORMALIZE_ALL_COMPOSE
  #G_NORMALIZE_NFKC = #G_NORMALIZE_ALL_COMPOSE
EndEnumeration

