#####################################################
#  PureBasic OpenSource Projects:                   #
#  https://github.com/fantaisie-software/purebasic  #
#####################################################

dist: trusty

git:
  depth: false

install:
  - npm install -g eclint

script:
  # =======================
  # Source Files Validation
  # =======================
  # 1. Check PureBasic sources for IDE Settings.
  # 2. Validate EditorConfig code styles via EClint:
  #      https://editorconfig.org
  #      https://www.npmjs.com/package/eclint
  - bash ./validate.sh
