Enumeration   ; GtkDebugFlag
  #GTK_DEBUG_MISC = 1<<0
  #GTK_DEBUG_PLUGSOCKET = 1<<1
  #GTK_DEBUG_TEXT = 1<<2
  #GTK_DEBUG_TREE = 1<<3
  #GTK_DEBUG_UPDATES = 1<<4
  #GTK_DEBUG_KEYBINDINGS = 1<<5
  #GTK_DEBUG_MULTIHEAD = 1<<6
EndEnumeration

