Enumeration   ; GtkFileChooserAction
  #GTK_FILE_CHOOSER_ACTION_OPEN
  #GTK_FILE_CHOOSER_ACTION_SAVE
  #GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER
  #GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER
EndEnumeration

Enumeration   ; GtkFileChooserError
  #GTK_FILE_CHOOSER_ERROR_NONEXISTENT
  #GTK_FILE_CHOOSER_ERROR_BAD_FILENAME
EndEnumeration

