#GTK_PRIORITY_RESIZE = (#G_PRIORITY_HIGH_IDLE+10)
#GTK_PRIORITY_REDRAW = (#G_PRIORITY_HIGH_IDLE+20)
#GTK_PRIORITY_HIGH = #G_PRIORITY_HIGH
#GTK_PRIORITY_INTERNAL = #GTK_PRIORITY_REDRAW
#GTK_PRIORITY_DEFAULT = #G_PRIORITY_DEFAULT_IDLE
#GTK_PRIORITY_LOW = #G_PRIORITY_LOW
