Enumeration   ; GtkPrivateFlags
  #PRIVATE_GTK_USER_STYLE = 1<<0
  #PRIVATE_GTK_RESIZE_PENDING = 1<<2
  #PRIVATE_GTK_LEAVE_PENDING = 1<<4
  #PRIVATE_GTK_HAS_SHAPE_MASK = 1<<5
  #PRIVATE_GTK_IN_REPARENT = 1<<6
  #PRIVATE_GTK_DIRECTION_SET = 1<<7
  #PRIVATE_GTK_DIRECTION_LTR = 1<<8
  #PRIVATE_GTK_ANCHORED = 1<<9
  #PRIVATE_GTK_CHILD_VISIBLE = 1<<10
  #PRIVATE_GTK_REDRAW_ON_ALLOC = 1<<11
  #PRIVATE_GTK_ALLOC_NEEDED = 1<<12
  #PRIVATE_GTK_REQUEST_NEEDED = 1<<13
EndEnumeration

