Structure GtkStyle
  parent_instance.GObject
  fg.GdkColor[5]
  bg.GdkColor[5]
  light.GdkColor[5]
  dark.GdkColor[5]
  mid.GdkColor[5]
  text.GdkColor[5]
  base.GdkColor[5]
  text_aa.GdkColor[5]
  black.GdkColor
  white.GdkColor
 *font_desc.PangoFontDescription
  xthickness.l
  ythickness.l
 *fg_gc.GdkGC[5]
 *bg_gc.GdkGC[5]
 *light_gc.GdkGC[5]
 *dark_gc.GdkGC[5]
 *mid_gc.GdkGC[5]
 *text_gc.GdkGC[5]
 *base_gc.GdkGC[5]
 *text_aa_gc.GdkGC[5]
 *black_gc.GdkGC
 *white_gc.GdkGC
 *bg_pixmap.GdkPixmap[5]
  attach_count.l
  depth.l
 *colormap.GdkColormap
 *private_font.GdkFont
 *private_font_desc.PangoFontDescription
 *rc_style.GtkRcStyle
 *styles.GSList
 *property_cache.GArray
 *icon_factories.GSList
EndStructure

Structure GtkStyleClass
  parent_class.GObjectClass
 *realize
 *unrealize
 *copy
 *clone
 *init_from_rc
 *set_background
 *render_icon
 *draw_hline
 *draw_vline
 *draw_shadow
 *draw_polygon
 *draw_arrow
 *draw_diamond
 *draw_string
 *draw_box
 *draw_flat_box
 *draw_check
 *draw_option
 *draw_tab
 *draw_shadow_gap
 *draw_box_gap
 *draw_extension
 *draw_focus
 *draw_slider
 *draw_handle
 *draw_expander
 *draw_layout
 *draw_resize_grip
 *_gtk_reserved
 *_gtk_reserved2
 *_gtk_reserved3
 *_gtk_reserved4
 *_gtk_reserved5
 *_gtk_reserved6
 *_gtk_reserved7
 *_gtk_reserved8
 *_gtk_reserved9
 *_gtk_reserved10
 *_gtk_reserved11
 *_gtk_reserved12
EndStructure

Structure GtkBorder
  left.l
  right.l
  top.l
  bottom.l
EndStructure

