XIncludeFile "common.pbi"

ImportC "-lpthread"
  ApiC(pthread_attr_destroy, (arg1))
  ApiC(pthread_attr_getdetachstate, (arg1, arg2))
  ApiC(pthread_attr_getguardsize, (arg1, arg2))
  ApiC(pthread_attr_getinheritsched, (arg1, arg2))
  ApiC(pthread_attr_getschedparam, (arg1, arg2))
  ApiC(pthread_attr_getschedpolicy, (arg1, arg2))
  ApiC(pthread_attr_getscope, (arg1, arg2))
  ApiC(pthread_attr_getstackaddr, (arg1, arg2))
  ApiC(pthread_attr_getstacksize, (arg1, arg2))
  ApiC(pthread_attr_init, (arg1))
  ApiC(pthread_attr_setdetachstate, (arg1, arg2))
  ApiC(pthread_attr_setguardsize, (arg1, arg2))
  ApiC(pthread_attr_setinheritsched, (arg1, arg2))
  ApiC(pthread_attr_setschedparam, (arg1, arg2))
  ApiC(pthread_attr_setschedpolicy, (arg1, arg2))
  ApiC(pthread_attr_setscope, (arg1, arg2))
  ApiC(pthread_attr_setstackaddr, (arg1, arg2))
  ApiC(pthread_attr_setstacksize, (arg1, arg2))
  ApiC(pthread_cancel, (arg1))
  ApiC(pthread_cleanup_pop, (arg1))
  ApiC(pthread_cleanup_push, (arg1))
  ApiC(pthread_cond_broadcast, (arg1))
  ApiC(pthread_cond_destroy, (arg1))
  ApiC(pthread_cond_init, (arg1, arg2))
  ApiC(pthread_cond_signal, (arg1, arg2))
  ApiC(pthread_cond_timedwait, (arg1, arg2, arg3))
  ApiC(pthread_cond_wait, (arg1, arg2))
  ApiC(pthread_condattr_destroy, (arg1))
  ApiC(pthread_condattr_getpshared, (arg1, arg2))
  ApiC(pthread_condattr_init, (arg1))
  ApiC(pthread_condattr_setpshared, (arg1, arg2))
  ApiC(pthread_create, (arg1, arg2, arg3, arg4))
  ApiC(pthread_detach, (arg1))
  ApiC(pthread_equal, (arg1, arg2))
  ApiC(pthread_exit, (arg1))
  ApiC(pthread_getconcurrency, ())
  ApiC(pthread_getschedparam, (arg1, arg2))
  ApiC(pthread_getspecific, (arg1))
  ApiC(pthread_join, (arg1, arg2))
  ApiC(pthread_key_create, (arg1, arg2))
  ApiC(pthread_key_delete, (arg1))
  ApiC(pthread_mutex_destroy, (arg1))
  ApiC(pthread_mutex_getprioceiling, (arg1, arg2))
  ApiC(pthread_mutex_init, (arg1, arg2))
  ApiC(pthread_mutex_lock, (arg1))
  ApiC(pthread_mutex_setprioceiling, (arg1, arg2, arg3))
  ApiC(pthread_mutex_trylock, (arg1))
  ApiC(pthread_mutex_unlock, (arg1))
  ApiC(pthread_mutexattr_destroy, (arg1))
  ApiC(pthread_mutexattr_getprioceiling, (arg1, arg2))
  ApiC(pthread_mutexattr_getprotocol, (arg1, arg2))
  ApiC(pthread_mutexattr_getpshared, (arg1, arg2))
  ApiC(pthread_mutexattr_gettype, (arg1, arg2))
  ApiC(pthread_mutexattr_init, (arg1))
  ApiC(pthread_mutexattr_setprioceiling, (arg1, arg2))
  ApiC(pthread_mutexattr_setprotocol, (arg1, arg2))
  ApiC(pthread_mutexattr_setpshared, (arg1, arg2))
  ApiC(pthread_mutexattr_settype, (arg1, arg2))
  ApiC(pthread_once, (arg1, arg2))
  ApiC(pthread_rwlock_destroy, (arg1))
  ApiC(pthread_rwlock_init, (arg1, arg2))
  ApiC(pthread_rwlock_rdlock, (arg1))
  ApiC(pthread_rwlock_tryrdlock, (arg1))
  ApiC(pthread_rwlock_trywrlock, (arg1))
  ApiC(pthread_rwlock_unlock, (arg1))
  ApiC(pthread_rwlock_wrlock, (arg1))
  ApiC(pthread_rwlockattr_destroy, (arg1))
  ApiC(pthread_rwlockattr_getpshared, (arg1, arg2))
  ApiC(pthread_rwlockattr_init, (arg1))
  ApiC(pthread_rwlockattr_setpshared, (arg1, arg2))
  ApiC(pthread_self, ())
  ApiC(pthread_setcancelstate, (arg1, arg2))
  ApiC(pthread_setcanceltype, (arg1, arg2))
  ApiC(pthread_setconcurrency, (arg1))
  ApiC(pthread_setschedparam, (arg1, arg2, arg3))
  ApiC(pthread_setspecific, (arg1, arg2))
  ApiC(pthread_testcancel, ())
EndImport
