XIncludeFile "common.pbi"

ImportC "-lSDL -lpthread"
  ApiC(SDL_AddTimer, (arg1, arg2, arg3))
  ApiC(SDL_AllocRW, ())
  ApiC(SDL_AudioDriverName, (arg1, arg2))
  ApiC(SDL_AudioInit, (arg1))
  ApiC(SDL_AudioQuit, ())
  ApiC(SDL_BuildAudioCVT, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(SDL_CDClose, (arg1))
  ApiC(SDL_CDEject, (arg1))
  ApiC(SDL_CDName, (arg1))
  ApiC(SDL_CDNumDrives, ())
  ApiC(SDL_CDOpen, (arg1))
  ApiC(SDL_CDPause, (arg1))
  ApiC(SDL_CDPlay, (arg1, arg2, arg3))
  ApiC(SDL_CDPlayTracks, (arg1, arg2, arg3, arg4, arg5))
  ApiC(SDL_CDResume, (arg1))
  ApiC(SDL_CDStatus, (arg1))
  ApiC(SDL_CDStop, (arg1))
  ApiC(SDL_ClearError, ())
  ApiC(SDL_CloseAudio, ())
  ApiC(SDL_CondBroadcast, (arg1))
  ApiC(SDL_CondSignal, (arg1))
  ApiC(SDL_CondWait, (arg1, arg2))
  ApiC(SDL_CondWaitTimeout, (arg1, arg2, arg3))
  ApiC(SDL_ConvertAudio, (arg1))
  ApiC(SDL_ConvertSurface, (arg1, arg2, arg3))
  ApiC(SDL_CreateCond, ())
  ApiC(SDL_CreateCursor, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(SDL_CreateMutex, ())
  ApiC(SDL_CreateRGBSurface, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(SDL_CreateRGBSurfaceFrom, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(SDL_CreateSemaphore, (arg1))
  ApiC(SDL_CreateThread, (arg1, arg2))
  ApiC(SDL_CreateYUVOverlay, (arg1, arg2, arg3, arg4))
  ApiC(SDL_Delay, (arg1))
  ApiC(SDL_DestroyCond, (arg1))
  ApiC(SDL_DestroyMutex, (arg1))
  ApiC(SDL_DestroySemaphore, (arg1))
  ApiC(SDL_DisplayFormat, (arg1))
  ApiC(SDL_DisplayFormatAlpha, (arg1))
  ApiC(SDL_DisplayYUVOverlay, (arg1, arg2))
  ApiC(SDL_EnableKeyRepeat, (arg1, arg2))
  ApiC(SDL_EnableUNICODE, (arg1))
  ApiC(SDL_EventState, (arg1, arg2))
  ApiC(SDL_FillRect, (arg1, arg2, arg3))
  ApiC(SDL_Flip, (arg1))
  ApiC(SDL_FreeCursor, (arg1))
  ApiC(SDL_FreeRW, (arg1))
  ApiC(SDL_FreeSurface, (arg1))
  ApiC(SDL_FreeWAV, (arg1))
  ApiC(SDL_FreeYUVOverlay, (arg1))
  ApiC(SDL_GetAppState, ())
  ApiC(SDL_GetAudioStatus, ())
  ApiC(SDL_GetClipRect, (arg1, arg2))
  ApiC(SDL_GetCursor, ())
  ApiC(SDL_getenv, (arg1))
  ApiC(SDL_GetError, ())
  ApiC(SDL_GetEventFilter, ())
  ApiC(SDL_GetGammaRamp, (arg1, arg2, arg3))
  ApiC(SDL_GetKeyName, (arg1))
  ApiC(SDL_GetKeyState, (arg1))
  ApiC(SDL_GetModState, ())
  ApiC(SDL_GetMouseState, (arg1, arg2))
  ApiC(SDL_GetRelativeMouseState, (arg1, arg2))
  ApiC(SDL_GetRGB, (arg1, arg2, arg3, arg4, arg5))
  ApiC(SDL_GetRGBA, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(SDL_GetThreadID, (arg1))
  ApiC(SDL_GetTicks, ())
  ApiC(SDL_GetVideoInfo, ())
  ApiC(SDL_GetVideoSurface, ())
  ApiC(SDL_GetWMInfo, (arg1))
  ApiC(SDL_GL_GetAttribute, (arg1, arg2))
  ApiC(SDL_GL_GetProcAddress, (arg1))
  ApiC(SDL_GL_LoadLibrary, (arg1))
  ApiC(SDL_GL_Lock, ())
  ApiC(SDL_GL_SetAttribute, (arg1, arg2))
  ApiC(SDL_GL_SwapBuffers, ())
  ApiC(SDL_GL_Unlock, ())
  ApiC(SDL_GL_UpdateRects, (arg1, arg2))
  ApiC(SDL_Init, (arg1))
  ApiC(SDL_InitQuickDraw, (arg1))
  ApiC(SDL_InitSubSystem, (arg1))
  ApiC(SDL_JoystickClose, (arg1))
  ApiC(SDL_JoystickEventState, (arg1))
  ApiC(SDL_JoystickGetAxis, (arg1, arg2))
  ApiC(SDL_JoystickGetBall, (arg1, arg2, arg3, arg4))
  ApiC(SDL_JoystickGetButton, (arg1, arg2))
  ApiC(SDL_JoystickGetHat, (arg1, arg2))
  ApiC(SDL_JoystickIndex, (arg1))
  ApiC(SDL_JoystickName, (arg1))
  ApiC(SDL_JoystickNumAxes, (arg1))
  ApiC(SDL_JoystickNumBalls, (arg1))
  ApiC(SDL_JoystickNumButtons, (arg1))
  ApiC(SDL_JoystickNumHats, (arg1))
  ApiC(SDL_JoystickOpen, (arg1))
  ApiC(SDL_JoystickOpened, (arg1))
  ApiC(SDL_JoystickUpdate, ())
  ApiC(SDL_KillThread, (arg1))
  ApiC(SDL_Linked_Version, ())
  ApiC(SDL_ListModes, (arg1, arg2))
  ApiC(SDL_LoadBMP_RW, (arg1, arg2))
  ApiC(SDL_LoadFunction, (arg1, arg2))
  ApiC(SDL_LoadObject, (arg1))
  ApiC(SDL_LoadWAV_RW, (arg1, arg2, arg3, arg4, arg5))
  ApiC(SDL_LockAudio, ())
  ApiC(SDL_LockSurface, (arg1))
  ApiC(SDL_LockYUVOverlay, (arg1))
  ApiC(SDL_LowerBlit, (arg1, arg2, arg3, arg4))
  ApiC(SDL_MapRGB, (arg1, arg2, arg3, arg4))
  ApiC(SDL_MapRGBA, (arg1, arg2, arg3, arg4, arg5))
  ApiC(SDL_MixAudio, (arg1, arg2, arg3, arg4))
  ApiC(SDL_mutexP, (arg1))
  ApiC(SDL_mutexV, (arg1))
  ApiC(SDL_NumJoysticks, ())
  ApiC(SDL_OpenAudio, (arg1, arg2))
  ApiC(SDL_PauseAudio, (arg1))
  ApiC(SDL_PeepEvents, (arg1, arg2, arg3, arg4))
  ApiC(SDL_PollEvent, (arg1))
  ApiC(SDL_PumpEvents, ())
  ApiC(SDL_PushEvent, (arg1))
  ApiC(SDL_putenv, (arg1))
  ApiC(SDL_Quit, ())
  ApiC(SDL_QuitSubSystem, (arg1))
  ApiC(SDL_ReadBE16, (arg1))
  ApiC(SDL_ReadBE32, (arg1))
  ApiC(SDL_ReadBE64, (arg1))
  ApiC(SDL_ReadLE16, (arg1))
  ApiC(SDL_ReadLE32, (arg1))
  ApiC(SDL_ReadLE64, (arg1))
  ApiC(SDL_RegisterApp, (arg1, arg2, arg3))
  ApiC(SDL_RemoveTimer, (arg1))
  ApiC(SDL_RWFromFile, (arg1, arg2))
  ApiC(SDL_RWFromFP, (arg1, arg2))
  ApiC(SDL_RWFromMem, (arg1, arg2))
  ApiC(SDL_SaveBMP_RW, (arg1, arg2, arg3))
  ApiC(SDL_SemPost, (arg1))
  ApiC(SDL_SemTryWait, (arg1))
  ApiC(SDL_SemValue, (arg1))
  ApiC(SDL_SemWait, (arg1))
  ApiC(SDL_SemWaitTimeout, (arg1, arg2))
  ApiC(SDL_SetAlpha, (arg1, arg2, arg3))
  ApiC(SDL_SetClipRect, (arg1, arg2))
  ApiC(SDL_SetColorKey, (arg1, arg2, arg3))
  ApiC(SDL_SetColors, (arg1, arg2, arg3, arg4))
  ApiC(SDL_SetCursor, (arg1))
  ApiC(SDL_SetError, (arg1, arg2))
  ApiC(SDL_SetEventFilter, (arg1))
  ApiC(SDL_SetGamma, (arg1, arg2, arg3))
  ApiC(SDL_SetGammaRamp, (arg1, arg2, arg3))
  ApiC(SDL_SetModState, (arg1))
  ApiC(SDL_SetModuleHandle, (arg1))
  ApiC(SDL_SetPalette, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(SDL_SetTimer, (arg1, arg2))
  ApiC(SDL_SetVideoMode, (arg1, arg2, arg3, arg4))
  ApiC(SDL_ShowCursor, (arg1))
  ApiC(SDL_SoftStretch, (arg1, arg2, arg3, arg4))
  ApiC(SDL_ThreadID, ())
  ApiC(SDL_UnloadObject, (arg1))
  ApiC(SDL_UnlockAudio, ())
  ApiC(SDL_UnlockSurface, (arg1))
  ApiC(SDL_UnlockYUVOverlay, (arg1))
  ApiC(SDL_UpdateRect, (arg1, arg2, arg3, arg4, arg5))
  ApiC(SDL_UpdateRects, (arg1, arg2, arg3))
  ApiC(SDL_UpperBlit, (arg1, arg2, arg3, arg4))
  ApiC(SDL_VideoDriverName, (arg1, arg2))
  ApiC(SDL_VideoInit, (arg1, arg2))
  ApiC(SDL_VideoModeOK, (arg1, arg2, arg3, arg4))
  ApiC(SDL_VideoQuit, ())
  ApiC(SDL_WaitEvent, (arg1))
  ApiC(SDL_WaitThread, (arg1, arg2))
  ApiC(SDL_WarpMouse, (arg1, arg2))
  ApiC(SDL_WasInit, (arg1))
  ApiC(SDL_WM_GetCaption, (arg1, arg2))
  ApiC(SDL_WM_GrabInput, (arg1))
  ApiC(SDL_WM_IconifyWindow, ())
  ApiC(SDL_WM_SetCaption, (arg1, arg2))
  ApiC(SDL_WM_SetIcon, (arg1, arg2))
  ApiC(SDL_WM_ToggleFullScreen, (arg1))
  ApiC(SDL_WriteBE16, (arg1, arg2))
  ApiC(SDL_WriteBE32, (arg1, arg2))
  ApiC(SDL_WriteBE64, (arg1, arg2))
  ApiC(SDL_WriteLE16, (arg1, arg2))
  ApiC(SDL_WriteLE32, (arg1, arg2))
  ApiC(SDL_WriteLE64, (arg1, arg2))
EndImport
