#
# Makefile for all included targets
# 

doc:
	"$(PUREBASIC_HOME)/SDK/DocMaker/DocMaker.exe" /LANGUAGE German /DOCUMENTATIONPATH "$(PB_SVN)/Documentation" /OUTPUTPATH "$(PB_SVN)/Build/Documentation"
	explorer "$(PB_SVN)\Build\Documentation"