
; IDAViewSite interface definition
;
Interface IDAViewSite
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  SetStatusText(a.l)
EndInterface

; IDAView interface definition
;
Interface IDAView
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_SimulationTime(a.l)
  Tick(a.l, b.l)
  Render()
  AddBvrToRun(a.l, b.l)
  RemoveRunningBvr(a.l)
  StartModel(a.l, b.l, c.l)
  StopModel()
  get_Window(a.l)
  put_Window(a.l)
  get_IDirectDrawSurface(a.l)
  put_IDirectDrawSurface(a.l)
  get_DC(a.l)
  put_DC(a.l)
  get_CompositeDirectlyToTarget(a.l)
  put_CompositeDirectlyToTarget(a.l)
  SetViewport(a.l, b.l, c.l, d.l)
  SetClipRect(a.l, b.l, c.l, d.l)
  RePaint(a.l, b.l, c.l, d.l)
  PaletteChanged(a.l)
  get_Site(a.l)
  put_Site(a.l)
  put_ClientSite(a.l)
  get_ClientSite(a.l)
  OnMouseMove(a.l, b.l, c.l, d.l)
  OnMouseButton(a.l, b.l, c.l, d.l, e.l, f.l)
  OnKey(a.l, b.l, c.l, d.l)
  OnFocus(a.l)
  get_Preferences(a.l)
  QueryHitPoint(a.l, b.l, c.l, d.l, e.l)
EndInterface

; IDABehavior interface definition
;
Interface IDABehavior
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
EndInterface

; IDANumber interface definition
;
Interface IDANumber
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Extract(a.l)
  AnimateProperty(a.l, b.l, c.l, d.l, e.l)
  ToStringAnim(a.l, b.l)
  ToString(a.l, b.l)
EndInterface

; IDABvrHook interface definition
;
Interface IDABvrHook
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Notify(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
EndInterface

; IDADrawingSurface interface definition
;
Interface IDADrawingSurface
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Image(a.l)
  put_LineStyle(a.l)
  put_BorderStyle(a.l)
  put_FontStyle(a.l)
  put_ClipMatte(a.l)
  put_MouseEventsEnabled(a.l)
  put_HatchFillTransparent(a.l)
  get_LocalContextImage(a.l)
  Reset()
  Clear()
  SaveGraphicsState()
  RestoreGraphicsState()
  Opacity(a.l)
  OpacityAnim(a.l)
  Crop(a.l, b.l, c.l, d.l)
  CropPoints(a.l, b.l)
  Transform(a.l)
  LineColor(a.l)
  LineWidth(a.l)
  LineDashStyle(a.l)
  LineEndStyle(a.l)
  LineJoinStyle(a.l)
  BorderColor(a.l)
  BorderWidth(a.l)
  BorderDashStyle(a.l)
  BorderEndStyle(a.l)
  BorderJoinStyle(a.l)
  Font(a.l, b.l, c.l, d.l, e.l, f.l)
  TextureFill(a.l, b.l, c.l)
  ImageFill(a.l, b.l, c.l)
  FillTexture(a.l)
  FillImage(a.l)
  FillStyle(a.l)
  FillColor(a.l)
  SecondaryFillColor(a.l)
  GradientShape(a.l)
  GradientExtent(a.l, b.l, c.l, d.l)
  GradientExtentPoints(a.l, b.l)
  GradientRolloffPower(a.l)
  GradientRolloffPowerAnim(a.l)
  FixedFillScale()
  HorizontalFillScale()
  VerticalFillScale()
  AutoSizeFillScale()
  PolylineEx(a.l, b.l)
  Polyline(a.l)
  PolygonEx(a.l, b.l)
  Polygon(a.l)
  LinePoints(a.l, b.l)
  Line(a.l, b.l, c.l, d.l)
  ArcRadians(a.l, b.l, c.l, d.l, e.l, f.l)
  ArcDegrees(a.l, b.l, c.l, d.l, e.l, f.l)
  Oval(a.l, b.l, c.l, d.l)
  Rect(a.l, b.l, c.l, d.l)
  RoundRect(a.l, b.l, c.l, d.l, e.l, f.l)
  PieRadians(a.l, b.l, c.l, d.l, e.l, f.l)
  PieDegrees(a.l, b.l, c.l, d.l, e.l, f.l)
  Text(a.l, b.l, c.l)
  TextPoint(a.l, b.l)
  FillPath(a.l)
  DrawPath(a.l)
  OverlayImage(a.l)
EndInterface

; IDAPickableResult interface definition
;
Interface IDAPickableResult
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Image(a.l)
  get_Geometry(a.l)
  get_PickEvent(a.l)
EndInterface

; IDAEvent interface definition
;
Interface IDAEvent
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Notify(a.l, b.l)
  Snapshot(a.l, b.l)
  AttachData(a.l, b.l)
  ScriptCallback(a.l, b.l, c.l)
EndInterface

; IDA2Behavior interface definition
;
Interface IDA2Behavior
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  SwitchToEx(a.l, b.l)
  ApplyPreference(a.l, b.l, c.l)
  ExtendedAttrib(a.l, b.l, c.l)
EndInterface

; IDAImport interface definition
;
Interface IDAImport
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  ImportStatus(a.l)
  ImportCancel()
  get_ImportPriority(a.l)
  put_ImportPriority(a.l)
EndInterface

; IDAModifiableBehavior interface definition
;
Interface IDAModifiableBehavior
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  get_CurrentBehavior(a.l)
  put_CurrentBehavior(a.l)
  SwitchToEx(a.l, b.l)
EndInterface

; IDAUntilNotifier interface definition
;
Interface IDAUntilNotifier
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  Notify(a.l, b.l, c.l, d.l)
EndInterface

; IDABoolean interface definition
;
Interface IDABoolean
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Extract(a.l)
EndInterface

; IDACamera interface definition
;
Interface IDACamera
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Transform(a.l, b.l)
  Depth(a.l, b.l)
  DepthAnim(a.l, b.l)
  DepthResolution(a.l, b.l)
  DepthResolutionAnim(a.l, b.l)
EndInterface

; IDAColor interface definition
;
Interface IDAColor
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  get_Red(a.l)
  get_Green(a.l)
  get_Blue(a.l)
  get_Hue(a.l)
  get_Saturation(a.l)
  get_Lightness(a.l)
EndInterface

; IDAGeometry interface definition
;
Interface IDAGeometry
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  RenderSound(a.l, b.l)
  Pickable(a.l)
  PickableOccluded(a.l)
  Undetectable(a.l)
  EmissiveColor(a.l, b.l)
  DiffuseColor(a.l, b.l)
  SpecularColor(a.l, b.l)
  SpecularExponent(a.l, b.l)
  SpecularExponentAnim(a.l, b.l)
  Texture(a.l, b.l)
  Opacity(a.l, b.l)
  OpacityAnim(a.l, b.l)
  Transform(a.l, b.l)
  get_BoundingBox(a.l)
  Render(a.l, b.l)
  LightColor(a.l, b.l)
  LightAttenuationAnim(a.l, b.l, c.l, d.l)
  LightAttenuation(a.l, b.l, c.l, d.l)
EndInterface

; IDAImage interface definition
;
Interface IDAImage
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Pickable(a.l)
  PickableOccluded(a.l)
  ApplyBitmapEffect(a.l, b.l, c.l)
  get_BoundingBox(a.l)
  Crop(a.l, b.l, c.l)
  Transform(a.l, b.l)
  OpacityAnim(a.l, b.l)
  Opacity(a.l, b.l)
  Undetectable(a.l)
  Tile(a.l)
  Clip(a.l, b.l)
  MapToUnitSquare(a.l)
  ClipPolygonImageEx(a.l, b.l, c.l)
  ClipPolygonImage(a.l, b.l)
EndInterface

; IDAMatte interface definition
;
Interface IDAMatte
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Transform(a.l, b.l)
EndInterface

; IDAMicrophone interface definition
;
Interface IDAMicrophone
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Transform(a.l, b.l)
EndInterface

; IDAMontage interface definition
;
Interface IDAMontage
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Render(a.l)
EndInterface

; IDAPath2 interface definition
;
Interface IDAPath2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Transform(a.l, b.l)
  BoundingBox(a.l, b.l)
  Fill(a.l, b.l, c.l)
  Draw(a.l, b.l)
  Close(a.l)
EndInterface

; IDAPoint2 interface definition
;
Interface IDAPoint2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  AnimateControlPosition(a.l, b.l, c.l, d.l, e.l)
  AnimateControlPositionPixel(a.l, b.l, c.l, d.l, e.l)
  get_X(a.l)
  get_Y(a.l)
  get_PolarCoordAngle(a.l)
  get_PolarCoordLength(a.l)
  Transform(a.l, b.l)
EndInterface

; IDAPoint3 interface definition
;
Interface IDAPoint3
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Project(a.l, b.l)
  get_X(a.l)
  get_Y(a.l)
  get_Z(a.l)
  get_SphericalCoordXYAngle(a.l)
  get_SphericalCoordYZAngle(a.l)
  get_SphericalCoordLength(a.l)
  Transform(a.l, b.l)
EndInterface

; IDASound interface definition
;
Interface IDASound
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  PhaseAnim(a.l, b.l)
  Phase(a.l, b.l)
  RateAnim(a.l, b.l)
  Rate(a.l, b.l)
  PanAnim(a.l, b.l)
  Pan(a.l, b.l)
  GainAnim(a.l, b.l)
  Gain(a.l, b.l)
  Loop(a.l)
EndInterface

; IDAString interface definition
;
Interface IDAString
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Extract(a.l)
  AnimateProperty(a.l, b.l, c.l, d.l, e.l)
EndInterface

; IDATransform2 interface definition
;
Interface IDATransform2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Inverse(a.l)
  get_IsSingular(a.l)
EndInterface

; IDATransform3 interface definition
;
Interface IDATransform3
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Inverse(a.l)
  get_IsSingular(a.l)
  ParallelTransform2(a.l)
EndInterface

; IDAVector2 interface definition
;
Interface IDAVector2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  get_Length(a.l)
  get_LengthSquared(a.l)
  Normalize(a.l)
  MulAnim(a.l, b.l)
  Mul(a.l, b.l)
  DivAnim(a.l, b.l)
  Div(a.l, b.l)
  get_X(a.l)
  get_Y(a.l)
  get_PolarCoordAngle(a.l)
  get_PolarCoordLength(a.l)
  Transform(a.l, b.l)
EndInterface

; IDAVector3 interface definition
;
Interface IDAVector3
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  get_Length(a.l)
  get_LengthSquared(a.l)
  Normalize(a.l)
  MulAnim(a.l, b.l)
  Mul(a.l, b.l)
  DivAnim(a.l, b.l)
  Div(a.l, b.l)
  get_X(a.l)
  get_Y(a.l)
  get_Z(a.l)
  get_SphericalCoordXYAngle(a.l)
  get_SphericalCoordYZAngle(a.l)
  get_SphericalCoordLength(a.l)
  Transform(a.l, b.l)
EndInterface

; IDAFontStyle interface definition
;
Interface IDAFontStyle
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Bold(a.l)
  Italic(a.l)
  Underline(a.l)
  Strikethrough(a.l)
  AntiAliasing(a.l, b.l)
  Color(a.l, b.l)
  FamilyAnim(a.l, b.l)
  Family(a.l, b.l)
  SizeAnim(a.l, b.l)
  Size(a.l, b.l)
  Weight(a.l, b.l)
  WeightAnim(a.l, b.l)
EndInterface

; IDALineStyle interface definition
;
Interface IDALineStyle
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  End(a.l, b.l)
  Join(a.l, b.l)
  Dash(a.l, b.l)
  WidthAnim(a.l, b.l)
  width(a.l, b.l)
  AntiAliasing(a.l, b.l)
  Detail(a.l)
  Color(a.l, b.l)
EndInterface

; IDAEndStyle interface definition
;
Interface IDAEndStyle
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
EndInterface

; IDAJoinStyle interface definition
;
Interface IDAJoinStyle
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
EndInterface

; IDADashStyle interface definition
;
Interface IDADashStyle
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
EndInterface

; IDABbox2 interface definition
;
Interface IDABbox2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  get_Min(a.l)
  get_Max(a.l)
EndInterface

; IDABbox3 interface definition
;
Interface IDABbox3
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  get_Min(a.l)
  get_Max(a.l)
EndInterface

; IDAPair interface definition
;
Interface IDAPair
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  get_First(a.l)
  get_Second(a.l)
EndInterface

; IDAArray interface definition
;
Interface IDAArray
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  NthAnim(a.l, b.l)
  Length(a.l)
EndInterface

; IDATuple interface definition
;
Interface IDATuple
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Nth(a.l, b.l)
  get_Length(a.l)
EndInterface

; IDAUserData interface definition
;
Interface IDAUserData
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  get_Data(a.l)
EndInterface

; IDA2Geometry interface definition
;
Interface IDA2Geometry
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  RenderSound(a.l, b.l)
  Pickable(a.l)
  PickableOccluded(a.l)
  Undetectable(a.l)
  EmissiveColor(a.l, b.l)
  DiffuseColor(a.l, b.l)
  SpecularColor(a.l, b.l)
  SpecularExponent(a.l, b.l)
  SpecularExponentAnim(a.l, b.l)
  Texture(a.l, b.l)
  Opacity(a.l, b.l)
  OpacityAnim(a.l, b.l)
  Transform(a.l, b.l)
  get_BoundingBox(a.l)
  Render(a.l, b.l)
  LightColor(a.l, b.l)
  LightAttenuationAnim(a.l, b.l, c.l, d.l)
  LightAttenuation(a.l, b.l, c.l, d.l)
  AddPickData(a.l, b.l, c.l)
  Shadow(a.l, b.l, c.l, d.l)
  LightRangeAnim(a.l, b.l)
  LightRange(a.l, b.l)
  BlendTextureDiffuse(a.l, b.l)
  AmbientColor(a.l, b.l)
  D3DRMTexture(a.l, b.l)
  ModelClip(a.l, b.l, c.l)
  Lighting(a.l, b.l)
  TextureImage(a.l, b.l)
EndInterface

; IDA2Image interface definition
;
Interface IDA2Image
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Pickable(a.l)
  PickableOccluded(a.l)
  ApplyBitmapEffect(a.l, b.l, c.l)
  get_BoundingBox(a.l)
  Crop(a.l, b.l, c.l)
  Transform(a.l, b.l)
  OpacityAnim(a.l, b.l)
  Opacity(a.l, b.l)
  Undetectable(a.l)
  Tile(a.l)
  Clip(a.l, b.l)
  MapToUnitSquare(a.l)
  ClipPolygonImageEx(a.l, b.l, c.l)
  ClipPolygonImage(a.l, b.l)
  AddPickData(a.l, b.l, c.l)
  RenderResolution(a.l, b.l, c.l)
  ImageQuality(a.l, b.l)
  ColorKey(a.l, b.l)
EndInterface

; IDA2FontStyle interface definition
;
Interface IDA2FontStyle
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Bold(a.l)
  Italic(a.l)
  Underline(a.l)
  Strikethrough(a.l)
  AntiAliasing(a.l, b.l)
  Color(a.l, b.l)
  FamilyAnim(a.l, b.l)
  Family(a.l, b.l)
  SizeAnim(a.l, b.l)
  Size(a.l, b.l)
  Weight(a.l, b.l)
  WeightAnim(a.l, b.l)
  TransformCharacters(a.l, b.l)
EndInterface

; IDA2LineStyle interface definition
;
Interface IDA2LineStyle
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  End(a.l, b.l)
  Join(a.l, b.l)
  Dash(a.l, b.l)
  WidthAnim(a.l, b.l)
  width(a.l, b.l)
  AntiAliasing(a.l, b.l)
  Detail(a.l)
  Color(a.l, b.l)
  DashStyle(a.l, b.l)
  MiterLimit(a.l, b.l)
  MiterLimitAnim(a.l, b.l)
  JoinStyle(a.l, b.l)
  EndStyle(a.l, b.l)
EndInterface

; IDA2Event interface definition
;
Interface IDA2Event
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  Notify(a.l, b.l)
  Snapshot(a.l, b.l)
  AttachData(a.l, b.l)
  ScriptCallback(a.l, b.l, c.l)
  NotifyScript(a.l, b.l)
EndInterface

; IDA2Array interface definition
;
Interface IDA2Array
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetClassName(a.l)
  Init(a.l)
  Importance(a.l, b.l)
  RunOnce(a.l)
  SubstituteTime(a.l, b.l)
  SwitchTo(a.l)
  SwitchToNumber(a.l)
  SwitchToString(a.l)
  Hook(a.l, b.l)
  Duration(a.l, b.l)
  DurationAnim(a.l, b.l)
  Repeat(a.l, b.l)
  RepeatForever(a.l)
  IsReady(a.l, b.l)
  NthAnim(a.l, b.l)
  Length(a.l)
  AddElement(a.l, b.l, c.l)
  RemoveElement(a.l)
EndInterface

; IDAPreferences interface definition
;
Interface IDAPreferences
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  PutPreference(a.l, b.l)
  GetPreference(a.l, b.l)
  Propagate()
EndInterface

; IDA2View interface definition
;
Interface IDA2View
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_SimulationTime(a.l)
  Tick(a.l, b.l)
  Render()
  AddBvrToRun(a.l, b.l)
  RemoveRunningBvr(a.l)
  StartModel(a.l, b.l, c.l)
  StopModel()
  get_Window(a.l)
  put_Window(a.l)
  get_IDirectDrawSurface(a.l)
  put_IDirectDrawSurface(a.l)
  get_DC(a.l)
  put_DC(a.l)
  get_CompositeDirectlyToTarget(a.l)
  put_CompositeDirectlyToTarget(a.l)
  SetViewport(a.l, b.l, c.l, d.l)
  SetClipRect(a.l, b.l, c.l, d.l)
  RePaint(a.l, b.l, c.l, d.l)
  PaletteChanged(a.l)
  get_Site(a.l)
  put_Site(a.l)
  put_ClientSite(a.l)
  get_ClientSite(a.l)
  OnMouseMove(a.l, b.l, c.l, d.l)
  OnMouseButton(a.l, b.l, c.l, d.l, e.l, f.l)
  OnKey(a.l, b.l, c.l, d.l)
  OnFocus(a.l)
  get_Preferences(a.l)
  QueryHitPoint(a.l, b.l, c.l, d.l, e.l)
  QueryHitPointEx(a.l, b.l, c.l, d.l, e.l, f.l)
  StartModelEx(a.l, b.l, c.l, d.l)
  GetDDD3DRM(a.l, b.l)
  GetRMDevice(a.l, b.l)
  GetInvalidatedRects(a.l, b.l, c.l, d.l)
EndInterface

; IDASite interface definition
;
Interface IDASite
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  SetStatusText(a.l)
  ReportError(a.l, b.l)
  ReportGC(a.l)
EndInterface

; IDAImportationResult interface definition
;
Interface IDAImportationResult
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Image(a.l)
  get_Sound(a.l)
  get_Geometry(a.l)
  get_Duration(a.l)
  get_CompletionEvent(a.l)
  get_Progress(a.l)
  get_Size(a.l)
EndInterface

; IDADXTransformResult interface definition
;
Interface IDADXTransformResult
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_OutputBvr(a.l)
  get_TheTransform(a.l)
  PutBvrAsProperty(a.l, b.l)
EndInterface

; IDAStatics interface definition
;
Interface IDAStatics
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_VersionString(a.l)
  get_Site(a.l)
  put_Site(a.l)
  put_ClientSite(a.l)
  get_ClientSite(a.l)
  put_PixelConstructionMode(a.l)
  get_PixelConstructionMode(a.l)
  TriggerEvent(a.l, b.l)
  NewDrawingSurface(a.l)
  ImportMovie(a.l, b.l)
  ImportMovieAsync(a.l, b.l, c.l, d.l)
  ImportImage(a.l, b.l)
  ImportImageAsync(a.l, b.l, c.l)
  ImportImageColorKey(a.l, b.l, c.l, d.l, e.l)
  ImportImageAsyncColorKey(a.l, b.l, c.l, d.l, e.l, f.l)
  ImportSound(a.l, b.l)
  ImportSoundAsync(a.l, b.l, c.l)
  ImportGeometry(a.l, b.l)
  ImportGeometryAsync(a.l, b.l, c.l)
  ImportDirectDrawSurface(a.l, b.l, c.l)
  Cond(a.l, b.l, c.l, d.l)
  DAArrayEx(a.l, b.l, c.l)
  DAArray(a.l, b.l)
  DATupleEx(a.l, b.l, c.l)
  DATuple(a.l, b.l)
  ModifiableBehavior(a.l, b.l)
  UninitializedArray(a.l, b.l)
  UninitializedTuple(a.l, b.l)
  NumberBSplineEx(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l)
  NumberBSpline(a.l, b.l, c.l, d.l, e.l, f.l)
  Point2BSplineEx(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l)
  Point2BSpline(a.l, b.l, c.l, d.l, e.l, f.l)
  Point3BSplineEx(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l)
  Point3BSpline(a.l, b.l, c.l, d.l, e.l, f.l)
  Vector2BSplineEx(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l)
  Vector2BSpline(a.l, b.l, c.l, d.l, e.l, f.l)
  Vector3BSplineEx(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l)
  Vector3BSpline(a.l, b.l, c.l, d.l, e.l, f.l)
  Pow(a.l, b.l, c.l)
  Abs(a.l, b.l)
  Sqrt(a.l, b.l)
  Floor(a.l, b.l)
  Round(a.l, b.l)
  Ceiling(a.l, b.l)
  Asin(a.l, b.l)
  Acos(a.l, b.l)
  Atan(a.l, b.l)
  Sin(a.l, b.l)
  Cos(a.l, b.l)
  Tan(a.l, b.l)
  Exp(a.l, b.l)
  Ln(a.l, b.l)
  Log10(a.l, b.l)
  ToDegrees(a.l, b.l)
  ToRadians(a.l, b.l)
  Mod(a.l, b.l, c.l)
  Atan2(a.l, b.l, c.l)
  Add(a.l, b.l, c.l)
  Sub(a.l, b.l, c.l)
  Mul(a.l, b.l, c.l)
  Div(a.l, b.l, c.l)
  LT(a.l, b.l, c.l)
  LTE(a.l, b.l, c.l)
  GT(a.l, b.l, c.l)
  GTE(a.l, b.l, c.l)
  EQ(a.l, b.l, c.l)
  NE(a.l, b.l, c.l)
  Neg(a.l, b.l)
  InterpolateAnim(a.l, b.l, c.l, d.l)
  Interpolate(a.l, b.l, c.l, d.l)
  SlowInSlowOutAnim(a.l, b.l, c.l, d.l, e.l)
  SlowInSlowOut(a.l, b.l, c.l, d.l, e.l)
  SoundSource(a.l, b.l)
  Mix(a.l, b.l, c.l)
  And(a.l, b.l, c.l)
  Or(a.l, b.l, c.l)
  Not(a.l, b.l)
  Integral(a.l, b.l)
  Derivative(a.l, b.l)
  IntegralVector2(a.l, b.l)
  IntegralVector3(a.l, b.l)
  DerivativeVector2(a.l, b.l)
  DerivativeVector3(a.l, b.l)
  DerivativePoint2(a.l, b.l)
  DerivativePoint3(a.l, b.l)
  KeyState(a.l, b.l)
  KeyUp(a.l, b.l)
  KeyDown(a.l, b.l)
  DANumber(a.l, b.l)
  DAString(a.l, b.l)
  DABoolean(a.l, b.l)
  SeededRandom(a.l, b.l)
  get_MousePosition(a.l)
  get_LeftButtonState(a.l)
  get_RightButtonState(a.l)
  get_DATrue(a.l)
  get_DAFalse(a.l)
  get_LocalTime(a.l)
  get_GlobalTime(a.l)
  get_Pixel(a.l)
  UserData(a.l, b.l)
  UntilNotify(a.l, b.l, c.l, d.l)
  Until(a.l, b.l, c.l, d.l)
  UntilEx(a.l, b.l, c.l)
  Sequence(a.l, b.l, c.l)
  FollowPath(a.l, b.l, c.l)
  FollowPathAngle(a.l, b.l, c.l)
  FollowPathAngleUpright(a.l, b.l, c.l)
  FollowPathEval(a.l, b.l, c.l)
  FollowPathAngleEval(a.l, b.l, c.l)
  FollowPathAngleUprightEval(a.l, b.l, c.l)
  FollowPathAnim(a.l, b.l, c.l)
  FollowPathAngleAnim(a.l, b.l, c.l)
  FollowPathAngleUprightAnim(a.l, b.l, c.l)
  ConcatString(a.l, b.l, c.l)
  PerspectiveCamera(a.l, b.l, c.l)
  PerspectiveCameraAnim(a.l, b.l, c.l)
  ParallelCamera(a.l, b.l)
  ParallelCameraAnim(a.l, b.l)
  ColorRgbAnim(a.l, b.l, c.l, d.l)
  ColorRgb(a.l, b.l, c.l, d.l)
  ColorRgb255(a.l, b.l, c.l, d.l)
  ColorHsl(a.l, b.l, c.l, d.l)
  ColorHslAnim(a.l, b.l, c.l, d.l)
  get_Red(a.l)
  get_Green(a.l)
  get_Blue(a.l)
  get_Cyan(a.l)
  get_Magenta(a.l)
  get_Yellow(a.l)
  get_Black(a.l)
  get_White(a.l)
  get_Aqua(a.l)
  get_Fuchsia(a.l)
  get_Gray(a.l)
  get_Lime(a.l)
  get_Maroon(a.l)
  get_Navy(a.l)
  get_Olive(a.l)
  get_Purple(a.l)
  get_Silver(a.l)
  get_Teal(a.l)
  Predicate(a.l, b.l)
  NotEvent(a.l, b.l)
  AndEvent(a.l, b.l, c.l)
  OrEvent(a.l, b.l, c.l)
  ThenEvent(a.l, b.l, c.l)
  get_LeftButtonDown(a.l)
  get_LeftButtonUp(a.l)
  get_RightButtonDown(a.l)
  get_RightButtonUp(a.l)
  get_Always(a.l)
  get_Never(a.l)
  TimerAnim(a.l, b.l)
  Timer(a.l, b.l)
  AppTriggeredEvent(a.l)
  ScriptCallback(a.l, b.l, c.l, d.l)
  get_EmptyGeometry(a.l)
  UnionGeometry(a.l, b.l, c.l)
  UnionGeometryArrayEx(a.l, b.l, c.l)
  UnionGeometryArray(a.l, b.l)
  get_EmptyImage(a.l)
  get_DetectableEmptyImage(a.l)
  SolidColorImage(a.l, b.l)
  GradientPolygonEx(a.l, b.l, c.l, d.l, e.l)
  GradientPolygon(a.l, b.l, c.l)
  RadialGradientPolygonEx(a.l, b.l, c.l, d.l, e.l, f.l)
  RadialGradientPolygon(a.l, b.l, c.l, d.l, e.l)
  RadialGradientPolygonAnimEx(a.l, b.l, c.l, d.l, e.l, f.l)
  RadialGradientPolygonAnim(a.l, b.l, c.l, d.l, e.l)
  GradientSquare(a.l, b.l, c.l, d.l, e.l)
  RadialGradientSquare(a.l, b.l, c.l, d.l)
  RadialGradientSquareAnim(a.l, b.l, c.l, d.l)
  RadialGradientRegularPoly(a.l, b.l, c.l, d.l, e.l)
  RadialGradientRegularPolyAnim(a.l, b.l, c.l, d.l, e.l)
  GradientHorizontal(a.l, b.l, c.l, d.l)
  GradientHorizontalAnim(a.l, b.l, c.l, d.l)
  HatchHorizontal(a.l, b.l, c.l)
  HatchHorizontalAnim(a.l, b.l, c.l)
  HatchVertical(a.l, b.l, c.l)
  HatchVerticalAnim(a.l, b.l, c.l)
  HatchForwardDiagonal(a.l, b.l, c.l)
  HatchForwardDiagonalAnim(a.l, b.l, c.l)
  HatchBackwardDiagonal(a.l, b.l, c.l)
  HatchBackwardDiagonalAnim(a.l, b.l, c.l)
  HatchCross(a.l, b.l, c.l)
  HatchCrossAnim(a.l, b.l, c.l)
  HatchDiagonalCross(a.l, b.l, c.l)
  HatchDiagonalCrossAnim(a.l, b.l, c.l)
  Overlay(a.l, b.l, c.l)
  OverlayArrayEx(a.l, b.l, c.l)
  OverlayArray(a.l, b.l)
  get_AmbientLight(a.l)
  get_DirectionalLight(a.l)
  get_PointLight(a.l)
  SpotLightAnim(a.l, b.l, c.l)
  SpotLight(a.l, b.l, c.l)
  get_DefaultLineStyle(a.l)
  get_EmptyLineStyle(a.l)
  get_JoinStyleBevel(a.l)
  get_JoinStyleRound(a.l)
  get_JoinStyleMiter(a.l)
  get_EndStyleFlat(a.l)
  get_EndStyleSquare(a.l)
  get_EndStyleRound(a.l)
  get_DashStyleSolid(a.l)
  get_DashStyleDashed(a.l)
  get_DefaultMicrophone(a.l)
  get_OpaqueMatte(a.l)
  get_ClearMatte(a.l)
  UnionMatte(a.l, b.l, c.l)
  IntersectMatte(a.l, b.l, c.l)
  DifferenceMatte(a.l, b.l, c.l)
  FillMatte(a.l, b.l)
  TextMatte(a.l, b.l, c.l)
  get_EmptyMontage(a.l)
  ImageMontage(a.l, b.l, c.l)
  ImageMontageAnim(a.l, b.l, c.l)
  UnionMontage(a.l, b.l, c.l)
  Concat(a.l, b.l, c.l)
  ConcatArrayEx(a.l, b.l, c.l)
  ConcatArray(a.l, b.l)
  Line(a.l, b.l, c.l)
  Ray(a.l, b.l)
  StringPathAnim(a.l, b.l, c.l)
  StringPath(a.l, b.l, c.l)
  PolylineEx(a.l, b.l, c.l)
  Polyline(a.l, b.l)
  PolydrawPathEx(a.l, b.l, c.l, d.l, e.l)
  PolydrawPath(a.l, b.l, c.l)
  ArcRadians(a.l, b.l, c.l, d.l, e.l)
  ArcRadiansAnim(a.l, b.l, c.l, d.l, e.l)
  ArcDegrees(a.l, b.l, c.l, d.l, e.l)
  PieRadians(a.l, b.l, c.l, d.l, e.l)
  PieRadiansAnim(a.l, b.l, c.l, d.l, e.l)
  PieDegrees(a.l, b.l, c.l, d.l, e.l)
  Oval(a.l, b.l, c.l)
  OvalAnim(a.l, b.l, c.l)
  Rect(a.l, b.l, c.l)
  RectAnim(a.l, b.l, c.l)
  RoundRect(a.l, b.l, c.l, d.l, e.l)
  RoundRectAnim(a.l, b.l, c.l, d.l, e.l)
  CubicBSplinePathEx(a.l, b.l, c.l, d.l, e.l)
  CubicBSplinePath(a.l, b.l, c.l)
  TextPath(a.l, b.l, c.l)
  get_Silence(a.l)
  MixArrayEx(a.l, b.l, c.l)
  MixArray(a.l, b.l)
  get_SinSynth(a.l)
  get_DefaultFont(a.l)
  FontAnim(a.l, b.l, c.l, d.l)
  Font(a.l, b.l, c.l, d.l)
  StringImageAnim(a.l, b.l, c.l)
  StringImage(a.l, b.l, c.l)
  TextImageAnim(a.l, b.l, c.l)
  TextImage(a.l, b.l, c.l)
  get_XVector2(a.l)
  get_YVector2(a.l)
  get_ZeroVector2(a.l)
  get_Origin2(a.l)
  Vector2Anim(a.l, b.l, c.l)
  Vector2(a.l, b.l, c.l)
  Point2Anim(a.l, b.l, c.l)
  Point2(a.l, b.l, c.l)
  Vector2PolarAnim(a.l, b.l, c.l)
  Vector2Polar(a.l, b.l, c.l)
  Vector2PolarDegrees(a.l, b.l, c.l)
  Point2PolarAnim(a.l, b.l, c.l)
  Point2Polar(a.l, b.l, c.l)
  DotVector2(a.l, b.l, c.l)
  NegVector2(a.l, b.l)
  SubVector2(a.l, b.l, c.l)
  AddVector2(a.l, b.l, c.l)
  AddPoint2Vector(a.l, b.l, c.l)
  SubPoint2Vector(a.l, b.l, c.l)
  SubPoint2(a.l, b.l, c.l)
  DistancePoint2(a.l, b.l, c.l)
  DistanceSquaredPoint2(a.l, b.l, c.l)
  get_XVector3(a.l)
  get_YVector3(a.l)
  get_ZVector3(a.l)
  get_ZeroVector3(a.l)
  get_Origin3(a.l)
  Vector3Anim(a.l, b.l, c.l, d.l)
  Vector3(a.l, b.l, c.l, d.l)
  Point3Anim(a.l, b.l, c.l, d.l)
  Point3(a.l, b.l, c.l, d.l)
  Vector3SphericalAnim(a.l, b.l, c.l, d.l)
  Vector3Spherical(a.l, b.l, c.l, d.l)
  Point3SphericalAnim(a.l, b.l, c.l, d.l)
  Point3Spherical(a.l, b.l, c.l, d.l)
  DotVector3(a.l, b.l, c.l)
  CrossVector3(a.l, b.l, c.l)
  NegVector3(a.l, b.l)
  SubVector3(a.l, b.l, c.l)
  AddVector3(a.l, b.l, c.l)
  AddPoint3Vector(a.l, b.l, c.l)
  SubPoint3Vector(a.l, b.l, c.l)
  SubPoint3(a.l, b.l, c.l)
  DistancePoint3(a.l, b.l, c.l)
  DistanceSquaredPoint3(a.l, b.l, c.l)
  get_IdentityTransform3(a.l)
  Translate3Anim(a.l, b.l, c.l, d.l)
  Translate3(a.l, b.l, c.l, d.l)
  Translate3Rate(a.l, b.l, c.l, d.l)
  Translate3Vector(a.l, b.l)
  Translate3Point(a.l, b.l)
  Scale3Anim(a.l, b.l, c.l, d.l)
  Scale3(a.l, b.l, c.l, d.l)
  Scale3Rate(a.l, b.l, c.l, d.l)
  Scale3Vector(a.l, b.l)
  Scale3UniformAnim(a.l, b.l)
  Scale3Uniform(a.l, b.l)
  Scale3UniformRate(a.l, b.l)
  Rotate3Anim(a.l, b.l, c.l)
  Rotate3(a.l, b.l, c.l)
  Rotate3Rate(a.l, b.l, c.l)
  Rotate3Degrees(a.l, b.l, c.l)
  Rotate3RateDegrees(a.l, b.l, c.l)
  XShear3Anim(a.l, b.l, c.l)
  XShear3(a.l, b.l, c.l)
  XShear3Rate(a.l, b.l, c.l)
  YShear3Anim(a.l, b.l, c.l)
  YShear3(a.l, b.l, c.l)
  YShear3Rate(a.l, b.l, c.l)
  ZShear3Anim(a.l, b.l, c.l)
  ZShear3(a.l, b.l, c.l)
  ZShear3Rate(a.l, b.l, c.l)
  Transform4x4AnimEx(a.l, b.l, c.l)
  Transform4x4Anim(a.l, b.l)
  Compose3(a.l, b.l, c.l)
  Compose3ArrayEx(a.l, b.l, c.l)
  Compose3Array(a.l, b.l)
  LookAtFrom(a.l, b.l, c.l, d.l)
  get_IdentityTransform2(a.l)
  Translate2Anim(a.l, b.l, c.l)
  Translate2(a.l, b.l, c.l)
  Translate2Rate(a.l, b.l, c.l)
  Translate2Vector(a.l, b.l)
  Translate2Point(a.l, b.l)
  Scale2Anim(a.l, b.l, c.l)
  Scale2(a.l, b.l, c.l)
  Scale2Rate(a.l, b.l, c.l)
  Scale2Vector2(a.l, b.l)
  Scale2Vector(a.l, b.l)
  Scale2UniformAnim(a.l, b.l)
  Scale2Uniform(a.l, b.l)
  Scale2UniformRate(a.l, b.l)
  Rotate2Anim(a.l, b.l)
  Rotate2(a.l, b.l)
  Rotate2Rate(a.l, b.l)
  Rotate2Degrees(a.l, b.l)
  Rotate2RateDegrees(a.l, b.l)
  XShear2Anim(a.l, b.l)
  XShear2(a.l, b.l)
  XShear2Rate(a.l, b.l)
  YShear2Anim(a.l, b.l)
  YShear2(a.l, b.l)
  YShear2Rate(a.l, b.l)
  Transform3x2AnimEx(a.l, b.l, c.l)
  Transform3x2Anim(a.l, b.l)
  Compose2(a.l, b.l, c.l)
  Compose2ArrayEx(a.l, b.l, c.l)
  Compose2Array(a.l, b.l)
  Tuple(a.l, b.l)
  Array(a.l, b.l)
  get_AreBlockingImportsComplete(a.l)
EndInterface

; IDA2Statics interface definition
;
Interface IDA2Statics
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_VersionString(a.l)
  get_Site(a.l)
  put_Site(a.l)
  put_ClientSite(a.l)
  get_ClientSite(a.l)
  put_PixelConstructionMode(a.l)
  get_PixelConstructionMode(a.l)
  TriggerEvent(a.l, b.l)
  NewDrawingSurface(a.l)
  ImportMovie(a.l, b.l)
  ImportMovieAsync(a.l, b.l, c.l, d.l)
  ImportImage(a.l, b.l)
  ImportImageAsync(a.l, b.l, c.l)
  ImportImageColorKey(a.l, b.l, c.l, d.l, e.l)
  ImportImageAsyncColorKey(a.l, b.l, c.l, d.l, e.l, f.l)
  ImportSound(a.l, b.l)
  ImportSoundAsync(a.l, b.l, c.l)
  ImportGeometry(a.l, b.l)
  ImportGeometryAsync(a.l, b.l, c.l)
  ImportDirectDrawSurface(a.l, b.l, c.l)
  Cond(a.l, b.l, c.l, d.l)
  DAArrayEx(a.l, b.l, c.l)
  DAArray(a.l, b.l)
  DATupleEx(a.l, b.l, c.l)
  DATuple(a.l, b.l)
  ModifiableBehavior(a.l, b.l)
  UninitializedArray(a.l, b.l)
  UninitializedTuple(a.l, b.l)
  NumberBSplineEx(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l)
  NumberBSpline(a.l, b.l, c.l, d.l, e.l, f.l)
  Point2BSplineEx(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l)
  Point2BSpline(a.l, b.l, c.l, d.l, e.l, f.l)
  Point3BSplineEx(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l)
  Point3BSpline(a.l, b.l, c.l, d.l, e.l, f.l)
  Vector2BSplineEx(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l)
  Vector2BSpline(a.l, b.l, c.l, d.l, e.l, f.l)
  Vector3BSplineEx(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l)
  Vector3BSpline(a.l, b.l, c.l, d.l, e.l, f.l)
  Pow(a.l, b.l, c.l)
  Abs(a.l, b.l)
  Sqrt(a.l, b.l)
  Floor(a.l, b.l)
  Round(a.l, b.l)
  Ceiling(a.l, b.l)
  Asin(a.l, b.l)
  Acos(a.l, b.l)
  Atan(a.l, b.l)
  Sin(a.l, b.l)
  Cos(a.l, b.l)
  Tan(a.l, b.l)
  Exp(a.l, b.l)
  Ln(a.l, b.l)
  Log10(a.l, b.l)
  ToDegrees(a.l, b.l)
  ToRadians(a.l, b.l)
  Mod(a.l, b.l, c.l)
  Atan2(a.l, b.l, c.l)
  Add(a.l, b.l, c.l)
  Sub(a.l, b.l, c.l)
  Mul(a.l, b.l, c.l)
  Div(a.l, b.l, c.l)
  LT(a.l, b.l, c.l)
  LTE(a.l, b.l, c.l)
  GT(a.l, b.l, c.l)
  GTE(a.l, b.l, c.l)
  EQ(a.l, b.l, c.l)
  NE(a.l, b.l, c.l)
  Neg(a.l, b.l)
  InterpolateAnim(a.l, b.l, c.l, d.l)
  Interpolate(a.l, b.l, c.l, d.l)
  SlowInSlowOutAnim(a.l, b.l, c.l, d.l, e.l)
  SlowInSlowOut(a.l, b.l, c.l, d.l, e.l)
  SoundSource(a.l, b.l)
  Mix(a.l, b.l, c.l)
  And(a.l, b.l, c.l)
  Or(a.l, b.l, c.l)
  Not(a.l, b.l)
  Integral(a.l, b.l)
  Derivative(a.l, b.l)
  IntegralVector2(a.l, b.l)
  IntegralVector3(a.l, b.l)
  DerivativeVector2(a.l, b.l)
  DerivativeVector3(a.l, b.l)
  DerivativePoint2(a.l, b.l)
  DerivativePoint3(a.l, b.l)
  KeyState(a.l, b.l)
  KeyUp(a.l, b.l)
  KeyDown(a.l, b.l)
  DANumber(a.l, b.l)
  DAString(a.l, b.l)
  DABoolean(a.l, b.l)
  SeededRandom(a.l, b.l)
  get_MousePosition(a.l)
  get_LeftButtonState(a.l)
  get_RightButtonState(a.l)
  get_DATrue(a.l)
  get_DAFalse(a.l)
  get_LocalTime(a.l)
  get_GlobalTime(a.l)
  get_Pixel(a.l)
  UserData(a.l, b.l)
  UntilNotify(a.l, b.l, c.l, d.l)
  Until(a.l, b.l, c.l, d.l)
  UntilEx(a.l, b.l, c.l)
  Sequence(a.l, b.l, c.l)
  FollowPath(a.l, b.l, c.l)
  FollowPathAngle(a.l, b.l, c.l)
  FollowPathAngleUpright(a.l, b.l, c.l)
  FollowPathEval(a.l, b.l, c.l)
  FollowPathAngleEval(a.l, b.l, c.l)
  FollowPathAngleUprightEval(a.l, b.l, c.l)
  FollowPathAnim(a.l, b.l, c.l)
  FollowPathAngleAnim(a.l, b.l, c.l)
  FollowPathAngleUprightAnim(a.l, b.l, c.l)
  ConcatString(a.l, b.l, c.l)
  PerspectiveCamera(a.l, b.l, c.l)
  PerspectiveCameraAnim(a.l, b.l, c.l)
  ParallelCamera(a.l, b.l)
  ParallelCameraAnim(a.l, b.l)
  ColorRgbAnim(a.l, b.l, c.l, d.l)
  ColorRgb(a.l, b.l, c.l, d.l)
  ColorRgb255(a.l, b.l, c.l, d.l)
  ColorHsl(a.l, b.l, c.l, d.l)
  ColorHslAnim(a.l, b.l, c.l, d.l)
  get_Red(a.l)
  get_Green(a.l)
  get_Blue(a.l)
  get_Cyan(a.l)
  get_Magenta(a.l)
  get_Yellow(a.l)
  get_Black(a.l)
  get_White(a.l)
  get_Aqua(a.l)
  get_Fuchsia(a.l)
  get_Gray(a.l)
  get_Lime(a.l)
  get_Maroon(a.l)
  get_Navy(a.l)
  get_Olive(a.l)
  get_Purple(a.l)
  get_Silver(a.l)
  get_Teal(a.l)
  Predicate(a.l, b.l)
  NotEvent(a.l, b.l)
  AndEvent(a.l, b.l, c.l)
  OrEvent(a.l, b.l, c.l)
  ThenEvent(a.l, b.l, c.l)
  get_LeftButtonDown(a.l)
  get_LeftButtonUp(a.l)
  get_RightButtonDown(a.l)
  get_RightButtonUp(a.l)
  get_Always(a.l)
  get_Never(a.l)
  TimerAnim(a.l, b.l)
  Timer(a.l, b.l)
  AppTriggeredEvent(a.l)
  ScriptCallback(a.l, b.l, c.l, d.l)
  get_EmptyGeometry(a.l)
  UnionGeometry(a.l, b.l, c.l)
  UnionGeometryArrayEx(a.l, b.l, c.l)
  UnionGeometryArray(a.l, b.l)
  get_EmptyImage(a.l)
  get_DetectableEmptyImage(a.l)
  SolidColorImage(a.l, b.l)
  GradientPolygonEx(a.l, b.l, c.l, d.l, e.l)
  GradientPolygon(a.l, b.l, c.l)
  RadialGradientPolygonEx(a.l, b.l, c.l, d.l, e.l, f.l)
  RadialGradientPolygon(a.l, b.l, c.l, d.l, e.l)
  RadialGradientPolygonAnimEx(a.l, b.l, c.l, d.l, e.l, f.l)
  RadialGradientPolygonAnim(a.l, b.l, c.l, d.l, e.l)
  GradientSquare(a.l, b.l, c.l, d.l, e.l)
  RadialGradientSquare(a.l, b.l, c.l, d.l)
  RadialGradientSquareAnim(a.l, b.l, c.l, d.l)
  RadialGradientRegularPoly(a.l, b.l, c.l, d.l, e.l)
  RadialGradientRegularPolyAnim(a.l, b.l, c.l, d.l, e.l)
  GradientHorizontal(a.l, b.l, c.l, d.l)
  GradientHorizontalAnim(a.l, b.l, c.l, d.l)
  HatchHorizontal(a.l, b.l, c.l)
  HatchHorizontalAnim(a.l, b.l, c.l)
  HatchVertical(a.l, b.l, c.l)
  HatchVerticalAnim(a.l, b.l, c.l)
  HatchForwardDiagonal(a.l, b.l, c.l)
  HatchForwardDiagonalAnim(a.l, b.l, c.l)
  HatchBackwardDiagonal(a.l, b.l, c.l)
  HatchBackwardDiagonalAnim(a.l, b.l, c.l)
  HatchCross(a.l, b.l, c.l)
  HatchCrossAnim(a.l, b.l, c.l)
  HatchDiagonalCross(a.l, b.l, c.l)
  HatchDiagonalCrossAnim(a.l, b.l, c.l)
  Overlay(a.l, b.l, c.l)
  OverlayArrayEx(a.l, b.l, c.l)
  OverlayArray(a.l, b.l)
  get_AmbientLight(a.l)
  get_DirectionalLight(a.l)
  get_PointLight(a.l)
  SpotLightAnim(a.l, b.l, c.l)
  SpotLight(a.l, b.l, c.l)
  get_DefaultLineStyle(a.l)
  get_EmptyLineStyle(a.l)
  get_JoinStyleBevel(a.l)
  get_JoinStyleRound(a.l)
  get_JoinStyleMiter(a.l)
  get_EndStyleFlat(a.l)
  get_EndStyleSquare(a.l)
  get_EndStyleRound(a.l)
  get_DashStyleSolid(a.l)
  get_DashStyleDashed(a.l)
  get_DefaultMicrophone(a.l)
  get_OpaqueMatte(a.l)
  get_ClearMatte(a.l)
  UnionMatte(a.l, b.l, c.l)
  IntersectMatte(a.l, b.l, c.l)
  DifferenceMatte(a.l, b.l, c.l)
  FillMatte(a.l, b.l)
  TextMatte(a.l, b.l, c.l)
  get_EmptyMontage(a.l)
  ImageMontage(a.l, b.l, c.l)
  ImageMontageAnim(a.l, b.l, c.l)
  UnionMontage(a.l, b.l, c.l)
  Concat(a.l, b.l, c.l)
  ConcatArrayEx(a.l, b.l, c.l)
  ConcatArray(a.l, b.l)
  Line(a.l, b.l, c.l)
  Ray(a.l, b.l)
  StringPathAnim(a.l, b.l, c.l)
  StringPath(a.l, b.l, c.l)
  PolylineEx(a.l, b.l, c.l)
  Polyline(a.l, b.l)
  PolydrawPathEx(a.l, b.l, c.l, d.l, e.l)
  PolydrawPath(a.l, b.l, c.l)
  ArcRadians(a.l, b.l, c.l, d.l, e.l)
  ArcRadiansAnim(a.l, b.l, c.l, d.l, e.l)
  ArcDegrees(a.l, b.l, c.l, d.l, e.l)
  PieRadians(a.l, b.l, c.l, d.l, e.l)
  PieRadiansAnim(a.l, b.l, c.l, d.l, e.l)
  PieDegrees(a.l, b.l, c.l, d.l, e.l)
  Oval(a.l, b.l, c.l)
  OvalAnim(a.l, b.l, c.l)
  Rect(a.l, b.l, c.l)
  RectAnim(a.l, b.l, c.l)
  RoundRect(a.l, b.l, c.l, d.l, e.l)
  RoundRectAnim(a.l, b.l, c.l, d.l, e.l)
  CubicBSplinePathEx(a.l, b.l, c.l, d.l, e.l)
  CubicBSplinePath(a.l, b.l, c.l)
  TextPath(a.l, b.l, c.l)
  get_Silence(a.l)
  MixArrayEx(a.l, b.l, c.l)
  MixArray(a.l, b.l)
  get_SinSynth(a.l)
  get_DefaultFont(a.l)
  FontAnim(a.l, b.l, c.l, d.l)
  Font(a.l, b.l, c.l, d.l)
  StringImageAnim(a.l, b.l, c.l)
  StringImage(a.l, b.l, c.l)
  TextImageAnim(a.l, b.l, c.l)
  TextImage(a.l, b.l, c.l)
  get_XVector2(a.l)
  get_YVector2(a.l)
  get_ZeroVector2(a.l)
  get_Origin2(a.l)
  Vector2Anim(a.l, b.l, c.l)
  Vector2(a.l, b.l, c.l)
  Point2Anim(a.l, b.l, c.l)
  Point2(a.l, b.l, c.l)
  Vector2PolarAnim(a.l, b.l, c.l)
  Vector2Polar(a.l, b.l, c.l)
  Vector2PolarDegrees(a.l, b.l, c.l)
  Point2PolarAnim(a.l, b.l, c.l)
  Point2Polar(a.l, b.l, c.l)
  DotVector2(a.l, b.l, c.l)
  NegVector2(a.l, b.l)
  SubVector2(a.l, b.l, c.l)
  AddVector2(a.l, b.l, c.l)
  AddPoint2Vector(a.l, b.l, c.l)
  SubPoint2Vector(a.l, b.l, c.l)
  SubPoint2(a.l, b.l, c.l)
  DistancePoint2(a.l, b.l, c.l)
  DistanceSquaredPoint2(a.l, b.l, c.l)
  get_XVector3(a.l)
  get_YVector3(a.l)
  get_ZVector3(a.l)
  get_ZeroVector3(a.l)
  get_Origin3(a.l)
  Vector3Anim(a.l, b.l, c.l, d.l)
  Vector3(a.l, b.l, c.l, d.l)
  Point3Anim(a.l, b.l, c.l, d.l)
  Point3(a.l, b.l, c.l, d.l)
  Vector3SphericalAnim(a.l, b.l, c.l, d.l)
  Vector3Spherical(a.l, b.l, c.l, d.l)
  Point3SphericalAnim(a.l, b.l, c.l, d.l)
  Point3Spherical(a.l, b.l, c.l, d.l)
  DotVector3(a.l, b.l, c.l)
  CrossVector3(a.l, b.l, c.l)
  NegVector3(a.l, b.l)
  SubVector3(a.l, b.l, c.l)
  AddVector3(a.l, b.l, c.l)
  AddPoint3Vector(a.l, b.l, c.l)
  SubPoint3Vector(a.l, b.l, c.l)
  SubPoint3(a.l, b.l, c.l)
  DistancePoint3(a.l, b.l, c.l)
  DistanceSquaredPoint3(a.l, b.l, c.l)
  get_IdentityTransform3(a.l)
  Translate3Anim(a.l, b.l, c.l, d.l)
  Translate3(a.l, b.l, c.l, d.l)
  Translate3Rate(a.l, b.l, c.l, d.l)
  Translate3Vector(a.l, b.l)
  Translate3Point(a.l, b.l)
  Scale3Anim(a.l, b.l, c.l, d.l)
  Scale3(a.l, b.l, c.l, d.l)
  Scale3Rate(a.l, b.l, c.l, d.l)
  Scale3Vector(a.l, b.l)
  Scale3UniformAnim(a.l, b.l)
  Scale3Uniform(a.l, b.l)
  Scale3UniformRate(a.l, b.l)
  Rotate3Anim(a.l, b.l, c.l)
  Rotate3(a.l, b.l, c.l)
  Rotate3Rate(a.l, b.l, c.l)
  Rotate3Degrees(a.l, b.l, c.l)
  Rotate3RateDegrees(a.l, b.l, c.l)
  XShear3Anim(a.l, b.l, c.l)
  XShear3(a.l, b.l, c.l)
  XShear3Rate(a.l, b.l, c.l)
  YShear3Anim(a.l, b.l, c.l)
  YShear3(a.l, b.l, c.l)
  YShear3Rate(a.l, b.l, c.l)
  ZShear3Anim(a.l, b.l, c.l)
  ZShear3(a.l, b.l, c.l)
  ZShear3Rate(a.l, b.l, c.l)
  Transform4x4AnimEx(a.l, b.l, c.l)
  Transform4x4Anim(a.l, b.l)
  Compose3(a.l, b.l, c.l)
  Compose3ArrayEx(a.l, b.l, c.l)
  Compose3Array(a.l, b.l)
  LookAtFrom(a.l, b.l, c.l, d.l)
  get_IdentityTransform2(a.l)
  Translate2Anim(a.l, b.l, c.l)
  Translate2(a.l, b.l, c.l)
  Translate2Rate(a.l, b.l, c.l)
  Translate2Vector(a.l, b.l)
  Translate2Point(a.l, b.l)
  Scale2Anim(a.l, b.l, c.l)
  Scale2(a.l, b.l, c.l)
  Scale2Rate(a.l, b.l, c.l)
  Scale2Vector2(a.l, b.l)
  Scale2Vector(a.l, b.l)
  Scale2UniformAnim(a.l, b.l)
  Scale2Uniform(a.l, b.l)
  Scale2UniformRate(a.l, b.l)
  Rotate2Anim(a.l, b.l)
  Rotate2(a.l, b.l)
  Rotate2Rate(a.l, b.l)
  Rotate2Degrees(a.l, b.l)
  Rotate2RateDegrees(a.l, b.l)
  XShear2Anim(a.l, b.l)
  XShear2(a.l, b.l)
  XShear2Rate(a.l, b.l)
  YShear2Anim(a.l, b.l)
  YShear2(a.l, b.l)
  YShear2Rate(a.l, b.l)
  Transform3x2AnimEx(a.l, b.l, c.l)
  Transform3x2Anim(a.l, b.l)
  Compose2(a.l, b.l, c.l)
  Compose2ArrayEx(a.l, b.l, c.l)
  Compose2Array(a.l, b.l)
  Tuple(a.l, b.l)
  Array(a.l, b.l)
  get_AreBlockingImportsComplete(a.l)
  ImportDirect3DRMVisual(a.l, b.l)
  ApplyDXTransformEx(a.l, b.l, c.l, d.l, e.l)
  ApplyDXTransform(a.l, b.l, c.l, d.l)
  ModifiableNumber(a.l, b.l)
  ModifiableString(a.l, b.l)
  DAArrayEx2(a.l, b.l, c.l, d.l)
  DAArray2(a.l, b.l, c.l)
  ImportGeometryWrapped(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l, l.l, m.l, n.l, o.l, p.l, q.l)
  ImportGeometryWrappedAsync(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l, l.l, m.l, n.l, o.l, p.l, q.l, r.l)
  ImportDirect3DRMVisualWrapped(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l, l.l, m.l, n.l, o.l, p.l, q.l)
  UntilNotifyScript(a.l, b.l, c.l, d.l)
  get_ViewFrameRate(a.l)
  UnionMontageArrayEx(a.l, b.l, c.l)
  UnionMontageArray(a.l, b.l)
  get_ModifiableBehaviorFlags(a.l)
  put_ModifiableBehaviorFlags(a.l)
  get_EmptyColor(a.l)
EndInterface

; IDAViewerControl interface definition
;
Interface IDAViewerControl
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UpdateInterval(a.l)
  put_UpdateInterval(a.l)
  get_View(a.l)
  put_View(a.l)
  get_Image(a.l)
  put_Image(a.l)
  get_BackgroundImage(a.l)
  put_BackgroundImage(a.l)
  get_Sound(a.l)
  put_Sound(a.l)
  get_PixelLibrary(a.l)
  get_MeterLibrary(a.l)
  AddBehaviorToRun(a.l)
  Start()
  get_InputImage(a.l)
  get_OpaqueForHitDetect(a.l)
  put_OpaqueForHitDetect(a.l)
  get_TimerSource(a.l)
  put_TimerSource(a.l)
  RegisterErrorHandler(a.l)
EndInterface

; IDAViewerControlWindowed interface definition
;
Interface IDAViewerControlWindowed
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UpdateInterval(a.l)
  put_UpdateInterval(a.l)
  get_View(a.l)
  put_View(a.l)
  get_Image(a.l)
  put_Image(a.l)
  get_BackgroundImage(a.l)
  put_BackgroundImage(a.l)
  get_Sound(a.l)
  put_Sound(a.l)
  get_PixelLibrary(a.l)
  get_MeterLibrary(a.l)
  AddBehaviorToRun(a.l)
  Start()
  get_InputImage(a.l)
  get_OpaqueForHitDetect(a.l)
  put_OpaqueForHitDetect(a.l)
  get_TimerSource(a.l)
  put_TimerSource(a.l)
  RegisterErrorHandler(a.l)
EndInterface

; IDA2ViewerControl interface definition
;
Interface IDA2ViewerControl
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UpdateInterval(a.l)
  put_UpdateInterval(a.l)
  get_View(a.l)
  put_View(a.l)
  get_Image(a.l)
  put_Image(a.l)
  get_BackgroundImage(a.l)
  put_BackgroundImage(a.l)
  get_Sound(a.l)
  put_Sound(a.l)
  get_PixelLibrary(a.l)
  get_MeterLibrary(a.l)
  AddBehaviorToRun(a.l)
  Start()
  get_InputImage(a.l)
  get_OpaqueForHitDetect(a.l)
  put_OpaqueForHitDetect(a.l)
  get_TimerSource(a.l)
  put_TimerSource(a.l)
  RegisterErrorHandler(a.l)
  SetPreference(a.l, b.l)
  GetPreference(a.l, b.l)
EndInterface

; IDA2ViewerControlWindowed interface definition
;
Interface IDA2ViewerControlWindowed
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UpdateInterval(a.l)
  put_UpdateInterval(a.l)
  get_View(a.l)
  put_View(a.l)
  get_Image(a.l)
  put_Image(a.l)
  get_BackgroundImage(a.l)
  put_BackgroundImage(a.l)
  get_Sound(a.l)
  put_Sound(a.l)
  get_PixelLibrary(a.l)
  get_MeterLibrary(a.l)
  AddBehaviorToRun(a.l)
  Start()
  get_InputImage(a.l)
  get_OpaqueForHitDetect(a.l)
  put_OpaqueForHitDetect(a.l)
  get_TimerSource(a.l)
  put_TimerSource(a.l)
  RegisterErrorHandler(a.l)
  SetPreference(a.l, b.l)
  GetPreference(a.l, b.l)
EndInterface
