
; IWebBrowser interface definition
;
Interface IWebBrowser
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GoBack()
  GoForward()
  GoHome()
  GoSearch()
  Navigate(a.p-bstr, b.l, c.l, d.l, e.l)
  Refresh()
  Refresh2(a.l)
  Stop()
  get_Application(a.l)
  get_Parent(a.l)
  get_Container(a.l)
  get_Document(a.l)
  get_TopLevelContainer(a.l)
  get_Type(a.l)
  get_Left(a.l)
  put_Left(a.l)
  get_Top(a.l)
  put_Top(a.l)
  get_Width(a.l)
  put_Width(a.l)
  get_Height(a.l)
  put_Height(a.l)
  get_LocationName(a.l)
  get_LocationURL(a.l)
  get_Busy(a.l)
EndInterface

; DWebBrowserEvents interface definition
;
Interface DWebBrowserEvents
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
EndInterface

; IWebBrowserApp interface definition
;
Interface IWebBrowserApp
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GoBack()
  GoForward()
  GoHome()
  GoSearch()
  Navigate(a.p-bstr, b.l, c.l, d.l, e.l)
  Refresh()
  Refresh2(a.l)
  Stop()
  get_Application(a.l)
  get_Parent(a.l)
  get_Container(a.l)
  get_Document(a.l)
  get_TopLevelContainer(a.l)
  get_Type(a.l)
  get_Left(a.l)
  put_Left(a.l)
  get_Top(a.l)
  put_Top(a.l)
  get_Width(a.l)
  put_Width(a.l)
  get_Height(a.l)
  put_Height(a.l)
  get_LocationName(a.l)
  get_LocationURL(a.l)
  get_Busy(a.l)
  Quit()
  ClientToWindow(a.l, b.l)
  PutProperty(a.p-bstr, b.p-variant)
  GetProperty(a.p-bstr, b.l)
  get_Name(a.l)
  get_HWND(a.l)
  get_FullName(a.l)
  get_Path(a.l)
  get_Visible(a.l)
  put_Visible(a.l)
  get_StatusBar(a.l)
  put_StatusBar(a.l)
  get_StatusText(a.l)
  put_StatusText(a.p-bstr)
  get_ToolBar(a.l)
  put_ToolBar(a.l)
  get_MenuBar(a.l)
  put_MenuBar(a.l)
  get_FullScreen(a.l)
  put_FullScreen(a.l)
EndInterface

; IWebBrowser2 interface definition
;
Interface IWebBrowser2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GoBack()
  GoForward()
  GoHome()
  GoSearch()
  Navigate(a.p-bstr, b.l, c.l, d.l, e.l)
  Refresh()
  Refresh2(a.l)
  Stop()
  get_Application(a.l)
  get_Parent(a.l)
  get_Container(a.l)
  get_Document(a.l)
  get_TopLevelContainer(a.l)
  get_Type(a.l)
  get_Left(a.l)
  put_Left(a.l)
  get_Top(a.l)
  put_Top(a.l)
  get_Width(a.l)
  put_Width(a.l)
  get_Height(a.l)
  put_Height(a.l)
  get_LocationName(a.l)
  get_LocationURL(a.l)
  get_Busy(a.l)
  Quit()
  ClientToWindow(a.l, b.l)
  PutProperty(a.p-bstr, b.p-variant)
  GetProperty(a.p-bstr, b.l)
  get_Name(a.l)
  get_HWND(a.l)
  get_FullName(a.l)
  get_Path(a.l)
  get_Visible(a.l)
  put_Visible(a.l)
  get_StatusBar(a.l)
  put_StatusBar(a.l)
  get_StatusText(a.l)
  put_StatusText(a.p-bstr)
  get_ToolBar(a.l)
  put_ToolBar(a.l)
  get_MenuBar(a.l)
  put_MenuBar(a.l)
  get_FullScreen(a.l)
  put_FullScreen(a.l)
  Navigate2(a.l, b.l, c.l, d.l, e.l)
  QueryStatusWB(a.l, b.l)
  ExecWB(a.l, b.l, c.l, d.l)
  ShowBrowserBar(a.l, b.l, c.l)
  get_ReadyState(a.l)
  get_Offline(a.l)
  put_Offline(a.l)
  get_Silent(a.l)
  put_Silent(a.l)
  get_RegisterAsBrowser(a.l)
  put_RegisterAsBrowser(a.l)
  get_RegisterAsDropTarget(a.l)
  put_RegisterAsDropTarget(a.l)
  get_TheaterMode(a.l)
  put_TheaterMode(a.l)
  get_AddressBar(a.l)
  put_AddressBar(a.l)
  get_Resizable(a.l)
  put_Resizable(a.l)
EndInterface

; DWebBrowserEvents2 interface definition
;
Interface DWebBrowserEvents2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
EndInterface

; DShellWindowsEvents interface definition
;
Interface DShellWindowsEvents
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
EndInterface

; IShellWindows interface definition
;
Interface IShellWindows
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Count(a.l)
  Item(a.p-variant, b.l)
  _NewEnum(a.l)
  Register(a.l, b.l, c.l, d.l)
  RegisterPending(a.l, b.l, c.l, d.l, e.l)
  Revoke(a.l)
  OnNavigate(a.l, b.l)
  OnActivated(a.l, b.l)
  FindWindowSW(a.l, b.l, c.l, d.l, e.l, f.l)
  OnCreated(a.l, b.l)
  ProcessAttachDetach(a.l)
EndInterface

; IShellUIHelper interface definition
;
Interface IShellUIHelper
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  ResetFirstBootMode()
  ResetSafeMode()
  RefreshOfflineDesktop()
  AddFavorite(a.p-bstr, b.l)
  AddChannel(a.p-bstr)
  AddDesktopComponent(a.p-bstr, b.p-bstr, c.l, d.l, e.l, f.l)
  IsSubscribed(a.p-bstr, b.l)
  NavigateAndFind(a.p-bstr, b.p-bstr, c.l)
  ImportExportFavorites(a.l, b.p-bstr)
  AutoCompleteSaveForm(a.l)
  AutoScan(a.p-bstr, b.p-bstr, c.l)
  AutoCompleteAttach(a.l)
  ShowBrowserUI(a.p-bstr, b.l, c.l)
EndInterface

; DShellNameSpaceEvents interface definition
;
Interface DShellNameSpaceEvents
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
EndInterface

; IShellFavoritesNameSpace interface definition
;
Interface IShellFavoritesNameSpace
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  MoveSelectionUp()
  MoveSelectionDown()
  ResetSort()
  NewFolder()
  Synchronize()
  Import()
  Export()
  InvokeContextMenuCommand(a.p-bstr)
  MoveSelectionTo()
  get_SubscriptionsEnabled(a.l)
  CreateSubscriptionForSelection(a.l)
  DeleteSubscriptionForSelection(a.l)
  SetRoot(a.p-bstr)
EndInterface

; IShellNameSpace interface definition
;
Interface IShellNameSpace
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  MoveSelectionUp()
  MoveSelectionDown()
  ResetSort()
  NewFolder()
  Synchronize()
  Import()
  Export()
  InvokeContextMenuCommand(a.p-bstr)
  MoveSelectionTo()
  get_SubscriptionsEnabled(a.l)
  CreateSubscriptionForSelection(a.l)
  DeleteSubscriptionForSelection(a.l)
  SetRoot(a.p-bstr)
  get_EnumOptions(a.l)
  put_EnumOptions(a.l)
  get_SelectedItem(a.l)
  put_SelectedItem(a.l)
  get_Root(a.l)
  put_Root(a.p-variant)
  get_Depth(a.l)
  put_Depth(a.l)
  get_Mode(a.l)
  put_Mode(a.l)
  get_Flags(a.l)
  put_Flags(a.l)
  put_TVFlags(a.l)
  get_TVFlags(a.l)
  get_Columns(a.l)
  put_Columns(a.p-bstr)
  get_CountViewTypes(a.l)
  SetViewType(a.l)
  SelectedItems(a.l)
  Expand(a.p-variant, b.l)
  UnselectAll()
EndInterface

; IScriptErrorList interface definition
;
Interface IScriptErrorList
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  advanceError()
  retreatError()
  canAdvanceError(a.l)
  canRetreatError(a.l)
  getErrorLine(a.l)
  getErrorChar(a.l)
  getErrorCode(a.l)
  getErrorMsg(a.l)
  getErrorUrl(a.l)
  getAlwaysShowLockState(a.l)
  getDetailsPaneOpen(a.l)
  setDetailsPaneOpen(a.l)
  getPerErrorDisplay(a.l)
  setPerErrorDisplay(a.l)
EndInterface

; ISearch interface definition
;
Interface ISearch
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Title(a.l)
  get_Id(a.l)
  get_Url(a.l)
EndInterface

; ISearches interface definition
;
Interface ISearches
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Count(a.l)
  get_Default(a.l)
  Item(a.p-variant, b.l)
  _NewEnum(a.l)
EndInterface

; ISearchAssistantOC interface definition
;
Interface ISearchAssistantOC
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  AddNextMenuItem(a.p-bstr, b.l)
  SetDefaultSearchUrl(a.p-bstr)
  NavigateToDefaultSearch()
  IsRestricted(a.p-bstr, b.l)
  get_ShellFeaturesEnabled(a.l)
  get_SearchAssistantDefault(a.l)
  get_Searches(a.l)
  get_InWebFolder(a.l)
  PutProperty(a.l, b.p-bstr, c.p-bstr)
  GetProperty(a.l, b.p-bstr, c.l)
  put_EventHandled(a.l)
  ResetNextMenu()
  FindOnWeb()
  FindFilesOrFolders()
  FindComputer()
  FindPrinter()
  FindPeople()
  GetSearchAssistantURL(a.l, b.l, c.l)
  NotifySearchSettingsChanged()
  put_ASProvider(a.p-bstr)
  get_ASProvider(a.l)
  put_ASSetting(a.l)
  get_ASSetting(a.l)
  NETDetectNextNavigate()
  PutFindText(a.p-bstr)
  get_Version(a.l)
  EncodeString(a.p-bstr, b.p-bstr, c.l, d.l)
EndInterface

; ISearchAssistantOC2 interface definition
;
Interface ISearchAssistantOC2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  AddNextMenuItem(a.p-bstr, b.l)
  SetDefaultSearchUrl(a.p-bstr)
  NavigateToDefaultSearch()
  IsRestricted(a.p-bstr, b.l)
  get_ShellFeaturesEnabled(a.l)
  get_SearchAssistantDefault(a.l)
  get_Searches(a.l)
  get_InWebFolder(a.l)
  PutProperty(a.l, b.p-bstr, c.p-bstr)
  GetProperty(a.l, b.p-bstr, c.l)
  put_EventHandled(a.l)
  ResetNextMenu()
  FindOnWeb()
  FindFilesOrFolders()
  FindComputer()
  FindPrinter()
  FindPeople()
  GetSearchAssistantURL(a.l, b.l, c.l)
  NotifySearchSettingsChanged()
  put_ASProvider(a.p-bstr)
  get_ASProvider(a.l)
  put_ASSetting(a.l)
  get_ASSetting(a.l)
  NETDetectNextNavigate()
  PutFindText(a.p-bstr)
  get_Version(a.l)
  EncodeString(a.p-bstr, b.p-bstr, c.l, d.l)
  get_ShowFindPrinter(a.l)
EndInterface

; ISearchAssistantOC3 interface definition
;
Interface ISearchAssistantOC3
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  AddNextMenuItem(a.p-bstr, b.l)
  SetDefaultSearchUrl(a.p-bstr)
  NavigateToDefaultSearch()
  IsRestricted(a.p-bstr, b.l)
  get_ShellFeaturesEnabled(a.l)
  get_SearchAssistantDefault(a.l)
  get_Searches(a.l)
  get_InWebFolder(a.l)
  PutProperty(a.l, b.p-bstr, c.p-bstr)
  GetProperty(a.l, b.p-bstr, c.l)
  put_EventHandled(a.l)
  ResetNextMenu()
  FindOnWeb()
  FindFilesOrFolders()
  FindComputer()
  FindPrinter()
  FindPeople()
  GetSearchAssistantURL(a.l, b.l, c.l)
  NotifySearchSettingsChanged()
  put_ASProvider(a.p-bstr)
  get_ASProvider(a.l)
  put_ASSetting(a.l)
  get_ASSetting(a.l)
  NETDetectNextNavigate()
  PutFindText(a.p-bstr)
  get_Version(a.l)
  EncodeString(a.p-bstr, b.p-bstr, c.l, d.l)
  get_ShowFindPrinter(a.l)
  get_SearchCompanionAvailable(a.l)
  put_UseSearchCompanion(a.l)
  get_UseSearchCompanion(a.l)
EndInterface

; _SearchAssistantEvents interface definition
;
Interface _SearchAssistantEvents
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
EndInterface
