
; IFaxTiff interface definition
;
Interface IFaxTiff
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_ReceiveTime(a.l)
  get_Image(a.l)
  put_Image(a.p-bstr)
  get_RecipientName(a.l)
  get_SenderName(a.l)
  get_Routing(a.l)
  get_CallerId(a.l)
  get_Csid(a.l)
  get_Tsid(a.l)
  get_RecipientNumber(a.l)
  get_RawReceiveTime(a.l)
  get_TiffTagString(a.l, b.l)
EndInterface

; IFaxServer interface definition
;
Interface IFaxServer
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  Connect(a.p-bstr)
  Disconnect()
  GetPorts(a.l)
  CreateDocument(a.p-bstr, b.l)
  GetJobs(a.l)
  get_Retries(a.l)
  put_Retries(a.l)
  get_RetryDelay(a.l)
  put_RetryDelay(a.l)
  get_DirtyDays(a.l)
  put_DirtyDays(a.l)
  get_Branding(a.l)
  put_Branding(a.l)
  get_UseDeviceTsid(a.l)
  put_UseDeviceTsid(a.l)
  get_ServerCoverpage(a.l)
  put_ServerCoverpage(a.l)
  get_PauseServerQueue(a.l)
  put_PauseServerQueue(a.l)
  get_ArchiveOutboundFaxes(a.l)
  put_ArchiveOutboundFaxes(a.l)
  get_ArchiveDirectory(a.l)
  put_ArchiveDirectory(a.p-bstr)
  get_ServerMapiProfile(a.l)
  put_ServerMapiProfile(a.p-bstr)
  get_DiscountRateStartHour(a.l)
  put_DiscountRateStartHour(a.l)
  get_DiscountRateStartMinute(a.l)
  put_DiscountRateStartMinute(a.l)
  get_DiscountRateEndHour(a.l)
  put_DiscountRateEndHour(a.l)
  get_DiscountRateEndMinute(a.l)
  put_DiscountRateEndMinute(a.l)
EndInterface

; IFaxPort interface definition
;
Interface IFaxPort
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_DeviceId(a.l)
  get_Rings(a.l)
  put_Rings(a.l)
  get_Csid(a.l)
  put_Csid(a.p-bstr)
  get_Tsid(a.l)
  put_Tsid(a.p-bstr)
  get_Send(a.l)
  put_Send(a.l)
  get_Receive(a.l)
  put_Receive(a.l)
  get_Priority(a.l)
  put_Priority(a.l)
  GetRoutingMethods(a.l)
  get_CanModify(a.l)
  GetStatus(a.l)
EndInterface

; IFaxPorts interface definition
;
Interface IFaxPorts
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Count(a.l)
  get_Item(a.l, b.l)
EndInterface

; IFaxRoutingMethod interface definition
;
Interface IFaxRoutingMethod
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_DeviceId(a.l)
  get_Enable(a.l)
  put_Enable(a.l)
  get_DeviceName(a.l)
  get_Guid(a.l)
  get_FunctionName(a.l)
  get_ImageName(a.l)
  get_FriendlyName(a.l)
  get_ExtensionName(a.l)
  get_RoutingData(a.l)
EndInterface

; IFaxRoutingMethods interface definition
;
Interface IFaxRoutingMethods
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Count(a.l)
  get_Item(a.l, b.l)
EndInterface

; IFaxStatus interface definition
;
Interface IFaxStatus
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_CallerId(a.l)
  get_Csid(a.l)
  get_CurrentPage(a.l)
  get_DeviceId(a.l)
  get_DeviceName(a.l)
  get_DocumentName(a.l)
  get_Send(a.l)
  get_Receive(a.l)
  get_Address(a.l)
  get_RoutingString(a.l)
  get_SenderName(a.l)
  get_RecipientName(a.l)
  get_DocumentSize(a.l)
  get_Description(a.l)
  get_PageCount(a.l)
  get_Tsid(a.l)
  get_StartTime(a.l)
  get_SubmittedTime(a.l)
  get_ElapsedTime(a.l)
  Refresh()
EndInterface

; IFaxDoc interface definition
;
Interface IFaxDoc
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_FileName(a.l)
  put_FileName(a.p-bstr)
  get_CoverpageName(a.l)
  put_CoverpageName(a.p-bstr)
  get_SendCoverpage(a.l)
  put_SendCoverpage(a.l)
  get_ServerCoverpage(a.l)
  put_ServerCoverpage(a.l)
  get_DiscountSend(a.l)
  put_DiscountSend(a.l)
  get_RecipientName(a.l)
  put_RecipientName(a.p-bstr)
  get_RecipientCompany(a.l)
  put_RecipientCompany(a.p-bstr)
  get_RecipientAddress(a.l)
  put_RecipientAddress(a.p-bstr)
  get_RecipientCity(a.l)
  put_RecipientCity(a.p-bstr)
  get_RecipientState(a.l)
  put_RecipientState(a.p-bstr)
  get_RecipientZip(a.l)
  put_RecipientZip(a.p-bstr)
  get_RecipientCountry(a.l)
  put_RecipientCountry(a.p-bstr)
  get_RecipientTitle(a.l)
  put_RecipientTitle(a.p-bstr)
  get_RecipientDepartment(a.l)
  put_RecipientDepartment(a.p-bstr)
  get_RecipientOffice(a.l)
  put_RecipientOffice(a.p-bstr)
  get_RecipientHomePhone(a.l)
  put_RecipientHomePhone(a.p-bstr)
  get_RecipientOfficePhone(a.l)
  put_RecipientOfficePhone(a.p-bstr)
  get_SenderName(a.l)
  put_SenderName(a.p-bstr)
  get_SenderCompany(a.l)
  put_SenderCompany(a.p-bstr)
  get_SenderAddress(a.l)
  put_SenderAddress(a.p-bstr)
  get_SenderTitle(a.l)
  put_SenderTitle(a.p-bstr)
  get_SenderDepartment(a.l)
  put_SenderDepartment(a.p-bstr)
  get_SenderOffice(a.l)
  put_SenderOffice(a.p-bstr)
  get_SenderHomePhone(a.l)
  put_SenderHomePhone(a.p-bstr)
  get_SenderOfficePhone(a.l)
  put_SenderOfficePhone(a.p-bstr)
  get_CoverpageNote(a.l)
  put_CoverpageNote(a.p-bstr)
  get_CoverpageSubject(a.l)
  put_CoverpageSubject(a.p-bstr)
  get_Tsid(a.l)
  put_Tsid(a.p-bstr)
  get_BillingCode(a.l)
  put_BillingCode(a.p-bstr)
  get_EmailAddress(a.l)
  put_EmailAddress(a.p-bstr)
  get_DisplayName(a.l)
  put_DisplayName(a.p-bstr)
  Send(a.l)
  get_FaxNumber(a.l)
  put_FaxNumber(a.p-bstr)
  putref_ConnectionObject(a.l)
  get_CallHandle(a.l)
  put_CallHandle(a.l)
  get_SenderFax(a.l)
  put_SenderFax(a.p-bstr)
EndInterface

; IFaxJobs interface definition
;
Interface IFaxJobs
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Count(a.l)
  get_Item(a.l, b.l)
EndInterface

; IFaxJob interface definition
;
Interface IFaxJob
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_JobId(a.l)
  get_Type(a.l)
  get_UserName(a.l)
  get_QueueStatus(a.l)
  get_DeviceStatus(a.l)
  get_PageCount(a.l)
  get_FaxNumber(a.l)
  get_RecipientName(a.l)
  get_Tsid(a.l)
  get_SenderName(a.l)
  get_SenderCompany(a.l)
  get_SenderDept(a.l)
  get_BillingCode(a.l)
  get_DisplayName(a.l)
  get_DiscountSend(a.l)
  SetStatus(a.l)
  Refresh()
EndInterface
