
; IADs interface definition
;
Interface IADs
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
EndInterface

; IADsContainer interface definition
;
Interface IADsContainer
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Count(a.l)
  get__NewEnum(a.l)
  get_Filter(a.l)
  put_Filter(a.p-variant)
  get_Hints(a.l)
  put_Hints(a.p-variant)
  GetObject(a.p-bstr, b.p-bstr, c.l)
  Create(a.p-bstr, b.p-bstr, c.l)
  Delete(a.p-bstr, b.p-bstr)
  CopyHere(a.p-bstr, b.p-bstr, c.l)
  MoveHere(a.p-bstr, b.p-bstr, c.l)
EndInterface

; IADsCollection interface definition
;
Interface IADsCollection
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get__NewEnum(a.l)
  Add(a.p-bstr, b.p-variant)
  Remove(a.p-bstr)
  GetObject(a.p-bstr, b.l)
EndInterface

; IADsMembers interface definition
;
Interface IADsMembers
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Count(a.l)
  get__NewEnum(a.l)
  get_Filter(a.l)
  put_Filter(a.p-variant)
EndInterface

; IADsPropertyList interface definition
;
Interface IADsPropertyList
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_PropertyCount(a.l)
  Next(a.l)
  Skip(a.l)
  Reset()
  Item(a.p-variant, b.l)
  GetPropertyItem(a.p-bstr, b.l, c.l)
  PutPropertyItem(a.p-variant)
  ResetPropertyItem(a.p-variant)
  PurgePropertyList()
EndInterface

; IADsPropertyEntry interface definition
;
Interface IADsPropertyEntry
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  Clear()
  get_Name(a.l)
  put_Name(a.p-bstr)
  get_ADsType(a.l)
  put_ADsType(a.l)
  get_ControlCode(a.l)
  put_ControlCode(a.l)
  get_Values(a.l)
  put_Values(a.p-variant)
EndInterface

; IADsPropertyValue interface definition
;
Interface IADsPropertyValue
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  Clear()
  get_ADsType(a.l)
  put_ADsType(a.l)
  get_DNString(a.l)
  put_DNString(a.p-bstr)
  get_CaseExactString(a.l)
  put_CaseExactString(a.p-bstr)
  get_CaseIgnoreString(a.l)
  put_CaseIgnoreString(a.p-bstr)
  get_PrintableString(a.l)
  put_PrintableString(a.p-bstr)
  get_NumericString(a.l)
  put_NumericString(a.p-bstr)
  get_Boolean(a.l)
  put_Boolean(a.l)
  get_Integer(a.l)
  put_Integer(a.l)
  get_OctetString(a.l)
  put_OctetString(a.p-variant)
  get_SecurityDescriptor(a.l)
  put_SecurityDescriptor(a.l)
  get_LargeInteger(a.l)
  put_LargeInteger(a.l)
  get_UTCTime(a.l)
  put_UTCTime(a.l)
EndInterface

; IADsPropertyValue2 interface definition
;
Interface IADsPropertyValue2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetObjectProperty(a.l, b.l)
  PutObjectProperty(a.l, b.p-variant)
EndInterface

; IPrivateDispatch interface definition
;
Interface IPrivateDispatch
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  ADSIInitializeDispatchManager(a.l)
  ADSIGetTypeInfoCount(a.l)
  ADSIGetTypeInfo(a.l, b.l, c.l)
  ADSIGetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  ADSIInvoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
EndInterface

; IPrivateUnknown interface definition
;
Interface IPrivateUnknown
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  ADSIInitializeObject(a.p-bstr, b.p-bstr, c.l)
  ADSIReleaseObject()
EndInterface

; IADsExtension interface definition
;
Interface IADsExtension
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Operate(a.l, b.p-variant, c.p-variant, d.p-variant)
  PrivateGetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  PrivateInvoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
EndInterface

; IADsDeleteOps interface definition
;
Interface IADsDeleteOps
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  DeleteObject(a.l)
EndInterface

; IADsNamespaces interface definition
;
Interface IADsNamespaces
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_DefaultContainer(a.l)
  put_DefaultContainer(a.p-bstr)
EndInterface

; IADsClass interface definition
;
Interface IADsClass
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_PrimaryInterface(a.l)
  get_CLSID(a.l)
  put_CLSID(a.p-bstr)
  get_OID(a.l)
  put_OID(a.p-bstr)
  get_Abstract(a.l)
  put_Abstract(a.l)
  get_Auxiliary(a.l)
  put_Auxiliary(a.l)
  get_MandatoryProperties(a.l)
  put_MandatoryProperties(a.p-variant)
  get_OptionalProperties(a.l)
  put_OptionalProperties(a.p-variant)
  get_NamingProperties(a.l)
  put_NamingProperties(a.p-variant)
  get_DerivedFrom(a.l)
  put_DerivedFrom(a.p-variant)
  get_AuxDerivedFrom(a.l)
  put_AuxDerivedFrom(a.p-variant)
  get_PossibleSuperiors(a.l)
  put_PossibleSuperiors(a.p-variant)
  get_Containment(a.l)
  put_Containment(a.p-variant)
  get_Container(a.l)
  put_Container(a.l)
  get_HelpFileName(a.l)
  put_HelpFileName(a.p-bstr)
  get_HelpFileContext(a.l)
  put_HelpFileContext(a.l)
  Qualifiers(a.l)
EndInterface

; IADsProperty interface definition
;
Interface IADsProperty
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_OID(a.l)
  put_OID(a.p-bstr)
  get_Syntax(a.l)
  put_Syntax(a.p-bstr)
  get_MaxRange(a.l)
  put_MaxRange(a.l)
  get_MinRange(a.l)
  put_MinRange(a.l)
  get_MultiValued(a.l)
  put_MultiValued(a.l)
  Qualifiers(a.l)
EndInterface

; IADsSyntax interface definition
;
Interface IADsSyntax
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_OleAutoDataType(a.l)
  put_OleAutoDataType(a.l)
EndInterface

; IADsLocality interface definition
;
Interface IADsLocality
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_Description(a.l)
  put_Description(a.p-bstr)
  get_LocalityName(a.l)
  put_LocalityName(a.p-bstr)
  get_PostalAddress(a.l)
  put_PostalAddress(a.p-bstr)
  get_SeeAlso(a.l)
  put_SeeAlso(a.p-variant)
EndInterface

; IADsO interface definition
;
Interface IADsO
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_Description(a.l)
  put_Description(a.p-bstr)
  get_LocalityName(a.l)
  put_LocalityName(a.p-bstr)
  get_PostalAddress(a.l)
  put_PostalAddress(a.p-bstr)
  get_TelephoneNumber(a.l)
  put_TelephoneNumber(a.p-bstr)
  get_FaxNumber(a.l)
  put_FaxNumber(a.p-bstr)
  get_SeeAlso(a.l)
  put_SeeAlso(a.p-variant)
EndInterface

; IADsOU interface definition
;
Interface IADsOU
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_Description(a.l)
  put_Description(a.p-bstr)
  get_LocalityName(a.l)
  put_LocalityName(a.p-bstr)
  get_PostalAddress(a.l)
  put_PostalAddress(a.p-bstr)
  get_TelephoneNumber(a.l)
  put_TelephoneNumber(a.p-bstr)
  get_FaxNumber(a.l)
  put_FaxNumber(a.p-bstr)
  get_SeeAlso(a.l)
  put_SeeAlso(a.p-variant)
  get_BusinessCategory(a.l)
  put_BusinessCategory(a.p-bstr)
EndInterface

; IADsDomain interface definition
;
Interface IADsDomain
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_IsWorkgroup(a.l)
  get_MinPasswordLength(a.l)
  put_MinPasswordLength(a.l)
  get_MinPasswordAge(a.l)
  put_MinPasswordAge(a.l)
  get_MaxPasswordAge(a.l)
  put_MaxPasswordAge(a.l)
  get_MaxBadPasswordsAllowed(a.l)
  put_MaxBadPasswordsAllowed(a.l)
  get_PasswordHistoryLength(a.l)
  put_PasswordHistoryLength(a.l)
  get_PasswordAttributes(a.l)
  put_PasswordAttributes(a.l)
  get_AutoUnlockInterval(a.l)
  put_AutoUnlockInterval(a.l)
  get_LockoutObservationInterval(a.l)
  put_LockoutObservationInterval(a.l)
EndInterface

; IADsComputer interface definition
;
Interface IADsComputer
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_ComputerID(a.l)
  get_Site(a.l)
  get_Description(a.l)
  put_Description(a.p-bstr)
  get_Location(a.l)
  put_Location(a.p-bstr)
  get_PrimaryUser(a.l)
  put_PrimaryUser(a.p-bstr)
  get_Owner(a.l)
  put_Owner(a.p-bstr)
  get_Division(a.l)
  put_Division(a.p-bstr)
  get_Department(a.l)
  put_Department(a.p-bstr)
  get_Role(a.l)
  put_Role(a.p-bstr)
  get_OperatingSystem(a.l)
  put_OperatingSystem(a.p-bstr)
  get_OperatingSystemVersion(a.l)
  put_OperatingSystemVersion(a.p-bstr)
  get_Model(a.l)
  put_Model(a.p-bstr)
  get_Processor(a.l)
  put_Processor(a.p-bstr)
  get_ProcessorCount(a.l)
  put_ProcessorCount(a.p-bstr)
  get_MemorySize(a.l)
  put_MemorySize(a.p-bstr)
  get_StorageCapacity(a.l)
  put_StorageCapacity(a.p-bstr)
  get_NetAddresses(a.l)
  put_NetAddresses(a.p-variant)
EndInterface

; IADsComputerOperations interface definition
;
Interface IADsComputerOperations
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  Status(a.l)
  Shutdown(a.l)
EndInterface

; IADsGroup interface definition
;
Interface IADsGroup
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_Description(a.l)
  put_Description(a.p-bstr)
  Members(a.l)
  IsMember(a.p-bstr, b.l)
  Add(a.p-bstr)
  Remove(a.p-bstr)
EndInterface

; IADsUser interface definition
;
Interface IADsUser
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_BadLoginAddress(a.l)
  get_BadLoginCount(a.l)
  get_LastLogin(a.l)
  get_LastLogoff(a.l)
  get_LastFailedLogin(a.l)
  get_PasswordLastChanged(a.l)
  get_Description(a.l)
  put_Description(a.p-bstr)
  get_Division(a.l)
  put_Division(a.p-bstr)
  get_Department(a.l)
  put_Department(a.p-bstr)
  get_EmployeeID(a.l)
  put_EmployeeID(a.p-bstr)
  get_FullName(a.l)
  put_FullName(a.p-bstr)
  get_FirstName(a.l)
  put_FirstName(a.p-bstr)
  get_LastName(a.l)
  put_LastName(a.p-bstr)
  get_OtherName(a.l)
  put_OtherName(a.p-bstr)
  get_NamePrefix(a.l)
  put_NamePrefix(a.p-bstr)
  get_NameSuffix(a.l)
  put_NameSuffix(a.p-bstr)
  get_Title(a.l)
  put_Title(a.p-bstr)
  get_Manager(a.l)
  put_Manager(a.p-bstr)
  get_TelephoneHome(a.l)
  put_TelephoneHome(a.p-variant)
  get_TelephoneMobile(a.l)
  put_TelephoneMobile(a.p-variant)
  get_TelephoneNumber(a.l)
  put_TelephoneNumber(a.p-variant)
  get_TelephonePager(a.l)
  put_TelephonePager(a.p-variant)
  get_FaxNumber(a.l)
  put_FaxNumber(a.p-variant)
  get_OfficeLocations(a.l)
  put_OfficeLocations(a.p-variant)
  get_PostalAddresses(a.l)
  put_PostalAddresses(a.p-variant)
  get_PostalCodes(a.l)
  put_PostalCodes(a.p-variant)
  get_SeeAlso(a.l)
  put_SeeAlso(a.p-variant)
  get_AccountDisabled(a.l)
  put_AccountDisabled(a.l)
  get_AccountExpirationDate(a.l)
  put_AccountExpirationDate(a.l)
  get_GraceLoginsAllowed(a.l)
  put_GraceLoginsAllowed(a.l)
  get_GraceLoginsRemaining(a.l)
  put_GraceLoginsRemaining(a.l)
  get_IsAccountLocked(a.l)
  put_IsAccountLocked(a.l)
  get_LoginHours(a.l)
  put_LoginHours(a.p-variant)
  get_LoginWorkstations(a.l)
  put_LoginWorkstations(a.p-variant)
  get_MaxLogins(a.l)
  put_MaxLogins(a.l)
  get_MaxStorage(a.l)
  put_MaxStorage(a.l)
  get_PasswordExpirationDate(a.l)
  put_PasswordExpirationDate(a.l)
  get_PasswordMinimumLength(a.l)
  put_PasswordMinimumLength(a.l)
  get_PasswordRequired(a.l)
  put_PasswordRequired(a.l)
  get_RequireUniquePassword(a.l)
  put_RequireUniquePassword(a.l)
  get_EmailAddress(a.l)
  put_EmailAddress(a.p-bstr)
  get_HomeDirectory(a.l)
  put_HomeDirectory(a.p-bstr)
  get_Languages(a.l)
  put_Languages(a.p-variant)
  get_Profile(a.l)
  put_Profile(a.p-bstr)
  get_LoginScript(a.l)
  put_LoginScript(a.p-bstr)
  get_Picture(a.l)
  put_Picture(a.p-variant)
  get_HomePage(a.l)
  put_HomePage(a.p-bstr)
  Groups(a.l)
  SetPassword(a.p-bstr)
  ChangePassword(a.p-bstr, b.p-bstr)
EndInterface

; IADsPrintQueue interface definition
;
Interface IADsPrintQueue
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_PrinterPath(a.l)
  put_PrinterPath(a.p-bstr)
  get_Model(a.l)
  put_Model(a.p-bstr)
  get_Datatype(a.l)
  put_Datatype(a.p-bstr)
  get_PrintProcessor(a.l)
  put_PrintProcessor(a.p-bstr)
  get_Description(a.l)
  put_Description(a.p-bstr)
  get_Location(a.l)
  put_Location(a.p-bstr)
  get_StartTime(a.l)
  put_StartTime(a.l)
  get_UntilTime(a.l)
  put_UntilTime(a.l)
  get_DefaultJobPriority(a.l)
  put_DefaultJobPriority(a.l)
  get_Priority(a.l)
  put_Priority(a.l)
  get_BannerPage(a.l)
  put_BannerPage(a.p-bstr)
  get_PrintDevices(a.l)
  put_PrintDevices(a.p-variant)
  get_NetAddresses(a.l)
  put_NetAddresses(a.p-variant)
EndInterface

; IADsPrintQueueOperations interface definition
;
Interface IADsPrintQueueOperations
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_Status(a.l)
  PrintJobs(a.l)
  Pause()
  Resume()
  Purge()
EndInterface

; IADsPrintJob interface definition
;
Interface IADsPrintJob
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_HostPrintQueue(a.l)
  get_User(a.l)
  get_UserPath(a.l)
  get_TimeSubmitted(a.l)
  get_TotalPages(a.l)
  get_Size(a.l)
  get_Description(a.l)
  put_Description(a.p-bstr)
  get_Priority(a.l)
  put_Priority(a.l)
  get_StartTime(a.l)
  put_StartTime(a.l)
  get_UntilTime(a.l)
  put_UntilTime(a.l)
  get_Notify(a.l)
  put_Notify(a.p-bstr)
  get_NotifyPath(a.l)
  put_NotifyPath(a.p-bstr)
EndInterface

; IADsPrintJobOperations interface definition
;
Interface IADsPrintJobOperations
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_Status(a.l)
  get_TimeElapsed(a.l)
  get_PagesPrinted(a.l)
  get_Position(a.l)
  put_Position(a.l)
  Pause()
  Resume()
EndInterface

; IADsService interface definition
;
Interface IADsService
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_HostComputer(a.l)
  put_HostComputer(a.p-bstr)
  get_DisplayName(a.l)
  put_DisplayName(a.p-bstr)
  get_Version(a.l)
  put_Version(a.p-bstr)
  get_ServiceType(a.l)
  put_ServiceType(a.l)
  get_StartType(a.l)
  put_StartType(a.l)
  get_Path(a.l)
  put_Path(a.p-bstr)
  get_StartupParameters(a.l)
  put_StartupParameters(a.p-bstr)
  get_ErrorControl(a.l)
  put_ErrorControl(a.l)
  get_LoadOrderGroup(a.l)
  put_LoadOrderGroup(a.p-bstr)
  get_ServiceAccountName(a.l)
  put_ServiceAccountName(a.p-bstr)
  get_ServiceAccountPath(a.l)
  put_ServiceAccountPath(a.p-bstr)
  get_Dependencies(a.l)
  put_Dependencies(a.p-variant)
EndInterface

; IADsServiceOperations interface definition
;
Interface IADsServiceOperations
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_Status(a.l)
  Start()
  Stop()
  Pause()
  Continue()
  SetPassword(a.p-bstr)
EndInterface

; IADsFileService interface definition
;
Interface IADsFileService
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_HostComputer(a.l)
  put_HostComputer(a.p-bstr)
  get_DisplayName(a.l)
  put_DisplayName(a.p-bstr)
  get_Version(a.l)
  put_Version(a.p-bstr)
  get_ServiceType(a.l)
  put_ServiceType(a.l)
  get_StartType(a.l)
  put_StartType(a.l)
  get_Path(a.l)
  put_Path(a.p-bstr)
  get_StartupParameters(a.l)
  put_StartupParameters(a.p-bstr)
  get_ErrorControl(a.l)
  put_ErrorControl(a.l)
  get_LoadOrderGroup(a.l)
  put_LoadOrderGroup(a.p-bstr)
  get_ServiceAccountName(a.l)
  put_ServiceAccountName(a.p-bstr)
  get_ServiceAccountPath(a.l)
  put_ServiceAccountPath(a.p-bstr)
  get_Dependencies(a.l)
  put_Dependencies(a.p-variant)
  get_Description(a.l)
  put_Description(a.p-bstr)
  get_MaxUserCount(a.l)
  put_MaxUserCount(a.l)
EndInterface

; IADsFileServiceOperations interface definition
;
Interface IADsFileServiceOperations
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_Status(a.l)
  Start()
  Stop()
  Pause()
  Continue()
  SetPassword(a.p-bstr)
  Sessions(a.l)
  Resources(a.l)
EndInterface

; IADsFileShare interface definition
;
Interface IADsFileShare
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_CurrentUserCount(a.l)
  get_Description(a.l)
  put_Description(a.p-bstr)
  get_HostComputer(a.l)
  put_HostComputer(a.p-bstr)
  get_Path(a.l)
  put_Path(a.p-bstr)
  get_MaxUserCount(a.l)
  put_MaxUserCount(a.l)
EndInterface

; IADsSession interface definition
;
Interface IADsSession
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_User(a.l)
  get_UserPath(a.l)
  get_Computer(a.l)
  get_ComputerPath(a.l)
  get_ConnectTime(a.l)
  get_IdleTime(a.l)
EndInterface

; IADsResource interface definition
;
Interface IADsResource
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Name(a.l)
  get_Class(a.l)
  get_GUID(a.l)
  get_ADsPath(a.l)
  get_Parent(a.l)
  get_Schema(a.l)
  GetInfo()
  SetInfo()
  Get(a.p-bstr, b.l)
  Put(a.p-bstr, b.p-variant)
  GetEx(a.p-bstr, b.l)
  PutEx(a.l, b.p-bstr, c.p-variant)
  GetInfoEx(a.p-variant, b.l)
  get_User(a.l)
  get_UserPath(a.l)
  get_Path(a.l)
  get_LockCount(a.l)
EndInterface

; IADsOpenDSObject interface definition
;
Interface IADsOpenDSObject
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  OpenDSObject(a.p-bstr, b.p-bstr, c.p-bstr, d.l, e.l)
EndInterface

; IDirectoryObject interface definition
;
Interface IDirectoryObject
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetObjectInformation(a.l)
  GetObjectAttributes(a.l, b.l, c.l, d.l)
  SetObjectAttributes(a.l, b.l, c.l)
  CreateDSObject(a.p-unicode, b.l, c.l, d.l)
  DeleteDSObject(a.p-unicode)
EndInterface

; IDirectorySearch interface definition
;
Interface IDirectorySearch
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  SetSearchPreference(a.l, b.l)
  ExecuteSearch(a.p-unicode, b.l, c.l, d.l)
  AbandonSearch(a.l)
  GetFirstRow(a.l)
  GetNextRow(a.l)
  GetPreviousRow(a.l)
  GetNextColumnName(a.l, b.l)
  GetColumn(a.l, b.p-unicode, c.l)
  FreeColumn(a.l)
  CloseSearchHandle(a.l)
EndInterface

; IDirectorySchemaMgmt interface definition
;
Interface IDirectorySchemaMgmt
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  EnumAttributes(a.l, b.l, c.l, d.l)
  CreateAttributeDefinition(a.p-unicode, b.l)
  WriteAttributeDefinition(a.p-unicode, b.l)
  DeleteAttributeDefinition(a.p-unicode)
  EnumClasses(a.l, b.l, c.l, d.l)
  WriteClassDefinition(a.p-unicode, b.l)
  CreateClassDefinition(a.p-unicode, b.l)
  DeleteClassDefinition(a.p-unicode)
EndInterface

; IADsAggregatee interface definition
;
Interface IADsAggregatee
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  ConnectAsAggregatee(a.l)
  DisconnectAsAggregatee()
  RelinquishInterface(a.l)
  RestoreInterface(a.l)
EndInterface

; IADsAggregator interface definition
;
Interface IADsAggregator
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  ConnectAsAggregator(a.l)
  DisconnectAsAggregator()
EndInterface

; IADsAccessControlEntry interface definition
;
Interface IADsAccessControlEntry
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_AccessMask(a.l)
  put_AccessMask(a.l)
  get_AceType(a.l)
  put_AceType(a.l)
  get_AceFlags(a.l)
  put_AceFlags(a.l)
  get_Flags(a.l)
  put_Flags(a.l)
  get_ObjectType(a.l)
  put_ObjectType(a.p-bstr)
  get_InheritedObjectType(a.l)
  put_InheritedObjectType(a.p-bstr)
  get_Trustee(a.l)
  put_Trustee(a.p-bstr)
EndInterface

; IADsAccessControlList interface definition
;
Interface IADsAccessControlList
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_AclRevision(a.l)
  put_AclRevision(a.l)
  get_AceCount(a.l)
  put_AceCount(a.l)
  AddAce(a.l)
  RemoveAce(a.l)
  CopyAccessList(a.l)
  get__NewEnum(a.l)
EndInterface

; IADsSecurityDescriptor interface definition
;
Interface IADsSecurityDescriptor
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Revision(a.l)
  put_Revision(a.l)
  get_Control(a.l)
  put_Control(a.l)
  get_Owner(a.l)
  put_Owner(a.p-bstr)
  get_OwnerDefaulted(a.l)
  put_OwnerDefaulted(a.l)
  get_Group(a.l)
  put_Group(a.p-bstr)
  get_GroupDefaulted(a.l)
  put_GroupDefaulted(a.l)
  get_DiscretionaryAcl(a.l)
  put_DiscretionaryAcl(a.l)
  get_DaclDefaulted(a.l)
  put_DaclDefaulted(a.l)
  get_SystemAcl(a.l)
  put_SystemAcl(a.l)
  get_SaclDefaulted(a.l)
  put_SaclDefaulted(a.l)
  CopySecurityDescriptor(a.l)
EndInterface

; IADsLargeInteger interface definition
;
Interface IADsLargeInteger
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_HighPart(a.l)
  put_HighPart(a.l)
  get_LowPart(a.l)
  put_LowPart(a.l)
EndInterface

; IADsNameTranslate interface definition
;
Interface IADsNameTranslate
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  put_ChaseReferral(a.l)
  Init(a.l, b.p-bstr)
  InitEx(a.l, b.p-bstr, c.p-bstr, d.p-bstr, e.p-bstr)
  Set(a.l, b.p-bstr)
  Get(a.l, b.l)
  SetEx(a.l, b.p-variant)
  GetEx(a.l, b.l)
EndInterface

; IADsCaseIgnoreList interface definition
;
Interface IADsCaseIgnoreList
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_CaseIgnoreList(a.l)
  put_CaseIgnoreList(a.p-variant)
EndInterface

; IADsFaxNumber interface definition
;
Interface IADsFaxNumber
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_TelephoneNumber(a.l)
  put_TelephoneNumber(a.p-bstr)
  get_Parameters(a.l)
  put_Parameters(a.p-variant)
EndInterface

; IADsNetAddress interface definition
;
Interface IADsNetAddress
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_AddressType(a.l)
  put_AddressType(a.l)
  get_Address(a.l)
  put_Address(a.p-variant)
EndInterface

; IADsOctetList interface definition
;
Interface IADsOctetList
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_OctetList(a.l)
  put_OctetList(a.p-variant)
EndInterface

; IADsEmail interface definition
;
Interface IADsEmail
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Type(a.l)
  put_Type(a.l)
  get_Address(a.l)
  put_Address(a.p-bstr)
EndInterface

; IADsPath interface definition
;
Interface IADsPath
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Type(a.l)
  put_Type(a.l)
  get_VolumeName(a.l)
  put_VolumeName(a.p-bstr)
  get_Path(a.l)
  put_Path(a.p-bstr)
EndInterface

; IADsReplicaPointer interface definition
;
Interface IADsReplicaPointer
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_ServerName(a.l)
  put_ServerName(a.p-bstr)
  get_ReplicaType(a.l)
  put_ReplicaType(a.l)
  get_ReplicaNumber(a.l)
  put_ReplicaNumber(a.l)
  get_Count(a.l)
  put_Count(a.l)
  get_ReplicaAddressHints(a.l)
  put_ReplicaAddressHints(a.p-variant)
EndInterface

; IADsAcl interface definition
;
Interface IADsAcl
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_ProtectedAttrName(a.l)
  put_ProtectedAttrName(a.p-bstr)
  get_SubjectName(a.l)
  put_SubjectName(a.p-bstr)
  get_Privileges(a.l)
  put_Privileges(a.l)
  CopyAcl(a.l)
EndInterface

; IADsTimestamp interface definition
;
Interface IADsTimestamp
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_WholeSeconds(a.l)
  put_WholeSeconds(a.l)
  get_EventID(a.l)
  put_EventID(a.l)
EndInterface

; IADsPostalAddress interface definition
;
Interface IADsPostalAddress
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_PostalAddress(a.l)
  put_PostalAddress(a.p-variant)
EndInterface

; IADsBackLink interface definition
;
Interface IADsBackLink
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_RemoteID(a.l)
  put_RemoteID(a.l)
  get_ObjectName(a.l)
  put_ObjectName(a.p-bstr)
EndInterface

; IADsTypedName interface definition
;
Interface IADsTypedName
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_ObjectName(a.l)
  put_ObjectName(a.p-bstr)
  get_Level(a.l)
  put_Level(a.l)
  get_Interval(a.l)
  put_Interval(a.l)
EndInterface

; IADsHold interface definition
;
Interface IADsHold
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_ObjectName(a.l)
  put_ObjectName(a.p-bstr)
  get_Amount(a.l)
  put_Amount(a.l)
EndInterface

; IADsObjectOptions interface definition
;
Interface IADsObjectOptions
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetOption(a.l, b.l)
  SetOption(a.l, b.p-variant)
EndInterface

; IADsPathname interface definition
;
Interface IADsPathname
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  Set(a.p-bstr, b.l)
  SetDisplayType(a.l)
  Retrieve(a.l, b.l)
  GetNumElements(a.l)
  GetElement(a.l, b.l)
  AddLeafElement(a.p-bstr)
  RemoveLeafElement()
  CopyPath(a.l)
  GetEscapedElement(a.l, b.p-bstr, c.l)
  get_EscapedMode(a.l)
  put_EscapedMode(a.l)
EndInterface

; IADsADSystemInfo interface definition
;
Interface IADsADSystemInfo
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UserName(a.l)
  get_ComputerName(a.l)
  get_SiteName(a.l)
  get_DomainShortName(a.l)
  get_DomainDNSName(a.l)
  get_ForestDNSName(a.l)
  get_PDCRoleOwner(a.l)
  get_SchemaRoleOwner(a.l)
  get_IsNativeMode(a.l)
  GetAnyDCName(a.l)
  GetDCSiteName(a.p-bstr, b.l)
  RefreshSchemaCache()
  GetTrees(a.l)
EndInterface

; IADsWinNTSystemInfo interface definition
;
Interface IADsWinNTSystemInfo
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UserName(a.l)
  get_ComputerName(a.l)
  get_DomainName(a.l)
  get_PDC(a.l)
EndInterface

; IADsDNWithBinary interface definition
;
Interface IADsDNWithBinary
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_BinaryValue(a.l)
  put_BinaryValue(a.p-variant)
  get_DNString(a.l)
  put_DNString(a.p-bstr)
EndInterface

; IADsDNWithString interface definition
;
Interface IADsDNWithString
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_StringValue(a.l)
  put_StringValue(a.p-bstr)
  get_DNString(a.l)
  put_DNString(a.p-bstr)
EndInterface

; IADsSecurityUtility interface definition
;
Interface IADsSecurityUtility
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetSecurityDescriptor(a.p-variant, b.l, c.l, d.l)
  SetSecurityDescriptor(a.p-variant, b.l, c.p-variant, d.l)
  ConvertSecurityDescriptor(a.p-variant, b.l, c.l, d.l)
  get_SecurityMask(a.l)
  put_SecurityMask(a.l)
EndInterface
