
; ITextDocument interface definition
;
Interface ITextDocument
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetName(a.l)
  GetSelection(a.l)
  GetStoryCount(a.l)
  GetStoryRanges(a.l)
  GetSaved(a.l)
  SetSaved(a.l)
  GetDefaultTabStop(a.l)
  SetDefaultTabStop(a.l)
  New()
  Open(a.l, b.l, c.l)
  Save(a.l, b.l, c.l)
  Freeze(a.l)
  Unfreeze(a.l)
  BeginEditCollection()
  EndEditCollection()
  Undo(a.l, b.l)
  Redo(a.l, b.l)
  Range(a.l, b.l, c.l)
  RangeFromPoint(a.l, b.l, c.l)
EndInterface

; ITextRange interface definition
;
Interface ITextRange
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetText(a.l)
  SetText(a.p-bstr)
  GetChar(a.l)
  SetChar(a.l)
  GetDuplicate(a.l)
  GetFormattedText(a.l)
  SetFormattedText(a.l)
  GetStart(a.l)
  SetStart(a.l)
  GetEnd(a.l)
  SetEnd(a.l)
  GetFont(a.l)
  SetFont(a.l)
  GetPara(a.l)
  SetPara(a.l)
  GetStoryLength(a.l)
  GetStoryType(a.l)
  Collapse(a.l)
  Expand(a.l, b.l)
  GetIndex(a.l, b.l)
  SetIndex(a.l, b.l, c.l)
  SetRange(a.l, b.l)
  InRange(a.l, b.l)
  InStory(a.l, b.l)
  IsEqual(a.l, b.l)
  Select()
  StartOf(a.l, b.l, c.l)
  EndOf(a.l, b.l, c.l)
  Move(a.l, b.l, c.l)
  MoveStart(a.l, b.l, c.l)
  MoveEnd(a.l, b.l, c.l)
  MoveWhile(a.l, b.l, c.l)
  MoveStartWhile(a.l, b.l, c.l)
  MoveEndWhile(a.l, b.l, c.l)
  MoveUntil(a.l, b.l, c.l)
  MoveStartUntil(a.l, b.l, c.l)
  MoveEndUntil(a.l, b.l, c.l)
  FindText(a.p-bstr, b.l, c.l, d.l)
  FindTextStart(a.p-bstr, b.l, c.l, d.l)
  FindTextEnd(a.p-bstr, b.l, c.l, d.l)
  Delete(a.l, b.l, c.l)
  Cut(a.l)
  Copy(a.l)
  Paste(a.l, b.l)
  CanPaste(a.l, b.l, c.l)
  CanEdit(a.l)
  ChangeCase(a.l)
  GetPoint(a.l, b.l, c.l)
  SetPoint(a.l, b.l, c.l, d.l)
  ScrollIntoView(a.l)
  GetEmbeddedObject(a.l)
EndInterface

; ITextSelection interface definition
;
Interface ITextSelection
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetText(a.l)
  SetText(a.p-bstr)
  GetChar(a.l)
  SetChar(a.l)
  GetDuplicate(a.l)
  GetFormattedText(a.l)
  SetFormattedText(a.l)
  GetStart(a.l)
  SetStart(a.l)
  GetEnd(a.l)
  SetEnd(a.l)
  GetFont(a.l)
  SetFont(a.l)
  GetPara(a.l)
  SetPara(a.l)
  GetStoryLength(a.l)
  GetStoryType(a.l)
  Collapse(a.l)
  Expand(a.l, b.l)
  GetIndex(a.l, b.l)
  SetIndex(a.l, b.l, c.l)
  SetRange(a.l, b.l)
  InRange(a.l, b.l)
  InStory(a.l, b.l)
  IsEqual(a.l, b.l)
  Select()
  StartOf(a.l, b.l, c.l)
  EndOf(a.l, b.l, c.l)
  Move(a.l, b.l, c.l)
  MoveStart(a.l, b.l, c.l)
  MoveEnd(a.l, b.l, c.l)
  MoveWhile(a.l, b.l, c.l)
  MoveStartWhile(a.l, b.l, c.l)
  MoveEndWhile(a.l, b.l, c.l)
  MoveUntil(a.l, b.l, c.l)
  MoveStartUntil(a.l, b.l, c.l)
  MoveEndUntil(a.l, b.l, c.l)
  FindText(a.p-bstr, b.l, c.l, d.l)
  FindTextStart(a.p-bstr, b.l, c.l, d.l)
  FindTextEnd(a.p-bstr, b.l, c.l, d.l)
  Delete(a.l, b.l, c.l)
  Cut(a.l)
  Copy(a.l)
  Paste(a.l, b.l)
  CanPaste(a.l, b.l, c.l)
  CanEdit(a.l)
  ChangeCase(a.l)
  GetPoint(a.l, b.l, c.l)
  SetPoint(a.l, b.l, c.l, d.l)
  ScrollIntoView(a.l)
  GetEmbeddedObject(a.l)
  GetFlags(a.l)
  SetFlags(a.l)
  GetType(a.l)
  MoveLeft(a.l, b.l, c.l, d.l)
  MoveRight(a.l, b.l, c.l, d.l)
  MoveUp(a.l, b.l, c.l, d.l)
  MoveDown(a.l, b.l, c.l, d.l)
  HomeKey(a.l, b.l, c.l)
  EndKey(a.l, b.l, c.l)
  TypeText(a.p-bstr)
EndInterface

; ITextFont interface definition
;
Interface ITextFont Extends IDispatch
  GetDuplicate(prop.i)
	SetDuplicate(Duplicate.i)
	CanChange(prop.i)
	IsEqual(pFont.i, prop.i)
	Reset(Value.l)
	GetStyle(prop.i)
	SetStyle(Style.l)
	GetAllCaps(prop.i)
	SetAllCaps(AllCaps.l)
	GetAnimation(prop.i)
	SetAnimation(Animation.l)
	GetBackColor(prop.i)
	SetBackColor(BackColor.l)
	GetBold(prop.i)
	SetBold(Bold.l)
	GetEmboss(prop.i)
	SetEmboss(Emboss.l)
	GetForeColor(prop.i)
	SetForeColor(ForeColor.l)
	GetHidden(prop.i)
	SetHidden(Hidden.l)
	GetEngrave(prop.i)
	SetEngrave(Engrave.l)
	GetItalic(prop.i)
	SetItalic(Italic.l)
	GetKerning(prop.i)
	SetKerning(Kerning.f)
	GetLanguageID(prop.i)
	SetLanguageID(LanguageID.l)
	GetName(prop.i)
	SetName(Name.p-bstr)
	GetOutline(prop.i)
	SetOutline(Outline.l)
	GetPosition(prop.i)
	SetPosition(Position.f)
	GetProtected(prop.i)
	SetProtected(Protected.l)
	GetShadow(prop.i)
	SetShadow(Shadow.l)
	GetSize(prop.i)
	SetSize(Size.f)
	GetSmallCaps(prop.i)
	SetSmallCaps(SmallCaps.l)
	GetSpacing(prop.i)
	SetSpacing(Spacing.f)
	GetStrikeThrough(prop.i)
	SetStrikeThrough(StrikeThrough.l)
	GetSubscript(prop.i)
	SetSubscript(Subscript.l)
	GetSuperscript(prop.i)
	SetSuperscript(Superscript.l)
	GetUnderline(prop.i)
	SetUnderline(Underline.l)
	GetWeight(prop.i)
	SetWeight(Weight.l)
EndInterface

; ITextPara interface definition
;
Interface ITextPara Extends IDispatch
  GetDuplicate(prop.i)
	SetDuplicate(Duplicate.i)
	CanChange(prop.i)
	IsEqual(pPara.i, prop.i)
	Reset(Value.l)
	GetStyle(prop.i)
	SetStyle(Style.l)
	GetAlignment(prop.i)
	SetAlignment(Alignment.l)
	GetHyphenation(prop.i)
	SetHyphenation(Hyphenation.l)
	GetFirstLineIndent(prop.i)
	GetKeepTogether(prop.i)
	SetKeepTogether(KeepTogether.l)
	GetKeepWithNext(prop.i)
	SetKeepWithNext(KeepWithNext.l)
	GetLeftIndent(prop.i)
	GetLineSpacing(prop.i)
	GetLineSpacingRule(prop.i)
	GetListAlignment(prop.i)
	SetListAlignment(ListAlignment.l)
	GetListLevelIndex(prop.i)
	SetListLevelIndex(ListLevelIndex.l)
	GetListStart(prop.i)
	SetListStart(ListStart.l)
	GetListTab(prop.i)
	SetListTab(ListTab.f)
	GetListType(prop.i)
	SetListType(ListType.l)
	GetNoLineNumber(prop.i)
	SetNoLineNumber(NoLineNumber.l)
	GetPageBreakBefore(prop.i)
	SetPageBreakBefore(PageBreakBefore.l)
	GetRightIndent(prop.i)
	SetRightIndent(RightIndent.f)
	SetIndents(First.f, Left.f, Right.f)
	SetLineSpacing(Rule.l, Spacing.f)
	GetSpaceAfter(prop.i)
	SetSpaceAfter(SpaceAfter.f)
	GetSpaceBefore(prop.i)
	SetSpaceBefore(SpaceBefore.f)
	GetWidowControl(prop.i)
	SetWidowControl(WidowControl.l)
	GetTabCount(prop.i)
	AddTab(tbPos.f, tbAlign.l, tbLeader.l)
	ClearAllTabs()
	DeleteTab(tbPos.f)
	GetTab(iTab.l, ptbPos.i, ptbAlign.i, ptbLeader.i)
EndInterface

; ITextStoryRanges interface definition
;
Interface ITextStoryRanges
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  _NewEnum(a.l)
  Item(a.l, b.l)
  GetCount(a.l)
EndInterface

; ITextDocument2 interface definition
;
Interface ITextDocument2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetName(a.l)
  GetSelection(a.l)
  GetStoryCount(a.l)
  GetStoryRanges(a.l)
  GetSaved(a.l)
  SetSaved(a.l)
  GetDefaultTabStop(a.l)
  SetDefaultTabStop(a.l)
  New()
  Open(a.l, b.l, c.l)
  Save(a.l, b.l, c.l)
  Freeze(a.l)
  Unfreeze(a.l)
  BeginEditCollection()
  EndEditCollection()
  Undo(a.l, b.l)
  Redo(a.l, b.l)
  Range(a.l, b.l, c.l)
  RangeFromPoint(a.l, b.l, c.l)
  AttachMsgFilter(a.l)
  SetEffectColor(a.l, b.l)
  GetEffectColor(a.l, b.l)
  GetCaretType(a.l)
  SetCaretType(a.l)
  GetImmContext(a.l)
  ReleaseImmContext(a.l)
  GetPreferredFont(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  GetNotificationMode(a.l)
  SetNotificationMode(a.l)
  GetClientRect(a.l, b.l, c.l, d.l, e.l)
  GetSelectionEx(a.l)
  GetWindow(a.l)
  GetFEFlags(a.l)
  UpdateWindow()
  CheckTextLimit(a.l, b.l)
  IMEInProgress(a.l)
  SysBeep()
  Update(a.l)
  Notify(a.l)
EndInterface

; ITextMsgFilter interface definition
;
Interface ITextMsgFilter
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  AttachDocument(a.l, b.l)
  HandleMessage(a.l, b.l, c.l, d.l)
  AttachMsgFilter(a.l)
EndInterface
