; --------------------------------------------------------------------------------------------
;  Copyright (c) Fantaisie Software. All rights reserved.
;  Dual licensed under the GPL and Fantaisie Software licenses.
;  See LICENSE and LICENSE-FANTAISIE in the project root for license information.
; --------------------------------------------------------------------------------------------
;
; DirectX Interface Definitions
;

IncludePath "InterfaceDX\"

IncludeFile "amaudio.pb"
IncludeFile "amparse.pb"
IncludeFile "amstream.pb"
IncludeFile "Amvideo.pb"
IncludeFile "austream.pb"
IncludeFile "bdaiface.pb"
; IncludeFile "bdatif.pb"
IncludeFile "control.pb"
IncludeFile "d3d.pb"
IncludeFile "d3d8.pb"
IncludeFile "d3d9.pb"
IncludeFile "d3drm.pb"
IncludeFile "d3drmobj.pb"
IncludeFile "d3drmwin.pb"
IncludeFile "d3dx9anim.pb"
IncludeFile "d3dx9core.pb"
IncludeFile "d3dx9effect.pb"
IncludeFile "d3dx9math.pb"
IncludeFile "d3dx9mesh.pb"
IncludeFile "d3dx9shader.pb"
IncludeFile "d3dx9xof.pb"
IncludeFile "ddraw.pb"
IncludeFile "ddstream.pb"
IncludeFile "dinput.pb"
IncludeFile "dinputd.pb"
IncludeFile "dmksctrl.pb"
IncludeFile "dmodshow.pb"
IncludeFile "dmplugin.pb"
IncludeFile "dmusicc.pb"
IncludeFile "dmusici.pb"
IncludeFile "dmusics.pb"
IncludeFile "dpaddr.pb"
IncludeFile "dplay.pb"
IncludeFile "dplay8.pb"
IncludeFile "dplobby.pb"
IncludeFile "dplobby8.pb"
IncludeFile "dpnathlp.pb"
IncludeFile "dshowasf.pb"
IncludeFile "dsound.pb"
IncludeFile "dvoice.pb"
IncludeFile "dvp.pb"
IncludeFile "DxDiag.pb"
IncludeFile "dxfile.pb"
IncludeFile "dxtrans.pb"
IncludeFile "il21dec.pb"
IncludeFile "Iwstdec.pb"
IncludeFile "ks.pb"
IncludeFile "ksproxy.pb"
IncludeFile "mediaobj.pb"
IncludeFile "medparam.pb"
IncludeFile "mixerocx.pb"
IncludeFile "mmstream.pb"
IncludeFile "mpconfig.pb"
IncludeFile "mpeg2data.pb"
IncludeFile "mpegtype.pb"
IncludeFile "Mstvca.pb"
IncludeFile "Mstve.pb"
IncludeFile "Msvidctl.pb"
IncludeFile "playlist.pb"
IncludeFile "qedit.pb"
IncludeFile "qnetwork.pb"
IncludeFile "regbag.pb"
IncludeFile "sbe.pb"
IncludeFile "Segment.pb"
IncludeFile "strmif.pb"
IncludeFile "tuner.pb"
IncludeFile "tvratings.pb"
IncludeFile "vidcap.pb"
IncludeFile "videoacc.pb"
IncludeFile "vmr9.pb"
IncludeFile "vpconfig.pb"
IncludeFile "vpnotify.pb"

; ExecutableFormat=
; EOF