# Small makefile to build the residents easily

all:
	pbcompiler PureBasic.pb /IGNORERESIDENT PureBasic.res /RESIDENT "$(PUREBASIC_HOME)\Residents\PureBasic.res" /QUIET
	pbcompiler Unicode.pb /IGNORERESIDENT Unicode.res /RESIDENT "$(PUREBASIC_HOME)\Residents\Unicode.res" /QUIET
	pbcompiler Unicode.pb /IGNORERESIDENT Unicode.res /UNICODE /RESIDENT "$(PUREBASIC_HOME)\Residents\Unicode\Unicode.res" /QUIET
	pbcompiler Windows.pb /IGNORERESIDENT Windows.res /RESIDENT "$(PUREBASIC_HOME)\Residents\Windows.res" /QUIET
	pbcompiler WindowsUnicode.pb /IGNORERESIDENT WindowsUnicode.res /RESIDENT "$(PUREBASIC_HOME)\Residents\WindowsUnicode.res" /QUIET
	pbcompiler WindowsUnicode.pb /IGNORERESIDENT WindowsUnicode.res /UNICODE /RESIDENT "$(PUREBASIC_HOME)\Residents\Unicode\WindowsUnicode.res" /QUIET
	pbcompiler Interface.pb /IGNORERESIDENT Interface.res /RESIDENT "$(PUREBASIC_HOME)\Residents\Interface.res" /QUIET
	pbcompiler InterfaceDX.pb /IGNORERESIDENT InterfaceDX.res /RESIDENT "$(PUREBASIC_HOME)\Residents\InterfaceDX.res" /QUIET
	pbcompiler ../expat.pb /IGNORERESIDENT Expat.res /RESIDENT "$(PUREBASIC_HOME)\Residents\Expat.res" /QUIET
	pbcompiler ../Scintilla.pb /IGNORERESIDENT Scintilla.res /RESIDENT "$(PUREBASIC_HOME)\Residents\Scintilla.res" /QUIET
	pbcompiler ../OpenGL.pb /IGNORERESIDENT OpenGL.res /RESIDENT "$(PUREBASIC_HOME)\Residents\OpenGL.res" /QUIET
