#
# Makefile for all included targets
# 

doc:
	"$(PUREBASIC_HOME)/SDK/DocMaker/DocMaker.exe" /LANGUAGE English /DOCUMENTATIONPATH "$(PB_SVN)/$(PB_BRANCH)/Documentation" /OUTPUTPATH "C:/PureBasic/BuildServer/Documentation"
