XIncludeFile "common.pbi"

CompilerIf #PB_GTK = 3
  ImportC "`pkg-config --libs gtk+-3.0` `pkg-config --libs gthread-2.0`"
  
CompilerElse ; GTK2
  ImportC "`pkg-config --libs gtk+-2.0` `pkg-config --libs gthread-2.0`"
  
  ; GTK 2 only functions
  ;
  ApiC(gdk_add_client_message_filter, (arg1, arg2, arg3))
  ApiC(gdk_display_add_client_message_filter, (arg1, arg2, arg3, arg4))
  ApiC(gdk_event_send_client_message, (arg1, arg2))
  ApiC(gdk_event_send_client_message_for_display, (arg1, arg2, arg3))
  ApiC(gdk_event_send_clientmessage_toall, (arg1))
  ApiC(gdk_screen_broadcast_client_message, (arg1, arg2))
CompilerEndIf

  ApiC(gdk_atom_intern, (arg1.p-utf8, arg2))
  ApiC(gdk_atom_name, (arg1))
  ApiC(gdk_axis_use_get_type, ())
  ApiC(gdk_beep, ())
  ApiC(gdk_bitmap_create_from_data, (arg1, arg2, arg3, arg4))
  ApiC(gdk_byte_order_get_type, ())
  ApiC(gdk_cap_style_get_type, ())
  ApiC(gdk_char_height, (arg1, arg2))
  ApiC(gdk_char_measure, (arg1, arg2))
  ApiC(gdk_char_width, (arg1, arg2))
  ApiC(gdk_char_width_wc, (arg1, arg2))
  ApiC(gdk_color_alloc, (arg1, arg2))
  ApiC(gdk_color_black, (arg1, arg2))
  ApiC(gdk_color_change, (arg1, arg2))
  ApiC(gdk_color_copy, (arg1))
  ApiC(gdk_color_equal, (arg1, arg2))
  ApiC(gdk_color_free, (arg1))
  ApiC(gdk_color_get_type, ())
  ApiC(gdk_color_hash, (arg1))
  ApiC(gdk_color_parse, (arg1, arg2))
  ApiC(gdk_color_white, (arg1, arg2))
  ApiC(gdk_colormap_alloc_color, (arg1, arg2, arg3, arg4))
  ApiC(gdk_colormap_alloc_colors, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_colormap_change, (arg1, arg2))
  ApiC(gdk_colormap_free_colors, (arg1, arg2, arg3))
  ApiC(gdk_colormap_get_screen, (arg1))
  ApiC(gdk_colormap_get_system, ())
  ApiC(gdk_colormap_get_system_size, ())
  ApiC(gdk_colormap_get_type, ())
  ApiC(gdk_colormap_get_visual, (arg1))
  ApiC(gdk_colormap_new, (arg1, arg2))
  ApiC(gdk_colormap_query_color, (arg1, arg2, arg3))
  ApiC(gdk_colormap_ref, (arg1))
  ApiC(gdk_colormap_unref, (arg1))
  ApiC(gdk_colors_alloc, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_colors_free, (arg1, arg2, arg3, arg4))
  ApiC(gdk_colors_store, (arg1))
  ApiC(gdk_crossing_mode_get_type, ())
  ApiC(gdk_cursor_get_display, (arg1))
  ApiC(gdk_cursor_get_type, ())
  ApiC(gdk_cursor_new, (arg1))
  ApiC(gdk_cursor_new_for_display, (arg1, arg2))
  ApiC(gdk_cursor_new_from_pixbuf, (arg1, arg2, arg3, arg4))
  ApiC(gdk_cursor_new_from_pixmap, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_cursor_ref, (arg1))
  ApiC(gdk_cursor_type_get_type, ())
  ApiC(gdk_cursor_unref, (arg1))
  ApiC(gdk_device_free_history, (arg1, arg2))
  ApiC(gdk_device_get_axis, (arg1, arg2, arg3, arg4))
  ApiC(gdk_device_get_core_pointer, ())
  ApiC(gdk_device_get_history, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_device_get_state, (arg1, arg2, arg3, arg4))
  ApiC(gdk_device_get_type, ())
  ApiC(gdk_device_set_axis_use, (arg1, arg2, arg3))
  ApiC(gdk_device_set_key, (arg1, arg2, arg3, arg4))
  ApiC(gdk_device_set_mode, (arg1, arg2))
  ApiC(gdk_device_set_source, (arg1, arg2))
  ApiC(gdk_devices_list, ())
  ApiC(gdk_display_beep, (arg1))
  ApiC(gdk_display_close, (arg1))
  ApiC(gdk_display_flush, (arg1))
  ApiC(gdk_display_get_core_pointer, (arg1))
  ApiC(gdk_display_get_default, ())
  ApiC(gdk_display_get_default_cursor_size, (arg1))
  ApiC(gdk_display_get_default_group, (arg1))
  ApiC(gdk_display_get_default_screen, (arg1))
  ApiC(gdk_display_get_event, (arg1))
  ApiC(gdk_display_get_maximal_cursor_size, (arg1, arg2, arg3))
  ApiC(gdk_display_get_n_screens, (arg1))
  ApiC(gdk_display_get_name, (arg1))
  ApiC(gdk_display_get_pointer, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_display_get_screen, (arg1, arg2))
  ApiC(gdk_display_get_type, ())
  ApiC(gdk_display_get_window_at_pointer, (arg1, arg2, arg3))
  ApiC(gdk_display_keyboard_ungrab, (arg1, arg2))
  ApiC(gdk_display_list_devices, (arg1))
  ApiC(gdk_display_manager_get, ())
  ApiC(gdk_display_manager_get_default_display, (arg1))
  ApiC(gdk_display_manager_get_type, ())
  ApiC(gdk_display_manager_list_displays, (arg1))
  ApiC(gdk_display_manager_set_default_display, (arg1, arg2))
  ApiC(gdk_display_open, (arg1))
  ApiC(gdk_display_open_default_libgtk_only, ())
  ApiC(gdk_display_peek_event, (arg1))
  ApiC(gdk_display_pointer_is_grabbed, (arg1))
  ApiC(gdk_display_pointer_ungrab, (arg1, arg2))
  ApiC(gdk_display_put_event, (arg1, arg2))
  ApiC(gdk_display_set_double_click_distance, (arg1, arg2))
  ApiC(gdk_display_set_double_click_time, (arg1, arg2))
  ApiC(gdk_display_set_pointer_hooks, (arg1, arg2))
  ApiC(gdk_display_supports_cursor_alpha, (arg1))
  ApiC(gdk_display_supports_cursor_color, (arg1))
  ApiC(gdk_display_sync, (arg1))
  ApiC(gdk_drag_abort, (arg1, arg2))
  ApiC(gdk_drag_action_get_type, ())
  ApiC(gdk_drag_begin, (arg1, arg2))
  ApiC(gdk_drag_context_get_type, ())
  ApiC(gdk_drag_context_new, ())
  ApiC(gdk_drag_context_ref, (arg1))
  ApiC(gdk_drag_context_unref, (arg1))
  ApiC(gdk_drag_drop, (arg1, arg2))
  ApiC(gdk_drag_find_window, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_drag_find_window_for_screen, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(gdk_drag_get_protocol, (arg1, arg2))
  ApiC(gdk_drag_get_protocol_for_display, (arg1, arg2, arg3))
  ApiC(gdk_drag_get_selection, (arg1))
  ApiC(gdk_drag_motion, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(gdk_drag_protocol_get_type, ())
  ApiC(gdk_drag_status, (arg1, arg2, arg3))
  ApiC(gdk_draw_arc, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(gdk_draw_drawable, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(gdk_draw_glyphs, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_draw_gray_image, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(gdk_draw_image, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(gdk_draw_indexed_image, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10))
  ApiC(gdk_draw_layout, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_draw_layout_line, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_draw_layout_line_with_colors, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(gdk_draw_layout_with_colors, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(gdk_draw_line, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_draw_lines, (arg1, arg2, arg3, arg4))
  ApiC(gdk_draw_pixbuf, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12))
  ApiC(gdk_draw_pixmap, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(gdk_draw_point, (arg1, arg2, arg3, arg4))
  ApiC(gdk_draw_points, (arg1, arg2, arg3, arg4))
  ApiC(gdk_draw_polygon, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_draw_rectangle, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(gdk_draw_rgb_32_image, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(gdk_draw_rgb_32_image_dithalign, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11))
  ApiC(gdk_draw_rgb_image, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(gdk_draw_rgb_image_dithalign, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11))
  ApiC(gdk_draw_segments, (arg1, arg2, arg3, arg4))
  ApiC(gdk_draw_string, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_draw_text, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(gdk_draw_text_wc, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(gdk_drawable_copy_to_image, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(gdk_drawable_get_clip_region, (arg1))
  ApiC(gdk_drawable_get_colormap, (arg1))
  ApiC(gdk_drawable_get_data, (arg1, arg2))
  ApiC(gdk_drawable_get_depth, (arg1))
  ApiC(gdk_drawable_get_display, (arg1))
  ApiC(gdk_drawable_get_image, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_drawable_get_screen, (arg1))
  ApiC(gdk_drawable_get_size, (arg1, arg2, arg3))
  ApiC(gdk_drawable_get_type, ())
  ApiC(gdk_drawable_get_visible_region, (arg1))
  ApiC(gdk_drawable_get_visual, (arg1))
  ApiC(gdk_drawable_ref, (arg1))
  ApiC(gdk_drawable_set_colormap, (arg1, arg2))
  ApiC(gdk_drawable_set_data, (arg1, arg2, arg3, arg4))
  ApiC(gdk_drawable_unref, (arg1))
  ApiC(gdk_drop_finish, (arg1, arg2, arg3))
  ApiC(gdk_drop_reply, (arg1, arg2, arg3))
  ApiC(gdk_error_trap_pop, ())
  ApiC(gdk_error_trap_push, ())
  ApiC(gdk_event_copy, (arg1))
  ApiC(gdk_event_free, (arg1))
  ApiC(gdk_event_get, ())
  ApiC(gdk_event_get_axis, (arg1, arg2, arg3))
  ApiC(gdk_event_get_coords, (arg1, arg2, arg3))
  ApiC(gdk_event_get_graphics_expose, (arg1))
  ApiC(gdk_event_get_root_coords, (arg1, arg2, arg3))
  ApiC(gdk_event_get_screen, (arg1))
  ApiC(gdk_event_get_state, (arg1, arg2))
  ApiC(gdk_event_get_time, (arg1))
  ApiC(gdk_event_get_type, ())
  ApiC(gdk_event_handler_set, (arg1, arg2, arg3))
  ApiC(gdk_event_mask_get_type, ())
  ApiC(gdk_event_new, (arg1))
  ApiC(gdk_event_peek, ())
  ApiC(gdk_event_put, (arg1))
  ApiC(gdk_event_set_screen, (arg1, arg2))
  ApiC(gdk_event_type_get_type, ())
  ApiC(gdk_events_pending, ())
  ApiC(gdk_exit, (arg1))
  ApiC(gdk_extension_mode_get_type, ())
  ApiC(gdk_fill_get_type, ())
  ApiC(gdk_fill_rule_get_type, ())
  ApiC(gdk_filter_return_get_type, ())
  ApiC(gdk_flush, ())
  ApiC(gdk_font_equal, (arg1, arg2))
  ApiC(gdk_font_from_description, (arg1))
  ApiC(gdk_font_from_description_for_display, (arg1, arg2))
  ApiC(gdk_font_get_display, (arg1))
  ApiC(gdk_font_get_type, ())
  ApiC(gdk_font_id, (arg1))
  ApiC(gdk_font_load, (arg1))
  ApiC(gdk_font_load_for_display, (arg1, arg2))
  ApiC(gdk_font_ref, (arg1))
  ApiC(gdk_font_type_get_type, ())
  ApiC(gdk_font_unref, (arg1))
  ApiC(gdk_fontset_load, (arg1))
  ApiC(gdk_fontset_load_for_display, (arg1, arg2))
  ApiC(gdk_free_compound_text, (arg1))
  ApiC(gdk_free_text_list, (arg1))
  ApiC(gdk_function_get_type, ())
  ApiC(gdk_gc_copy, (arg1, arg2))
  ApiC(gdk_gc_get_colormap, (arg1))
  ApiC(gdk_gc_get_screen, (arg1))
  ApiC(gdk_gc_get_type, ())
  ApiC(gdk_gc_get_values, (arg1, arg2))
  ApiC(gdk_gc_new, (arg1))
  ApiC(gdk_gc_new_with_values, (arg1, arg2, arg3))
  ApiC(gdk_gc_offset, (arg1, arg2, arg3))
  ApiC(gdk_gc_ref, (arg1))
  ApiC(gdk_gc_set_background, (arg1, arg2))
  ApiC(gdk_gc_set_clip_mask, (arg1, arg2))
  ApiC(gdk_gc_set_clip_origin, (arg1, arg2, arg3))
  ApiC(gdk_gc_set_clip_rectangle, (arg1, arg2))
  ApiC(gdk_gc_set_clip_region, (arg1, arg2))
  ApiC(gdk_gc_set_colormap, (arg1, arg2))
  ApiC(gdk_gc_set_dashes, (arg1, arg2, arg3, arg4))
  ApiC(gdk_gc_set_exposures, (arg1, arg2))
  ApiC(gdk_gc_set_fill, (arg1, arg2))
  ApiC(gdk_gc_set_font, (arg1, arg2))
  ApiC(gdk_gc_set_foreground, (arg1, arg2))
  ApiC(gdk_gc_set_function, (arg1, arg2))
  ApiC(gdk_gc_set_line_attributes, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_gc_set_rgb_bg_color, (arg1, arg2))
  ApiC(gdk_gc_set_rgb_fg_color, (arg1, arg2))
  ApiC(gdk_gc_set_stipple, (arg1, arg2))
  ApiC(gdk_gc_set_subwindow, (arg1, arg2))
  ApiC(gdk_gc_set_tile, (arg1, arg2))
  ApiC(gdk_gc_set_ts_origin, (arg1, arg2, arg3))
  ApiC(gdk_gc_set_values, (arg1, arg2, arg3))
  ApiC(gdk_gc_unref, (arg1))
  ApiC(gdk_gc_values_mask_get_type, ())
  ApiC(gdk_get_default_root_window, ())
  ApiC(gdk_get_display, ())
  ApiC(gdk_get_display_arg_name, ())
  ApiC(gdk_get_program_class, ())
  ApiC(gdk_get_show_events, ())
  ApiC(gdk_get_use_xshm, ())
  ApiC(gdk_grab_status_get_type, ())
  ApiC(gdk_gravity_get_type, ())
  ApiC(gdk_image_get, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_image_get_colormap, (arg1))
  ApiC(gdk_image_get_pixel, (arg1, arg2, arg3))
  ApiC(gdk_image_get_type, ())
  ApiC(gdk_image_new, (arg1, arg2, arg3, arg4))
  ApiC(gdk_image_new_bitmap, (arg1, arg2, arg3, arg4))
  ApiC(gdk_image_put_pixel, (arg1, arg2, arg3, arg4))
  ApiC(gdk_image_ref, (arg1))
  ApiC(gdk_image_set_colormap, (arg1, arg2))
  ApiC(gdk_image_type_get_type, ())
  ApiC(gdk_image_unref, (arg1))
  ApiC(gdk_init, (arg1, arg2))
  ApiC(gdk_init_check, (arg1, arg2))
  ApiC(gdk_input_add, (arg1, arg2, arg3, arg4))
  ApiC(gdk_input_add_full, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_input_condition_get_type, ())
  ApiC(gdk_input_mode_get_type, ())
  ApiC(gdk_input_remove, (arg1))
  ApiC(gdk_input_set_extension_events, (arg1, arg2, arg3))
  ApiC(gdk_input_source_get_type, ())
  ApiC(gdk_iswalnum, (arg1))
  ApiC(gdk_iswspace, (arg1))
  ApiC(gdk_join_style_get_type, ())
  ApiC(gdk_keyboard_grab, (arg1, arg2, arg3))
  ApiC(gdk_keyboard_ungrab, (arg1))
  ApiC(gdk_keymap_get_default, ())
  ApiC(gdk_keymap_get_direction, (arg1))
  ApiC(gdk_keymap_get_entries_for_keycode, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_keymap_get_entries_for_keyval, (arg1, arg2, arg3, arg4))
  ApiC(gdk_keymap_get_for_display, (arg1))
  ApiC(gdk_keymap_get_type, ())
  ApiC(gdk_keymap_lookup_key, (arg1, arg2))
  ApiC(gdk_keymap_translate_keyboard_state, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(gdk_keyval_convert_case, (arg1, arg2, arg3))
  ApiC(gdk_keyval_from_name, (arg1))
  ApiC(gdk_keyval_is_lower, (arg1))
  ApiC(gdk_keyval_is_upper, (arg1))
  ApiC(gdk_keyval_name, (arg1))
  ApiC(gdk_keyval_to_lower, (arg1))
  ApiC(gdk_keyval_to_unicode, (arg1))
  ApiC(gdk_keyval_to_upper, (arg1))
  ApiC(gdk_line_style_get_type, ())
  ApiC(gdk_list_visuals, ())
  ApiC(gdk_mbstowcs, (arg1, arg2, arg3))
  ApiC(gdk_modifier_type_get_type, ())
  ApiC(gdk_net_wm_supports, (arg1))
  ApiC(gdk_notify_startup_complete, ())
  ApiC(gdk_notify_type_get_type, ())
  ApiC(gdk_overlap_type_get_type, ())
  ApiC(gdk_pango_attr_embossed_new, (arg1))
  ApiC(gdk_pango_attr_stipple_new, (arg1))
  ApiC(gdk_pango_context_get, ())
  ApiC(gdk_pango_context_get_for_screen, (arg1))
  ApiC(gdk_pango_context_set_colormap, (arg1, arg2))
  ApiC(gdk_pango_layout_get_clip_region, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_pango_layout_line_get_clip_region, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_parse_args, (arg1, arg2))
  ApiC(gdk_pixbuf_get_from_drawable, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(gdk_pixbuf_get_from_image, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(gdk_pixbuf_render_pixmap_and_mask, (arg1, arg2, arg3, arg4))
  ApiC(gdk_pixbuf_render_pixmap_and_mask_for_colormap, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_pixbuf_render_threshold_alpha, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(gdk_pixbuf_render_to_drawable, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12))
  ApiC(gdk_pixbuf_render_to_drawable_alpha, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13))
  ApiC(gdk_pixmap_colormap_create_from_xpm, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_pixmap_colormap_create_from_xpm_d, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_pixmap_create_from_data, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(gdk_pixmap_create_from_xpm, (arg1, arg2, arg3, arg4))
  ApiC(gdk_pixmap_create_from_xpm_d, (arg1, arg2, arg3, arg4))
  ApiC(gdk_pixmap_draw_text, (arg1, arg2))
  ApiC(gdk_pixmap_draw_text_wc, (arg1, arg2))
  ApiC(gdk_pixmap_foreign_new, (arg1))
  ApiC(gdk_pixmap_foreign_new_for_display, (arg1, arg2))
  ApiC(gdk_pixmap_get_type, ())
  ApiC(gdk_pixmap_lookup, (arg1))
  ApiC(gdk_pixmap_lookup_for_display, (arg1, arg2))
  ApiC(gdk_pixmap_new, (arg1, arg2, arg3, arg4))
  ApiC(gdk_pointer_grab, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_pointer_is_grabbed, ())
  ApiC(gdk_pointer_ungrab, (arg1))
  ApiC(gdk_prop_mode_get_type, ())
  ApiC(gdk_property_change, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(gdk_property_delete, (arg1, arg2))
  ApiC(gdk_property_get, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10))
  ApiC(gdk_property_state_get_type, ())
  ApiC(gdk_query_depths, (arg1, arg2))
  ApiC(gdk_query_visual_types, (arg1, arg2))
  ApiC(gdk_rectangle_get_type, ())
  ApiC(gdk_rectangle_intersect, (arg1, arg2, arg3))
  ApiC(gdk_rectangle_union, (arg1, arg2, arg3))
  ApiC(gdk_region_copy, (arg1))
  ApiC(gdk_region_destroy, (arg1))
  ApiC(gdk_region_empty, (arg1))
  ApiC(gdk_region_equal, (arg1, arg2))
  ApiC(gdk_region_get_clipbox, (arg1, arg2))
  ApiC(gdk_region_get_rectangles, (arg1, arg2, arg3))
  ApiC(gdk_region_intersect, (arg1, arg2))
  ApiC(gdk_region_new, ())
  ApiC(gdk_region_offset, (arg1, arg2, arg3))
  ApiC(gdk_region_point_in, (arg1, arg2, arg3))
  ApiC(gdk_region_polygon, (arg1, arg2, arg3))
  ApiC(gdk_region_rect_in, (arg1, arg2))
  ApiC(gdk_region_rectangle, (arg1))
  ApiC(gdk_region_shrink, (arg1, arg2, arg3))
  ApiC(gdk_region_spans_intersect_foreach, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_region_subtract, (arg1, arg2))
  ApiC(gdk_region_union, (arg1, arg2))
  ApiC(gdk_region_union_with_rect, (arg1, arg2))
  ApiC(gdk_region_xor, (arg1, arg2))
  ApiC(gdk_rgb_cmap_free, (arg1))
  ApiC(gdk_rgb_cmap_new, (arg1, arg2))
  ApiC(gdk_rgb_dither_get_type, ())
  ApiC(gdk_rgb_ditherable, ())
  ApiC(gdk_rgb_find_color, (arg1, arg2))
  ApiC(gdk_rgb_gc_set_background, (arg1, arg2))
  ApiC(gdk_rgb_gc_set_foreground, (arg1, arg2))
  ApiC(gdk_rgb_get_colormap, ())
  ApiC(gdk_rgb_get_visual, ())
  ApiC(gdk_rgb_init, ())
  ApiC(gdk_rgb_set_install, (arg1))
  ApiC(gdk_rgb_set_min_colors, (arg1))
  ApiC(gdk_rgb_set_verbose, (arg1))
  ApiC(gdk_rgb_try_colormap, (arg1))
  ApiC(gdk_rgb_xpixel_from_rgb, (arg1))
  ApiC(gdk_screen_get_default, ())
  ApiC(gdk_screen_get_default_colormap, (arg1))
  ApiC(gdk_screen_get_display, (arg1))
  ApiC(gdk_screen_get_height, (arg1))
  ApiC(gdk_screen_get_height_mm, (arg1))
  ApiC(gdk_screen_get_monitor_at_point, (arg1, arg2, arg3))
  ApiC(gdk_screen_get_monitor_at_window, (arg1, arg2))
  ApiC(gdk_screen_get_monitor_geometry, (arg1, arg2, arg3))
  ApiC(gdk_screen_get_n_monitors, (arg1))
  ApiC(gdk_screen_get_number, (arg1))
  ApiC(gdk_screen_get_rgb_colormap, (arg1))
  ApiC(gdk_screen_get_rgb_visual, (arg1))
  ApiC(gdk_screen_get_root_window, (arg1))
  ApiC(gdk_screen_get_setting, (arg1, arg2, arg3))
  ApiC(gdk_screen_get_system_colormap, (arg1))
  ApiC(gdk_screen_get_system_visual, (arg1))
  ApiC(gdk_screen_get_toplevel_windows, (arg1))
  ApiC(gdk_screen_get_type, ())
  ApiC(gdk_screen_get_width, (arg1))
  ApiC(gdk_screen_get_width_mm, (arg1))
  ApiC(gdk_screen_height, ())
  ApiC(gdk_screen_height_mm, ())
  ApiC(gdk_screen_list_visuals, (arg1))
  ApiC(gdk_screen_make_display_name, (arg1))
  ApiC(gdk_screen_set_default_colormap, (arg1, arg2))
  ApiC(gdk_screen_width, ())
  ApiC(gdk_screen_width_mm, ())
  ApiC(gdk_scroll_direction_get_type, ())
  ApiC(gdk_selection_convert, (arg1, arg2, arg3, arg4))
  ApiC(gdk_selection_owner_get, (arg1))
  ApiC(gdk_selection_owner_get_for_display, (arg1, arg2))
  ApiC(gdk_selection_owner_set, (arg1, arg2, arg3, arg4))
  ApiC(gdk_selection_owner_set_for_display, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_selection_property_get, (arg1, arg2, arg3, arg4))
  ApiC(gdk_selection_send_notify, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_selection_send_notify_for_display, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_set_double_click_time, (arg1))
  ApiC(gdk_set_locale, ())
  ApiC(gdk_set_pointer_hooks, (arg1))
  ApiC(gdk_set_program_class, (arg1))
  ApiC(gdk_set_show_events, (arg1))
  ApiC(gdk_set_sm_client_id, (arg1))
  ApiC(gdk_set_use_xshm, (arg1))
  ApiC(gdk_setting_action_get_type, ())
  ApiC(gdk_setting_get, (arg1, arg2))
  ApiC(gdk_spawn_command_line_on_screen, (arg1, arg2, arg3))
  ApiC(gdk_spawn_on_screen, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(gdk_spawn_on_screen_with_pipes, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12))
  ApiC(gdk_status_get_type, ())
  ApiC(gdk_string_extents, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(gdk_string_height, (arg1, arg2))
  ApiC(gdk_string_measure, (arg1, arg2))
  ApiC(gdk_string_to_compound_text, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_string_to_compound_text_for_display, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_string_width, (arg1, arg2))
  ApiC(gdk_subwindow_mode_get_type, ())
  ApiC(gdk_synthesize_window_state, (arg1, arg2, arg3))
  ApiC(gdk_text_extents, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(gdk_text_extents_wc, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(gdk_text_height, (arg1, arg2, arg3))
  ApiC(gdk_text_measure, (arg1, arg2, arg3))
  ApiC(gdk_text_property_to_text_list, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_text_property_to_text_list_for_display, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_text_property_to_utf8_list, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_text_property_to_utf8_list_for_display, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_text_width, (arg1, arg2, arg3))
  ApiC(gdk_text_width_wc, (arg1, arg2, arg3))
  ApiC(gdk_threads_enter, ())
  ApiC(gdk_threads_init, ())
  ApiC(gdk_threads_leave, ())
  ApiC(gdk_threads_lock, ())
  ApiC(gdk_threads_set_lock_functions, (arg1, arg2))
  ApiC(gdk_threads_unlock, ())
  ApiC(gdk_unicode_to_keyval, (arg1))
  ApiC(gdk_utf8_to_compound_text, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_utf8_to_compound_text_for_display, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_utf8_to_string_target, (arg1))
  ApiC(gdk_visibility_state_get_type, ())
  ApiC(gdk_visual_get_best, ())
  ApiC(gdk_visual_get_best_depth, ())
  ApiC(gdk_visual_get_best_type, ())
  ApiC(gdk_visual_get_best_with_both, (arg1, arg2))
  ApiC(gdk_visual_get_best_with_depth, (arg1))
  ApiC(gdk_visual_get_best_with_type, (arg1))
  ApiC(gdk_visual_get_screen, (arg1))
  ApiC(gdk_visual_get_system, ())
  ApiC(gdk_visual_get_type, ())
  ApiC(gdk_visual_type_get_type, ())
  ApiC(gdk_wcstombs, (arg1))
  ApiC(gdk_window_add_filter, (arg1, arg2, arg3))
  ApiC(gdk_window_at_pointer, (arg1, arg2))
  ApiC(gdk_window_attributes_type_get_type, ())
  ApiC(gdk_window_begin_move_drag, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_window_begin_paint_rect, (arg1, arg2))
  ApiC(gdk_window_begin_paint_region, (arg1, arg2))
  ApiC(gdk_window_begin_resize_drag, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_window_class_get_type, ())
  ApiC(gdk_window_clear, (arg1))
  ApiC(gdk_window_clear_area, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_window_clear_area_e, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_window_constrain_size, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_window_deiconify, (arg1))
  ApiC(gdk_window_destroy, (arg1))
  ApiC(gdk_window_destroy_notify, (arg1))
  ApiC(gdk_window_edge_get_type, ())
  ApiC(gdk_window_end_paint, (arg1))
  ApiC(gdk_window_focus, (arg1, arg2))
  ApiC(gdk_window_foreign_new, (arg1))
  ApiC(gdk_window_foreign_new_for_display, (arg1, arg2))
  ApiC(gdk_window_freeze_updates, (arg1))
  ApiC(gdk_window_fullscreen, (arg1))
  ApiC(gdk_window_get_children, (arg1))
  ApiC(gdk_window_get_decorations, (arg1, arg2))
  ApiC(gdk_window_get_deskrelative_origin, (arg1, arg2, arg3))
  ApiC(gdk_window_get_events, (arg1))
  ApiC(gdk_window_get_frame_extents, (arg1, arg2))
  ApiC(gdk_window_get_geometry, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(gdk_window_get_group, (arg1))
  ApiC(gdk_window_get_internal_paint_info, (arg1, arg2, arg3, arg4))
  ApiC(gdk_window_get_origin, (arg1, arg2, arg3))
  ApiC(gdk_window_get_parent, (arg1))
  ApiC(gdk_window_get_pointer, (arg1, arg2, arg3, arg4))
  ApiC(gdk_window_get_position, (arg1, arg2, arg3))
  ApiC(gdk_window_get_root_origin, (arg1, arg2, arg3))
  ApiC(gdk_window_get_state, (arg1))
  ApiC(gdk_window_get_toplevel, (arg1))
  ApiC(gdk_window_get_toplevels, ())
  ApiC(gdk_window_get_update_area, (arg1))
  ApiC(gdk_window_get_user_data, (arg1, arg2))
  ApiC(gdk_window_get_window_type, (arg1))
  ApiC(gdk_window_hide, (arg1))
  ApiC(gdk_window_hints_get_type, ())
  ApiC(gdk_window_iconify, (arg1))
  ApiC(gdk_window_invalidate_maybe_recurse, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_window_invalidate_rect, (arg1, arg2, arg3))
  ApiC(gdk_window_invalidate_region, (arg1, arg2, arg3))
  ApiC(gdk_window_is_viewable, (arg1))
  ApiC(gdk_window_is_visible, (arg1))
  ApiC(gdk_window_lookup, (arg1))
  ApiC(gdk_window_lookup_for_display, (arg1, arg2))
  ApiC(gdk_window_lower, (arg1))
  ApiC(gdk_window_maximize, (arg1))
  ApiC(gdk_window_merge_child_shapes, (arg1))
  ApiC(gdk_window_move, (arg1, arg2, arg3))
  ApiC(gdk_window_move_resize, (arg1, arg2, arg3, arg4, arg5))
  ApiC(gdk_window_new, (arg1, arg2, arg3))
  ApiC(gdk_window_object_get_type, ())
  ApiC(gdk_window_peek_children, (arg1))
  ApiC(gdk_window_process_all_updates, ())
  ApiC(gdk_window_process_updates, (arg1, arg2))
  ApiC(gdk_window_raise, (arg1))
  ApiC(gdk_window_register_dnd, (arg1))
  ApiC(gdk_window_remove_filter, (arg1, arg2, arg3))
  ApiC(gdk_window_reparent, (arg1, arg2, arg3, arg4))
  ApiC(gdk_window_resize, (arg1, arg2, arg3))
  ApiC(gdk_window_scroll, (arg1, arg2, arg3))
  ApiC(gdk_window_set_accept_focus, (arg1, arg2))
  ApiC(gdk_window_set_back_pixmap, (arg1, arg2, arg3))
  ApiC(gdk_window_set_background, (arg1, arg2))
  ApiC(gdk_window_set_child_shapes, (arg1))
  ApiC(gdk_window_set_cursor, (arg1, arg2))
  ApiC(gdk_window_set_debug_updates, (arg1))
  ApiC(gdk_window_set_decorations, (arg1, arg2))
  ApiC(gdk_window_set_events, (arg1, arg2))
  ApiC(gdk_window_set_functions, (arg1, arg2))
  ApiC(gdk_window_set_geometry_hints, (arg1, arg2))
  ApiC(gdk_window_set_group, (arg1, arg2))
  ApiC(gdk_window_set_hints, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(gdk_window_set_icon, (arg1, arg2, arg3, arg4))
  ApiC(gdk_window_set_icon_list, (arg1, arg2))
  ApiC(gdk_window_set_icon_name, (arg1, arg2))
  ApiC(gdk_window_set_keep_above, (arg1, arg2))
  ApiC(gdk_window_set_keep_below, (arg1, arg2))
  ApiC(gdk_window_set_modal_hint, (arg1, arg2))
  ApiC(gdk_window_set_override_redirect, (arg1, arg2))
  ApiC(gdk_window_set_role, (arg1, arg2))
  ApiC(gdk_window_set_skip_pager_hint, (arg1, arg2))
  ApiC(gdk_window_set_skip_taskbar_hint, (arg1, arg2))
  ApiC(gdk_window_set_static_gravities, (arg1, arg2))
  ApiC(gdk_window_set_title, (arg1, arg2))
  ApiC(gdk_window_set_transient_for, (arg1, arg2))
  ApiC(gdk_window_set_type_hint, (arg1, arg2))
  ApiC(gdk_window_set_user_data, (arg1, arg2))
  ApiC(gdk_window_shape_combine_mask, (arg1, arg2, arg3, arg4))
  ApiC(gdk_window_shape_combine_region, (arg1, arg2, arg3, arg4))
  ApiC(gdk_window_show, (arg1))
  ApiC(gdk_window_show_unraised, (arg1))
  ApiC(gdk_window_state_get_type, ())
  ApiC(gdk_window_stick, (arg1))
  ApiC(gdk_window_thaw_updates, (arg1))
  ApiC(gdk_window_type_get_type, ())
  ApiC(gdk_window_type_hint_get_type, ())
  ApiC(gdk_window_unfullscreen, (arg1))
  ApiC(gdk_window_unmaximize, (arg1))
  ApiC(gdk_window_unstick, (arg1))
  ApiC(gdk_window_withdraw, (arg1))
  ApiC(gdk_wm_decoration_get_type, ())
  ApiC(gdk_wm_function_get_type, ())
  ApiC(gdk_x11_atom_to_xatom, (arg1))
  ApiC(gdk_x11_atom_to_xatom_for_display, (arg1, arg2))
  ApiC(gdk_x11_colormap_foreign_new, (arg1, arg2))
  ApiC(gdk_x11_colormap_get_xcolormap, (arg1))
  ApiC(gdk_x11_colormap_get_xdisplay, (arg1))
  ApiC(gdk_x11_cursor_get_xcursor, (arg1))
  ApiC(gdk_x11_cursor_get_xdisplay, (arg1))
  ApiC(gdk_x11_display_get_xdisplay, (arg1))
  ApiC(gdk_x11_display_grab, (arg1))
  ApiC(gdk_x11_display_ungrab, (arg1))
  ApiC(gdk_x11_drawable_get_xdisplay, (arg1))
  ApiC(gdk_x11_drawable_get_xid, (arg1))
  ApiC(gdk_x11_font_get_name, (arg1))
  ApiC(gdk_x11_font_get_xdisplay, (arg1))
  ApiC(gdk_x11_font_get_xfont, (arg1))
  ApiC(gdk_x11_gc_get_xdisplay, (arg1))
  ApiC(gdk_x11_gc_get_xgc, (arg1))
  ApiC(gdk_x11_get_default_root_xwindow, ())
  ApiC(gdk_x11_get_default_screen, ())
  ApiC(gdk_x11_get_default_xdisplay, ())
  ApiC(gdk_x11_get_server_time, (arg1))
  ApiC(gdk_x11_get_xatom_by_name, (arg1))
  ApiC(gdk_x11_get_xatom_by_name_for_display, (arg1, arg2))
  ApiC(gdk_x11_get_xatom_name, (arg1))
  ApiC(gdk_x11_get_xatom_name_for_display, (arg1, arg2))
  ApiC(gdk_x11_grab_server, ())
  ApiC(gdk_x11_image_get_xdisplay, (arg1))
  ApiC(gdk_x11_image_get_ximage, (arg1))
  ApiC(gdk_x11_lookup_xdisplay, (arg1))
  ApiC(gdk_x11_register_standard_event_type, (arg1, arg2, arg3))
  ApiC(gdk_x11_screen_get_screen_number, (arg1))
  ApiC(gdk_x11_screen_get_window_manager_name, (arg1))
  ApiC(gdk_x11_screen_get_xscreen, (arg1))
  ApiC(gdk_x11_screen_lookup_visual, (arg1, arg2))
  ApiC(gdk_x11_screen_supports_net_wm_hint, (arg1, arg2))
  ApiC(gdk_x11_ungrab_server, ())
  ApiC(gdk_x11_visual_get_xvisual, (arg1))
  ApiC(gdk_x11_xatom_to_atom, (arg1))
  ApiC(gdk_x11_xatom_to_atom_for_display, (arg1, arg2))
  ApiC(gdk_xid_table_lookup, (arg1))
  ApiC(gdk_xid_table_lookup_for_display, (arg1, arg2))
EndImport
