XIncludeFile "common.pbi"

CompilerIf #PB_GTK = 3
  ImportC "`pkg-config --libs gtk+-3.0` `pkg-config --libs gthread-2.0`"
  
CompilerElse ; GTK2
  ImportC "`pkg-config --libs gtk+-2.0` `pkg-config --libs gthread-2.0`"
CompilerEndIf

  ApiC(g_allocator_free, (arg1))
  ApiC(g_allocator_new, (arg1, arg2))
  ApiC(g_array_append_vals, (arg1, arg2, arg3))
  ApiC(g_array_free, (arg1, arg2))
  ApiC(g_array_insert_vals, (arg1, arg2, arg3, arg4))
  ApiC(g_array_new, (arg1, arg2, arg3))
  ApiC(g_array_prepend_vals, (arg1, arg2, arg3))
  ApiC(g_array_remove_index, (arg1, arg2))
  ApiC(g_array_remove_index_fast, (arg1, arg2))
  ApiC(g_array_remove_range, (arg1, arg2, arg3))
  ApiC(g_array_set_size, (arg1, arg2))
  ApiC(g_array_sized_new, (arg1, arg2, arg3, arg4))
  ApiC(g_array_sort, (arg1, arg2))
  ApiC(g_array_sort_with_data, (arg1, arg2, arg3))
  ApiC(g_ascii_digit_value, (arg1))
  ApiC(g_ascii_dtostr, (arg1, arg2, arg3))
  ApiC(g_ascii_formatd, (arg1, arg2, arg3, arg4))
  ApiC(g_ascii_strcasecmp, (arg1, arg2))
  ApiC(g_ascii_strdown, (arg1, arg2))
  ApiC(g_ascii_strncasecmp, (arg1, arg2, arg3))
  ApiC(g_ascii_strtod, (arg1, arg2))
  ApiC(g_ascii_strtoull, (arg1, arg2, arg3))
  ApiC(g_ascii_strup, (arg1, arg2))
  ApiC(g_ascii_tolower, (arg1))
  ApiC(g_ascii_toupper, (arg1))
  ApiC(g_ascii_xdigit_value, (arg1))
  ApiC(g_assert_warning, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_async_queue_length, (arg1))
  ApiC(g_async_queue_length_unlocked, (arg1))
  ApiC(g_async_queue_lock, (arg1))
  ApiC(g_async_queue_new, ())
  ApiC(g_async_queue_pop, (arg1))
  ApiC(g_async_queue_pop_unlocked, (arg1))
  ApiC(g_async_queue_push, (arg1, arg2))
  ApiC(g_async_queue_push_unlocked, (arg1, arg2))
  ApiC(g_async_queue_ref, (arg1))
  ApiC(g_async_queue_ref_unlocked, (arg1))
  ApiC(g_async_queue_timed_pop, (arg1, arg2))
  ApiC(g_async_queue_timed_pop_unlocked, (arg1, arg2))
  ApiC(g_async_queue_try_pop, (arg1))
  ApiC(g_async_queue_try_pop_unlocked, (arg1))
  ApiC(g_async_queue_unlock, (arg1))
  ApiC(g_async_queue_unref, (arg1))
  ApiC(g_async_queue_unref_and_unlock, (arg1))
  ApiC(g_atexit, (arg1))
  ApiC(g_atomic_int_add, (arg1, arg2))
  ApiC(g_atomic_int_compare_and_exchange, (arg1, arg2, arg3))
  ApiC(g_atomic_int_exchange_and_add, (arg1, arg2))
  ApiC(g_atomic_int_get, (arg1))
  ApiC(g_atomic_pointer_compare_and_exchange, (arg1, arg2, arg3))
  ApiC(g_atomic_pointer_get, (arg1))
  ApiC(g_basename, (arg1))
  ApiC(g_bit_nth_lsf, (arg1, arg2))
  ApiC(g_bit_nth_msf, (arg1, arg2))
  ApiC(g_bit_storage, (arg1))
  ApiC(g_blow_chunks, ())
  ApiC(g_build_filename, (arg1, arg2))
  ApiC(g_build_path, (arg1, arg2, arg3))
  ApiC(g_byte_array_append, (arg1, arg2, arg3))
  ApiC(g_byte_array_free, (arg1, arg2))
  ApiC(g_byte_array_new, ())
  ApiC(g_byte_array_prepend, (arg1, arg2, arg3))
  ApiC(g_byte_array_remove_index, (arg1, arg2))
  ApiC(g_byte_array_remove_index_fast, (arg1, arg2))
  ApiC(g_byte_array_remove_range, (arg1, arg2, arg3))
  ApiC(g_byte_array_set_size, (arg1, arg2))
  ApiC(g_byte_array_sized_new, (arg1))
  ApiC(g_byte_array_sort, (arg1, arg2))
  ApiC(g_byte_array_sort_with_data, (arg1, arg2, arg3))
  ApiC(g_cache_destroy, (arg1))
  ApiC(g_cache_insert, (arg1, arg2))
  ApiC(g_cache_key_foreach, (arg1, arg2, arg3))
  ApiC(g_cache_new, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(g_cache_remove, (arg1, arg2))
  ApiC(g_cache_value_foreach, (arg1, arg2, arg3))
  ApiC(g_child_watch_add, (arg1, arg2, arg3))
  ApiC(g_child_watch_add_full, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_child_watch_source_new, (arg1))
  ApiC(g_clear_error, (arg1))
  ApiC(g_completion_add_items, (arg1, arg2))
  ApiC(g_completion_clear_items, (arg1))
  ApiC(g_completion_complete, (arg1, arg2, arg3))
  ApiC(g_completion_complete_utf8, (arg1, arg2, arg3))
  ApiC(g_completion_free, (arg1))
  ApiC(g_completion_new, (arg1))
  ApiC(g_completion_remove_items, (arg1, arg2))
  ApiC(g_completion_set_compare, (arg1, arg2))
  ApiC(g_cond_timed_wait, (arg1, arg2, arg3))
  ApiC(g_cond_wait, (arg1, arg2))
  ApiC(g_convert, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(g_convert_error_quark, ())
  ApiC(g_convert_with_fallback, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(g_convert_with_iconv, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(g_critical, (arg1, arg2))
  ApiC(g_datalist_clear, (arg1))
  ApiC(g_datalist_foreach, (arg1, arg2, arg3))
  ApiC(g_datalist_id_get_data, (arg1, arg2))
  ApiC(g_datalist_id_remove_no_notify, (arg1, arg2))
  ApiC(g_datalist_id_set_data, (arg1, arg2, arg3))
  ApiC(g_datalist_id_set_data_full, (arg1, arg2, arg3, arg4))
  ApiC(g_datalist_init, (arg1))
  ApiC(g_datalist_set_data_full, (arg1, arg2, arg3, arg4))
  ApiC(g_dataset_destroy, (arg1))
  ApiC(g_dataset_foreach, (arg1, arg2, arg3))
  ApiC(g_dataset_id_get_data, (arg1, arg2))
  ApiC(g_dataset_id_remove_no_notify, (arg1, arg2))
  ApiC(g_dataset_id_set_data, (arg1, arg2, arg3))
  ApiC(g_dataset_id_set_data_full, (arg1, arg2, arg3, arg4))
  ApiC(g_dataset_set_data_full, (arg1, arg2, arg3, arg4))
  ApiC(g_date_add_days, (arg1, arg2))
  ApiC(g_date_add_months, (arg1, arg2))
  ApiC(g_date_add_years, (arg1, arg2))
  ApiC(g_date_clamp, (arg1, arg2, arg3))
  ApiC(g_date_clear, (arg1))
  ApiC(g_date_compare, (arg1, arg2))
  ApiC(g_date_days_between, (arg1, arg2))
  ApiC(g_date_free, (arg1))
  ApiC(g_date_get_day, (arg1))
  ApiC(g_date_get_day_of_year, (arg1))
  ApiC(g_date_get_days_in_month, (arg1, arg2))
  ApiC(g_date_get_iso8601_week_of_year, (arg1))
  ApiC(g_date_get_julian, (arg1))
  ApiC(g_date_get_monday_week_of_year, (arg1))
  ApiC(g_date_get_monday_weeks_in_year, (arg1))
  ApiC(g_date_get_month, (arg1))
  ApiC(g_date_get_sunday_week_of_year, (arg1))
  ApiC(g_date_get_sunday_weeks_in_year, (arg1))
  ApiC(g_date_get_weekday, (arg1))
  ApiC(g_date_get_year, (arg1))
  ApiC(g_date_is_first_of_month, (arg1))
  ApiC(g_date_is_last_of_month, (arg1))
  ApiC(g_date_is_leap_year, (arg1))
  ApiC(g_date_new, (arg1, arg2))
  ApiC(g_date_new_dmy, (arg1, arg2, arg3))
  ApiC(g_date_new_julian, (arg1))
  ApiC(g_date_order, (arg1, arg2))
  ApiC(g_date_set_day, (arg1, arg2))
  ApiC(g_date_set_dmy, (arg1, arg2, arg3, arg4))
  ApiC(g_date_set_julian, (arg1, arg2))
  ApiC(g_date_set_month, (arg1, arg2))
  ApiC(g_date_set_parse, (arg1, arg2))
  ApiC(g_date_set_time, (arg1, arg2))
  ApiC(g_date_set_year, (arg1, arg2))
  ApiC(g_date_strftime, (arg1, arg2, arg3, arg4))
  ApiC(g_date_subtract_days, (arg1, arg2))
  ApiC(g_date_subtract_months, (arg1, arg2))
  ApiC(g_date_subtract_years, (arg1, arg2))
  ApiC(g_date_to_struct_tm, (arg1, arg2))
  ApiC(g_date_valid, (arg1, arg2))
  ApiC(g_date_valid_day, (arg1))
  ApiC(g_date_valid_dmy, (arg1, arg2, arg3))
  ApiC(g_date_valid_julian, (arg1))
  ApiC(g_date_valid_month, (arg1))
  ApiC(g_date_valid_weekday, (arg1))
  ApiC(g_date_valid_year, (arg1))
  ApiC(g_debug, (arg1, arg2))
  ApiC(g_dir_close, (arg1))
  ApiC(g_dir_open, (arg1, arg2, arg3))
  ApiC(g_dir_read_name, (arg1))
  ApiC(g_dir_rewind, (arg1))
  ApiC(g_direct_equal, (arg1, arg2))
  ApiC(g_direct_hash, (arg1))
  ApiC(g_domain, (arg1, arg2))
  ApiC(g_error, (arg1, arg2))
  ApiC(g_error_copy, (arg1))
  ApiC(g_error_free, (arg1))
  ApiC(g_error_matches, (arg1, arg2, arg3))
  ApiC(g_error_new, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_error_new_literal, (arg1, arg2, arg3))
  ApiC(g_file_error_from_errno, (arg1))
  ApiC(g_file_error_quark, ())
  ApiC(g_file_get_contents, (arg1, arg2, arg3, arg4))
  ApiC(g_file_open_tmp, (arg1, arg2, arg3))
  ApiC(g_file_read_link, (arg1, arg2))
  ApiC(g_file_test, (arg1, arg2))
  ApiC(g_filename_display_basename, (arg1))
  ApiC(g_filename_display_name, (arg1))
  ApiC(g_filename_from_uri, (arg1, arg2, arg3))
  ApiC(g_filename_from_utf8, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_filename_to_uri, (arg1, arg2, arg3))
  ApiC(g_filename_to_utf8, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_find_program_in_path, (arg1))
  ApiC(g_fopen, (arg1, arg2))
  ApiC(g_fprintf, (arg1, arg2, arg3, arg4))
  ApiC(g_free, (arg1))
  ApiC(g_freopen, (arg1, arg2, arg3))
  ApiC(g_get_application_name, ())
  ApiC(g_get_charset, (arg1))
  ApiC(g_get_current_dir, ())
  ApiC(g_get_current_time, (arg1))
  ApiC(g_get_filename_charsets, (arg1))
  ApiC(g_get_home_dir, ())
  ApiC(g_get_language_names, ())
  ApiC(g_get_prgname, ())
  ApiC(g_get_real_name, ())
  ApiC(g_get_system_config_dirs, ())
  ApiC(g_get_system_data_dirs, ())
  ApiC(g_get_tmp_dir, ())
  ApiC(g_get_user_cache_dir, ())
  ApiC(g_get_user_config_dir, ())
  ApiC(g_get_user_data_dir, ())
  ApiC(g_get_user_name, ())
  ApiC(g_getenv, (arg1))
  ApiC(g_hash_table_destroy, (arg1))
  ApiC(g_hash_table_find, (arg1, arg2, arg3))
  ApiC(g_hash_table_foreach, (arg1, arg2, arg3))
  ApiC(g_hash_table_foreach_remove, (arg1, arg2, arg3))
  ApiC(g_hash_table_foreach_steal, (arg1, arg2, arg3))
  ApiC(g_hash_table_insert, (arg1, arg2, arg3))
  ApiC(g_hash_table_lookup, (arg1, arg2))
  ApiC(g_hash_table_lookup_extended, (arg1, arg2, arg3, arg4))
  ApiC(g_hash_table_new, (arg1, arg2))
  ApiC(g_hash_table_new_full, (arg1, arg2, arg3, arg4))
  ApiC(g_hash_table_remove, (arg1, arg2))
  ApiC(g_hash_table_replace, (arg1, arg2, arg3))
  ApiC(g_hash_table_size, (arg1))
  ApiC(g_hash_table_steal, (arg1, arg2))
  ApiC(g_hook_alloc, (arg1))
  ApiC(g_hook_compare_ids, (arg1, arg2))
  ApiC(g_hook_destroy, (arg1, arg2))
  ApiC(g_hook_destroy_link, (arg1, arg2))
  ApiC(g_hook_find, (arg1, arg2, arg3, arg4))
  ApiC(g_hook_find_data, (arg1, arg2, arg3))
  ApiC(g_hook_find_func, (arg1, arg2, arg3))
  ApiC(g_hook_find_func_data, (arg1, arg2, arg3, arg4))
  ApiC(g_hook_first_valid, (arg1, arg2))
  ApiC(g_hook_free, (arg1, arg2))
  ApiC(g_hook_get, (arg1, arg2))
  ApiC(g_hook_insert_before, (arg1, arg2, arg3))
  ApiC(g_hook_insert_sorted, (arg1, arg2, arg3))
  ApiC(g_hook_list_clear, (arg1))
  ApiC(g_hook_list_init, (arg1, arg2))
  ApiC(g_hook_list_invoke, (arg1, arg2))
  ApiC(g_hook_list_invoke_check, (arg1, arg2))
  ApiC(g_hook_list_marshal, (arg1, arg2, arg3, arg4))
  ApiC(g_hook_list_marshal_check, (arg1, arg2, arg3, arg4))
  ApiC(g_hook_next_valid, (arg1, arg2, arg3))
  ApiC(g_hook_prepend, (arg1, arg2))
  ApiC(g_hook_ref, (arg1, arg2))
  ApiC(g_hook_unref, (arg1, arg2))
  ApiC(g_iconv, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_iconv_close, (arg1))
  ApiC(g_iconv_open, (arg1, arg2))
  ApiC(g_idle_add, (arg1, arg2))
  ApiC(g_idle_add_full, (arg1, arg2, arg3, arg4))
  ApiC(g_idle_remove_by_data, (arg1))
  ApiC(g_idle_source_new, ())
  ApiC(g_int_equal, (arg1, arg2))
  ApiC(g_int_hash, (arg1))
  ApiC(g_io_add_watch, (arg1, arg2, arg3, arg4))
  ApiC(g_io_add_watch_full, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(g_io_channel_close, (arg1))
  ApiC(g_io_channel_error_from_errno, (arg1))
  ApiC(g_io_channel_error_quark, ())
  ApiC(g_io_channel_flush, (arg1, arg2))
  ApiC(g_io_channel_get_buffer_condition, (arg1))
  ApiC(g_io_channel_get_buffer_size, (arg1))
  ApiC(g_io_channel_get_buffered, (arg1))
  ApiC(g_io_channel_get_close_on_unref, (arg1))
  ApiC(g_io_channel_get_encoding, (arg1))
  ApiC(g_io_channel_get_flags, (arg1))
  ApiC(g_io_channel_get_line_term, (arg1, arg2))
  ApiC(g_io_channel_init, (arg1))
  ApiC(g_io_channel_new_file, (arg1, arg2, arg3))
  ApiC(g_io_channel_read, (arg1, arg2, arg3, arg4))
  ApiC(g_io_channel_read_chars, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_io_channel_read_line, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_io_channel_read_line_string, (arg1, arg2, arg3, arg4))
  ApiC(g_io_channel_read_to_end, (arg1, arg2, arg3, arg4))
  ApiC(g_io_channel_read_unichar, (arg1, arg2, arg3))
  ApiC(g_io_channel_ref, (arg1))
  ApiC(g_io_channel_seek, (arg1, arg2, arg3))
  ApiC(g_io_channel_seek_position, (arg1, arg2, arg3, arg4))
  ApiC(g_io_channel_set_buffer_size, (arg1, arg2))
  ApiC(g_io_channel_set_buffered, (arg1, arg2))
  ApiC(g_io_channel_set_close_on_unref, (arg1, arg2))
  ApiC(g_io_channel_set_encoding, (arg1, arg2, arg3))
  ApiC(g_io_channel_set_flags, (arg1, arg2, arg3))
  ApiC(g_io_channel_set_line_term, (arg1, arg2, arg3))
  ApiC(g_io_channel_shutdown, (arg1, arg2, arg3))
  ApiC(g_io_channel_unix_get_fd, (arg1))
  ApiC(g_io_channel_unix_new, (arg1))
  ApiC(g_io_channel_unref, (arg1))
  ApiC(g_io_channel_win32_get_fd, (arg1))
  ApiC(g_io_channel_win32_make_pollfd, (arg1, arg2, arg3))
  ApiC(g_io_channel_win32_new_fd, (arg1))
  ApiC(g_io_channel_win32_new_messages, (arg1))
  ApiC(g_io_channel_win32_new_socket, (arg1))
  ApiC(g_io_channel_win32_poll, (arg1))
  ApiC(g_io_channel_write, (arg1, arg2, arg3, arg4))
  ApiC(g_io_channel_write_chars, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_io_channel_write_unichar, (arg1, arg2, arg3))
  ApiC(g_io_create_watch, (arg1, arg2))
  ApiC(g_key_file_error_quark, ())
  ApiC(g_key_file_free, (arg1))
  ApiC(g_key_file_get_boolean, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_get_boolean_list, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_key_file_get_comment, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_get_groups, (arg1, arg2))
  ApiC(g_key_file_get_integer, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_get_integer_list, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_key_file_get_keys, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_get_locale_string, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_key_file_get_locale_string_list, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(g_key_file_get_start_group, (arg1))
  ApiC(g_key_file_get_string, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_get_string_list, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_key_file_get_value, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_has_group, (arg1, arg2))
  ApiC(g_key_file_has_key, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_load_from_data, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_key_file_load_from_data_dirs, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_key_file_load_from_file, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_new, ())
  ApiC(g_key_file_remove_comment, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_remove_group, (arg1, arg2, arg3))
  ApiC(g_key_file_remove_key, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_set_boolean, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_set_boolean_list, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_key_file_set_comment, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_key_file_set_integer, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_set_integer_list, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_key_file_set_list_separator, (arg1, arg2))
  ApiC(g_key_file_set_locale_string, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_key_file_set_locale_string_list, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(g_key_file_set_string, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_set_string_list, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_key_file_set_value, (arg1, arg2, arg3, arg4))
  ApiC(g_key_file_to_data, (arg1, arg2, arg3))
  ApiC(g_list_alloc, ())
  ApiC(g_list_append, (arg1, arg2))
  ApiC(g_list_concat, (arg1, arg2))
  ApiC(g_list_copy, (arg1))
  ApiC(g_list_delete_link, (arg1, arg2))
  ApiC(g_list_find, (arg1, arg2))
  ApiC(g_list_find_custom, (arg1, arg2, arg3))
  ApiC(g_list_first, (arg1))
  ApiC(g_list_foreach, (arg1, arg2, arg3))
  ApiC(g_list_free, (arg1))
  ApiC(g_list_free_1, (arg1))
  ApiC(g_list_index, (arg1, arg2))
  ApiC(g_list_insert, (arg1, arg2, arg3))
  ApiC(g_list_insert_before, (arg1, arg2, arg3))
  ApiC(g_list_insert_sorted, (arg1, arg2, arg3))
  ApiC(g_list_last, (arg1))
  ApiC(g_list_length, (arg1))
  ApiC(g_list_nth, (arg1, arg2))
  ApiC(g_list_nth_data, (arg1, arg2))
  ApiC(g_list_nth_prev, (arg1, arg2))
  ApiC(g_list_pop_allocator, ())
  ApiC(g_list_position, (arg1, arg2))
  ApiC(g_list_prepend, (arg1, arg2))
  ApiC(g_list_push_allocator, (arg1))
  ApiC(g_list_remove, (arg1, arg2))
  ApiC(g_list_remove_all, (arg1, arg2))
  ApiC(g_list_remove_link, (arg1, arg2))
  ApiC(g_list_reverse, (arg1))
  ApiC(g_list_sort, (arg1, arg2))
  ApiC(g_list_sort_with_data, (arg1, arg2, arg3))
  ApiC(g_locale_from_utf8, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_locale_to_utf8, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_log, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_log_default_handler, (arg1, arg2, arg3, arg4))
  ApiC(g_log_fallback_handler, (arg1, arg2, arg3, arg4))
  ApiC(g_log_remove_handler, (arg1, arg2))
  ApiC(g_log_set_always_fatal, (arg1))
  ApiC(g_log_set_default_handler, (arg1, arg2))
  ApiC(g_log_set_fatal_mask, (arg1, arg2))
  ApiC(g_log_set_handler, (arg1, arg2, arg3, arg4))
  ApiC(g_logv, (arg1, arg2, arg3, arg4))
  ApiC(g_lstat, (arg1, arg2))
  ApiC(g_main_context_acquire, (arg1))
  ApiC(g_main_context_add_poll, (arg1, arg2, arg3))
  ApiC(g_main_context_check, (arg1, arg2, arg3, arg4))
  ApiC(g_main_context_default, ())
  ApiC(g_main_context_dispatch, (arg1))
  ApiC(g_main_context_find_source_by_funcs_user_data, (arg1, arg2, arg3))
  ApiC(g_main_context_find_source_by_id, (arg1, arg2))
  ApiC(g_main_context_find_source_by_user_data, (arg1, arg2))
  ApiC(g_main_context_get_poll_func, (arg1))
  ApiC(g_main_context_iteration, (arg1, arg2))
  ApiC(g_main_context_new, ())
  ApiC(g_main_context_pending, (arg1))
  ApiC(g_main_context_prepare, (arg1, arg2))
  ApiC(g_main_context_query, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_main_context_ref, (arg1))
  ApiC(g_main_context_release, (arg1))
  ApiC(g_main_context_remove_poll, (arg1, arg2))
  ApiC(g_main_context_set_poll_func, (arg1, arg2))
  ApiC(g_main_context_unref, (arg1))
  ApiC(g_main_context_wait, (arg1, arg2, arg3))
  ApiC(g_main_context_wakeup, (arg1))
  ApiC(g_main_depth, ())
  ApiC(g_main_loop_get_context, (arg1))
  ApiC(g_main_loop_is_running, (arg1))
  ApiC(g_main_loop_new, (arg1, arg2))
  ApiC(g_main_loop_quit, (arg1))
  ApiC(g_main_loop_ref, (arg1))
  ApiC(g_main_loop_run, (arg1))
  ApiC(g_main_loop_unref, (arg1))
  ApiC(g_malloc, (arg1))
  ApiC(g_malloc0, (arg1))
  ApiC(g_markup_error_quark, ())
  ApiC(g_markup_escape_text, (arg1, arg2))
  ApiC(g_markup_parse_context_end_parse, (arg1, arg2))
  ApiC(g_markup_parse_context_free, (arg1))
  ApiC(g_markup_parse_context_get_element, (arg1))
  ApiC(g_markup_parse_context_get_position, (arg1, arg2, arg3))
  ApiC(g_markup_parse_context_new, (arg1, arg2, arg3, arg4))
  ApiC(g_markup_parse_context_parse, (arg1, arg2, arg3, arg4))
  ApiC(g_markup_printf_escaped, (arg1, arg2, arg3))
  ApiC(g_markup_vprintf_escaped, (arg1, arg2))
  ApiC(g_mem_chunk_alloc, (arg1))
  ApiC(g_mem_chunk_alloc0, (arg1))
  ApiC(g_mem_chunk_clean, (arg1))
  ApiC(g_mem_chunk_destroy, (arg1))
  ApiC(g_mem_chunk_free, (arg1, arg2))
  ApiC(g_mem_chunk_info, ())
  ApiC(g_mem_chunk_new, (arg1, arg2))
  ApiC(g_mem_chunk_print, (arg1))
  ApiC(g_mem_chunk_reset, (arg1))
  ApiC(g_mem_is_system_malloc, ())
  ApiC(g_mem_profile, ())
  ApiC(g_mem_set_vtable, (arg1))
  ApiC(g_memdup, (arg1, arg2))
  ApiC(g_memmove, (arg1, arg2, arg3))
  ApiC(g_message, (arg1, arg2))
  ApiC(g_mkdir, (arg1, arg2))
  ApiC(g_mkstemp, (arg1))
  ApiC(g_mutex_free, (arg1))
  ApiC(g_mutex_lock, (arg1))
  ApiC(g_mutex_trylock, (arg1))
  ApiC(g_mutex_unlock, (arg1))
  ApiC(g_node_child_index, (arg1, arg2))
  ApiC(g_node_child_position, (arg1, arg2))
  ApiC(g_node_children_foreach, (arg1, arg2, arg3, arg4))
  ApiC(g_node_copy, (arg1))
  ApiC(g_node_copy_deep, (arg1, arg2, arg3))
  ApiC(g_node_depth, (arg1))
  ApiC(g_node_destroy, (arg1))
  ApiC(g_node_find, (arg1, arg2, arg3, arg4))
  ApiC(g_node_find_child, (arg1, arg2, arg3))
  ApiC(g_node_first_sibling, (arg1))
  ApiC(g_node_get_root, (arg1))
  ApiC(g_node_insert, (arg1, arg2, arg3))
  ApiC(g_node_insert_after, (arg1, arg2, arg3))
  ApiC(g_node_insert_before, (arg1, arg2, arg3))
  ApiC(g_node_is_ancestor, (arg1, arg2))
  ApiC(g_node_last_child, (arg1))
  ApiC(g_node_last_sibling, (arg1))
  ApiC(g_node_max_height, (arg1))
  ApiC(g_node_n_children, (arg1))
  ApiC(g_node_n_nodes, (arg1, arg2))
  ApiC(g_node_new, (arg1))
  ApiC(g_node_nth_child, (arg1, arg2))
  ApiC(g_node_pop_allocator, ())
  ApiC(g_node_prepend, (arg1, arg2))
  ApiC(g_node_push_allocator, (arg1))
  ApiC(g_node_reverse_children, (arg1))
  ApiC(g_node_traverse, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(g_node_unlink, (arg1))
  ApiC(g_nullify_pointer, (arg1))
  ApiC(g_on_error_query, (arg1))
  ApiC(g_on_error_stack_trace, (arg1, arg2))
  ApiC(g_once, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_once_impl, (arg1, arg2, arg3))
  ApiC(g_open, (arg1, arg2, arg3))
  ApiC(g_option_context_add_group, (arg1, arg2))
  ApiC(g_option_context_add_main_entries, (arg1, arg2, arg3))
  ApiC(g_option_context_free, (arg1))
  ApiC(g_option_context_get_help_enabled, (arg1))
  ApiC(g_option_context_get_ignore_unknown_options, (arg1))
  ApiC(g_option_context_get_main_group, (arg1))
  ApiC(g_option_context_new, (arg1))
  ApiC(g_option_context_parse, (arg1, arg2, arg3, arg4))
  ApiC(g_option_context_set_help_enabled, (arg1, arg2))
  ApiC(g_option_context_set_ignore_unknown_options, (arg1, arg2))
  ApiC(g_option_context_set_main_group, (arg1, arg2))
  ApiC(g_option_error_quark, ())
  ApiC(g_option_group_add_entries, (arg1, arg2))
  ApiC(g_option_group_free, (arg1))
  ApiC(g_option_group_new, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_option_group_set_error_hook, (arg1, arg2))
  ApiC(g_option_group_set_parse_hooks, (arg1, arg2, arg3))
  ApiC(g_option_group_set_translate_func, (arg1, arg2, arg3, arg4))
  ApiC(g_option_group_set_translation_domain, (arg1, arg2))
  ApiC(g_parse_debug_string, (arg1, arg2, arg3))
  ApiC(g_path_get_basename, (arg1))
  ApiC(g_path_get_dirname, (arg1))
  ApiC(g_path_is_absolute, (arg1))
  ApiC(g_path_skip_root, (arg1))
  ApiC(g_pattern_match, (arg1, arg2, arg3, arg4))
  ApiC(g_pattern_match_simple, (arg1, arg2))
  ApiC(g_pattern_match_string, (arg1, arg2))
  ApiC(g_pattern_spec_equal, (arg1, arg2))
  ApiC(g_pattern_spec_free, (arg1))
  ApiC(g_pattern_spec_new, (arg1))
  ApiC(g_print, (arg1, arg2, arg3))
  ApiC(g_printerr, (arg1, arg2, arg3))
  ApiC(g_printf, (arg1, arg2, arg3))
  ApiC(g_printf_string_upper_bound, (arg1, arg2))
  ApiC(g_propagate_error, (arg1, arg2))
  ApiC(g_ptr_array_add, (arg1, arg2))
  ApiC(g_ptr_array_foreach, (arg1, arg2, arg3))
  ApiC(g_ptr_array_free, (arg1, arg2))
  ApiC(g_ptr_array_new, ())
  ApiC(g_ptr_array_remove, (arg1, arg2))
  ApiC(g_ptr_array_remove_fast, (arg1, arg2))
  ApiC(g_ptr_array_remove_index, (arg1, arg2))
  ApiC(g_ptr_array_remove_index_fast, (arg1, arg2))
  ApiC(g_ptr_array_remove_range, (arg1, arg2, arg3))
  ApiC(g_ptr_array_set_size, (arg1, arg2))
  ApiC(g_ptr_array_sized_new, (arg1))
  ApiC(g_ptr_array_sort, (arg1, arg2))
  ApiC(g_ptr_array_sort_with_data, (arg1, arg2, arg3))
  ApiC(g_qsort_with_data, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_quark_from_static_string, (arg1))
  ApiC(g_quark_from_string, (arg1))
  ApiC(g_quark_to_string, (arg1))
  ApiC(g_quark_try_string, (arg1))
  ApiC(g_queue_copy, (arg1))
  ApiC(g_queue_delete_link, (arg1, arg2))
  ApiC(g_queue_find, (arg1, arg2))
  ApiC(g_queue_find_custom, (arg1, arg2, arg3))
  ApiC(g_queue_foreach, (arg1, arg2, arg3))
  ApiC(g_queue_free, (arg1))
  ApiC(g_queue_get_length, (arg1))
  ApiC(g_queue_index, (arg1, arg2))
  ApiC(g_queue_insert_after, (arg1, arg2, arg3))
  ApiC(g_queue_insert_before, (arg1, arg2, arg3))
  ApiC(g_queue_insert_sorted, (arg1, arg2, arg3, arg4))
  ApiC(g_queue_is_empty, (arg1))
  ApiC(g_queue_link_index, (arg1, arg2))
  ApiC(g_queue_new, ())
  ApiC(g_queue_peek_head, (arg1))
  ApiC(g_queue_peek_head_link, (arg1))
  ApiC(g_queue_peek_nth, (arg1, arg2))
  ApiC(g_queue_peek_nth_link, (arg1, arg2))
  ApiC(g_queue_peek_tail, (arg1))
  ApiC(g_queue_peek_tail_link, (arg1))
  ApiC(g_queue_pop_head, (arg1))
  ApiC(g_queue_pop_head_link, (arg1))
  ApiC(g_queue_pop_nth, (arg1, arg2))
  ApiC(g_queue_pop_nth_link, (arg1, arg2))
  ApiC(g_queue_pop_tail, (arg1))
  ApiC(g_queue_pop_tail_link, (arg1))
  ApiC(g_queue_push_head, (arg1, arg2))
  ApiC(g_queue_push_head_link, (arg1, arg2))
  ApiC(g_queue_push_nth, (arg1, arg2, arg3))
  ApiC(g_queue_push_nth_link, (arg1, arg2, arg3))
  ApiC(g_queue_push_tail, (arg1, arg2))
  ApiC(g_queue_push_tail_link, (arg1, arg2))
  ApiC(g_queue_remove, (arg1, arg2))
  ApiC(g_queue_remove_all, (arg1, arg2))
  ApiC(g_queue_reverse, (arg1))
  ApiC(g_queue_sort, (arg1, arg2, arg3))
  ApiC(g_queue_unlink, (arg1, arg2))
  ApiC(g_rand_copy, (arg1))
  ApiC(g_rand_double, (arg1))
  ApiC(g_rand_double_range, (arg1, arg2, arg3))
  ApiC(g_rand_free, (arg1))
  ApiC(g_rand_int, (arg1))
  ApiC(g_rand_int_range, (arg1, arg2, arg3))
  ApiC(g_rand_new, ())
  ApiC(g_rand_new_with_seed, (arg1))
  ApiC(g_rand_new_with_seed_array, (arg1, arg2))
  ApiC(g_rand_set_seed, (arg1, arg2))
  ApiC(g_rand_set_seed_array, (arg1, arg2, arg3))
  ApiC(g_random_double, ())
  ApiC(g_random_double_range, (arg1, arg2))
  ApiC(g_random_int, ())
  ApiC(g_random_int_range, (arg1, arg2))
  ApiC(g_random_set_seed, (arg1))
  ApiC(g_realloc, (arg1, arg2))
  ApiC(g_relation_count, (arg1))
  ApiC(g_relation_delete, (arg1))
  ApiC(g_relation_destroy, (arg1))
  ApiC(g_relation_exists, (arg1, arg2))
  ApiC(g_relation_index, (arg1))
  ApiC(g_relation_insert, (arg1))
  ApiC(g_relation_new, (arg1))
  ApiC(g_relation_print, (arg1))
  ApiC(g_relation_select, (arg1))
  ApiC(g_remove, (arg1))
  ApiC(g_rename, (arg1, arg2))
  ApiC(g_return_if_fail, (arg1))
  ApiC(g_return_if_fail_warning, (arg1, arg2, arg3))
  ApiC(g_rmdir, (arg1))
  ApiC(g_scanner_cur_line, (arg1))
  ApiC(g_scanner_cur_position, (arg1))
  ApiC(g_scanner_cur_token, (arg1))
  ApiC(g_scanner_cur_value, (arg1))
  ApiC(g_scanner_destroy, (arg1))
  ApiC(g_scanner_eof, (arg1))
  ApiC(g_scanner_error, (arg1))
  ApiC(g_scanner_get_next_token, (arg1))
  ApiC(g_scanner_input_file, (arg1, arg2))
  ApiC(g_scanner_input_text, (arg1, arg2, arg3))
  ApiC(g_scanner_lookup_symbol, (arg1, arg2))
  ApiC(g_scanner_new, (arg1))
  ApiC(g_scanner_peek_next_token, (arg1))
  ApiC(g_scanner_scope_add_symbol, (arg1, arg2, arg3, arg4))
  ApiC(g_scanner_scope_foreach_symbol, (arg1, arg2, arg3, arg4))
  ApiC(g_scanner_scope_lookup_symbol, (arg1, arg2, arg3))
  ApiC(g_scanner_scope_remove_symbol, (arg1, arg2, arg3))
  ApiC(g_scanner_set_scope, (arg1, arg2))
  ApiC(g_scanner_sync_file_offset, (arg1))
  ApiC(g_scanner_unexp_token, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(g_scanner_warn, (arg1, arg2, arg3, arg4))
  ApiC(g_set_application_name, (arg1))
  ApiC(g_set_error, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(g_set_prgname, (arg1))
  ApiC(g_set_print_handler, (arg1))
  ApiC(g_set_printerr_handler, (arg1))
  ApiC(g_setenv, (arg1, arg2, arg3))
  ApiC(g_shell_error_quark, ())
  ApiC(g_shell_parse_argv, (arg1, arg2, arg3, arg4))
  ApiC(g_shell_quote, (arg1))
  ApiC(g_shell_unquote, (arg1, arg2))
  ApiC(g_slist_alloc, ())
  ApiC(g_slist_append, (arg1, arg2))
  ApiC(g_slist_concat, (arg1, arg2))
  ApiC(g_slist_copy, (arg1))
  ApiC(g_slist_delete_link, (arg1, arg2))
  ApiC(g_slist_find, (arg1, arg2))
  ApiC(g_slist_find_custom, (arg1, arg2, arg3))
  ApiC(g_slist_foreach, (arg1, arg2, arg3))
  ApiC(g_slist_free, (arg1))
  ApiC(g_slist_free_1, (arg1))
  ApiC(g_slist_index, (arg1, arg2))
  ApiC(g_slist_insert, (arg1, arg2, arg3))
  ApiC(g_slist_insert_before, (arg1, arg2, arg3))
  ApiC(g_slist_insert_sorted, (arg1, arg2, arg3))
  ApiC(g_slist_last, (arg1))
  ApiC(g_slist_length, (arg1))
  ApiC(g_slist_nth, (arg1, arg2))
  ApiC(g_slist_nth_data, (arg1, arg2))
  ApiC(g_slist_pop_allocator, ())
  ApiC(g_slist_position, (arg1, arg2))
  ApiC(g_slist_prepend, (arg1, arg2))
  ApiC(g_slist_push_allocator, (arg1))
  ApiC(g_slist_remove, (arg1, arg2))
  ApiC(g_slist_remove_all, (arg1, arg2))
  ApiC(g_slist_remove_link, (arg1, arg2))
  ApiC(g_slist_reverse, (arg1))
  ApiC(g_slist_sort, (arg1, arg2))
  ApiC(g_slist_sort_with_data, (arg1, arg2, arg3))
  ApiC(g_snprintf, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_source_add_poll, (arg1, arg2))
  ApiC(g_source_attach, (arg1, arg2))
  ApiC(g_source_connect_closure, (arg1, arg2))
  ApiC(g_source_destroy, (arg1))
  ApiC(g_source_get_can_recurse, (arg1))
  ApiC(g_source_get_context, (arg1))
  ApiC(g_source_get_current_time, (arg1, arg2))
  ApiC(g_source_get_id, (arg1))
  ApiC(g_source_get_priority, (arg1))
  ApiC(g_source_new, (arg1, arg2))
  ApiC(g_source_ref, (arg1))
  ApiC(g_source_remove, (arg1))
  ApiC(g_source_remove_by_funcs_user_data, (arg1, arg2))
  ApiC(g_source_remove_by_user_data, (arg1))
  ApiC(g_source_remove_poll, (arg1, arg2))
  ApiC(g_source_set_callback, (arg1, arg2, arg3, arg4))
  ApiC(g_source_set_callback_indirect, (arg1, arg2, arg3))
  ApiC(g_source_set_can_recurse, (arg1, arg2))
  ApiC(g_source_set_priority, (arg1, arg2))
  ApiC(g_source_unref, (arg1))
  ApiC(g_spaced_primes_closest, (arg1))
  ApiC(g_spawn_async, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(g_spawn_async_with_pipes, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11))
  ApiC(g_spawn_close_pid, (arg1))
  ApiC(g_spawn_command_line_async, (arg1, arg2))
  ApiC(g_spawn_command_line_sync, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_spawn_error_quark, ())
  ApiC(g_spawn_sync, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10))
  ApiC(g_sprintf, (arg1, arg2, arg3, arg4))
  ApiC(g_stat, (arg1, arg2))
  ApiC(g_static_mutex_free, (arg1))
  ApiC(g_static_mutex_get_mutex_impl, (arg1))
  ApiC(g_static_mutex_init, (arg1))
  ApiC(g_static_mutex_lock, (arg1))
  ApiC(g_static_mutex_trylock, (arg1, arg2))
  ApiC(g_static_mutex_unlock, (arg1))
  ApiC(g_static_private_free, (arg1))
  ApiC(g_static_private_get, (arg1))
  ApiC(g_static_private_init, (arg1))
  ApiC(g_static_private_set, (arg1, arg2, arg3))
  ApiC(g_static_rec_mutex_free, (arg1))
  ApiC(g_static_rec_mutex_init, (arg1))
  ApiC(g_static_rec_mutex_lock, (arg1))
  ApiC(g_static_rec_mutex_lock_full, (arg1, arg2))
  ApiC(g_static_rec_mutex_trylock, (arg1))
  ApiC(g_static_rec_mutex_unlock, (arg1))
  ApiC(g_static_rec_mutex_unlock_full, (arg1))
  ApiC(g_static_rw_lock_free, (arg1))
  ApiC(g_static_rw_lock_init, (arg1))
  ApiC(g_static_rw_lock_reader_lock, (arg1))
  ApiC(g_static_rw_lock_reader_trylock, (arg1))
  ApiC(g_static_rw_lock_reader_unlock, (arg1))
  ApiC(g_static_rw_lock_writer_lock, (arg1))
  ApiC(g_static_rw_lock_writer_trylock, (arg1))
  ApiC(g_static_rw_lock_writer_unlock, (arg1))
  ApiC(g_stpcpy, (arg1, arg2))
  ApiC(g_str_equal, (arg1, arg2))
  ApiC(g_str_has_prefix, (arg1, arg2))
  ApiC(g_str_has_suffix, (arg1, arg2))
  ApiC(g_str_hash, (arg1))
  ApiC(g_strcanon, (arg1, arg2, arg3))
  ApiC(g_strcasecmp, (arg1, arg2))
  ApiC(g_strchomp, (arg1))
  ApiC(g_strchug, (arg1))
  ApiC(g_strcompress, (arg1))
  ApiC(g_strconcat, (arg1, arg2))
  ApiC(g_strdelimit, (arg1, arg2, arg3))
  ApiC(g_strdown, (arg1))
  ApiC(g_strdup, (arg1))
  ApiC(g_strdup_printf, (arg1, arg2, arg3))
  ApiC(g_strdup_vprintf, (arg1, arg2))
  ApiC(g_strdupv, (arg1))
  ApiC(g_strerror, (arg1))
  ApiC(g_strescape, (arg1))
  ApiC(g_strfreev, (arg1))
  ApiC(g_string_append, (arg1, arg2))
  ApiC(g_string_append_c, (arg1, arg2))
  ApiC(g_string_append_c_inline, (arg1, arg2))
  ApiC(g_string_append_len, (arg1, arg2, arg3))
  ApiC(g_string_append_printf, (arg1, arg2, arg3, arg4))
  ApiC(g_string_append_unichar, (arg1, arg2))
  ApiC(g_string_ascii_down, (arg1))
  ApiC(g_string_ascii_up, (arg1))
  ApiC(g_string_assign, (arg1, arg2))
  ApiC(g_string_chunk_free, (arg1))
  ApiC(g_string_chunk_insert, (arg1, arg2))
  ApiC(g_string_chunk_insert_const, (arg1, arg2))
  ApiC(g_string_chunk_insert_len, (arg1, arg2, arg3))
  ApiC(g_string_chunk_new, (arg1))
  ApiC(g_string_down, (arg1))
  ApiC(g_string_equal, (arg1, arg2))
  ApiC(g_string_erase, (arg1, arg2, arg3))
  ApiC(g_string_free, (arg1, arg2))
  ApiC(g_string_hash, (arg1))
  ApiC(g_string_insert, (arg1, arg2, arg3))
  ApiC(g_string_insert_c, (arg1, arg2, arg3))
  ApiC(g_string_insert_len, (arg1, arg2, arg3, arg4))
  ApiC(g_string_insert_unichar, (arg1, arg2, arg3))
  ApiC(g_string_new, (arg1))
  ApiC(g_string_new_len, (arg1, arg2))
  ApiC(g_string_prepend, (arg1, arg2))
  ApiC(g_string_prepend_c, (arg1, arg2))
  ApiC(g_string_prepend_len, (arg1, arg2, arg3))
  ApiC(g_string_prepend_unichar, (arg1, arg2))
  ApiC(g_string_printf, (arg1, arg2, arg3, arg4))
  ApiC(g_string_set_size, (arg1, arg2))
  ApiC(g_string_sized_new, (arg1))
  ApiC(g_string_truncate, (arg1, arg2))
  ApiC(g_string_up, (arg1))
  ApiC(g_strip_context, (arg1, arg2))
  ApiC(g_strjoin, (arg1, arg2))
  ApiC(g_strjoinv, (arg1, arg2))
  ApiC(g_strlcat, (arg1, arg2, arg3))
  ApiC(g_strlcpy, (arg1, arg2, arg3))
  ApiC(g_strncasecmp, (arg1, arg2, arg3))
  ApiC(g_strndup, (arg1, arg2))
  ApiC(g_strnfill, (arg1, arg2))
  ApiC(g_strreverse, (arg1))
  ApiC(g_strrstr, (arg1, arg2))
  ApiC(g_strrstr_len, (arg1, arg2, arg3))
  ApiC(g_strsignal, (arg1))
  ApiC(g_strsplit, (arg1, arg2))
  ApiC(g_strsplit_set, (arg1, arg2, arg3))
  ApiC(g_strstr_len, (arg1, arg2, arg3))
  ApiC(g_strtod, (arg1, arg2))
  ApiC(g_strup, (arg1))
  ApiC(g_strv_length, (arg1))
  ApiC(g_thread_create_full, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(g_thread_error_quark, ())
  ApiC(g_thread_exit, (arg1))
  ApiC(g_thread_init, (arg1))
  ApiC(g_thread_init_with_errorcheck_mutexes, (arg1))
  ApiC(g_thread_join, (arg1))
  ApiC(g_thread_pool_free, (arg1, arg2, arg3))
  ApiC(g_thread_pool_get_max_threads, (arg1))
  ApiC(g_thread_pool_get_max_unused_threads, ())
  ApiC(g_thread_pool_get_num_threads, (arg1))
  ApiC(g_thread_pool_get_num_unused_threads, ())
  ApiC(g_thread_pool_new, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_thread_pool_push, (arg1, arg2, arg3))
  ApiC(g_thread_pool_set_max_threads, (arg1, arg2, arg3))
  ApiC(g_thread_pool_set_max_unused_threads, (arg1))
  ApiC(g_thread_pool_stop_unused_threads, ())
  ApiC(g_thread_pool_unprocessed, (arg1))
  ApiC(g_thread_self, ())
  ApiC(g_thread_set_priority, (arg1, arg2))
  ApiC(g_time_val_add, (arg1, arg2))
  ApiC(g_timeout_add, (arg1, arg2, arg3))
  ApiC(g_timeout_add_full, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_timeout_source_new, (arg1))
  ApiC(g_timer_continue, (arg1))
  ApiC(g_timer_destroy, (arg1))
  ApiC(g_timer_elapsed, (arg1, arg2))
  ApiC(g_timer_new, ())
  ApiC(g_timer_reset, (arg1))
  ApiC(g_timer_start, (arg1))
  ApiC(g_timer_stop, (arg1))
  ApiC(g_trash_stack_height, (arg1))
  ApiC(g_trash_stack_peek, (arg1))
  ApiC(g_trash_stack_pop, (arg1))
  ApiC(g_trash_stack_push, (arg1, arg2))
  ApiC(g_tree_destroy, (arg1))
  ApiC(g_tree_foreach, (arg1, arg2, arg3))
  ApiC(g_tree_height, (arg1))
  ApiC(g_tree_insert, (arg1, arg2, arg3))
  ApiC(g_tree_lookup, (arg1, arg2))
  ApiC(g_tree_lookup_extended, (arg1, arg2, arg3, arg4))
  ApiC(g_tree_new, (arg1))
  ApiC(g_tree_new_full, (arg1, arg2, arg3, arg4))
  ApiC(g_tree_new_with_data, (arg1, arg2))
  ApiC(g_tree_nnodes, (arg1))
  ApiC(g_tree_remove, (arg1, arg2))
  ApiC(g_tree_replace, (arg1, arg2, arg3))
  ApiC(g_tree_search, (arg1, arg2, arg3))
  ApiC(g_tree_steal, (arg1, arg2))
  ApiC(g_tree_traverse, (arg1, arg2, arg3, arg4))
  ApiC(g_try_malloc, (arg1))
  ApiC(g_try_realloc, (arg1, arg2))
  ApiC(g_tuples_destroy, (arg1))
  ApiC(g_tuples_index, (arg1, arg2, arg3))
  ApiC(g_ucs4_to_utf16, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_ucs4_to_utf8, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_unichar_break_type, (arg1))
  ApiC(g_unichar_digit_value, (arg1))
  ApiC(g_unichar_get_mirror_char, (arg1, arg2))
  ApiC(g_unichar_isalnum, (arg1))
  ApiC(g_unichar_isalpha, (arg1))
  ApiC(g_unichar_iscntrl, (arg1))
  ApiC(g_unichar_isdefined, (arg1))
  ApiC(g_unichar_isdigit, (arg1))
  ApiC(g_unichar_isgraph, (arg1))
  ApiC(g_unichar_islower, (arg1))
  ApiC(g_unichar_isprint, (arg1))
  ApiC(g_unichar_ispunct, (arg1))
  ApiC(g_unichar_isspace, (arg1))
  ApiC(g_unichar_istitle, (arg1))
  ApiC(g_unichar_isupper, (arg1))
  ApiC(g_unichar_iswide, (arg1))
  ApiC(g_unichar_isxdigit, (arg1))
  ApiC(g_unichar_to_utf8, (arg1, arg2))
  ApiC(g_unichar_tolower, (arg1))
  ApiC(g_unichar_totitle, (arg1))
  ApiC(g_unichar_toupper, (arg1))
  ApiC(g_unichar_type, (arg1))
  ApiC(g_unichar_validate, (arg1))
  ApiC(g_unichar_xdigit_value, (arg1))
  ApiC(g_unicode_canonical_decomposition, (arg1, arg2))
  ApiC(g_unicode_canonical_ordering, (arg1, arg2))
  ApiC(g_unlink, (arg1))
  ApiC(g_unsetenv, (arg1))
  ApiC(g_uri_list_extract_uris, (arg1))
  ApiC(g_usleep, (arg1))
  ApiC(g_utf16_to_ucs4, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_utf16_to_utf8, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_utf8_casefold, (arg1, arg2))
  ApiC(g_utf8_collate, (arg1, arg2))
  ApiC(g_utf8_collate_key, (arg1, arg2))
  ApiC(g_utf8_find_next_char, (arg1, arg2))
  ApiC(g_utf8_find_prev_char, (arg1, arg2))
  ApiC(g_utf8_get_char, (arg1))
  ApiC(g_utf8_get_char_validated, (arg1, arg2))
  ApiC(g_utf8_normalize, (arg1, arg2, arg3))
  ApiC(g_utf8_offset_to_pointer, (arg1, arg2))
  ApiC(g_utf8_pointer_to_offset, (arg1, arg2))
  ApiC(g_utf8_prev_char, (arg1))
  ApiC(g_utf8_strchr, (arg1, arg2, arg3))
  ApiC(g_utf8_strdown, (arg1, arg2))
  ApiC(g_utf8_strlen, (arg1, arg2))
  ApiC(g_utf8_strncpy, (arg1, arg2, arg3))
  ApiC(g_utf8_strrchr, (arg1, arg2, arg3))
  ApiC(g_utf8_strreverse, (arg1, arg2))
  ApiC(g_utf8_strup, (arg1, arg2))
  ApiC(g_utf8_to_ucs4, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_utf8_to_ucs4_fast, (arg1, arg2, arg3))
  ApiC(g_utf8_to_utf16, (arg1, arg2, arg3, arg4, arg5))
  ApiC(g_utf8_validate, (arg1, arg2, arg3))
  ApiC(g_vasprintf, (arg1, arg2, arg3))
  ApiC(g_vfprintf, (arg1, arg2, arg3))
  ApiC(g_vprintf, (arg1, arg2))
  ApiC(g_vsnprintf, (arg1, arg2, arg3, arg4))
  ApiC(g_vsprintf, (arg1, arg2, arg3))
  ApiC(g_warning, (arg1, arg2))
  ApiC(g_win32_error_message, (arg1))
  ApiC(g_win32_ftruncate, (arg1, arg2))
  ApiC(g_win32_get_package_installation_directory, (arg1, arg2))
  ApiC(g_win32_get_package_installation_subdirectory, (arg1, arg2, arg3))
  ApiC(g_win32_get_windows_version, ())
  ApiC(g_win32_getlocale, ())
EndImport
