XIncludeFile "common.pbi"

ImportC "-framework ApplicationServices"
  
  ApiC(AXAPIEnabled, ())
  ApiC(AXUIElementCopyAttributeNames, (element, *names))
  ApiC(AXUIElementCopyAttributeValue, (element, attribute, *value))
  ApiC(AXUIElementCreateApplication, (pid))
  ApiC(AXUIElementGetTypeID, ())
  ApiC(AXUIElementPerformAction, (element, action))
  ApiC(AXUIElementSetAttributeValue, (element, attribute, value))
  ApiC(AXValueGetTypeID, ())
  ApiC(CGBitmapContextCreate, (*bdata, width, height, bitsPerComponent, bytesPerRow, colorspace, bitmapInfo))
  ApiC(CGColorGetTypeID, ())
  ApiC(CGColorSpaceCreateDeviceGray, ())
  ApiC(CGColorSpaceCreateDeviceRGB, ())
  ApiC(CGColorSpaceGetTypeID, ())
  ApiC(CGColorSpaceRelease, (space))
  ApiC(CGColorSpaceRetain, (space))
  ApiC(CGContextGetTypeID, ())
  ApiC(CGContextRelease, (c))
  ApiC(CGContextRetain, (c))
  ApiC(CGDataProviderCopyData, (provider))
  ApiC(CGDataProviderCreateWithCFData, (cfdata))
  ApiC(CGDataProviderGetTypeID, ())
  ApiC(CGDataProviderRelease, (provider))
  ApiC(CGDataProviderRetain, (provider))
  ApiC(CGDisplayCreateImage, (displayID))
  ApiC(CGDisplayIsBuiltin, (display))
  ApiC(CGDisplayPixelsHigh, (display))
  ApiC(CGDisplayPixelsWide, (display))
  ApiC(CGEventCreate, (source))
  ApiC(CGEventCreateKeyboardEvent, (source, virtualKey, keyDown))
  ApiC(CGEventGetDoubleValueField, .d(event, field))
  ApiC(CGEventGetFlags, .q(event))
  ApiC(CGEventGetIntegerValueField, .q(event, field))
  ApiC(CGEventGetTimestamp, .q(event))
  ApiC(CGEventGetType, (event))
  ApiC(CGEventGetTypeID, ())
  ApiC(CGEventKeyboardGetUnicodeString, (event, maxStringLength, *actualStringLength, *unicodeString))
  ApiC(CGEventPost, (tap, event))
  ApiC(CGEventPostToPSN, (*psn, event))
  ApiC(CGEventSetDoubleValueField, (event, field, value.d))
  ApiC(CGEventSetFlags, (event, flags.q))
  ApiC(CGEventSetIntegerValueField, (event, field, value.q))
  ApiC(CGEventSetTimestamp, (event, timestamp.q))
  ApiC(CGEventSetType, (event, type))
  ApiC(CGEventSourceButtonState, (stateID, button))
  ApiC(CGEventSourceCreate, (stateID))
  ApiC(CGEventSourceKeyState, (stateID, key))
  ApiC(CGEventSourceFlagsState, (stateID))
  ApiC(CGEventTapCreate, (tap, place, options, eventsOfInterest.q, callback, refcon))
  ApiC(CGEventTapCreateForPSN, (*psn, place, options, eventsOfInterest.q, callback, refcon))
  ApiC(CGEventTapEnable, (tap, enable))
  ApiC(CGEventTapIsEnabled, (tap))
  ApiC(CGEventTapPostEvent, (proxy, event))
  ApiC(CGFontGetTypeID, ())
  ApiC(CGFunctionGetTypeID, ())
  ApiC(CGGradientGetTypeID, ())
  ApiC(CGImageCreate, (width, height, bitsPerComponent, bitsPerPixel, bytesPerRow, space, bitmapInfo, provider, *decode, shouldInterpolate, intent))
  ApiC(CGImageGetAlphaInfo, (image))
  ApiC(CGImageGetBitmapInfo, (image))
  ApiC(CGImageGetBitsPerComponent, (image))
  ApiC(CGImageGetBitsPerPixel, (image))
  ApiC(CGImageGetBytesPerRow, (image))
  ApiC(CGImageGetColorSpace, (image))
  ApiC(CGImageGetDataProvider, (image))
  ApiC(CGImageGetHeight, (image))
  ApiC(CGImageGetTypeID, ())
  ApiC(CGImageGetWidth, (image))
  ApiC(CGImageRelease, (image))
  ApiC(CGImageRetain, (image))
  ApiC(CGImageSourceCopyProperties, (isrc, options))
  ApiC(CGImageSourceCopyPropertiesAtIndex, (isrc, index, options))
  ApiC(CGImageSourceCreateImageAtIndex, (isrc, index, options))
  ApiC(CGImageSourceCreateWithURL, (url, options))
  ApiC(CGMainDisplayID, ())
  ApiC(CGPathGetTypeID, ())
  ApiC(CGPatternGetTypeID, ())
  ApiC(CGShadingGetTypeID, ())
  ApiC(PMPaperGetPPDPaperName, (paper, *paperName))
  ApiC(PMPrinterGetName, (printer))
  ApiC(PMPrinterGetPaperList, (printer, *paperList))
  ApiC(PMPrinterIsDefault, (printer))
  ApiC(PMServerCreatePrinterList, (server, *printerList))
  
  ApiC(ContinueSpeech, (chan))
  ApiC(CopySpeechProperty, (chan, property, *object))
  ApiC(CountVoices, (*numVoices))
  ApiC(DisposeSpeechChannel, (chan))
  ApiC(GetIndVoice, (index, *voice))
  ApiC(GetVoiceDescription, (*voice, *info, infoLength))
  ApiC(NewSpeechChannel, (*voice, *chan))
  ApiC(PauseSpeechAt, (chan, whereToPause))
  ApiC(SetSpeechProperty, (chan, property, object))
  ApiC(SpeakCFString, (chan, aString, options))
  ApiC(SpeechBusy, ())
  ApiC(SpeechBusySystemWide, ())
  ApiC(StopSpeech, (chan))
  ApiC(StopSpeechAt, (chan, whereToStop))
  
EndImport
