XIncludeFile "common.pbi"

ImportC "-framework CoreFoundation"
  ApiC(CFAbsoluteTimeGetCurrent, .d())
  ApiC(CFArrayAppendValue, (theArray, *value))
  ApiC(CFArrayCreate, (allocator, *values, numValues, *callBacks))
  ApiC(CFArrayCreateMutable, (allocator, capacity, *callBacks))
  ApiC(CFArrayCreateMutableCopy, (allocator, capacity, theArray))
  ApiC(CFArrayGetCount, (theArray))
  ApiC(CFArrayGetTypeID, ())
  ApiC(CFArrayGetValueAtIndex, (theArray, idx))
  ApiC(CFArrayInsertValueAtIndex, (theArray, idx, *value))
  ApiC(CFArrayRemoveAllValues, (theArray))
  ApiC(CFArrayRemoveValueAtIndex, (theArray, idx))
  ApiC(CFArraySetValueAtIndex, (theArray, idx, *value))
  ApiC(CFBooleanGetTypeID, ())
  ApiC(CFBooleanGetValue, (boolean))
  ApiC(CFBundleCopyBundleURL, (bundle))
  ApiC(CFBundleGetMainBundle, ())
  ApiC(CFDataCreate, (allocator, *bytes, length))
  ApiC(CFDataGetBytePtr, (theData))
  ApiC(CFDataGetTypeID, ())
  ApiC(CFDateFormatterCreate, (allocator, locale, dateStyle, timeStyle))
  ApiC(CFDateFormatterCreateDateFormatFromTemplate, (allocator, tmplate, options, locale))
  ApiC(CFDateFormatterCreateDateFromString, (allocator, formatter, string, *rangep))
  ApiC(CFDateFormatterCreateStringWithAbsoluteTime, (allocator, formatter, at.d))
  ApiC(CFDateFormatterCreateStringWithDate, (allocator, formatter, date))
  ApiC(CFDateFormatterGetAbsoluteTimeFromString, (formatter, string, *rangep, *atp))
  ApiC(CFDateFormatterGetTypeID, ())
  ApiC(CFDateFormatterSetFormat, (formatter, formatString))
  ApiC(CFDateGetTypeID, ())
  ApiC(CFDictionaryAddValue, (theDict, *key, *value))
  ApiC(CFDictionaryCreate, (allocator, *keys, *values, numValues, *keyCallBacks, *valueCallBacks))
  ApiC(CFDictionaryCreateMutable, (allocator, capacity, *keyCallBacks, *valueCallBacks))
  ApiC(CFDictionaryCreateMutableCopy, (allocator, capacity, theDict))
  ApiC(CFDictionaryGetTypeID, ())
  ApiC(CFDictionaryGetValue, (theDict, *key))
  ApiC(CFDictionaryRemoveAllValues, (theDict))
  ApiC(CFDictionaryRemoveValue, (theDict, *key))
  ApiC(CFDictionaryReplaceValue, (theDict, *key, *value))
  ApiC(CFDictionarySetValue, (theDict, *key, *value))
  ApiC(CFEqual, (cf1, cf2))
  ApiC(CFGetTypeID, (cf))
  ApiC(CFLocaleCopyCurrent, ())
  ApiC(CFLocaleCreate, (allocator, localeIdentifier))
  ApiC(CFLocaleGetSystem, ())
  ApiC(CFMachPortCreateRunLoopSource, (allocator, port, order))
  ApiC(CFMachPortInvalidate, (port))
  ApiC(CFMachPortIsValid, (port))
  ApiC(CFNullGetTypeID, ())
  ApiC(CFNumberCreate, (allocator, theType, *valuePtr))
  ApiC(CFNumberFormatterCreate, (allocator, locale, style))
  ApiC(CFNumberFormatterCreateNumberFromString, (allocator, formatter, string, *rangep, options))
  ApiC(CFNumberFormatterCreateStringWithNumber, (allocator, formatter, number))
  ApiC(CFNumberFormatterCreateStringWithValue, (allocator, formatter, numberType, *valuePtr))
  ApiC(CFNumberFormatterGetTypeID, ())
  ApiC(CFNumberFormatterSetFormat, (formatter, formatString))
  ApiC(CFNumberGetTypeID, ())
  ApiC(CFNumberGetValue, (number, theType, *valuePtr))
  ApiC(CFPreferencesCopyValue, (key, applicationID, userName, hostName))
  ApiC(CFRelease, (cf))
  ApiC(CFRetain, (cf))
  ApiC(CFRunLoopAddCommonMode, (rl, mode))
  ApiC(CFRunLoopAddObserver, (rl, observer, mode))
  ApiC(CFRunLoopAddSource, (rl, source, mode))
  ApiC(CFRunLoopAddTimer, (rl, timer, mode))
  ApiC(CFRunLoopObserverDoesRepeat, (observer))
  ApiC(CFRunLoopObserverGetActivities, (observer))
  ApiC(CFRunLoopGetCurrent, ())
  ApiC(CFRunLoopGetMain, ())
  ApiC(CFRunLoopTimerGetNextFireDate, .d(timer))
  ApiC(CFRunLoopObserverCreate, (allocator, activities, repeats, order, callout, *context))
  ApiC(CFRunLoopObserverInvalidate, (observer))
  ApiC(CFRunLoopObserverIsValid, (observer))
  ApiC(CFRunLoopRemoveObserver, (rl, observer, mode))
  ApiC(CFRunLoopRemoveSource, (rl, source, mode))
  ApiC(CFRunLoopRemoveTimer, (rl, timer, mode))
  ApiC(CFRunLoopTimerCreate, (allocator, fireDate.d, interval.d, flags, order, callout, *context))
  ApiC(CFSetCreate, (allocator, *values, numValues, *callBacks))
  ApiC(CFSetGetCount, (theSet))
  ApiC(CFSetGetTypeID, ())
  ApiC(CFSetGetValues, (theSet, *values))
  ApiC(CFStringAppendCString, (theString, *cStr, encoding))
  ApiC(CFStringAppendCharacters, (theString, *chars, numChars))
  ApiC(CFStringAppendPascalString, (theString, *pStr, encoding))
  ApiC(CFStringCapitalize, (theString, locale))
  ApiC(CFStringCompare, (theString1, theString2, compareOptions))
  ApiC(CFStringCreateArrayBySeparatingStrings, (alloc, theString, separatorString))
  ApiC(CFStringCreateByCombiningStrings, (alloc, theArray, separatorString))
  ApiC(CFStringCreateMutable, (alloc, maxLength))
  ApiC(CFStringCreateMutableCopy, (alloc, maxLength, theString))
  ApiC(CFStringCreateWithBytes, (alloc, *bytes, numBytes, encoding, isExternalRepresentation))
  ApiC(CFStringCreateWithCString, (alloc, *cStr, encoding))
  ApiC(CFStringCreateWithCharacters, (alloc, *chars, numChars))
  ApiC(CFStringCreateWithPascalString, (alloc, *pStr, encoding))
  ApiC(CFStringGetDoubleValue, .d(str))
  ApiC(CFStringGetCString, (theString, *buffer, bufferSize, encoding))
  ApiC(CFStringGetCStringPtr, (theString, encoding))
  ApiC(CFStringGetIntValue, (str))
  ApiC(CFStringGetLength, (theString))
  ApiC(CFStringGetPascalString, (theString, *buffer, bufferSize, encoding))
  ApiC(CFStringGetTypeID, ())
  ApiC(CFStringHasPrefix, (theString, prefix))
  ApiC(CFStringHasSuffix, (theString, suffix))
  ApiC(CFStringLowercase, (theString, locale))
  ApiC(CFStringReplaceAll, (theString, replacement))
  ApiC(CFStringTrim, (theString, trimString))
  ApiC(CFStringTrimWhitespace, (theString))
  ApiC(CFStringUppercase, (theString, locale))
  ApiC(CFURLCreateFromFileSystemRepresentation, (allocator, *buffer, bufLen, isDirectory))
  ApiC(CFURLCreateWithFileSystemPath, (allocator, filePath, pathStyle, isDirectory))
  ApiC(CFURLCreateWithString, (allocator, URLString, baseURL))
  ApiC(CFURLGetFileSystemRepresentation, (url, resolveAgainstBase, *buffer, maxBufLen))
  ApiC(CFURLGetString, (anURL))
EndImport
