XIncludeFile "common.pbi"

ImportC "-framework Foundation"
  ApiC(NSDecimalAdd, (*result, *leftOperand, *rightOperand, roundingMode))
  ApiC(NSDecimalCompact, (*number))
  ApiC(NSDecimalCompare, (*leftOperand, *rightOperand))
  ApiC(NSDecimalCopy, (*destination, *source))
  ApiC(NSDecimalDivide, (*result, *leftOperand, *rightOperand, roundingMode))
  ApiC(NSDecimalMultiply, (*result, *leftOperand, *rightOperand, roundingMode))
  ApiC(NSDecimalMultiplyByPowerOf10, (*result, *number, power.w, roundingMode))
  ApiC(NSDecimalNormalize, (*number1, *number2, roundingMode))
  ApiC(NSDecimalPower, (*result, *number, power, roundingMode))
  ApiC(NSDecimalRound, (*result, *number, scale, roundingMode))
  ApiC(NSDecimalString, (*dcm, locale))
  ApiC(NSDecimalSubtract, (*result, *leftOperand, *rightOperand, roundingMode))
  ApiC(NSFullUserName, ())
  ApiC(NSHomeDirectory, ())
  ApiC(NSSearchPathForDirectoriesInDomains, (directory, domainMask, expandTilde))
  ApiC(NSClassFromString, (aClassName))
  ApiC(NSProtocolFromString, (namestr))
  ApiC(NSSelectorFromString, (aSelectorName))
  ApiC(NSStringFromClass, (aClass))
  ApiC(NSStringFromProtocol, (proto))
  ApiC(NSStringFromSelector, (aSelector))
  ApiC(class_addIvar, (cls, name.p-utf8, size, alignment, types.p-utf8))
  ApiC(class_addMethod, (cls, name, imp, types.p-utf8))
  ApiC(class_addProtocol, (cls, *protocol))
  ApiC(class_createInstance, (cls, extraBytes))
  ApiC(class_getClassMethod, (aClass, aSelector))
  ApiC(class_getClassVariable, (cls, name.p-utf8))
  ApiC(class_getImageName, (cls))
  ApiC(class_getInstanceMethod, (aClass, aSelector))
  ApiC(class_getInstanceVariable, (cls, name.p-utf8))
  ApiC(class_getMethodImplementation, (cls, name))
  ApiC(class_getName, (cls))
  ApiC(class_getSuperclass, (cls))
  ApiC(class_getVersion, (cls))
  ApiC(class_replaceMethod, (cls, name, imp, types.p-utf8))
  ApiC(class_setVersion, (cls, version))
  ApiC(dlclose, (handle))
  ApiC(dlerror, ())
  ApiC(dlopen, (path.p-utf8, mode))
  ApiC(dlsym, (handle, symbol.p-utf8))
  ApiC(ivar_getOffset, (ivar))
  ApiC(mach_absolute_time, .q())
  ApiC(method_exchangeImplementations, (m1, m2))
  ApiC(method_getImplementation, (method))
  ApiC(method_getTypeEncoding, (method))
  ApiC(method_setImplementation, (method, imp))
  ApiC(objc_allocateClassPair, (superclass, name.p-utf8, extraBytes))
  ApiC(objc_getAssociatedObject, (object, *key))
  ApiC(objc_getClass, (name.p-utf8))
  ApiC(objc_getMetaClass, (name.p-utf8))
  ApiC(objc_getProtocol, (name.p-utf8))
  ApiC(objc_lookUpClass, (name.p-utf8))
  ApiC(objc_registerClassPair, (cls))
  ApiC(objc_removeAssociatedObjects, (object))
  ApiC(objc_setAssociatedObject, (object, *key, value, policy))
  ApiC(object_getClass, (obj))
  ApiC(object_getClassName, (obj))
  ApiC(object_getIndexedIvars, (obj))
  ApiC(object_getInstanceVariable, (obj, name.p-utf8, *pOutValue))
  ApiC(object_getIvar, (obj, ivar))
  ApiC(object_setClass, (obj, cls))
  ApiC(object_setInstanceVariable, (obj, name.p-utf8, *value))
  ApiC(object_setIvar, (obj, ivar, value))
  ApiC(sel_getName, (aSelector))
  ApiC(sel_isEqual, (lhs, rhs))
  ApiC(sel_registerName, (str.p-utf8))
  ApiC(sysctlbyname, (name.p-ascii, *oldp, *oldlenp, *newp, newlen))
EndImport
