XIncludeFile "common.pbi"

CompilerSelect #PB_Compiler_OS

CompilerCase #PB_OS_Windows

  ; All Windows specific functions
  ;
  Import "opengl32.lib"
         Api(wglChoosePixelFormat, (arg1, arg2), 8)
         Api(wglCopyContext, (arg1, arg2, arg3), 12)
         Api(wglCreateContext, (arg1), 4)
         Api(wglCreateLayerContext, (arg1, arg2), 8)
         Api(wglDeleteContext, (arg1), 4)
         Api(wglDescribeLayerPlane, (arg1, arg2, arg3, arg4, arg5), 20)
         Api(wglDescribePixelFormat, (arg1, arg2, arg3, arg4), 16)
         Api(wglGetCurrentContext, (), 0)
         Api(wglGetCurrentDC, (), 0)
         Api(wglGetDefaultProcAddress, (arg1), 4)
         Api(wglGetLayerPaletteEntries, (arg1, arg2, arg3, arg4, arg5), 20)
         Api(wglGetPixelFormat, (arg1), 4)
         Api(wglGetProcAddress, (arg1.p-ascii), 4)
         Api(wglMakeCurrent, (arg1, arg2), 8)
         Api(wglRealizeLayerPalette, (arg1, arg2, arg3), 12)
         Api(wglSetLayerPaletteEntries, (arg1, arg2, arg3, arg4, arg5), 20)
         Api(wglSetPixelFormat, (arg1, arg2, arg3), 12)
         Api(wglShareLists, (arg1, arg2), 8)
         Api(wglSwapBuffers, (arg1), 4)
         Api(wglSwapLayerBuffers, (arg1, arg2), 8)
         Api(wglSwapMultipleBuffers, (arg1, arg2), 8)
    AnsiWide(wglUseFontBitmaps, (arg1, arg2, arg3, arg4), 16)
    AnsiWide(wglUseFontOutlines, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)

CompilerCase #PB_OS_MacOS

  ImportC "-framework Carbon -framework OpenGL"

CompilerDefault ; Linux

  ImportC "-L/usr/X11R6/lib -lGL -lGLU -lXxf86vm -lX11"

CompilerEndSelect

  ; Common OpenGL functions
  ;
  Api(glAccum, (arg1, arg2.f), 8)
  Api(glAlphaFunc, (arg1, arg2.f), 8)
  Api(glAreTexturesResident, (arg1, arg2, arg3), 12)
  Api(glArrayElement, (arg1), 4)
  Api(glBegin, (arg1), 4)
  Api(glBindTexture, (arg1, arg2), 8)
  Api(glBitmap, (arg1, arg2, arg3.f, arg4.f, arg5.f, arg6.f, arg7), 28)
  Api(glBlendFunc, (arg1, arg2), 8)
  Api(glCallList, (arg1), 4)
  Api(glCallLists, (arg1, arg2, arg3), 12)
  Api(glClear, (arg1), 4)
  Api(glClearAccum, (arg1.f, arg2.f, arg3.f, arg4.f), 16)
  Api(glClearColor, (arg1.f, arg2.f, arg3.f, arg4.f), 16)
  Api(glClearDepth, (arg1.d), 8)
  Api(glClearIndex, (arg1.f), 4)
  Api(glClearStencil, (arg1), 4)
  Api(glClipPlane, (arg1, arg2), 8)
  Api(glColor3b, (arg1, arg2, arg3), 12)
  Api(glColor3bv, (arg1), 4)
  Api(glColor3d, (arg1.d, arg2.d, arg3.d), 24)
  Api(glColor3dv, (arg1), 4)
  Api(glColor3f, (arg1.f, arg2.f, arg3.f), 12)
  Api(glColor3fv, (arg1), 4)
  Api(glColor3i, (arg1, arg2, arg3), 12)
  Api(glColor3iv, (arg1), 4)
  Api(glColor3s, (arg1, arg2, arg3), 12)
  Api(glColor3sv, (arg1), 4)
  Api(glColor3ub, (arg1, arg2, arg3), 12)
  Api(glColor3ubv, (arg1), 4)
  Api(glColor3ui, (arg1, arg2, arg3), 12)
  Api(glColor3uiv, (arg1), 4)
  Api(glColor3us, (arg1, arg2, arg3), 12)
  Api(glColor3usv, (arg1), 4)
  Api(glColor4b, (arg1, arg2, arg3, arg4), 16)
  Api(glColor4bv, (arg1), 4)
  Api(glColor4d, (arg1.d, arg2.d, arg3.d, arg4.d), 32)
  Api(glColor4dv, (arg1), 4)
  Api(glColor4f, (arg1.f, arg2.f, arg3.f, arg4.f), 16)
  Api(glColor4fv, (arg1), 4)
  Api(glColor4i, (arg1, arg2, arg3, arg4), 16)
  Api(glColor4iv, (arg1), 4)
  Api(glColor4s, (arg1, arg2, arg3, arg4), 16)
  Api(glColor4sv, (arg1), 4)
  Api(glColor4ub, (arg1, arg2, arg3, arg4), 16)
  Api(glColor4ubv, (arg1), 4)
  Api(glColor4ui, (arg1, arg2, arg3, arg4), 16)
  Api(glColor4uiv, (arg1), 4)
  Api(glColor4us, (arg1, arg2, arg3, arg4), 16)
  Api(glColor4usv, (arg1), 4)
  Api(glColorMask, (arg1, arg2, arg3, arg4), 16)
  Api(glColorMaterial, (arg1, arg2), 8)
  Api(glColorPointer, (arg1, arg2, arg3, arg4), 16)
  Api(glCopyPixels, (arg1, arg2, arg3, arg4, arg5), 20)
  Api(glCopyTexImage1D, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  Api(glCopyTexImage2D, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  Api(glCopyTexSubImage1D, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  Api(glCopyTexSubImage2D, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  Api(glCullFace, (arg1), 4)
  Api(glDebugEntry, (arg1, arg2), 8)
  Api(glDeleteLists, (arg1, arg2), 8)
  Api(glDeleteTextures, (arg1, arg2), 8)
  Api(glDepthFunc, (arg1), 4)
  Api(glDepthMask, (arg1), 4)
  Api(glDepthRange, (arg1.d, arg2.d), 16)
  Api(glDisable, (arg1), 4)
  Api(glDisableClientState, (arg1), 4)
  Api(glDrawArrays, (arg1, arg2, arg3), 12)
  Api(glDrawBuffer, (arg1), 4)
  Api(glDrawElements, (arg1, arg2, arg3, arg4), 16)
  Api(glDrawPixels, (arg1, arg2, arg3, arg4, arg5), 20)
  Api(glEdgeFlag, (arg1), 4)
  Api(glEdgeFlagPointer, (arg1, arg2), 8)
  Api(glEdgeFlagv, (arg1), 4)
  Api(glEnable, (arg1), 4)
  Api(glEnableClientState, (arg1), 4)
  Api(glEnd, (), 0)
  Api(glEndList, (), 0)
  Api(glEvalCoord1d, (arg1.d), 8)
  Api(glEvalCoord1dv, (arg1), 4)
  Api(glEvalCoord1f, (arg1.f), 4)
  Api(glEvalCoord1fv, (arg1), 4)
  Api(glEvalCoord2d, (arg1.d, arg2.d), 16)
  Api(glEvalCoord2dv, (arg1), 4)
  Api(glEvalCoord2f, (arg1.f, arg2.f), 8)
  Api(glEvalCoord2fv, (arg1), 4)
  Api(glEvalMesh1, (arg1, arg2, arg3), 12)
  Api(glEvalMesh2, (arg1, arg2, arg3, arg4, arg5), 20)
  Api(glEvalPoint1, (arg1), 4)
  Api(glEvalPoint2, (arg1, arg2), 8)
  Api(glFeedbackBuffer, (arg1, arg2, arg3), 12)
  Api(glFinish, (), 0)
  Api(glFlush, (), 0)
  Api(glFogf, (arg1, arg2.f), 8)
  Api(glFogfv, (arg1, arg2), 8)
  Api(glFogi, (arg1, arg2), 8)
  Api(glFogiv, (arg1, arg2), 8)
  Api(glFrontFace, (arg1), 4)
  Api(glFrustum, (arg1.d, arg2.d, arg3.d, arg4.d, arg5.d, arg6.d), 48)
  Api(glGenLists, (arg1), 4)
  Api(glGenTextures, (arg1, arg2), 8)
  Api(glGetBooleanv, (arg1, arg2), 8)
  Api(glGetClipPlane, (arg1, arg2), 8)
  Api(glGetDoublev, (arg1, arg2), 8)
  Api(glGetError, (), 0)
  Api(glGetFloatv, (arg1, arg2), 8)
  Api(glGetIntegerv, (arg1, arg2), 8)
  Api(glGetLightfv, (arg1, arg2, arg3), 12)
  Api(glGetLightiv, (arg1, arg2, arg3), 12)
  Api(glGetMapdv, (arg1, arg2, arg3), 12)
  Api(glGetMapfv, (arg1, arg2, arg3), 12)
  Api(glGetMapiv, (arg1, arg2, arg3), 12)
  Api(glGetMaterialfv, (arg1, arg2, arg3), 12)
  Api(glGetMaterialiv, (arg1, arg2, arg3), 12)
  Api(glGetPixelMapfv, (arg1, arg2), 8)
  Api(glGetPixelMapuiv, (arg1, arg2), 8)
  Api(glGetPixelMapusv, (arg1, arg2), 8)
  Api(glGetPointerv, (arg1, arg2), 8)
  Api(glGetPolygonStipple, (arg1), 4)
  Api(glGetString, (arg1), 4)
  Api(glGetTexEnvfv, (arg1, arg2, arg3), 12)
  Api(glGetTexEnviv, (arg1, arg2, arg3), 12)
  Api(glGetTexGendv, (arg1, arg2, arg3), 12)
  Api(glGetTexGenfv, (arg1, arg2, arg3), 12)
  Api(glGetTexGeniv, (arg1, arg2, arg3), 12)
  Api(glGetTexImage, (arg1, arg2, arg3, arg4, arg5), 20)
  Api(glGetTexLevelParameterfv, (arg1, arg2, arg3, arg4), 16)
  Api(glGetTexLevelParameteriv, (arg1, arg2, arg3, arg4), 16)
  Api(glGetTexParameterfv, (arg1, arg2, arg3), 12)
  Api(glGetTexParameteriv, (arg1, arg2, arg3), 12)
  Api(glHint, (arg1, arg2), 8)
  Api(glIndexd, (arg1.d), 8)
  Api(glIndexdv, (arg1), 4)
  Api(glIndexf, (arg1.f), 4)
  Api(glIndexfv, (arg1), 4)
  Api(glIndexi, (arg1), 4)
  Api(glIndexiv, (arg1), 4)
  Api(glIndexMask, (arg1), 4)
  Api(glIndexPointer, (arg1, arg2, arg3), 12)
  Api(glIndexs, (arg1), 4)
  Api(glIndexsv, (arg1), 4)
  Api(glIndexub, (arg1), 4)
  Api(glIndexubv, (arg1), 4)
  Api(glInitNames, (), 0)
  Api(glInterleavedArrays, (arg1, arg2, arg3), 12)
  Api(glIsEnabled, (arg1), 4)
  Api(glIsList, (arg1), 4)
  Api(glIsTexture, (arg1), 4)
  Api(glLightf, (arg1, arg2, arg3.f), 12)
  Api(glLightfv, (arg1, arg2, arg3), 12)
  Api(glLighti, (arg1, arg2, arg3), 12)
  Api(glLightiv, (arg1, arg2, arg3), 12)
  Api(glLightModelf, (arg1, arg2.f), 8)
  Api(glLightModelfv, (arg1, arg2), 8)
  Api(glLightModeli, (arg1, arg2), 8)
  Api(glLightModeliv, (arg1, arg2), 8)
  Api(glLineStipple, (arg1, arg2), 8)
  Api(glLineWidth, (arg1.f), 4)
  Api(glListBase, (arg1), 4)
  Api(glLoadIdentity, (), 0)
  Api(glLoadMatrixd, (arg1), 4)
  Api(glLoadMatrixf, (arg1), 4)
  Api(glLoadName, (arg1), 4)
  Api(glLogicOp, (arg1), 4)
  Api(glMap1d, (arg1, arg2.d, arg3.d, arg4, arg5, arg6), 32)
  Api(glMap1f, (arg1, arg2.f, arg3.f, arg4, arg5, arg6), 24)
  Api(glMap2d, (arg1, arg2.d, arg3.d, arg4, arg5, arg6.d, arg7.d, arg8, arg9, arg10), 56)
  Api(glMap2f, (arg1, arg2.f, arg3.f, arg4, arg5, arg6.f, arg7.f, arg8, arg9, arg10), 40)
  Api(glMapGrid1d, (arg1, arg2.d, arg3.d), 20)
  Api(glMapGrid1f, (arg1, arg2.f, arg3.f), 12)
  Api(glMapGrid2d, (arg1, arg2.d, arg3.d, arg4, arg5.d, arg6.d), 40)
  Api(glMapGrid2f, (arg1, arg2.f, arg3.f, arg4, arg5.f, arg6.f), 24)
  Api(glMaterialf, (arg1, arg2.f, arg3.f), 12)
  Api(glMaterialfv, (arg1, arg2, arg3), 12)
  Api(glMateriali, (arg1, arg2, arg3), 12)
  Api(glMaterialiv, (arg1, arg2, arg3), 12)
  Api(glMatrixMode, (arg1), 4)
  Api(GlmfBeginGlsBlock, (arg1), 4)
  Api(GlmfCloseMetaFile, (arg1), 4)
  Api(GlmfEndGlsBlock, (arg1), 4)
  Api(GlmfEndPlayback, (arg1), 4)
  Api(GlmfInitPlayback, (arg1, arg2, arg3), 12)
  Api(GlmfPlayGlsRecord, (arg1, arg2, arg3, arg4), 16)
  Api(glMultMatrixd, (arg1), 4)
  Api(glMultMatrixf, (arg1), 4)
  Api(glNewList, (arg1, arg2), 8)
  Api(glNormal3b, (arg1, arg2, arg3), 12)
  Api(glNormal3bv, (arg1), 4)
  Api(glNormal3d, (arg1.d, arg2.d, arg3.d), 24)
  Api(glNormal3dv, (arg1), 4)
  Api(glNormal3f, (arg1.f, arg2.f, arg3.f), 12)
  Api(glNormal3fv, (arg1), 4)
  Api(glNormal3i, (arg1, arg2, arg3), 12)
  Api(glNormal3iv, (arg1), 4)
  Api(glNormal3s, (arg1, arg2, arg3), 12)
  Api(glNormal3sv, (arg1), 4)
  Api(glNormalPointer, (arg1, arg2, arg3), 12)
  Api(glOrtho, (arg1.d, arg2.d, arg3.d, arg4.d, arg5.d, arg6.d), 48)
  Api(glPassThrough, (arg1.f), 4)
  Api(glPixelMapfv, (arg1, arg2, arg3), 12)
  Api(glPixelMapuiv, (arg1, arg2, arg3), 12)
  Api(glPixelMapusv, (arg1, arg2, arg3), 12)
  Api(glPixelStoref, (arg1, arg2.f), 8)
  Api(glPixelStorei, (arg1, arg2), 8)
  Api(glPixelTransferf, (arg1, arg2.f), 8)
  Api(glPixelTransferi, (arg1, arg2), 8)
  Api(glPixelZoom, (arg1, arg2), 8)
  Api(glPointSize, (arg1.f), 4)
  Api(glPolygonMode, (arg1, arg2), 8)
  Api(glPolygonOffset, (arg1, arg2), 8)
  Api(glPolygonStipple, (arg1), 4)
  Api(glPopAttrib, (), 0)
  Api(glPopClientAttrib, (), 0)
  Api(glPopMatrix, (), 0)
  Api(glPopName, (), 0)
  Api(glPrioritizeTextures, (arg1, arg2, arg3), 12)
  Api(glPushAttrib, (arg1), 4)
  Api(glPushClientAttrib, (arg1), 4)
  Api(glPushMatrix, (), 0)
  Api(glPushName, (arg1), 4)
  Api(glRasterPos2d, (arg1.d, arg2.d), 16)
  Api(glRasterPos2dv, (arg1), 4)
  Api(glRasterPos2f, (arg1.f, arg2.f), 8)
  Api(glRasterPos2fv, (arg1), 4)
  Api(glRasterPos2i, (arg1, arg2), 8)
  Api(glRasterPos2iv, (arg1), 4)
  Api(glRasterPos2s, (arg1, arg2), 8)
  Api(glRasterPos2sv, (arg1), 4)
  Api(glRasterPos3d, (arg1.d, arg2.d, arg3.d), 24)
  Api(glRasterPos3dv, (arg1), 4)
  Api(glRasterPos3f, (arg1.f, arg2.f, arg3.f), 12)
  Api(glRasterPos3fv, (arg1), 4)
  Api(glRasterPos3i, (arg1, arg2, arg3), 12)
  Api(glRasterPos3iv, (arg1), 4)
  Api(glRasterPos3s, (arg1, arg2, arg3), 12)
  Api(glRasterPos3sv, (arg1), 4)
  Api(glRasterPos4d, (arg1.d, arg2.d, arg3.d, arg4.d), 32)
  Api(glRasterPos4dv, (arg1), 4)
  Api(glRasterPos4f, (arg1.f, arg2.f, arg3.f, arg4.f), 16)
  Api(glRasterPos4fv, (arg1), 4)
  Api(glRasterPos4i, (arg1, arg2, arg3, arg4), 16)
  Api(glRasterPos4iv, (arg1), 4)
  Api(glRasterPos4s, (arg1, arg2, arg3, arg4), 16)
  Api(glRasterPos4sv, (arg1), 4)
  Api(glReadBuffer, (arg1), 4)
  Api(glReadPixels, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  Api(glRectd, (arg1.d, arg2.d, arg3.d, arg4.d), 32)
  Api(glRectdv, (arg1, arg2), 8)
  Api(glRectf, (arg1.f, arg2.f, arg3.f, arg4.f), 16)
  Api(glRectfv, (arg1, arg2), 8)
  Api(glRecti, (arg1, arg2, arg3, arg4), 16)
  Api(glRectiv, (arg1, arg2), 8)
  Api(glRects, (arg1, arg2, arg3, arg4), 16)
  Api(glRectsv, (arg1, arg2), 8)
  Api(glRenderMode, (arg1), 4)
  Api(glRotated, (arg1.d, arg2.d, arg3.d, arg4.d), 32)
  Api(glRotatef, (arg1.f, arg2.f, arg3.f, arg4.f), 16)
  Api(glScaled, (arg1.d, arg2.d, arg3.d), 24)
  Api(glScalef, (arg1.f, arg2.f, arg3.f), 12)
  Api(glScissor, (arg1, arg2, arg3, arg4), 16)
  Api(glSelectBuffer, (arg1, arg2), 8)
  Api(glShadeModel, (arg1), 4)
  Api(glStencilFunc, (arg1, arg2, arg3), 12)
  Api(glStencilMask, (arg1), 4)
  Api(glStencilOp, (arg1, arg2, arg3), 12)
  Api(glTexCoord1d, (arg1.d), 8)
  Api(glTexCoord1dv, (arg1), 4)
  Api(glTexCoord1f, (arg1.f), 4)
  Api(glTexCoord1fv, (arg1), 4)
  Api(glTexCoord1i, (arg1), 4)
  Api(glTexCoord1iv, (arg1), 4)
  Api(glTexCoord1s, (arg1), 4)
  Api(glTexCoord1sv, (arg1), 4)
  Api(glTexCoord2d, (arg1.d, arg2.d), 16)
  Api(glTexCoord2dv, (arg1), 4)
  Api(glTexCoord2f, (arg1.f, arg2.f), 8)
  Api(glTexCoord2fv, (arg1), 4)
  Api(glTexCoord2i, (arg1, arg2), 8)
  Api(glTexCoord2iv, (arg1), 4)
  Api(glTexCoord2s, (arg1, arg2), 8)
  Api(glTexCoord2sv, (arg1), 4)
  Api(glTexCoord3d, (arg1.d, arg2.d, arg3.d), 24)
  Api(glTexCoord3dv, (arg1), 4)
  Api(glTexCoord3f, (arg1.f, arg2.f, arg3.f), 12)
  Api(glTexCoord3fv, (arg1), 4)
  Api(glTexCoord3i, (arg1, arg2, arg3), 12)
  Api(glTexCoord3iv, (arg1), 4)
  Api(glTexCoord3s, (arg1, arg2, arg3), 12)
  Api(glTexCoord3sv, (arg1), 4)
  Api(glTexCoord4d, (arg1.d, arg2.d, arg3.d, arg4.d), 32)
  Api(glTexCoord4dv, (arg1), 4)
  Api(glTexCoord4f, (arg1.f, arg2.f, arg3.f, arg4.f), 16)
  Api(glTexCoord4fv, (arg1), 4)
  Api(glTexCoord4i, (arg1, arg2, arg3, arg4), 16)
  Api(glTexCoord4iv, (arg1), 4)
  Api(glTexCoord4s, (arg1, arg2, arg3, arg4), 16)
  Api(glTexCoord4sv, (arg1), 4)
  Api(glTexCoordPointer, (arg1, arg2, arg3, arg4), 16)
  Api(glTexEnvf, (arg1, arg2, arg3.f), 12)
  Api(glTexEnvfv, (arg1, arg2, arg3), 12)
  Api(glTexEnvi, (arg1, arg2, arg3), 12)
  Api(glTexEnviv, (arg1, arg2, arg3), 12)
  Api(glTexGend, (arg1, arg2, arg3.d), 16)
  Api(glTexGendv, (arg1, arg2, arg3), 12)
  Api(glTexGenf, (arg1, arg2, arg3.f), 12)
  Api(glTexGenfv, (arg1, arg2, arg3), 12)
  Api(glTexGeni, (arg1, arg2, arg3), 12)
  Api(glTexGeniv, (arg1, arg2, arg3), 12)
  Api(glTexImage1D, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  Api(glTexImage2D, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
  Api(glTexParameterf, (arg1, arg2, arg3.f), 12)
  Api(glTexParameterfv, (arg1, arg2, arg3), 12)
  Api(glTexParameteri, (arg1, arg2, arg3), 12)
  Api(glTexParameteriv, (arg1, arg2, arg3), 12)
  Api(glTexSubImage1D, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  Api(glTexSubImage2D, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
  Api(glTranslated, (arg1.d, arg2.d, arg3.d), 24)
  Api(glTranslatef, (arg1.f, arg2.f, arg3.f), 12)
  Api(glVertex2d, (arg1.d, arg2.d), 16)
  Api(glVertex2dv, (arg1), 4)
  Api(glVertex2f, (arg1.f, arg2.f), 8)
  Api(glVertex2fv, (arg1), 4)
  Api(glVertex2i, (arg1, arg2), 8)
  Api(glVertex2iv, (arg1), 4)
  Api(glVertex2s, (arg1, arg2), 8)
  Api(glVertex2sv, (arg1), 4)
  Api(glVertex3d, (arg1.d, arg2.d, arg3.d), 24)
  Api(glVertex3dv, (arg1), 4)
  Api(glVertex3f, (arg1.f, arg2.f, arg3.f), 12)
  Api(glVertex3fv, (arg1), 4)
  Api(glVertex3i, (arg1, arg2, arg3), 12)
  Api(glVertex3iv, (arg1), 4)
  Api(glVertex3s, (arg1, arg2, arg3), 12)
  Api(glVertex3sv, (arg1), 4)
  Api(glVertex4d, (arg1.d, arg2.d, arg3.d, arg4.d), 32)
  Api(glVertex4dv, (arg1), 4)
  Api(glVertex4f, (arg1.f, arg2.f, arg3.f, arg4.f), 16)
  Api(glVertex4fv, (arg1), 4)
  Api(glVertex4i, (arg1, arg2, arg3, arg4), 16)
  Api(glVertex4iv, (arg1), 4)
  Api(glVertex4s, (arg1, arg2, arg3, arg4), 16)
  Api(glVertex4sv, (arg1), 4)
  Api(glVertexPointer, (arg1, arg2, arg3, arg4), 16)
  Api(glViewport, (arg1, arg2, arg3, arg4), 16)
EndImport
