XIncludeFile "common.pbi"

CompilerIf #PB_Compiler_OS = #PB_OS_Windows
  #LibName$ = "sqlite3.lib"
CompilerElse
  #LibName$ = "-lpbsqlite3 -ldl"
CompilerEndIf

Import #LibName$
  ApiC(sqlite3_aggregate_context, (arg1, arg2))
  ApiC(sqlite3_aggregate_count, (arg1))
  ApiC(sqlite3_auto_extension, (arg1))
  ApiC(sqlite3_bind_blob, (arg1, arg2, arg3, arg4, arg5))
  ApiC(sqlite3_bind_double, (arg1, arg2, arg3))
  ApiC(sqlite3_bind_int, (arg1, arg2, arg3))
  ApiC(sqlite3_bind_int64, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_bind_null, (arg1, arg2))
  ApiC(sqlite3_bind_parameter_count, (arg1))
  ApiC(sqlite3_bind_parameter_index, (arg1, arg2))
  ApiC(sqlite3_bind_parameter_name, (arg1, arg2))
  ApiC(sqlite3_bind_text, (arg1, arg2, arg3, arg4, arg5))
  ApiC(sqlite3_bind_text16, (arg1, arg2, arg3, arg4, arg5))
  ApiC(sqlite3_bind_value, (arg1, arg2, arg3))
  ApiC(sqlite3_bind_zeroblob, (arg1, arg2, arg3))
  ApiC(sqlite3_blob_bytes, (arg1))
  ApiC(sqlite3_blob_close, (arg1))
  ApiC(sqlite3_blob_open, (arg1, arg2, arg3, arg4, arg5, arg6, arg7))
  ApiC(sqlite3_blob_read, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_blob_write, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_busy_handler, (arg1, arg2, arg3))
  ApiC(sqlite3_busy_timeout, (arg1, arg2))
  ApiC(sqlite3_changes, (arg1))
  ApiC(sqlite3_clear_bindings, (arg1))
  ApiC(sqlite3_close, (arg1))
  ApiC(sqlite3_collation_needed, (arg1, arg2, arg3))
  ApiC(sqlite3_collation_needed16, (arg1, arg2, arg3))
  ApiC(sqlite3_column_blob, (arg1, arg2))
  ApiC(sqlite3_column_bytes, (arg1, arg2))
  ApiC(sqlite3_column_bytes16, (arg1, arg2))
  ApiC(sqlite3_column_count, (arg1))
  ApiC(sqlite3_column_database_name, (arg1, arg2))
  ApiC(sqlite3_column_database_name16, (arg1, arg2))
  ApiC(sqlite3_column_decltype, (arg1, arg2))
  ApiC(sqlite3_column_decltype16, (arg1, arg2))
  ApiC(sqlite3_column_double, (arg1, arg2))
  ApiC(sqlite3_column_int, (arg1, arg2))
  ApiC(sqlite3_column_int64, (arg1, arg2))
  ApiC(sqlite3_column_name, (arg1, arg2))
  ApiC(sqlite3_column_name16, (arg1, arg2))
  ApiC(sqlite3_column_origin_name, (arg1, arg2))
  ApiC(sqlite3_column_origin_name16, (arg1, arg2))
  ApiC(sqlite3_column_table_name, (arg1, arg2))
  ApiC(sqlite3_column_table_name16, (arg1, arg2))
  ApiC(sqlite3_column_text, (arg1, arg2))
  ApiC(sqlite3_column_text16, (arg1, arg2))
  ApiC(sqlite3_column_type, (arg1, arg2))
  ApiC(sqlite3_column_value, (arg1, arg2))
  ApiC(sqlite3_commit_hook, (arg1, arg2, arg3))
  ApiC(sqlite3_complete, (arg1))
  ApiC(sqlite3_complete16, (arg1))
  ApiC(sqlite3_create_collation, (arg1, arg2, arg3, arg4, arg5))
  ApiC(sqlite3_create_collation16, (arg1, arg2, arg3, arg4, arg5))
  ApiC(sqlite3_create_collation_v2, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(sqlite3_create_function, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(sqlite3_create_function16, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8))
  ApiC(sqlite3_create_module, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_create_module_v2, (arg1, arg2, arg3, arg4, arg5))
  ApiC(sqlite3_data_count, (arg1))
  ApiC(sqlite3_db_handle, (arg1))
  ApiC(sqlite3_declare_vtab, (arg1, arg2))
  ApiC(sqlite3_enable_load_extension, (arg1, arg2))
  ApiC(sqlite3_enable_shared_cache, (arg1))
  ApiC(sqlite3_errcode, (arg1))
  ApiC(sqlite3_errmsg, (arg1))
  ApiC(sqlite3_errmsg16, (arg1))
  ApiC(sqlite3_exec, (arg1, arg2, arg3, arg4, arg5))
  ApiC(sqlite3_expired, (arg1))
  ApiC(sqlite3_extended_result_codes, (arg1, arg2))
  ApiC(sqlite3_finalize, (arg1))
  ApiC(sqlite3_free, (arg1))
  ApiC(sqlite3_free_table, (arg1))
  ApiC(sqlite3_get_autocommit, (arg1))
  ApiC(sqlite3_get_auxdata, (arg1, arg2))
  ApiC(sqlite3_get_table, (arg1, arg2, arg3, arg4, arg5, arg6))
  ApiC(sqlite3_global_recover, ())
  ApiC(sqlite3_interrupt, (arg1))
  ApiC(sqlite3_key, (arg1, arg2))
  ApiC(sqlite3_last_insert_rowid, (arg1))
  ApiC(sqlite3_libversion, ())
  ApiC(sqlite3_libversion_number, ())
  ApiC(sqlite3_load_extension, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_malloc, (arg1))
  ApiC(sqlite3_open, (arg1, arg2))
  ApiC(sqlite3_open16, (arg1, arg2))
  ApiC(sqlite3_overload_function, (arg1, arg2, arg3))
  ApiC(sqlite3_prepare, (arg1, arg2, arg3, arg4, arg5))
  ApiC(sqlite3_prepare16, (arg1, arg2, arg3, arg4, arg5))
  ApiC(sqlite3_prepare16_v2, (arg1, arg2, arg3, arg4, arg5))
  ApiC(sqlite3_prepare_v2, (arg1, arg2, arg3, arg4, arg5))
  ApiC(sqlite3_profile, (arg1, arg2, arg3))
  ApiC(sqlite3_progress_handler, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_realloc, (arg1, arg2))
  ApiC(sqlite3_rekey, (arg1, arg2, arg3))
  ApiC(sqlite3_release_memory, (arg1))
  ApiC(sqlite3_reset, (arg1))
  ApiC(sqlite3_reset_auto_extension, ())
  ApiC(sqlite3_result_blob, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_result_double, (arg1, arg2, arg3))
  ApiC(sqlite3_result_error, (arg1, arg2, arg3))
  ApiC(sqlite3_result_error16, (arg1, arg2, arg3))
  ApiC(sqlite3_result_error_toobig, (arg1))
  ApiC(sqlite3_result_int, (arg1, arg2))
  ApiC(sqlite3_result_int64, (arg1, arg2, arg3))
  ApiC(sqlite3_result_null, (arg1))
  ApiC(sqlite3_result_text, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_result_text16, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_result_text16be, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_result_text16le, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_result_value, (arg1, arg2))
  ApiC(sqlite3_result_zeroblob, (arg1, arg2))
  ApiC(sqlite3_rollback_hook, (arg1, arg2, arg3))
  ApiC(sqlite3_set_authorizer, (arg1, arg2, arg3))
  ApiC(sqlite3_set_auxdata, (arg1, arg2, arg3, arg4))
  ApiC(sqlite3_sleep, (arg1))
  ApiC(sqlite3_soft_heap_limit, (arg1))
  ApiC(sqlite3_step, (arg1))
  ApiC(sqlite3_table_column_metadata, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9))
  ApiC(sqlite3_thread_cleanup, ())
  ApiC(sqlite3_total_changes, (arg1))
  ApiC(sqlite3_trace, (arg1, arg2, arg3))
  ApiC(sqlite3_transfer_bindings, (arg1, arg2))
  ApiC(sqlite3_update_hook, (arg1, arg2, arg3))
  ApiC(sqlite3_user_data, (arg1))
  ApiC(sqlite3_value_blob, (arg1))
  ApiC(sqlite3_value_bytes, (arg1))
  ApiC(sqlite3_value_bytes16, (arg1))
  ApiC(sqlite3_value_double, (arg1))
  ApiC(sqlite3_value_int, (arg1))
  ApiC(sqlite3_value_int64, (arg1))
  ApiC(sqlite3_value_numeric_type, (arg1))
  ApiC(sqlite3_value_text, (arg1))
  ApiC(sqlite3_value_text16, (arg1))
  ApiC(sqlite3_value_text16be, (arg1))
  ApiC(sqlite3_value_text16le, (arg1))
  ApiC(sqlite3_value_type, (arg1))
  ApiC(sqlite3_vmprintf, (arg1, arg2))
EndImport
