
EXAMPLES =  2DDrawing.exe \
            2DDrawingAlpha.exe \
            Arithmetic.exe \
            AsmInline.exe \
            AudioCD.exe \
            CGI.exe \
            Cipher.exe \
            Clipboard.exe \
            Console.exe \
            DLLSample.exe \
            Database.exe \
            Date.exe \
            Desktop.exe \
            DirectScreenDrawing.exe \
            Dialog.exe \
            DragDrop.exe \
            File.exe \
            FileSystem.exe \
            Font.exe \
            Ftp.exe \
            Gadget.exe \
            GadgetAdvanced.exe \
            GadgetSplitter.exe \
            GadgetSplitterAdvanced.exe \
            Help.exe \
            Http.exe \
            Image.exe \
            ImagePlugin.exe \
            ImagePlugin_GIF.exe \
            Joystick.exe \
            Keyboard.exe \
            Library.exe \
            List.exe \
            MDI_ImageViewer.exe \
            Mail.exe \
            Math.exe \
            MemoryBank.exe \
            Menu.exe \
            Music.exe \
            Mouse.exe \
            Movie.exe \
            NetworkClient.exe \
            NetworkServer.exe \
            OnError.exe \
            Packer.exe \
            PopupMenu.exe \
            Preference.exe \
            Printer.exe \
            RegularExpression.exe \
            Requester.exe \
            Runtime.exe \
            SerialPort.exe \
            Sort_(Numeric).exe \
            Sort_(String).exe \
            Sound.exe \
            SoundPlugin.exe \
            Sprite.exe \
            StatusBar.exe \
            String.exe \
            Systray.exe \
            Thread.exe \
            ToolBar.exe \
            WebBrowser.exe \
            WebView.exe \
            Win32_API.exe \
            Window.exe \
            WindowedScreen.exe \
            Xml.exe


all: $(EXAMPLES)
	

%.exe : %.pb
	pbcompiler $< /QUIET /CHECK
