
; IDirect3DRM interface definition
;
Interface IDirect3DRM
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  CreateObject(a.l, b.l, c.l, d.l)
  CreateFrame(a.l, b.l)
  CreateMesh(a.l)
  CreateMeshBuilder(a.l)
  CreateFace(a.l)
  CreateAnimation(a.l)
  CreateAnimationSet(a.l)
  CreateTexture(a.l, b.l)
  CreateLight(a.l, b.l, c.l)
  CreateLightRGB(a.l, b.f, c.f, d.f, e.l)
  CreateMaterial(a.f, b.l)
  CreateDevice(a.l, b.l, c.l)
  CreateDeviceFromSurface(a.l, b.l, c.l, d.l)
  CreateDeviceFromD3D(a.l, b.l, c.l)
  CreateDeviceFromClipper(a.l, b.l, c.l, d.l, e.l)
  CreateTextureFromSurface(a.l, b.l)
  CreateShadow(a.l, b.l, c.f, d.f, e.f, f.f, g.f, h.f, i.l)
  CreateViewport(a.l, b.l, c.l, d.l, e.l, f.l, g.l)
  CreateWrap(a.l, b.l, c.f, d.f, e.f, f.f, g.f, h.f, i.f, j.f, k.f, l.f, m.f, n.f, o.f, p.l)
  CreateUserVisual(a.l, b.l, c.l)
  LoadTexture(a.s, b.l)
  LoadTextureFromResource(a.l, b.l)
  SetSearchPath(a.s)
  AddSearchPath(a.s)
  GetSearchPath(a.l, b.l)
  SetDefaultTextureColors(a.l)
  SetDefaultTextureShades(a.l)
  GetDevices(a.l)
  GetNamedObject(a.s, b.l)
  EnumerateObjects(a.l, b.l)
  Load(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l)
  Tick(a.f)
EndInterface

; IDirect3DRM2 interface definition
;
Interface IDirect3DRM2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  CreateObject(a.l, b.l, c.l, d.l)
  CreateFrame(a.l, b.l)
  CreateMesh(a.l)
  CreateMeshBuilder(a.l)
  CreateFace(a.l)
  CreateAnimation(a.l)
  CreateAnimationSet(a.l)
  CreateTexture(a.l, b.l)
  CreateLight(a.l, b.l, c.l)
  CreateLightRGB(a.l, b.f, c.f, d.f, e.l)
  CreateMaterial(a.f, b.l)
  CreateDevice(a.l, b.l, c.l)
  CreateDeviceFromSurface(a.l, b.l, c.l, d.l)
  CreateDeviceFromD3D(a.l, b.l, c.l)
  CreateDeviceFromClipper(a.l, b.l, c.l, d.l, e.l)
  CreateTextureFromSurface(a.l, b.l)
  CreateShadow(a.l, b.l, c.f, d.f, e.f, f.f, g.f, h.f, i.l)
  CreateViewport(a.l, b.l, c.l, d.l, e.l, f.l, g.l)
  CreateWrap(a.l, b.l, c.f, d.f, e.f, f.f, g.f, h.f, i.f, j.f, k.f, l.f, m.f, n.f, o.f, p.l)
  CreateUserVisual(a.l, b.l, c.l)
  LoadTexture(a.s, b.l)
  LoadTextureFromResource(a.l, b.l, c.l, d.l)
  SetSearchPath(a.s)
  AddSearchPath(a.s)
  GetSearchPath(a.l, b.l)
  SetDefaultTextureColors(a.l)
  SetDefaultTextureShades(a.l)
  GetDevices(a.l)
  GetNamedObject(a.s, b.l)
  EnumerateObjects(a.l, b.l)
  Load(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l)
  Tick(a.f)
  CreateProgressiveMesh(a.l)
EndInterface

; IDirect3DRM3 interface definition
;
Interface IDirect3DRM3
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  CreateObject(a.l, b.l, c.l, d.l)
  CreateFrame(a.l, b.l)
  CreateMesh(a.l)
  CreateMeshBuilder(a.l)
  CreateFace(a.l)
  CreateAnimation(a.l)
  CreateAnimationSet(a.l)
  CreateTexture(a.l, b.l)
  CreateLight(a.l, b.l, c.l)
  CreateLightRGB(a.l, b.f, c.f, d.f, e.l)
  CreateMaterial(a.f, b.l)
  CreateDevice(a.l, b.l, c.l)
  CreateDeviceFromSurface(a.l, b.l, c.l, d.l, e.l)
  CreateDeviceFromD3D(a.l, b.l, c.l)
  CreateDeviceFromClipper(a.l, b.l, c.l, d.l, e.l)
  CreateTextureFromSurface(a.l, b.l)
  CreateShadow(a.l, b.l, c.f, d.f, e.f, f.f, g.f, h.f, i.l)
  CreateViewport(a.l, b.l, c.l, d.l, e.l, f.l, g.l)
  CreateWrap(a.l, b.l, c.f, d.f, e.f, f.f, g.f, h.f, i.f, j.f, k.f, l.f, m.f, n.f, o.f, p.l)
  CreateUserVisual(a.l, b.l, c.l)
  LoadTexture(a.s, b.l)
  LoadTextureFromResource(a.l, b.l, c.l, d.l)
  SetSearchPath(a.s)
  AddSearchPath(a.s)
  GetSearchPath(a.l, b.l)
  SetDefaultTextureColors(a.l)
  SetDefaultTextureShades(a.l)
  GetDevices(a.l)
  GetNamedObject(a.s, b.l)
  EnumerateObjects(a.l, b.l)
  Load(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l)
  Tick(a.f)
  CreateProgressiveMesh(a.l)
  RegisterClient(a.l, b.l)
  UnregisterClient(a.l)
  CreateClippedVisual(a.l, b.l)
  SetOptions(a.l)
  GetOptions(a.l)
EndInterface
