
; IDirect3DRMObject interface definition
;
Interface IDirect3DRMObject
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
EndInterface

; IDirect3DRMObject2 interface definition
;
Interface IDirect3DRMObject2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  AddDestroyCallback(a.l, b.l)
  Clone(a.l, b.l, c.l)
  DeleteDestroyCallback(a.l, b.l)
  GetClientData(a.l, b.l)
  GetDirect3DRM(a.l)
  GetName(a.l, b.l)
  SetClientData(a.l, b.l, c.l)
  SetName(a.s)
  GetAge(a.l, b.l)
EndInterface

; IDirect3DRMVisual interface definition
;
Interface IDirect3DRMVisual
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
EndInterface

; IDirect3DRMDevice interface definition
;
Interface IDirect3DRMDevice
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Init(a.l, b.l)
  InitFromD3D(a.l, b.l)
  InitFromClipper(a.l, b.l, c.l, d.l)
  Update()
  AddUpdateCallback(a.l, b.l)
  DeleteUpdateCallback(a.l, b.l)
  SetBufferCount(a.l)
  GetBufferCount()
  SetDither(a.l)
  SetShades(a.l)
  SetQuality(a.l)
  SetTextureQuality(a.l)
  GetViewports(a.l)
  GetDither()
  GetShades()
  GetHeight()
  GetWidth()
  GetTrianglesDrawn()
  GetWireframeOptions()
  GetQuality()
  GetColorModel()
  GetTextureQuality()
  GetDirect3DDevice(a.l)
EndInterface

; IDirect3DRMDevice2 interface definition
;
Interface IDirect3DRMDevice2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Init(a.l, b.l)
  InitFromD3D(a.l, b.l)
  InitFromClipper(a.l, b.l, c.l, d.l)
  Update()
  AddUpdateCallback(a.l, b.l)
  DeleteUpdateCallback(a.l, b.l)
  SetBufferCount(a.l)
  GetBufferCount()
  SetDither(a.l)
  SetShades(a.l)
  SetQuality(a.l)
  SetTextureQuality(a.l)
  GetViewports(a.l)
  GetDither()
  GetShades()
  GetHeight()
  GetWidth()
  GetTrianglesDrawn()
  GetWireframeOptions()
  GetQuality()
  GetColorModel()
  GetTextureQuality()
  GetDirect3DDevice(a.l)
  InitFromD3D2(a.l, b.l)
  InitFromSurface(a.l, b.l, c.l)
  SetRenderMode(a.l)
  GetRenderMode()
  GetDirect3DDevice2(a.l)
EndInterface

; IDirect3DRMDevice3 interface definition
;
Interface IDirect3DRMDevice3
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Init(a.l, b.l)
  InitFromD3D(a.l, b.l)
  InitFromClipper(a.l, b.l, c.l, d.l)
  Update()
  AddUpdateCallback(a.l, b.l)
  DeleteUpdateCallback(a.l, b.l)
  SetBufferCount(a.l)
  GetBufferCount()
  SetDither(a.l)
  SetShades(a.l)
  SetQuality(a.l)
  SetTextureQuality(a.l)
  GetViewports(a.l)
  GetDither()
  GetShades()
  GetHeight()
  GetWidth()
  GetTrianglesDrawn()
  GetWireframeOptions()
  GetQuality()
  GetColorModel()
  GetTextureQuality()
  GetDirect3DDevice(a.l)
  InitFromD3D2(a.l, b.l)
  InitFromSurface(a.l, b.l, c.l, d.l)
  SetRenderMode(a.l)
  GetRenderMode()
  GetDirect3DDevice2(a.l)
  FindPreferredTextureFormat(a.l, b.l, c.l)
  RenderStateChange(a.l, b.l, c.l)
  LightStateChange(a.l, b.l, c.l)
  GetStateChangeOptions(a.l, b.l, c.l)
  SetStateChangeOptions(a.l, b.l, c.l)
EndInterface

; IDirect3DRMViewport interface definition
;
Interface IDirect3DRMViewport
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Init(a.l, b.l, c.l, d.l, e.l, f.l)
  Clear()
  Render(a.l)
  SetFront(a.f)
  SetBack(a.f)
  SetField(a.f)
  SetUniformScaling(a.l)
  SetCamera(a.l)
  SetProjection(a.l)
  Transform(a.l, b.l)
  InverseTransform(a.l, b.l)
  Configure(a.l, b.l, c.l, d.l)
  ForceUpdate(a.l, b.l, c.l, d.l)
  SetPlane(a.f, b.f, c.f, d.f)
  GetCamera(a.l)
  GetDevice(a.l)
  GetPlane(a.l, b.l, c.l, d.l)
  Pick(a.l, b.l, c.l)
  GetUniformScaling()
  GetX()
  GetY()
  GetWidth()
  GetHeight()
  GetField()
  GetBack()
  GetFront()
  GetProjection()
  GetDirect3DViewport(a.l)
EndInterface

; IDirect3DRMViewport2 interface definition
;
Interface IDirect3DRMViewport2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Init(a.l, b.l, c.l, d.l, e.l, f.l)
  Clear(a.l)
  Render(a.l)
  SetFront(a.f)
  SetBack(a.f)
  SetField(a.f)
  SetUniformScaling(a.l)
  SetCamera(a.l)
  SetProjection(a.l)
  Transform(a.l, b.l)
  InverseTransform(a.l, b.l)
  Configure(a.l, b.l, c.l, d.l)
  ForceUpdate(a.l, b.l, c.l, d.l)
  SetPlane(a.f, b.f, c.f, d.f)
  GetCamera(a.l)
  GetDevice(a.l)
  GetPlane(a.l, b.l, c.l, d.l)
  Pick(a.l, b.l, c.l)
  GetUniformScaling()
  GetX()
  GetY()
  GetWidth()
  GetHeight()
  GetField()
  GetBack()
  GetFront()
  GetProjection()
  GetDirect3DViewport(a.l)
  TransformVectors(a.l, b.l, c.l)
  InverseTransformVectors(a.l, b.l, c.l)
EndInterface

; IDirect3DRMFrame interface definition
;
Interface IDirect3DRMFrame
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  AddChild(a.l)
  AddLight(a.l)
  AddMoveCallback(a.l, b.l)
  AddTransform(a.l, b.l)
  AddTranslation(a.l, b.f, c.f, d.f)
  AddScale(a.l, b.f, c.f, d.f)
  AddRotation(a.l, b.f, c.f, d.f, e.f)
  AddVisual(a.l)
  GetChildren(a.l)
  GetColor()
  GetLights(a.l)
  GetMaterialMode()
  GetParent(a.l)
  GetPosition(a.l, b.l)
  GetRotation(a.l, b.l, c.f)
  GetScene(a.l)
  GetSortMode()
  GetTexture(a.l)
  GetTransform(a.l)
  GetVelocity(a.l, b.l, c.l)
  GetOrientation(a.l, b.l, c.l)
  GetVisuals(a.l)
  GetTextureTopology(a.l, b.l)
  InverseTransform(a.l, b.l)
  Load(a.l, b.l, c.l, d.l, e.l)
  LookAt(a.l, b.l, c.l)
  Move(a.f)
  DeleteChild(a.l)
  DeleteLight(a.l)
  DeleteMoveCallback(a.l, b.l)
  DeleteVisual(a.l)
  GetSceneBackground()
  GetSceneBackgroundDepth(a.l)
  GetSceneFogColor()
  GetSceneFogEnable()
  GetSceneFogMode()
  GetSceneFogParams(a.l, b.l, c.l)
  SetSceneBackground(a.l)
  SetSceneBackgroundRGB(a.f, b.f, c.f)
  SetSceneBackgroundDepth(a.l)
  SetSceneBackgroundImage(a.l)
  SetSceneFogEnable(a.l)
  SetSceneFogColor(a.l)
  SetSceneFogMode(a.l)
  SetSceneFogParams(a.f, b.f, c.f)
  SetColor(a.l)
  SetColorRGB(a.f, b.f, c.f)
  GetZbufferMode()
  SetMaterialMode(a.l)
  SetOrientation(a.l, b.f, c.f, d.f, e.f, f.f, g.f)
  SetPosition(a.l, b.f, c.f, d.f)
  SetRotation(a.l, b.f, c.f, d.f, e.f)
  SetSortMode(a.l)
  SetTexture(a.l)
  SetTextureTopology(a.l, b.l)
  SetVelocity(a.l, b.f, c.f, d.f, e.l)
  SetZbufferMode(a.l)
  Transform(a.l, b.l)
EndInterface

; IDirect3DRMFrame2 interface definition
;
Interface IDirect3DRMFrame2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  AddChild(a.l)
  AddLight(a.l)
  AddMoveCallback(a.l, b.l)
  AddTransform(a.l, b.l)
  AddTranslation(a.l, b.f, c.f, d.f)
  AddScale(a.l, b.f, c.f, d.f)
  AddRotation(a.l, b.f, c.f, d.f, e.f)
  AddVisual(a.l)
  GetChildren(a.l)
  GetColor()
  GetLights(a.l)
  GetMaterialMode()
  GetParent(a.l)
  GetPosition(a.l, b.l)
  GetRotation(a.l, b.l, c.f)
  GetScene(a.l)
  GetSortMode()
  GetTexture(a.l)
  GetTransform(a.l)
  GetVelocity(a.l, b.l, c.l)
  GetOrientation(a.l, b.l, c.l)
  GetVisuals(a.l)
  GetTextureTopology(a.l, b.l)
  InverseTransform(a.l, b.l)
  Load(a.l, b.l, c.l, d.l, e.l)
  LookAt(a.l, b.l, c.l)
  Move(a.f)
  DeleteChild(a.l)
  DeleteLight(a.l)
  DeleteMoveCallback(a.l, b.l)
  DeleteVisual(a.l)
  GetSceneBackground()
  GetSceneBackgroundDepth(a.l)
  GetSceneFogColor()
  GetSceneFogEnable()
  GetSceneFogMode()
  GetSceneFogParams(a.l, b.l, c.l)
  SetSceneBackground(a.l)
  SetSceneBackgroundRGB(a.f, b.f, c.f)
  SetSceneBackgroundDepth(a.l)
  SetSceneBackgroundImage(a.l)
  SetSceneFogEnable(a.l)
  SetSceneFogColor(a.l)
  SetSceneFogMode(a.l)
  SetSceneFogParams(a.f, b.f, c.f)
  SetColor(a.l)
  SetColorRGB(a.f, b.f, c.f)
  GetZbufferMode()
  SetMaterialMode(a.l)
  SetOrientation(a.l, b.f, c.f, d.f, e.f, f.f, g.f)
  SetPosition(a.l, b.f, c.f, d.f)
  SetRotation(a.l, b.f, c.f, d.f, e.f)
  SetSortMode(a.l)
  SetTexture(a.l)
  SetTextureTopology(a.l, b.l)
  SetVelocity(a.l, b.f, c.f, d.f, e.l)
  SetZbufferMode(a.l)
  Transform(a.l, b.l)
  AddMoveCallback2(a.l, b.l, c.l)
  GetBox(a.l)
  GetBoxEnable()
  GetAxes(a.l, b.l)
  GetMaterial(a.l)
  GetInheritAxes()
  GetHierarchyBox(a.l)
  SetBox(a.l)
  SetBoxEnable(a.l)
  SetAxes(a.f, b.f, c.f, d.f, e.f, f.f)
  SetInheritAxes(a.l)
  SetMaterial(a.l)
  SetQuaternion(a.l, b.l)
  RayPick(a.l, b.l, c.l, d.l)
  Save(a.s, b.l, c.l)
EndInterface

; IDirect3DRMFrame3 interface definition
;
Interface IDirect3DRMFrame3
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  AddChild(a.l)
  AddLight(a.l)
  AddMoveCallback(a.l, b.l, c.l)
  AddTransform(a.l, b.l)
  AddTranslation(a.l, b.f, c.f, d.f)
  AddScale(a.l, b.f, c.f, d.f)
  AddRotation(a.l, b.f, c.f, d.f, e.f)
  AddVisual(a.l)
  GetChildren(a.l)
  GetColor()
  GetLights(a.l)
  GetMaterialMode()
  GetParent(a.l)
  GetPosition(a.l, b.l)
  GetRotation(a.l, b.l, c.f)
  GetScene(a.l)
  GetSortMode()
  GetTexture(a.l)
  GetTransform(a.l, b.l)
  GetVelocity(a.l, b.l, c.l)
  GetOrientation(a.l, b.l, c.l)
  GetVisuals(a.l, b.l)
  InverseTransform(a.l, b.l)
  Load(a.l, b.l, c.l, d.l, e.l)
  LookAt(a.l, b.l, c.l)
  Move(a.f)
  DeleteChild(a.l)
  DeleteLight(a.l)
  DeleteMoveCallback(a.l, b.l)
  DeleteVisual(a.l)
  GetSceneBackground()
  GetSceneBackgroundDepth(a.l)
  GetSceneFogColor()
  GetSceneFogEnable()
  GetSceneFogMode()
  GetSceneFogParams(a.l, b.l, c.l)
  SetSceneBackground(a.l)
  SetSceneBackgroundRGB(a.f, b.f, c.f)
  SetSceneBackgroundDepth(a.l)
  SetSceneBackgroundImage(a.l)
  SetSceneFogEnable(a.l)
  SetSceneFogColor(a.l)
  SetSceneFogMode(a.l)
  SetSceneFogParams(a.f, b.f, c.f)
  SetColor(a.l)
  SetColorRGB(a.f, b.f, c.f)
  GetZbufferMode()
  SetMaterialMode(a.l)
  SetOrientation(a.l, b.f, c.f, d.f, e.f, f.f, g.f)
  SetPosition(a.l, b.f, c.f, d.f)
  SetRotation(a.l, b.f, c.f, d.f, e.f)
  SetSortMode(a.l)
  SetTexture(a.l)
  SetVelocity(a.l, b.f, c.f, d.f, e.l)
  SetZbufferMode(a.l)
  Transform(a.l, b.l)
  GetBox(a.l)
  GetBoxEnable()
  GetAxes(a.l, b.l)
  GetMaterial(a.l)
  GetInheritAxes()
  GetHierarchyBox(a.l)
  SetBox(a.l)
  SetBoxEnable(a.l)
  SetAxes(a.f, b.f, c.f, d.f, e.f, f.f)
  SetInheritAxes(a.l)
  SetMaterial(a.l)
  SetQuaternion(a.l, b.l)
  RayPick(a.l, b.l, c.l, d.l)
  Save(a.s, b.l, c.l)
  TransformVectors(a.l, b.l, c.l, d.l)
  InverseTransformVectors(a.l, b.l, c.l, d.l)
  SetTraversalOptions(a.l)
  GetTraversalOptions(a.l)
  SetSceneFogMethod(a.l)
  GetSceneFogMethod(a.l)
  SetMaterialOverride(a.l)
  GetMaterialOverride(a.l)
EndInterface

; IDirect3DRMMesh interface definition
;
Interface IDirect3DRMMesh
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Scale(a.f, b.f, c.f)
  Translate(a.f, b.f, c.f)
  GetBox(a.l)
  AddGroup(a.l, b.l, c.l, d.l, e.l)
  SetVertices(a.l, b.l, c.l, d.l)
  SetGroupColor(a.l, b.l)
  SetGroupColorRGB(a.l, b.f, c.f, d.f)
  SetGroupMapping(a.l, b.l)
  SetGroupQuality(a.l, b.l)
  SetGroupMaterial(a.l, b.l)
  SetGroupTexture(a.l, b.l)
  GetGroupCount()
  GetGroup(a.l, b.l, c.l, d.l, e.l, f.l)
  GetVertices(a.l, b.l, c.l, d.l)
  GetGroupColor(a.l)
  GetGroupMapping(a.l)
  GetGroupQuality(a.l)
  GetGroupMaterial(a.l, b.l)
  GetGroupTexture(a.l, b.l)
EndInterface

; IDirect3DRMProgressiveMesh interface definition
;
Interface IDirect3DRMProgressiveMesh
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Load(a.l, b.l, c.l, d.l, e.l)
  GetLoadStatus(a.l)
  SetMinRenderDetail(a.f)
  Abort(a.l)
  GetFaceDetail(a.l)
  GetVertexDetail(a.l)
  SetFaceDetail(a.l)
  SetVertexDetail(a.l)
  GetFaceDetailRange(a.l, b.l)
  GetVertexDetailRange(a.l, b.l)
  GetDetail(a.l)
  SetDetail(a.f)
  RegisterEvents(a.l, b.l, c.l)
  CreateMesh(a.l)
  Duplicate(a.l)
  GetBox(a.l)
  SetQuality(a.l)
  GetQuality(a.l)
EndInterface

; IDirect3DRMShadow interface definition
;
Interface IDirect3DRMShadow
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Init(a.l, b.l, c.f, d.f, e.f, f.f, g.f, h.f)
EndInterface

; IDirect3DRMShadow2 interface definition
;
Interface IDirect3DRMShadow2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Init(a.l, b.l, c.f, d.f, e.f, f.f, g.f, h.f)
  GetVisual(a.l)
  SetVisual(a.l, b.l)
  GetLight(a.l)
  SetLight(a.l, b.l)
  GetPlane(a.f, b.f, c.f, d.f, e.f, f.f)
  SetPlane(a.f, b.f, c.f, d.f, e.f, f.f, g.l)
  GetOptions(a.l)
  SetOptions(a.l)
EndInterface

; IDirect3DRMFace interface definition
;
Interface IDirect3DRMFace
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  AddVertex(a.f, b.f, c.f)
  AddVertexAndNormalIndexed(a.l, b.l)
  SetColorRGB(a.f, b.f, c.f)
  SetColor(a.l)
  SetTexture(a.l)
  SetTextureCoordinates(a.l, b.f, c.f)
  SetMaterial(a.l)
  SetTextureTopology(a.l, b.l)
  GetVertex(a.l, b.l, c.l)
  GetVertices(a.l, b.l, c.l)
  GetTextureCoordinates(a.l, b.l, c.l)
  GetTextureTopology(a.l, b.l)
  GetNormal(a.l)
  GetTexture(a.l)
  GetMaterial(a.l)
  GetVertexCount()
  GetVertexIndex(a.l)
  GetTextureCoordinateIndex(a.l)
  GetColor()
EndInterface

; IDirect3DRMFace2 interface definition
;
Interface IDirect3DRMFace2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  AddVertex(a.f, b.f, c.f)
  AddVertexAndNormalIndexed(a.l, b.l)
  SetColorRGB(a.f, b.f, c.f)
  SetColor(a.l)
  SetTexture(a.l)
  SetTextureCoordinates(a.l, b.f, c.f)
  SetMaterial(a.l)
  SetTextureTopology(a.l, b.l)
  GetVertex(a.l, b.l, c.l)
  GetVertices(a.l, b.l, c.l)
  GetTextureCoordinates(a.l, b.l, c.l)
  GetTextureTopology(a.l, b.l)
  GetNormal(a.l)
  GetTexture(a.l)
  GetMaterial(a.l)
  GetVertexCount()
  GetVertexIndex(a.l)
  GetTextureCoordinateIndex(a.l)
  GetColor()
EndInterface

; IDirect3DRMMeshBuilder interface definition
;
Interface IDirect3DRMMeshBuilder
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Load(a.l, b.l, c.l, d.l, e.l)
  Save(a.s, b.l, c.l)
  Scale(a.f, b.f, c.f)
  Translate(a.f, b.f, c.f)
  SetColorSource(a.l)
  GetBox(a.l)
  GenerateNormals()
  GetColorSource()
  AddMesh(a.l)
  AddMeshBuilder(a.l)
  AddFrame(a.l)
  AddFace(a.l)
  AddFaces(a.l, b.l, c.l, d.l, e.l, f.l)
  ReserveSpace(a.l, b.l, c.l)
  SetColorRGB(a.f, b.f, c.f)
  SetColor(a.l)
  SetTexture(a.l)
  SetMaterial(a.l)
  SetTextureTopology(a.l, b.l)
  SetQuality(a.l)
  SetPerspective(a.l)
  SetVertex(a.l, b.f, c.f, d.f)
  SetNormal(a.l, b.f, c.f, d.f)
  SetTextureCoordinates(a.l, b.f, c.f)
  SetVertexColor(a.l, b.l)
  SetVertexColorRGB(a.l, b.f, c.f, d.f)
  GetFaces(a.l)
  GetVertices(a.l, b.l, c.l, d.l, e.l, f.l)
  GetTextureCoordinates(a.l, b.l, c.l)
  AddVertex(a.f, b.f, c.f)
  AddNormal(a.f, b.f, c.f)
  CreateFace(a.l)
  GetQuality()
  GetPerspective()
  GetFaceCount()
  GetVertexCount()
  GetVertexColor(a.l)
  CreateMesh(a.l)
EndInterface

; IDirect3DRMMeshBuilder2 interface definition
;
Interface IDirect3DRMMeshBuilder2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Load(a.l, b.l, c.l, d.l, e.l)
  Save(a.s, b.l, c.l)
  Scale(a.f, b.f, c.f)
  Translate(a.f, b.f, c.f)
  SetColorSource(a.l)
  GetBox(a.l)
  GenerateNormals()
  GetColorSource()
  AddMesh(a.l)
  AddMeshBuilder(a.l)
  AddFrame(a.l)
  AddFace(a.l)
  AddFaces(a.l, b.l, c.l, d.l, e.l, f.l)
  ReserveSpace(a.l, b.l, c.l)
  SetColorRGB(a.f, b.f, c.f)
  SetColor(a.l)
  SetTexture(a.l)
  SetMaterial(a.l)
  SetTextureTopology(a.l, b.l)
  SetQuality(a.l)
  SetPerspective(a.l)
  SetVertex(a.l, b.f, c.f, d.f)
  SetNormal(a.l, b.f, c.f, d.f)
  SetTextureCoordinates(a.l, b.f, c.f)
  SetVertexColor(a.l, b.l)
  SetVertexColorRGB(a.l, b.f, c.f, d.f)
  GetFaces(a.l)
  GetVertices(a.l, b.l, c.l, d.l, e.l, f.l)
  GetTextureCoordinates(a.l, b.l, c.l)
  AddVertex(a.f, b.f, c.f)
  AddNormal(a.f, b.f, c.f)
  CreateFace(a.l)
  GetQuality()
  GetPerspective()
  GetFaceCount()
  GetVertexCount()
  GetVertexColor(a.l)
  CreateMesh(a.l)
  GenerateNormals2(a.f, b.l)
  GetFace(a.l, b.l)
EndInterface

; IDirect3DRMMeshBuilder3 interface definition
;
Interface IDirect3DRMMeshBuilder3
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Load(a.l, b.l, c.l, d.l, e.l)
  Save(a.s, b.l, c.l)
  Scale(a.f, b.f, c.f)
  Translate(a.f, b.f, c.f)
  SetColorSource(a.l)
  GetBox(a.l)
  GenerateNormals(a.f, b.l)
  GetColorSource()
  AddMesh(a.l)
  AddMeshBuilder(a.l, b.l)
  AddFrame(a.l)
  AddFace(a.l)
  AddFaces(a.l, b.l, c.l, d.l, e.l, f.l)
  ReserveSpace(a.l, b.l, c.l)
  SetColorRGB(a.f, b.f, c.f)
  SetColor(a.l)
  SetTexture(a.l)
  SetMaterial(a.l)
  SetTextureTopology(a.l, b.l)
  SetQuality(a.l)
  SetPerspective(a.l)
  SetVertex(a.l, b.f, c.f, d.f)
  SetNormal(a.l, b.f, c.f, d.f)
  SetTextureCoordinates(a.l, b.f, c.f)
  SetVertexColor(a.l, b.l)
  SetVertexColorRGB(a.l, b.f, c.f, d.f)
  GetFaces(a.l)
  GetGeometry(a.l, b.l, c.l, d.l, e.l, f.l)
  GetTextureCoordinates(a.l, b.l, c.l)
  AddVertex(a.f, b.f, c.f)
  AddNormal(a.f, b.f, c.f)
  CreateFace(a.l)
  GetQuality()
  GetPerspective()
  GetFaceCount()
  GetVertexCount()
  GetVertexColor(a.l)
  CreateMesh(a.l)
  GetFace(a.l, b.l)
  GetVertex(a.l, b.l)
  GetNormal(a.l, b.l)
  DeleteVertices(a.l, b.l)
  DeleteNormals(a.l, b.l)
  DeleteFace(a.l)
  Empty(a.l)
  Optimize(a.l)
  AddFacesIndexed(a.l, b.l, c.l, d.l)
  CreateSubMesh(a.l)
  GetParentMesh(a.l, b.l)
  GetSubMeshes(a.l, b.l)
  DeleteSubMesh(a.l)
  Enable(a.l)
  GetEnable(a.l)
  AddTriangles(a.l, b.l, c.l, d.l)
  SetVertices(a.l, b.l, c.l)
  GetVertices(a.l, b.l, c.l)
  SetNormals(a.l, b.l, c.l)
  GetNormals(a.l, b.l, c.l)
  GetNormalCount()
EndInterface

; IDirect3DRMLight interface definition
;
Interface IDirect3DRMLight
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  SetType(a.l)
  SetColor(a.l)
  SetColorRGB(a.f, b.f, c.f)
  SetRange(a.f)
  SetUmbra(a.f)
  SetPenumbra(a.f)
  SetConstantAttenuation(a.f)
  SetLinearAttenuation(a.f)
  SetQuadraticAttenuation(a.f)
  GetRange()
  GetUmbra()
  GetPenumbra()
  GetConstantAttenuation()
  GetLinearAttenuation()
  GetQuadraticAttenuation()
  GetColor()
  GetType()
  SetEnableFrame(a.l)
  GetEnableFrame(a.l)
EndInterface

; IDirect3DRMTexture interface definition
;
Interface IDirect3DRMTexture
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  InitFromFile(a.s)
  InitFromSurface(a.l)
  InitFromResource(a.l)
  Changed(a.l, b.l)
  SetColors(a.l)
  SetShades(a.l)
  SetDecalSize(a.f, b.f)
  SetDecalOrigin(a.l, b.l)
  SetDecalScale(a.l)
  SetDecalTransparency(a.l)
  SetDecalTransparentColor(a.l)
  GetDecalSize(a.l, b.l)
  GetDecalOrigin(a.l, b.l)
  GetImage()
  GetShades()
  GetColors()
  GetDecalScale()
  GetDecalTransparency()
  GetDecalTransparentColor()
EndInterface

; IDirect3DRMTexture2 interface definition
;
Interface IDirect3DRMTexture2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  InitFromFile(a.s)
  InitFromSurface(a.l)
  InitFromResource(a.l)
  Changed(a.l, b.l)
  SetColors(a.l)
  SetShades(a.l)
  SetDecalSize(a.f, b.f)
  SetDecalOrigin(a.l, b.l)
  SetDecalScale(a.l)
  SetDecalTransparency(a.l)
  SetDecalTransparentColor(a.l)
  GetDecalSize(a.l, b.l)
  GetDecalOrigin(a.l, b.l)
  GetImage()
  GetShades()
  GetColors()
  GetDecalScale()
  GetDecalTransparency()
  GetDecalTransparentColor()
  InitFromImage(a.l)
  InitFromResource2(a.l, b.l, c.l)
  GenerateMIPMap(a.l)
EndInterface

; IDirect3DRMTexture3 interface definition
;
Interface IDirect3DRMTexture3
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  InitFromFile(a.s)
  InitFromSurface(a.l)
  InitFromResource(a.l)
  Changed(a.l, b.l, c.l)
  SetColors(a.l)
  SetShades(a.l)
  SetDecalSize(a.f, b.f)
  SetDecalOrigin(a.l, b.l)
  SetDecalScale(a.l)
  SetDecalTransparency(a.l)
  SetDecalTransparentColor(a.l)
  GetDecalSize(a.l, b.l)
  GetDecalOrigin(a.l, b.l)
  GetImage()
  GetShades()
  GetColors()
  GetDecalScale()
  GetDecalTransparency()
  GetDecalTransparentColor()
  InitFromImage(a.l)
  InitFromResource2(a.l, b.l, c.l)
  GenerateMIPMap(a.l)
  GetSurface(a.l, b.l)
  SetCacheOptions(a.l, b.l)
  GetCacheOptions(a.l, b.l)
  SetDownsampleCallback(a.l, b.l)
  SetValidationCallback(a.l, b.l)
EndInterface

; IDirect3DRMWrap interface definition
;
Interface IDirect3DRMWrap
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Init(a.l, b.l, c.f, d.f, e.f, f.f, g.f, h.f, i.f, j.f, k.f, l.f, m.f, n.f, o.f)
  Apply(a.l)
  ApplyRelative(a.l, b.l)
EndInterface

; IDirect3DRMMaterial interface definition
;
Interface IDirect3DRMMaterial
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  SetPower(a.f)
  SetSpecular(a.f, b.f, c.f)
  SetEmissive(a.f, b.f, c.f)
  GetPower()
  GetSpecular(a.l, b.l, c.l)
  GetEmissive(a.l, b.l, c.l)
EndInterface

; IDirect3DRMMaterial2 interface definition
;
Interface IDirect3DRMMaterial2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  SetPower(a.f)
  SetSpecular(a.f, b.f, c.f)
  SetEmissive(a.f, b.f, c.f)
  GetPower()
  GetSpecular(a.l, b.l, c.l)
  GetEmissive(a.l, b.l, c.l)
  GetAmbient(a.l, b.l, c.l)
  SetAmbient(a.f, b.f, c.f)
EndInterface

; IDirect3DRMAnimation interface definition
;
Interface IDirect3DRMAnimation
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  SetOptions(a.l)
  AddRotateKey(a.f, b.l)
  AddPositionKey(a.f, b.f, c.f, d.f)
  AddScaleKey(a.f, b.f, c.f, d.f)
  DeleteKey(a.f)
  SetFrame(a.l)
  SetTime(a.f)
  GetOptions()
EndInterface

; IDirect3DRMAnimation2 interface definition
;
Interface IDirect3DRMAnimation2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  SetOptions(a.l)
  AddRotateKey(a.f, b.l)
  AddPositionKey(a.f, b.f, c.f, d.f)
  AddScaleKey(a.f, b.f, c.f, d.f)
  DeleteKey(a.f)
  SetFrame(a.l)
  SetTime(a.f)
  GetOptions()
  GetFrame(a.l)
  DeleteKeyByID(a.l)
  AddKey(a.l)
  ModifyKey(a.l)
  GetKeys(a.f, b.f, c.l, d.l)
EndInterface

; IDirect3DRMAnimationSet interface definition
;
Interface IDirect3DRMAnimationSet
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  AddAnimation(a.l)
  Load(a.l, b.l, c.l, d.l, e.l, f.l)
  DeleteAnimation(a.l)
  SetTime(a.f)
EndInterface

; IDirect3DRMAnimationSet2 interface definition
;
Interface IDirect3DRMAnimationSet2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  AddAnimation(a.l)
  Load(a.l, b.l, c.l, d.l, e.l, f.l)
  DeleteAnimation(a.l)
  SetTime(a.f)
  GetAnimations(a.l)
EndInterface

; IDirect3DRMUserVisual interface definition
;
Interface IDirect3DRMUserVisual
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Init(a.l, b.l)
EndInterface

; IDirect3DRMArray interface definition
;
Interface IDirect3DRMArray
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetSize()
EndInterface

; IDirect3DRMObjectArray interface definition
;
Interface IDirect3DRMObjectArray
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetSize()
  GetElement(a.l, b.l)
EndInterface

; IDirect3DRMDeviceArray interface definition
;
Interface IDirect3DRMDeviceArray
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetSize()
  GetElement(a.l, b.l)
EndInterface

; IDirect3DRMFrameArray interface definition
;
Interface IDirect3DRMFrameArray
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetSize()
  GetElement(a.l, b.l)
EndInterface

; IDirect3DRMViewportArray interface definition
;
Interface IDirect3DRMViewportArray
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetSize()
  GetElement(a.l, b.l)
EndInterface

; IDirect3DRMVisualArray interface definition
;
Interface IDirect3DRMVisualArray
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetSize()
  GetElement(a.l, b.l)
EndInterface

; IDirect3DRMAnimationArray interface definition
;
Interface IDirect3DRMAnimationArray
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetSize()
  GetElement(a.l, b.l)
EndInterface

; IDirect3DRMPickedArray interface definition
;
Interface IDirect3DRMPickedArray
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetSize()
  GetPick(a.l, b.l, c.l, d.l)
EndInterface

; IDirect3DRMLightArray interface definition
;
Interface IDirect3DRMLightArray
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetSize()
  GetElement(a.l, b.l)
EndInterface

; IDirect3DRMFaceArray interface definition
;
Interface IDirect3DRMFaceArray
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetSize()
  GetElement(a.l, b.l)
EndInterface

; IDirect3DRMPicked2Array interface definition
;
Interface IDirect3DRMPicked2Array
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetSize()
  GetPick(a.l, b.l, c.l, d.l)
EndInterface

; IDirect3DRMInterpolator interface definition
;
Interface IDirect3DRMInterpolator
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  AttachObject(a.l)
  GetAttachedObjects(a.l)
  DetachObject(a.l)
  SetIndex(a.f)
  GetIndex()
  Interpolate(a.f, b.l, c.l)
EndInterface

; IDirect3DRMClippedVisual interface definition
;
Interface IDirect3DRMClippedVisual
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Clone(a.l, b.l, c.l)
  AddDestroyCallback(a.l, b.l)
  DeleteDestroyCallback(a.l, b.l)
  SetAppData(a.l)
  GetAppData()
  SetName(a.s)
  GetName(a.l, b.l)
  GetClassName(a.l, b.l)
  Init(a.l)
  AddPlane(a.l, b.l, c.l, d.l, e.l)
  DeletePlane(a.l, b.l)
  GetPlaneIDs(a.l, b.l, c.l)
  GetPlane(a.l, b.l, c.l, d.l, e.l)
  SetPlane(a.l, b.l, c.l, d.l, e.l)
EndInterface
