
; ID3DXAnimationSet interface definition
;
Interface ID3DXAnimationSet
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetName()
  GetPeriod()
  GetPeriodicPosition(a.d)
  GetNumAnimations()
  GetAnimationNameByIndex(a.l, b.l)
  GetAnimationIndexByName(a.s, b.l)
  GetSRT(a.d, b.l, c.l, d.l, e.l)
  GetCallback(a.d, b.l, c.l, d.l)
EndInterface

; ID3DXKeyframedAnimationSet interface definition
;
Interface ID3DXKeyframedAnimationSet
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetName()
  GetPeriod()
  GetPeriodicPosition(a.d)
  GetNumAnimations()
  GetAnimationNameByIndex(a.l, b.l)
  GetAnimationIndexByName(a.s, b.l)
  GetSRT(a.d, b.l, c.l, d.l, e.l)
  GetCallback(a.d, b.l, c.l, d.l)
  GetPlaybackType()
  GetSourceTicksPerSecond()
  GetNumScaleKeys(a.l)
  GetScaleKeys(a.l, b.l)
  GetScaleKey(a.l, b.l, c.l)
  SetScaleKey(a.l, b.l, c.l)
  GetNumRotationKeys(a.l)
  GetRotationKeys(a.l, b.l)
  GetRotationKey(a.l, b.l, c.l)
  SetRotationKey(a.l, b.l, c.l)
  GetNumTranslationKeys(a.l)
  GetTranslationKeys(a.l, b.l)
  GetTranslationKey(a.l, b.l, c.l)
  SetTranslationKey(a.l, b.l, c.l)
  GetNumCallbackKeys()
  GetCallbackKeys(a.l)
  GetCallbackKey(a.l, b.l)
  SetCallbackKey(a.l, b.l)
  UnregisterScaleKey(a.l, b.l)
  UnregisterRotationKey(a.l, b.l)
  UnregisterTranslationKey(a.l, b.l)
  RegisterAnimationSRTKeys(a.s, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  Compress(a.l, b.f, c.l, d.l)
  UnregisterAnimation(a.l)
EndInterface

; ID3DXCompressedAnimationSet interface definition
;
Interface ID3DXCompressedAnimationSet
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetName()
  GetPeriod()
  GetPeriodicPosition(a.d)
  GetNumAnimations()
  GetAnimationNameByIndex(a.l, b.l)
  GetAnimationIndexByName(a.s, b.l)
  GetSRT(a.d, b.l, c.l, d.l, e.l)
  GetCallback(a.d, b.l, c.l, d.l)
  GetPlaybackType()
  GetSourceTicksPerSecond()
  GetCompressedData(a.l)
  GetNumCallbackKeys()
  GetCallbackKeys(a.l)
EndInterface

; ID3DXAnimationController interface definition
;
Interface ID3DXAnimationController
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetMaxNumAnimationOutputs()
  GetMaxNumAnimationSets()
  GetMaxNumTracks()
  GetMaxNumEvents()
  RegisterAnimationOutput(a.s, b.l, c.l, d.l, e.l)
  RegisterAnimationSet(a.l)
  UnregisterAnimationSet(a.l)
  GetNumAnimationSets()
  GetAnimationSet(a.l, b.l)
  GetAnimationSetByName(a.s, b.l)
  AdvanceTime(a.d, b.l)
  ResetTime()
  GetTime()
  SetTrackAnimationSet(a.l, b.l)
  GetTrackAnimationSet(a.l, b.l)
  SetTrackPriority(a.l, b.l)
  SetTrackSpeed(a.l, b.f)
  SetTrackWeight(a.l, b.f)
  SetTrackPosition(a.l, b.d)
  SetTrackEnable(a.l, b.l)
  SetTrackDesc(a.l, b.l)
  GetTrackDesc(a.l, b.l)
  SetPriorityBlend(a.f)
  GetPriorityBlend()
  KeyTrackSpeed(a.l, b.f, c.d, d.d, e.l)
  KeyTrackWeight(a.l, b.f, c.d, d.d, e.l)
  KeyTrackPosition(a.l, b.d, c.d)
  KeyTrackEnable(a.l, b.l, c.d)
  KeyPriorityBlend(a.f, b.d, c.d, d.l)
  UnkeyEvent(a.l)
  UnkeyAllTrackEvents(a.l)
  UnkeyAllPriorityBlends()
  GetCurrentTrackEvent(a.l, b.l)
  GetCurrentPriorityBlend()
  GetUpcomingTrackEvent(a.l, b.l)
  GetUpcomingPriorityBlend(a.l)
  ValidateEvent(a.l)
  GetEventDesc(a.l, b.l)
  CloneAnimationController(a.l, b.l, c.l, d.l, e.l)
EndInterface
