
; ID3DXBaseMesh interface definition
;
Interface ID3DXBaseMesh
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  DrawSubset(a.l)
  GetNumFaces()
  GetNumVertices()
  GetFVF()
  GetDeclaration(a.l)
  GetNumBytesPerVertex()
  GetOptions()
  GetDevice(a.l)
  CloneMeshFVF(a.l, b.l, c.l, d.l)
  CloneMesh(a.l, b.l, c.l, d.l)
  GetVertexBuffer(a.l)
  GetIndexBuffer(a.l)
  LockVertexBuffer(a.l, b.l)
  UnlockVertexBuffer()
  LockIndexBuffer(a.l, b.l)
  UnlockIndexBuffer()
  GetAttributeTable(a.l, b.l)
  ConvertPointRepsToAdjacency(a.l, b.l)
  ConvertAdjacencyToPointReps(a.l, b.l)
  GenerateAdjacency(a.f, b.l)
  UpdateSemantics(a.l)
EndInterface

; ID3DXMesh interface definition
;
Interface ID3DXMesh
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  DrawSubset(a.l)
  GetNumFaces()
  GetNumVertices()
  GetFVF()
  GetDeclaration(a.l)
  GetNumBytesPerVertex()
  GetOptions()
  GetDevice(a.l)
  CloneMeshFVF(a.l, b.l, c.l, d.l)
  CloneMesh(a.l, b.l, c.l, d.l)
  GetVertexBuffer(a.l)
  GetIndexBuffer(a.l)
  LockVertexBuffer(a.l, b.l)
  UnlockVertexBuffer()
  LockIndexBuffer(a.l, b.l)
  UnlockIndexBuffer()
  GetAttributeTable(a.l, b.l)
  ConvertPointRepsToAdjacency(a.l, b.l)
  ConvertAdjacencyToPointReps(a.l, b.l)
  GenerateAdjacency(a.f, b.l)
  UpdateSemantics(a.l)
  LockAttributeBuffer(a.l, b.l)
  UnlockAttributeBuffer()
  Optimize(a.l, b.l, c.l, d.l, e.l, f.l)
  OptimizeInplace(a.l, b.l, c.l, d.l, e.l)
  SetAttributeTable(a.l, b.l)
EndInterface

; ID3DXPMesh interface definition
;
Interface ID3DXPMesh
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  DrawSubset(a.l)
  GetNumFaces()
  GetNumVertices()
  GetFVF()
  GetDeclaration(a.l)
  GetNumBytesPerVertex()
  GetOptions()
  GetDevice(a.l)
  CloneMeshFVF(a.l, b.l, c.l, d.l)
  CloneMesh(a.l, b.l, c.l, d.l)
  GetVertexBuffer(a.l)
  GetIndexBuffer(a.l)
  LockVertexBuffer(a.l, b.l)
  UnlockVertexBuffer()
  LockIndexBuffer(a.l, b.l)
  UnlockIndexBuffer()
  GetAttributeTable(a.l, b.l)
  ConvertPointRepsToAdjacency(a.l, b.l)
  ConvertAdjacencyToPointReps(a.l, b.l)
  GenerateAdjacency(a.f, b.l)
  UpdateSemantics(a.l)
  ClonePMeshFVF(a.l, b.l, c.l, d.l)
  ClonePMesh(a.l, b.l, c.l, d.l)
  SetNumFaces(a.l)
  SetNumVertices(a.l)
  GetMaxFaces()
  GetMinFaces()
  GetMaxVertices()
  GetMinVertices()
  Save(a.l, b.l, c.l, d.l)
  Optimize(a.l, b.l, c.l, d.l, e.l)
  OptimizeBaseLOD(a.l, b.l)
  TrimByFaces(a.l, b.l, c.l, d.l)
  TrimByVertices(a.l, b.l, c.l, d.l)
  GetAdjacency(a.l)
  GenerateVertexHistory(a.l)
EndInterface

; ID3DXSPMesh interface definition
;
Interface ID3DXSPMesh
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetNumFaces()
  GetNumVertices()
  GetFVF()
  GetDeclaration(a.l)
  GetOptions()
  GetDevice(a.l)
  CloneMeshFVF(a.l, b.l, c.l, d.l, e.l, f.l)
  CloneMesh(a.l, b.l, c.l, d.l, e.l, f.l)
  ClonePMeshFVF(a.l, b.l, c.l, d.l, e.l, f.l)
  ClonePMesh(a.l, b.l, c.l, d.l, e.l, f.l)
  ReduceFaces(a.l)
  ReduceVertices(a.l)
  GetMaxFaces()
  GetMaxVertices()
  GetVertexAttributeWeights(a.l)
  GetVertexWeights(a.l)
EndInterface

; ID3DXPatchMesh interface definition
;
Interface ID3DXPatchMesh
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetNumPatches()
  GetNumVertices()
  GetDeclaration(a.l)
  GetControlVerticesPerPatch()
  GetOptions()
  GetDevice(a.l)
  GetPatchInfo(a.l)
  GetVertexBuffer(a.l)
  GetIndexBuffer(a.l)
  LockVertexBuffer(a.l, b.l)
  UnlockVertexBuffer()
  LockIndexBuffer(a.l, b.l)
  UnlockIndexBuffer()
  LockAttributeBuffer(a.l, b.l)
  UnlockAttributeBuffer()
  GetTessSize(a.f, b.l, c.l, d.l)
  GenerateAdjacency(a.f)
  CloneMesh(a.l, b.l, c.l)
  Optimize(a.l)
  SetDisplaceParam(a.l, b.l, c.l, d.l, e.l, f.l)
  GetDisplaceParam(a.l, b.l, c.l, d.l, e.l, f.l)
  Tessellate(a.f, b.l)
  TessellateAdaptive(a.l, b.l, c.l, d.l)
EndInterface

; ID3DXSkinInfo interface definition
;
Interface ID3DXSkinInfo
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  SetBoneInfluence(a.l, b.l, c.l, d.l)
  SetBoneVertexInfluence(a.l, b.l, c.f)
  GetNumBoneInfluences(a.l)
  GetBoneInfluence(a.l, b.l, c.l)
  GetBoneVertexInfluence(a.l, b.l, c.l, d.l)
  GetMaxVertexInfluences(a.l)
  GetNumBones()
  FindBoneVertexInfluenceIndex(a.l, b.l, c.l)
  GetMaxFaceInfluences(a.l, b.l, c.l)
  SetMinBoneInfluence(a.f)
  GetMinBoneInfluence()
  SetBoneName(a.l, b.s)
  GetBoneName(a.l)
  SetBoneOffsetMatrix(a.l, b.l)
  GetBoneOffsetMatrix(a.l)
  Clone(a.l)
  Remap(a.l, b.l)
  SetFVF(a.l)
  SetDeclaration(a.l)
  GetFVF()
  GetDeclaration(a.l)
  UpdateSkinnedMesh(a.l, b.l, c.l, d.l)
  ConvertToBlendedMesh(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l)
  ConvertToIndexedBlendedMesh(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l)
EndInterface

; ID3DXPRTBuffer interface definition
;
Interface ID3DXPRTBuffer
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetNumSamples()
  GetNumCoeffs()
  GetNumChannels()
  IsTexture()
  GetWidth()
  GetHeight()
  Resize(a.l)
  LockBuffer(a.l, b.l, c.l)
  UnlockBuffer()
  ScaleBuffer(a.f)
  AddBuffer(a.l)
  AttachGH(a.l)
  ReleaseGH()
  EvalGH()
  ExtractTexture(a.l, b.l, c.l, d.l)
  ExtractToMesh(a.l, b.l, c.l, d.l)
EndInterface

; ID3DXPRTCompBuffer interface definition
;
Interface ID3DXPRTCompBuffer
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetNumSamples()
  GetNumCoeffs()
  GetNumChannels()
  IsTexture()
  GetWidth()
  GetHeight()
  GetNumClusters()
  GetNumPCA()
  NormalizeData()
  ExtractBasis(a.l, b.l)
  ExtractClusterIDs(a.l)
  ExtractPCA(a.l, b.l, c.l)
  ExtractTexture(a.l, b.l, c.l)
  ExtractToMesh(a.l, b.l, c.l, d.l)
EndInterface

; ID3DXTextureGutterHelper interface definition
;
Interface ID3DXTextureGutterHelper
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetWidth()
  GetHeight()
  ApplyGuttersFloat(a.l, b.l, c.l, d.l)
  ApplyGuttersTex(a.l)
  ApplyGuttersPRT(a.l)
  GetFaceMap(a.l)
  GetBaryMap(a.l)
  GetTexelMap(a.l)
  GetGutterMap(a.l)
  SetFaceMap(a.l)
  SetBaryMap(a.l)
  SetTexelMap(a.l)
  SetGutterMap(a.l)
EndInterface

; ID3DXPRTEngine interface definition
;
Interface ID3DXPRTEngine
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  SetMeshMaterials(a.l, b.l, c.l, d.l, e.f)
  SetPerVertexAlbedo(a.l, b.l, c.l)
  SetPerTexelAlbedo(a.l, b.l, c.l)
  GetVertexAlbedo(a.l, b.l)
  SetPerTexelNormal(a.l)
  ExtractPerVertexAlbedo(a.l, b.l, c.l)
  ResampleBuffer(a.l, b.l)
  GetAdaptedMesh(a.l, b.l, c.l, d.l, e.l)
  GetNumVerts()
  GetNumFaces()
  SetMinMaxIntersection(a.f, b.f)
  RobustMeshRefine(a.f, b.l)
  SetSamplingInfo(a.l, b.l, c.l, d.l, e.f)
  ComputeDirectLightingSH(a.l, b.l)
  ComputeDirectLightingSHAdaptive(a.l, b.f, c.f, d.l, e.l)
  ComputeDirectLightingSHGPU(a.l, b.l, c.l, d.f, e.f, f.l)
  ComputeSS(a.l, b.l, c.l)
  ComputeSSAdaptive(a.l, b.f, c.f, d.l, e.l, f.l)
  ComputeBounce(a.l, b.l, c.l)
  ComputeBounceAdaptive(a.l, b.f, c.f, d.l, e.l, f.l)
  ComputeVolumeSamplesDirectSH(a.l, b.l, c.l, d.l, e.l)
  ComputeVolumeSamples(a.l, b.l, c.l, d.l, e.l)
  ComputeSurfSamplesDirectSH(a.l, b.l, c.l, d.l, e.l)
  ComputeSurfSamplesBounce(a.l, b.l, c.l, d.l, e.l, f.l)
  FreeSSData()
  FreeBounceData()
  ComputeLDPRTCoeffs(a.l, b.l, c.l, d.l)
  ScaleMeshChunk(a.l, b.f, c.l)
  MultiplyAlbedo(a.l)
  SetCallBack(a.l, b.f, c.l)
EndInterface
