
; ID3DXEffectPool interface definition
;
Interface ID3DXEffectPool
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
EndInterface

; ID3DXBaseEffect interface definition
;
Interface ID3DXBaseEffect
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetDesc(a.l)
  GetParameterDesc(a.l, b.l)
  GetTechniqueDesc(a.l, b.l)
  GetPassDesc(a.l, b.l)
  GetFunctionDesc(a.l, b.l)
  GetParameter(a.l, b.l)
  GetParameterByName(a.l, b.s)
  GetParameterBySemantic(a.l, b.s)
  GetParameterElement(a.l, b.l)
  GetTechnique(a.l)
  GetTechniqueByName(a.s)
  GetPass(a.l, b.l)
  GetPassByName(a.l, b.s)
  GetFunction(a.l)
  GetFunctionByName(a.s)
  GetAnnotation(a.l, b.l)
  GetAnnotationByName(a.l, b.s)
  SetValue(a.l, b.l, c.l)
  GetValue(a.l, b.l, c.l)
  SetBool(a.l, b.l)
  GetBool(a.l, b.l)
  SetBoolArray(a.l, b.l, c.l)
  GetBoolArray(a.l, b.l, c.l)
  SetInt(a.l, b.l)
  GetInt(a.l, b.l)
  SetIntArray(a.l, b.l, c.l)
  GetIntArray(a.l, b.l, c.l)
  SetFloat(a.l, b.f)
  GetFloat(a.l, b.l)
  SetFloatArray(a.l, b.l, c.l)
  GetFloatArray(a.l, b.l, c.l)
  SetVector(a.l, b.l)
  GetVector(a.l, b.l)
  SetVectorArray(a.l, b.l, c.l)
  GetVectorArray(a.l, b.l, c.l)
  SetMatrix(a.l, b.l)
  GetMatrix(a.l, b.l)
  SetMatrixArray(a.l, b.l, c.l)
  GetMatrixArray(a.l, b.l, c.l)
  SetMatrixPointerArray(a.l, b.l, c.l)
  GetMatrixPointerArray(a.l, b.l, c.l)
  SetMatrixTranspose(a.l, b.l)
  GetMatrixTranspose(a.l, b.l)
  SetMatrixTransposeArray(a.l, b.l, c.l)
  GetMatrixTransposeArray(a.l, b.l, c.l)
  SetMatrixTransposePointerArray(a.l, b.l, c.l)
  GetMatrixTransposePointerArray(a.l, b.l, c.l)
  SetString(a.l, b.s)
  GetString(a.l, b.l)
  SetTexture(a.l, b.l)
  GetTexture(a.l, b.l)
  GetPixelShader(a.l, b.l)
  GetVertexShader(a.l, b.l)
  SetArrayRange(a.l, b.l, c.l)
EndInterface

; ID3DXEffectStateManager interface definition
;
Interface ID3DXEffectStateManager
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  SetTransform(a.l, b.l)
  SetMaterial(a.l)
  SetLight(a.l, b.l)
  LightEnable(a.l, b.l)
  SetRenderState(a.l, b.l)
  SetTexture(a.l, b.l)
  SetTextureStageState(a.l, b.l, c.l)
  SetSamplerState(a.l, b.l, c.l)
  SetNPatchMode(a.f)
  SetFVF(a.l)
  SetVertexShader(a.l)
  SetVertexShaderConstantF(a.l, b.l, c.l)
  SetVertexShaderConstantI(a.l, b.l, c.l)
  SetVertexShaderConstantB(a.l, b.l, c.l)
  SetPixelShader(a.l)
  SetPixelShaderConstantF(a.l, b.l, c.l)
  SetPixelShaderConstantI(a.l, b.l, c.l)
  SetPixelShaderConstantB(a.l, b.l, c.l)
EndInterface

; ID3DXEffect interface definition
;
Interface ID3DXEffect
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetDesc(a.l)
  GetParameterDesc(a.l, b.l)
  GetTechniqueDesc(a.l, b.l)
  GetPassDesc(a.l, b.l)
  GetFunctionDesc(a.l, b.l)
  GetParameter(a.l, b.l)
  GetParameterByName(a.l, b.s)
  GetParameterBySemantic(a.l, b.s)
  GetParameterElement(a.l, b.l)
  GetTechnique(a.l)
  GetTechniqueByName(a.s)
  GetPass(a.l, b.l)
  GetPassByName(a.l, b.s)
  GetFunction(a.l)
  GetFunctionByName(a.s)
  GetAnnotation(a.l, b.l)
  GetAnnotationByName(a.l, b.s)
  SetValue(a.l, b.l, c.l)
  GetValue(a.l, b.l, c.l)
  SetBool(a.l, b.l)
  GetBool(a.l, b.l)
  SetBoolArray(a.l, b.l, c.l)
  GetBoolArray(a.l, b.l, c.l)
  SetInt(a.l, b.l)
  GetInt(a.l, b.l)
  SetIntArray(a.l, b.l, c.l)
  GetIntArray(a.l, b.l, c.l)
  SetFloat(a.l, b.f)
  GetFloat(a.l, b.l)
  SetFloatArray(a.l, b.l, c.l)
  GetFloatArray(a.l, b.l, c.l)
  SetVector(a.l, b.l)
  GetVector(a.l, b.l)
  SetVectorArray(a.l, b.l, c.l)
  GetVectorArray(a.l, b.l, c.l)
  SetMatrix(a.l, b.l)
  GetMatrix(a.l, b.l)
  SetMatrixArray(a.l, b.l, c.l)
  GetMatrixArray(a.l, b.l, c.l)
  SetMatrixPointerArray(a.l, b.l, c.l)
  GetMatrixPointerArray(a.l, b.l, c.l)
  SetMatrixTranspose(a.l, b.l)
  GetMatrixTranspose(a.l, b.l)
  SetMatrixTransposeArray(a.l, b.l, c.l)
  GetMatrixTransposeArray(a.l, b.l, c.l)
  SetMatrixTransposePointerArray(a.l, b.l, c.l)
  GetMatrixTransposePointerArray(a.l, b.l, c.l)
  SetString(a.l, b.s)
  GetString(a.l, b.l)
  SetTexture(a.l, b.l)
  GetTexture(a.l, b.l)
  GetPixelShader(a.l, b.l)
  GetVertexShader(a.l, b.l)
  SetArrayRange(a.l, b.l, c.l)
  GetPool(a.l)
  SetTechnique(a.l)
  GetCurrentTechnique()
  ValidateTechnique(a.l)
  FindNextValidTechnique(a.l, b.l)
  IsParameterUsed(a.l, b.l)
  Begin(a.l, b.l)
  BeginPass(a.l)
  CommitChanges()
  EndPass()
  End()
  GetDevice(a.l)
  OnLostDevice()
  OnResetDevice()
  SetStateManager(a.l)
  GetStateManager(a.l)
  BeginParameterBlock()
  EndParameterBlock()
  ApplyParameterBlock(a.l)
  CloneEffect(a.l, b.l)
EndInterface

; ID3DXEffectCompiler interface definition
;
Interface ID3DXEffectCompiler
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetDesc(a.l)
  GetParameterDesc(a.l, b.l)
  GetTechniqueDesc(a.l, b.l)
  GetPassDesc(a.l, b.l)
  GetFunctionDesc(a.l, b.l)
  GetParameter(a.l, b.l)
  GetParameterByName(a.l, b.s)
  GetParameterBySemantic(a.l, b.s)
  GetParameterElement(a.l, b.l)
  GetTechnique(a.l)
  GetTechniqueByName(a.s)
  GetPass(a.l, b.l)
  GetPassByName(a.l, b.s)
  GetFunction(a.l)
  GetFunctionByName(a.s)
  GetAnnotation(a.l, b.l)
  GetAnnotationByName(a.l, b.s)
  SetValue(a.l, b.l, c.l)
  GetValue(a.l, b.l, c.l)
  SetBool(a.l, b.l)
  GetBool(a.l, b.l)
  SetBoolArray(a.l, b.l, c.l)
  GetBoolArray(a.l, b.l, c.l)
  SetInt(a.l, b.l)
  GetInt(a.l, b.l)
  SetIntArray(a.l, b.l, c.l)
  GetIntArray(a.l, b.l, c.l)
  SetFloat(a.l, b.f)
  GetFloat(a.l, b.l)
  SetFloatArray(a.l, b.l, c.l)
  GetFloatArray(a.l, b.l, c.l)
  SetVector(a.l, b.l)
  GetVector(a.l, b.l)
  SetVectorArray(a.l, b.l, c.l)
  GetVectorArray(a.l, b.l, c.l)
  SetMatrix(a.l, b.l)
  GetMatrix(a.l, b.l)
  SetMatrixArray(a.l, b.l, c.l)
  GetMatrixArray(a.l, b.l, c.l)
  SetMatrixPointerArray(a.l, b.l, c.l)
  GetMatrixPointerArray(a.l, b.l, c.l)
  SetMatrixTranspose(a.l, b.l)
  GetMatrixTranspose(a.l, b.l)
  SetMatrixTransposeArray(a.l, b.l, c.l)
  GetMatrixTransposeArray(a.l, b.l, c.l)
  SetMatrixTransposePointerArray(a.l, b.l, c.l)
  GetMatrixTransposePointerArray(a.l, b.l, c.l)
  SetString(a.l, b.s)
  GetString(a.l, b.l)
  SetTexture(a.l, b.l)
  GetTexture(a.l, b.l)
  GetPixelShader(a.l, b.l)
  GetVertexShader(a.l, b.l)
  SetArrayRange(a.l, b.l, c.l)
  SetLiteral(a.l, b.l)
  GetLiteral(a.l, b.l)
  CompileEffect(a.l, b.l, c.l)
  CompileShader(a.l, b.s, c.l, d.l, e.l, f.l)
EndInterface
