
; IDirectDraw interface definition
;
Interface IDirectDraw
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Compact()
  CreateClipper(a.l, b.l, c.l)
  CreatePalette(a.l, b.l, c.l, d.l)
  CreateSurface(a.l, b.l, c.l)
  DuplicateSurface(a.l, b.l)
  EnumDisplayModes(a.l, b.l, c.l, d.l)
  EnumSurfaces(a.l, b.l, c.l, d.l)
  FlipToGDISurface()
  GetCaps(a.l, b.l)
  GetDisplayMode(a.l)
  GetFourCCCodes(a.l, b.l)
  GetGDISurface(a.l)
  GetMonitorFrequency(a.l)
  GetScanLine(a.l)
  GetVerticalBlankStatus(a.l)
  Initialize(a.l)
  RestoreDisplayMode()
  SetCooperativeLevel(a.l, b.l)
  SetDisplayMode(a.l, b.l, c.l)
  WaitForVerticalBlank(a.l, b.l)
EndInterface

; IDirectDraw2 interface definition
;
Interface IDirectDraw2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Compact()
  CreateClipper(a.l, b.l, c.l)
  CreatePalette(a.l, b.l, c.l, d.l)
  CreateSurface(a.l, b.l, c.l)
  DuplicateSurface(a.l, b.l)
  EnumDisplayModes(a.l, b.l, c.l, d.l)
  EnumSurfaces(a.l, b.l, c.l, d.l)
  FlipToGDISurface()
  GetCaps(a.l, b.l)
  GetDisplayMode(a.l)
  GetFourCCCodes(a.l, b.l)
  GetGDISurface(a.l)
  GetMonitorFrequency(a.l)
  GetScanLine(a.l)
  GetVerticalBlankStatus(a.l)
  Initialize(a.l)
  RestoreDisplayMode()
  SetCooperativeLevel(a.l, b.l)
  SetDisplayMode(a.l, b.l, c.l, d.l, e.l)
  WaitForVerticalBlank(a.l, b.l)
  GetAvailableVidMem(a.l, b.l, c.l)
EndInterface

; IDirectDraw4 interface definition
;
Interface IDirectDraw4
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Compact()
  CreateClipper(a.l, b.l, c.l)
  CreatePalette(a.l, b.l, c.l, d.l)
  CreateSurface(a.l, b.l, c.l)
  DuplicateSurface(a.l, b.l)
  EnumDisplayModes(a.l, b.l, c.l, d.l)
  EnumSurfaces(a.l, b.l, c.l, d.l)
  FlipToGDISurface()
  GetCaps(a.l, b.l)
  GetDisplayMode(a.l)
  GetFourCCCodes(a.l, b.l)
  GetGDISurface(a.l)
  GetMonitorFrequency(a.l)
  GetScanLine(a.l)
  GetVerticalBlankStatus(a.l)
  Initialize(a.l)
  RestoreDisplayMode()
  SetCooperativeLevel(a.l, b.l)
  SetDisplayMode(a.l, b.l, c.l, d.l, e.l)
  WaitForVerticalBlank(a.l, b.l)
  GetAvailableVidMem(a.l, b.l, c.l)
  GetSurfaceFromDC(a.l, b.l)
  RestoreAllSurfaces()
  TestCooperativeLevel()
  GetDeviceIdentifier(a.l, b.l)
EndInterface

; IDirectDraw7 interface definition
;
Interface IDirectDraw7
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Compact()
  CreateClipper(a.l, b.l, c.l)
  CreatePalette(a.l, b.l, c.l, d.l)
  CreateSurface(a.l, b.l, c.l)
  DuplicateSurface(a.l, b.l)
  EnumDisplayModes(a.l, b.l, c.l, d.l)
  EnumSurfaces(a.l, b.l, c.l, d.l)
  FlipToGDISurface()
  GetCaps(a.l, b.l)
  GetDisplayMode(a.l)
  GetFourCCCodes(a.l, b.l)
  GetGDISurface(a.l)
  GetMonitorFrequency(a.l)
  GetScanLine(a.l)
  GetVerticalBlankStatus(a.l)
  Initialize(a.l)
  RestoreDisplayMode()
  SetCooperativeLevel(a.l, b.l)
  SetDisplayMode(a.l, b.l, c.l, d.l, e.l)
  WaitForVerticalBlank(a.l, b.l)
  GetAvailableVidMem(a.l, b.l, c.l)
  GetSurfaceFromDC(a.l, b.l)
  RestoreAllSurfaces()
  TestCooperativeLevel()
  GetDeviceIdentifier(a.l, b.l)
  StartModeTest(a.l, b.l, c.l)
  EvaluateMode(a.l, b.l)
EndInterface

; IDirectDrawPalette interface definition
;
Interface IDirectDrawPalette
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetCaps(a.l)
  GetEntries(a.l, b.l, c.l, d.l)
  Initialize(a.l, b.l, c.l)
  SetEntries(a.l, b.l, c.l, d.l)
EndInterface

; IDirectDrawClipper interface definition
;
Interface IDirectDrawClipper
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetClipList(a.l, b.l, c.l)
  GetHWnd(a.l)
  Initialize(a.l, b.l)
  IsClipListChanged(a.l)
  SetClipList(a.l, b.l)
  SetHWnd(a.l, b.l)
EndInterface

; IDirectDrawSurface interface definition
;
Interface IDirectDrawSurface
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  AddAttachedSurface(a.l)
  AddOverlayDirtyRect(a.l)
  Blt(a.l, b.l, c.l, d.l, e.l)
  BltBatch(a.l, b.l, c.l)
  BltFast(a.l, b.l, c.l, d.l, e.l)
  DeleteAttachedSurface(a.l, b.l)
  EnumAttachedSurfaces(a.l, b.l)
  EnumOverlayZOrders(a.l, b.l, c.l)
  Flip(a.l, b.l)
  GetAttachedSurface(a.l, b.l)
  GetBltStatus(a.l)
  GetCaps(a.l)
  GetClipper(a.l)
  GetColorKey(a.l, b.l)
  GetDC(a.l)
  GetFlipStatus(a.l)
  GetOverlayPosition(a.l, b.l)
  GetPalette(a.l)
  GetPixelFormat(a.l)
  GetSurfaceDesc(a.l)
  Initialize(a.l, b.l)
  IsLost()
  Lock(a.l, b.l, c.l, d.l)
  ReleaseDC(a.l)
  Restore()
  SetClipper(a.l)
  SetColorKey(a.l, b.l)
  SetOverlayPosition(a.l, b.l)
  SetPalette(a.l)
  Unlock(a.l)
  UpdateOverlay(a.l, b.l, c.l, d.l, e.l)
  UpdateOverlayDisplay(a.l)
  UpdateOverlayZOrder(a.l, b.l)
EndInterface

; IDirectDrawSurface2 interface definition
;
Interface IDirectDrawSurface2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  AddAttachedSurface(a.l)
  AddOverlayDirtyRect(a.l)
  Blt(a.l, b.l, c.l, d.l, e.l)
  BltBatch(a.l, b.l, c.l)
  BltFast(a.l, b.l, c.l, d.l, e.l)
  DeleteAttachedSurface(a.l, b.l)
  EnumAttachedSurfaces(a.l, b.l)
  EnumOverlayZOrders(a.l, b.l, c.l)
  Flip(a.l, b.l)
  GetAttachedSurface(a.l, b.l)
  GetBltStatus(a.l)
  GetCaps(a.l)
  GetClipper(a.l)
  GetColorKey(a.l, b.l)
  GetDC(a.l)
  GetFlipStatus(a.l)
  GetOverlayPosition(a.l, b.l)
  GetPalette(a.l)
  GetPixelFormat(a.l)
  GetSurfaceDesc(a.l)
  Initialize(a.l, b.l)
  IsLost()
  Lock(a.l, b.l, c.l, d.l)
  ReleaseDC(a.l)
  Restore()
  SetClipper(a.l)
  SetColorKey(a.l, b.l)
  SetOverlayPosition(a.l, b.l)
  SetPalette(a.l)
  Unlock(a.l)
  UpdateOverlay(a.l, b.l, c.l, d.l, e.l)
  UpdateOverlayDisplay(a.l)
  UpdateOverlayZOrder(a.l, b.l)
  GetDDInterface(a.l)
  PageLock(a.l)
  PageUnlock(a.l)
EndInterface

; IDirectDrawSurface3 interface definition
;
Interface IDirectDrawSurface3
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  AddAttachedSurface(a.l)
  AddOverlayDirtyRect(a.l)
  Blt(a.l, b.l, c.l, d.l, e.l)
  BltBatch(a.l, b.l, c.l)
  BltFast(a.l, b.l, c.l, d.l, e.l)
  DeleteAttachedSurface(a.l, b.l)
  EnumAttachedSurfaces(a.l, b.l)
  EnumOverlayZOrders(a.l, b.l, c.l)
  Flip(a.l, b.l)
  GetAttachedSurface(a.l, b.l)
  GetBltStatus(a.l)
  GetCaps(a.l)
  GetClipper(a.l)
  GetColorKey(a.l, b.l)
  GetDC(a.l)
  GetFlipStatus(a.l)
  GetOverlayPosition(a.l, b.l)
  GetPalette(a.l)
  GetPixelFormat(a.l)
  GetSurfaceDesc(a.l)
  Initialize(a.l, b.l)
  IsLost()
  Lock(a.l, b.l, c.l, d.l)
  ReleaseDC(a.l)
  Restore()
  SetClipper(a.l)
  SetColorKey(a.l, b.l)
  SetOverlayPosition(a.l, b.l)
  SetPalette(a.l)
  Unlock(a.l)
  UpdateOverlay(a.l, b.l, c.l, d.l, e.l)
  UpdateOverlayDisplay(a.l)
  UpdateOverlayZOrder(a.l, b.l)
  GetDDInterface(a.l)
  PageLock(a.l)
  PageUnlock(a.l)
  SetSurfaceDesc(a.l, b.l)
EndInterface

; IDirectDrawSurface4 interface definition
;
Interface IDirectDrawSurface4
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  AddAttachedSurface(a.l)
  AddOverlayDirtyRect(a.l)
  Blt(a.l, b.l, c.l, d.l, e.l)
  BltBatch(a.l, b.l, c.l)
  BltFast(a.l, b.l, c.l, d.l, e.l)
  DeleteAttachedSurface(a.l, b.l)
  EnumAttachedSurfaces(a.l, b.l)
  EnumOverlayZOrders(a.l, b.l, c.l)
  Flip(a.l, b.l)
  GetAttachedSurface(a.l, b.l)
  GetBltStatus(a.l)
  GetCaps(a.l)
  GetClipper(a.l)
  GetColorKey(a.l, b.l)
  GetDC(a.l)
  GetFlipStatus(a.l)
  GetOverlayPosition(a.l, b.l)
  GetPalette(a.l)
  GetPixelFormat(a.l)
  GetSurfaceDesc(a.l)
  Initialize(a.l, b.l)
  IsLost()
  Lock(a.l, b.l, c.l, d.l)
  ReleaseDC(a.l)
  Restore()
  SetClipper(a.l)
  SetColorKey(a.l, b.l)
  SetOverlayPosition(a.l, b.l)
  SetPalette(a.l)
  Unlock(a.l)
  UpdateOverlay(a.l, b.l, c.l, d.l, e.l)
  UpdateOverlayDisplay(a.l)
  UpdateOverlayZOrder(a.l, b.l)
  GetDDInterface(a.l)
  PageLock(a.l)
  PageUnlock(a.l)
  SetSurfaceDesc(a.l, b.l)
  SetPrivateData(a.l, b.l, c.l, d.l)
  GetPrivateData(a.l, b.l, c.l)
  FreePrivateData(a.l)
  GetUniquenessValue(a.l)
  ChangeUniquenessValue()
EndInterface

; IDirectDrawSurface7 interface definition
;
Interface IDirectDrawSurface7
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  AddAttachedSurface(a.l)
  AddOverlayDirtyRect(a.l)
  Blt(a.l, b.l, c.l, d.l, e.l)
  BltBatch(a.l, b.l, c.l)
  BltFast(a.l, b.l, c.l, d.l, e.l)
  DeleteAttachedSurface(a.l, b.l)
  EnumAttachedSurfaces(a.l, b.l)
  EnumOverlayZOrders(a.l, b.l, c.l)
  Flip(a.l, b.l)
  GetAttachedSurface(a.l, b.l)
  GetBltStatus(a.l)
  GetCaps(a.l)
  GetClipper(a.l)
  GetColorKey(a.l, b.l)
  GetDC(a.l)
  GetFlipStatus(a.l)
  GetOverlayPosition(a.l, b.l)
  GetPalette(a.l)
  GetPixelFormat(a.l)
  GetSurfaceDesc(a.l)
  Initialize(a.l, b.l)
  IsLost()
  Lock(a.l, b.l, c.l, d.l)
  ReleaseDC(a.l)
  Restore()
  SetClipper(a.l)
  SetColorKey(a.l, b.l)
  SetOverlayPosition(a.l, b.l)
  SetPalette(a.l)
  Unlock(a.l)
  UpdateOverlay(a.l, b.l, c.l, d.l, e.l)
  UpdateOverlayDisplay(a.l)
  UpdateOverlayZOrder(a.l, b.l)
  GetDDInterface(a.l)
  PageLock(a.l)
  PageUnlock(a.l)
  SetSurfaceDesc(a.l, b.l)
  SetPrivateData(a.l, b.l, c.l, d.l)
  GetPrivateData(a.l, b.l, c.l)
  FreePrivateData(a.l)
  GetUniquenessValue(a.l)
  ChangeUniquenessValue()
  SetPriority(a.l)
  GetPriority(a.l)
  SetLOD(a.l)
  GetLOD(a.l)
EndInterface

; IDirectDrawColorControl interface definition
;
Interface IDirectDrawColorControl
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetColorControls(a.l)
  SetColorControls(a.l)
EndInterface

; IDirectDrawGammaControl interface definition
;
Interface IDirectDrawGammaControl
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetGammaRamp(a.l, b.l)
  SetGammaRamp(a.l, b.l)
EndInterface
