
; IDirectPlay8Client interface definition
;
Interface IDirectPlay8Client
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Initialize(a.l, b.l, c.l)
  EnumServiceProviders(a.l, b.l, c.l, d.l, e.l, f.l)
  EnumHosts(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l)
  CancelAsyncOperation(a.l, b.l)
  Connect(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l)
  Send(a.l, b.l, c.l, d.l, e.l, f.l)
  GetSendQueueInfo(a.l, b.l, c.l)
  GetApplicationDesc(a.l, b.l, c.l)
  SetClientInfo(a.l, b.l, c.l, d.l)
  GetServerInfo(a.l, b.l, c.l)
  GetServerAddress(a.l, b.l)
  Close(a.l)
  ReturnBuffer(a.l, b.l)
  GetCaps(a.l, b.l)
  SetCaps(a.l, b.l)
  SetSPCaps(a.l, b.l, c.l)
  GetSPCaps(a.l, b.l, c.l)
  GetConnectionInfo(a.l, b.l)
  RegisterLobby(a.l, b.l, c.l)
EndInterface

; IDirectPlay8Server interface definition
;
Interface IDirectPlay8Server
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Initialize(a.l, b.l, c.l)
  EnumServiceProviders(a.l, b.l, c.l, d.l, e.l, f.l)
  CancelAsyncOperation(a.l, b.l)
  GetSendQueueInfo(a.l, b.l, c.l, d.l)
  GetApplicationDesc(a.l, b.l, c.l)
  SetServerInfo(a.l, b.l, c.l, d.l)
  GetClientInfo(a.l, b.l, c.l, d.l)
  GetClientAddress(a.l, b.l, c.l)
  GetLocalHostAddresses(a.l, b.l, c.l)
  SetApplicationDesc(a.l, b.l)
  Host(a.l, b.l, c.l, d.l, e.l, f.l, g.l)
  SendTo(a.l, b.l, c.l, d.l, e.l, f.l, g.l)
  CreateGroup(a.l, b.l, c.l, d.l, e.l)
  DestroyGroup(a.l, b.l, c.l, d.l)
  AddPlayerToGroup(a.l, b.l, c.l, d.l, e.l)
  RemovePlayerFromGroup(a.l, b.l, c.l, d.l, e.l)
  SetGroupInfo(a.l, b.l, c.l, d.l, e.l)
  GetGroupInfo(a.l, b.l, c.l, d.l)
  EnumPlayersAndGroups(a.l, b.l, c.l)
  EnumGroupMembers(a.l, b.l, c.l, d.l)
  Close(a.l)
  DestroyClient(a.l, b.l, c.l, d.l)
  ReturnBuffer(a.l, b.l)
  GetPlayerContext(a.l, b.l, c.l)
  GetGroupContext(a.l, b.l, c.l)
  GetCaps(a.l, b.l)
  SetCaps(a.l, b.l)
  SetSPCaps(a.l, b.l, c.l)
  GetSPCaps(a.l, b.l, c.l)
  GetConnectionInfo(a.l, b.l, c.l)
  RegisterLobby(a.l, b.l, c.l)
EndInterface

; IDirectPlay8Peer interface definition
;
Interface IDirectPlay8Peer
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Initialize(a.l, b.l, c.l)
  EnumServiceProviders(a.l, b.l, c.l, d.l, e.l, f.l)
  CancelAsyncOperation(a.l, b.l)
  Connect(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l)
  SendTo(a.l, b.l, c.l, d.l, e.l, f.l, g.l)
  GetSendQueueInfo(a.l, b.l, c.l, d.l)
  Host(a.l, b.l, c.l, d.l, e.l, f.l, g.l)
  GetApplicationDesc(a.l, b.l, c.l)
  SetApplicationDesc(a.l, b.l)
  CreateGroup(a.l, b.l, c.l, d.l, e.l)
  DestroyGroup(a.l, b.l, c.l, d.l)
  AddPlayerToGroup(a.l, b.l, c.l, d.l, e.l)
  RemovePlayerFromGroup(a.l, b.l, c.l, d.l, e.l)
  SetGroupInfo(a.l, b.l, c.l, d.l, e.l)
  GetGroupInfo(a.l, b.l, c.l, d.l)
  EnumPlayersAndGroups(a.l, b.l, c.l)
  EnumGroupMembers(a.l, b.l, c.l, d.l)
  SetPeerInfo(a.l, b.l, c.l, d.l)
  GetPeerInfo(a.l, b.l, c.l, d.l)
  GetPeerAddress(a.l, b.l, c.l)
  GetLocalHostAddresses(a.l, b.l, c.l)
  Close(a.l)
  EnumHosts(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l)
  DestroyPeer(a.l, b.l, c.l, d.l)
  ReturnBuffer(a.l, b.l)
  GetPlayerContext(a.l, b.l, c.l)
  GetGroupContext(a.l, b.l, c.l)
  GetCaps(a.l, b.l)
  SetCaps(a.l, b.l)
  SetSPCaps(a.l, b.l, c.l)
  GetSPCaps(a.l, b.l, c.l)
  GetConnectionInfo(a.l, b.l, c.l)
  RegisterLobby(a.l, b.l, c.l)
  TerminateSession(a.l, b.l, c.l)
EndInterface

; IDirectPlay8ThreadPool interface definition
;
Interface IDirectPlay8ThreadPool
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Initialize(a.l, b.l, c.l)
  Close(a.l)
  GetThreadCount(a.l, b.l, c.l)
  SetThreadCount(a.l, b.l, c.l)
  DoWork(a.l, b.l)
EndInterface

; IDirectPlay8NATResolver interface definition
;
Interface IDirectPlay8NATResolver
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Initialize(a.l, b.l, c.l)
  Start(a.l, b.l, c.l)
  Close(a.l)
  EnumDevices(a.l, b.l, c.l, d.l)
  GetAddresses(a.l, b.l, c.l)
EndInterface
