
; ITuningSpaces interface definition
;
Interface ITuningSpaces
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Count(a.l)
  get__NewEnum(a.l)
  get_Item(a.p-variant, b.l)
  get_EnumTuningSpaces(a.l)
EndInterface

; ITuningSpaceContainer interface definition
;
Interface ITuningSpaceContainer
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Count(a.l)
  get__NewEnum(a.l)
  get_Item(a.p-variant, b.l)
  put_Item(a.p-variant, b.l)
  TuningSpacesForCLSID(a.p-bstr, b.l)
  _TuningSpacesForCLSID(a.l, b.l)
  TuningSpacesForName(a.p-bstr, b.l)
  FindID(a.l, b.l)
  Add(a.l, b.l)
  get_EnumTuningSpaces(a.l)
  Remove(a.p-variant)
  get_MaxCount(a.l)
  put_MaxCount(a.l)
EndInterface

; ITuningSpace interface definition
;
Interface ITuningSpace
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UniqueName(a.l)
  put_UniqueName(a.p-bstr)
  get_FriendlyName(a.l)
  put_FriendlyName(a.p-bstr)
  get_CLSID(a.l)
  get_NetworkType(a.l)
  put_NetworkType(a.p-bstr)
  get__NetworkType(a.l)
  put__NetworkType(a.l)
  CreateTuneRequest(a.l)
  EnumCategoryGUIDs(a.l)
  EnumDeviceMonikers(a.l)
  get_DefaultPreferredComponentTypes(a.l)
  put_DefaultPreferredComponentTypes(a.l)
  get_FrequencyMapping(a.l)
  put_FrequencyMapping(a.p-bstr)
  get_DefaultLocator(a.l)
  put_DefaultLocator(a.l)
  Clone(a.l)
EndInterface

; IEnumTuningSpaces interface definition
;
Interface IEnumTuningSpaces
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Next(a.l, b.l, c.l)
  Skip(a.l)
  Reset()
  Clone(a.l)
EndInterface

; IDVBTuningSpace interface definition
;
Interface IDVBTuningSpace
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UniqueName(a.l)
  put_UniqueName(a.p-bstr)
  get_FriendlyName(a.l)
  put_FriendlyName(a.p-bstr)
  get_CLSID(a.l)
  get_NetworkType(a.l)
  put_NetworkType(a.p-bstr)
  get__NetworkType(a.l)
  put__NetworkType(a.l)
  CreateTuneRequest(a.l)
  EnumCategoryGUIDs(a.l)
  EnumDeviceMonikers(a.l)
  get_DefaultPreferredComponentTypes(a.l)
  put_DefaultPreferredComponentTypes(a.l)
  get_FrequencyMapping(a.l)
  put_FrequencyMapping(a.p-bstr)
  get_DefaultLocator(a.l)
  put_DefaultLocator(a.l)
  Clone(a.l)
  get_SystemType(a.l)
  put_SystemType(a.l)
EndInterface

; IDVBTuningSpace2 interface definition
;
Interface IDVBTuningSpace2
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UniqueName(a.l)
  put_UniqueName(a.p-bstr)
  get_FriendlyName(a.l)
  put_FriendlyName(a.p-bstr)
  get_CLSID(a.l)
  get_NetworkType(a.l)
  put_NetworkType(a.p-bstr)
  get__NetworkType(a.l)
  put__NetworkType(a.l)
  CreateTuneRequest(a.l)
  EnumCategoryGUIDs(a.l)
  EnumDeviceMonikers(a.l)
  get_DefaultPreferredComponentTypes(a.l)
  put_DefaultPreferredComponentTypes(a.l)
  get_FrequencyMapping(a.l)
  put_FrequencyMapping(a.p-bstr)
  get_DefaultLocator(a.l)
  put_DefaultLocator(a.l)
  Clone(a.l)
  get_SystemType(a.l)
  put_SystemType(a.l)
  get_NetworkID(a.l)
  put_NetworkID(a.l)
EndInterface

; IDVBSTuningSpace interface definition
;
Interface IDVBSTuningSpace
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UniqueName(a.l)
  put_UniqueName(a.p-bstr)
  get_FriendlyName(a.l)
  put_FriendlyName(a.p-bstr)
  get_CLSID(a.l)
  get_NetworkType(a.l)
  put_NetworkType(a.p-bstr)
  get__NetworkType(a.l)
  put__NetworkType(a.l)
  CreateTuneRequest(a.l)
  EnumCategoryGUIDs(a.l)
  EnumDeviceMonikers(a.l)
  get_DefaultPreferredComponentTypes(a.l)
  put_DefaultPreferredComponentTypes(a.l)
  get_FrequencyMapping(a.l)
  put_FrequencyMapping(a.p-bstr)
  get_DefaultLocator(a.l)
  put_DefaultLocator(a.l)
  Clone(a.l)
  get_SystemType(a.l)
  put_SystemType(a.l)
  get_NetworkID(a.l)
  put_NetworkID(a.l)
  get_LowOscillator(a.l)
  put_LowOscillator(a.l)
  get_HighOscillator(a.l)
  put_HighOscillator(a.l)
  get_LNBSwitch(a.l)
  put_LNBSwitch(a.l)
  get_InputRange(a.l)
  put_InputRange(a.p-bstr)
  get_SpectralInversion(a.l)
  put_SpectralInversion(a.l)
EndInterface

; IAuxInTuningSpace interface definition
;
Interface IAuxInTuningSpace
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UniqueName(a.l)
  put_UniqueName(a.p-bstr)
  get_FriendlyName(a.l)
  put_FriendlyName(a.p-bstr)
  get_CLSID(a.l)
  get_NetworkType(a.l)
  put_NetworkType(a.p-bstr)
  get__NetworkType(a.l)
  put__NetworkType(a.l)
  CreateTuneRequest(a.l)
  EnumCategoryGUIDs(a.l)
  EnumDeviceMonikers(a.l)
  get_DefaultPreferredComponentTypes(a.l)
  put_DefaultPreferredComponentTypes(a.l)
  get_FrequencyMapping(a.l)
  put_FrequencyMapping(a.p-bstr)
  get_DefaultLocator(a.l)
  put_DefaultLocator(a.l)
  Clone(a.l)
EndInterface

; IAnalogTVTuningSpace interface definition
;
Interface IAnalogTVTuningSpace
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UniqueName(a.l)
  put_UniqueName(a.p-bstr)
  get_FriendlyName(a.l)
  put_FriendlyName(a.p-bstr)
  get_CLSID(a.l)
  get_NetworkType(a.l)
  put_NetworkType(a.p-bstr)
  get__NetworkType(a.l)
  put__NetworkType(a.l)
  CreateTuneRequest(a.l)
  EnumCategoryGUIDs(a.l)
  EnumDeviceMonikers(a.l)
  get_DefaultPreferredComponentTypes(a.l)
  put_DefaultPreferredComponentTypes(a.l)
  get_FrequencyMapping(a.l)
  put_FrequencyMapping(a.p-bstr)
  get_DefaultLocator(a.l)
  put_DefaultLocator(a.l)
  Clone(a.l)
  get_MinChannel(a.l)
  put_MinChannel(a.l)
  get_MaxChannel(a.l)
  put_MaxChannel(a.l)
  get_InputType(a.l)
  put_InputType(a.l)
  get_CountryCode(a.l)
  put_CountryCode(a.l)
EndInterface

; IATSCTuningSpace interface definition
;
Interface IATSCTuningSpace
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UniqueName(a.l)
  put_UniqueName(a.p-bstr)
  get_FriendlyName(a.l)
  put_FriendlyName(a.p-bstr)
  get_CLSID(a.l)
  get_NetworkType(a.l)
  put_NetworkType(a.p-bstr)
  get__NetworkType(a.l)
  put__NetworkType(a.l)
  CreateTuneRequest(a.l)
  EnumCategoryGUIDs(a.l)
  EnumDeviceMonikers(a.l)
  get_DefaultPreferredComponentTypes(a.l)
  put_DefaultPreferredComponentTypes(a.l)
  get_FrequencyMapping(a.l)
  put_FrequencyMapping(a.p-bstr)
  get_DefaultLocator(a.l)
  put_DefaultLocator(a.l)
  Clone(a.l)
  get_MinChannel(a.l)
  put_MinChannel(a.l)
  get_MaxChannel(a.l)
  put_MaxChannel(a.l)
  get_InputType(a.l)
  put_InputType(a.l)
  get_CountryCode(a.l)
  put_CountryCode(a.l)
  get_MinMinorChannel(a.l)
  put_MinMinorChannel(a.l)
  get_MaxMinorChannel(a.l)
  put_MaxMinorChannel(a.l)
  get_MinPhysicalChannel(a.l)
  put_MinPhysicalChannel(a.l)
  get_MaxPhysicalChannel(a.l)
  put_MaxPhysicalChannel(a.l)
EndInterface

; IAnalogRadioTuningSpace interface definition
;
Interface IAnalogRadioTuningSpace
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_UniqueName(a.l)
  put_UniqueName(a.p-bstr)
  get_FriendlyName(a.l)
  put_FriendlyName(a.p-bstr)
  get_CLSID(a.l)
  get_NetworkType(a.l)
  put_NetworkType(a.p-bstr)
  get__NetworkType(a.l)
  put__NetworkType(a.l)
  CreateTuneRequest(a.l)
  EnumCategoryGUIDs(a.l)
  EnumDeviceMonikers(a.l)
  get_DefaultPreferredComponentTypes(a.l)
  put_DefaultPreferredComponentTypes(a.l)
  get_FrequencyMapping(a.l)
  put_FrequencyMapping(a.p-bstr)
  get_DefaultLocator(a.l)
  put_DefaultLocator(a.l)
  Clone(a.l)
  get_MinFrequency(a.l)
  put_MinFrequency(a.l)
  get_MaxFrequency(a.l)
  put_MaxFrequency(a.l)
  get_Step(a.l)
  put_Step(a.l)
EndInterface

; ITuneRequest interface definition
;
Interface ITuneRequest
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_TuningSpace(a.l)
  get_Components(a.l)
  Clone(a.l)
  get_Locator(a.l)
  put_Locator(a.l)
EndInterface

; IChannelTuneRequest interface definition
;
Interface IChannelTuneRequest
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_TuningSpace(a.l)
  get_Components(a.l)
  Clone(a.l)
  get_Locator(a.l)
  put_Locator(a.l)
  get_Channel(a.l)
  put_Channel(a.l)
EndInterface

; IATSCChannelTuneRequest interface definition
;
Interface IATSCChannelTuneRequest
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_TuningSpace(a.l)
  get_Components(a.l)
  Clone(a.l)
  get_Locator(a.l)
  put_Locator(a.l)
  get_Channel(a.l)
  put_Channel(a.l)
  get_MinorChannel(a.l)
  put_MinorChannel(a.l)
EndInterface

; IDVBTuneRequest interface definition
;
Interface IDVBTuneRequest
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_TuningSpace(a.l)
  get_Components(a.l)
  Clone(a.l)
  get_Locator(a.l)
  put_Locator(a.l)
  get_ONID(a.l)
  put_ONID(a.l)
  get_TSID(a.l)
  put_TSID(a.l)
  get_SID(a.l)
  put_SID(a.l)
EndInterface

; IMPEG2TuneRequest interface definition
;
Interface IMPEG2TuneRequest
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_TuningSpace(a.l)
  get_Components(a.l)
  Clone(a.l)
  get_Locator(a.l)
  put_Locator(a.l)
  get_TSID(a.l)
  put_TSID(a.l)
  get_ProgNo(a.l)
  put_ProgNo(a.l)
EndInterface

; IMPEG2TuneRequestFactory interface definition
;
Interface IMPEG2TuneRequestFactory
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  CreateTuneRequest(a.l, b.l)
EndInterface

; IMPEG2TuneRequestSupport interface definition
;
Interface IMPEG2TuneRequestSupport
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
EndInterface

; ITuner interface definition
;
Interface ITuner
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  get_TuningSpace(a.l)
  put_TuningSpace(a.l)
  EnumTuningSpaces(a.l)
  get_TuneRequest(a.l)
  put_TuneRequest(a.l)
  Validate(a.l)
  get_PreferredComponentTypes(a.l)
  put_PreferredComponentTypes(a.l)
  get_SignalStrength(a.l)
  TriggerSignalEvents(a.l)
EndInterface

; IScanningTuner interface definition
;
Interface IScanningTuner
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  get_TuningSpace(a.l)
  put_TuningSpace(a.l)
  EnumTuningSpaces(a.l)
  get_TuneRequest(a.l)
  put_TuneRequest(a.l)
  Validate(a.l)
  get_PreferredComponentTypes(a.l)
  put_PreferredComponentTypes(a.l)
  get_SignalStrength(a.l)
  TriggerSignalEvents(a.l)
  SeekUp()
  SeekDown()
  ScanUp(a.l)
  ScanDown(a.l)
  AutoProgram()
EndInterface

; IComponentType interface definition
;
Interface IComponentType
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Category(a.l)
  put_Category(a.l)
  get_MediaMajorType(a.l)
  put_MediaMajorType(a.p-bstr)
  get__MediaMajorType(a.l)
  put__MediaMajorType(a.l)
  get_MediaSubType(a.l)
  put_MediaSubType(a.p-bstr)
  get__MediaSubType(a.l)
  put__MediaSubType(a.l)
  get_MediaFormatType(a.l)
  put_MediaFormatType(a.p-bstr)
  get__MediaFormatType(a.l)
  put__MediaFormatType(a.l)
  get_MediaType(a.l)
  put_MediaType(a.l)
  Clone(a.l)
EndInterface

; ILanguageComponentType interface definition
;
Interface ILanguageComponentType
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Category(a.l)
  put_Category(a.l)
  get_MediaMajorType(a.l)
  put_MediaMajorType(a.p-bstr)
  get__MediaMajorType(a.l)
  put__MediaMajorType(a.l)
  get_MediaSubType(a.l)
  put_MediaSubType(a.p-bstr)
  get__MediaSubType(a.l)
  put__MediaSubType(a.l)
  get_MediaFormatType(a.l)
  put_MediaFormatType(a.p-bstr)
  get__MediaFormatType(a.l)
  put__MediaFormatType(a.l)
  get_MediaType(a.l)
  put_MediaType(a.l)
  Clone(a.l)
  get_LangID(a.l)
  put_LangID(a.l)
EndInterface

; IMPEG2ComponentType interface definition
;
Interface IMPEG2ComponentType
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Category(a.l)
  put_Category(a.l)
  get_MediaMajorType(a.l)
  put_MediaMajorType(a.p-bstr)
  get__MediaMajorType(a.l)
  put__MediaMajorType(a.l)
  get_MediaSubType(a.l)
  put_MediaSubType(a.p-bstr)
  get__MediaSubType(a.l)
  put__MediaSubType(a.l)
  get_MediaFormatType(a.l)
  put_MediaFormatType(a.p-bstr)
  get__MediaFormatType(a.l)
  put__MediaFormatType(a.l)
  get_MediaType(a.l)
  put_MediaType(a.l)
  Clone(a.l)
  get_LangID(a.l)
  put_LangID(a.l)
  get_StreamType(a.l)
  put_StreamType(a.l)
EndInterface

; IATSCComponentType interface definition
;
Interface IATSCComponentType
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Category(a.l)
  put_Category(a.l)
  get_MediaMajorType(a.l)
  put_MediaMajorType(a.p-bstr)
  get__MediaMajorType(a.l)
  put__MediaMajorType(a.l)
  get_MediaSubType(a.l)
  put_MediaSubType(a.p-bstr)
  get__MediaSubType(a.l)
  put__MediaSubType(a.l)
  get_MediaFormatType(a.l)
  put_MediaFormatType(a.p-bstr)
  get__MediaFormatType(a.l)
  put__MediaFormatType(a.l)
  get_MediaType(a.l)
  put_MediaType(a.l)
  Clone(a.l)
  get_LangID(a.l)
  put_LangID(a.l)
  get_StreamType(a.l)
  put_StreamType(a.l)
  get_Flags(a.l)
  put_Flags(a.l)
EndInterface

; IEnumComponentTypes interface definition
;
Interface IEnumComponentTypes
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Next(a.l, b.l, c.l)
  Skip(a.l)
  Reset()
  Clone(a.l)
EndInterface

; IComponentTypes interface definition
;
Interface IComponentTypes
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Count(a.l)
  get__NewEnum(a.l)
  EnumComponentTypes(a.l)
  get_Item(a.p-variant, b.l)
  put_Item(a.p-variant, b.l)
  Add(a.l, b.l)
  Remove(a.p-variant)
  Clone(a.l)
EndInterface

; IComponent interface definition
;
Interface IComponent
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Type(a.l)
  put_Type(a.l)
  get_DescLangID(a.l)
  put_DescLangID(a.l)
  get_Status(a.l)
  put_Status(a.l)
  get_Description(a.l)
  put_Description(a.p-bstr)
  Clone(a.l)
EndInterface

; IMPEG2Component interface definition
;
Interface IMPEG2Component
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Type(a.l)
  put_Type(a.l)
  get_DescLangID(a.l)
  put_DescLangID(a.l)
  get_Status(a.l)
  put_Status(a.l)
  get_Description(a.l)
  put_Description(a.p-bstr)
  Clone(a.l)
  get_PID(a.l)
  put_PID(a.l)
  get_PCRPID(a.l)
  put_PCRPID(a.l)
  get_ProgramNumber(a.l)
  put_ProgramNumber(a.l)
EndInterface

; IEnumComponents interface definition
;
Interface IEnumComponents
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Next(a.l, b.l, c.l)
  Skip(a.l)
  Reset()
  Clone(a.l)
EndInterface

; IComponents interface definition
;
Interface IComponents
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_Count(a.l)
  get__NewEnum(a.l)
  EnumComponents(a.l)
  get_Item(a.p-variant, b.l)
  Add(a.l, b.l)
  Remove(a.p-variant)
  Clone(a.l)
EndInterface

; ILocator interface definition
;
Interface ILocator
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_CarrierFrequency(a.l)
  put_CarrierFrequency(a.l)
  get_InnerFEC(a.l)
  put_InnerFEC(a.l)
  get_InnerFECRate(a.l)
  put_InnerFECRate(a.l)
  get_OuterFEC(a.l)
  put_OuterFEC(a.l)
  get_OuterFECRate(a.l)
  put_OuterFECRate(a.l)
  get_Modulation(a.l)
  put_Modulation(a.l)
  get_SymbolRate(a.l)
  put_SymbolRate(a.l)
  Clone(a.l)
EndInterface

; IATSCLocator interface definition
;
Interface IATSCLocator
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_CarrierFrequency(a.l)
  put_CarrierFrequency(a.l)
  get_InnerFEC(a.l)
  put_InnerFEC(a.l)
  get_InnerFECRate(a.l)
  put_InnerFECRate(a.l)
  get_OuterFEC(a.l)
  put_OuterFEC(a.l)
  get_OuterFECRate(a.l)
  put_OuterFECRate(a.l)
  get_Modulation(a.l)
  put_Modulation(a.l)
  get_SymbolRate(a.l)
  put_SymbolRate(a.l)
  Clone(a.l)
  get_PhysicalChannel(a.l)
  put_PhysicalChannel(a.l)
  get_TSID(a.l)
  put_TSID(a.l)
EndInterface

; IDVBTLocator interface definition
;
Interface IDVBTLocator
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_CarrierFrequency(a.l)
  put_CarrierFrequency(a.l)
  get_InnerFEC(a.l)
  put_InnerFEC(a.l)
  get_InnerFECRate(a.l)
  put_InnerFECRate(a.l)
  get_OuterFEC(a.l)
  put_OuterFEC(a.l)
  get_OuterFECRate(a.l)
  put_OuterFECRate(a.l)
  get_Modulation(a.l)
  put_Modulation(a.l)
  get_SymbolRate(a.l)
  put_SymbolRate(a.l)
  Clone(a.l)
  get_Bandwidth(a.l)
  put_Bandwidth(a.l)
  get_LPInnerFEC(a.l)
  put_LPInnerFEC(a.l)
  get_LPInnerFECRate(a.l)
  put_LPInnerFECRate(a.l)
  get_HAlpha(a.l)
  put_HAlpha(a.l)
  get_Guard(a.l)
  put_Guard(a.l)
  get_Mode(a.l)
  put_Mode(a.l)
  get_OtherFrequencyInUse(a.l)
  put_OtherFrequencyInUse(a.l)
EndInterface

; IDVBSLocator interface definition
;
Interface IDVBSLocator
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_CarrierFrequency(a.l)
  put_CarrierFrequency(a.l)
  get_InnerFEC(a.l)
  put_InnerFEC(a.l)
  get_InnerFECRate(a.l)
  put_InnerFECRate(a.l)
  get_OuterFEC(a.l)
  put_OuterFEC(a.l)
  get_OuterFECRate(a.l)
  put_OuterFECRate(a.l)
  get_Modulation(a.l)
  put_Modulation(a.l)
  get_SymbolRate(a.l)
  put_SymbolRate(a.l)
  Clone(a.l)
  get_SignalPolarisation(a.l)
  put_SignalPolarisation(a.l)
  get_WestPosition(a.l)
  put_WestPosition(a.l)
  get_OrbitalPosition(a.l)
  put_OrbitalPosition(a.l)
  get_Azimuth(a.l)
  put_Azimuth(a.l)
  get_Elevation(a.l)
  put_Elevation(a.l)
EndInterface

; IDVBCLocator interface definition
;
Interface IDVBCLocator
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  GetTypeInfoCount(a.l)
  GetTypeInfo(a.l, b.l, c.l)
  GetIDsOfNames(a.l, b.l, c.l, d.l, e.l)
  Invoke(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l)
  get_CarrierFrequency(a.l)
  put_CarrierFrequency(a.l)
  get_InnerFEC(a.l)
  put_InnerFEC(a.l)
  get_InnerFECRate(a.l)
  put_InnerFECRate(a.l)
  get_OuterFEC(a.l)
  put_OuterFEC(a.l)
  get_OuterFECRate(a.l)
  put_OuterFECRate(a.l)
  get_Modulation(a.l)
  put_Modulation(a.l)
  get_SymbolRate(a.l)
  put_SymbolRate(a.l)
  Clone(a.l)
EndInterface

; IBroadcastEvent interface definition
;
Interface IBroadcastEvent
  QueryInterface(a.l, b.l)
  AddRef()
  Release()
  Fire(a.l)
EndInterface
