#
# Makefile for all included targets
# 

doc:
	"$(PUREBASIC_HOME)/SDK/DocMaker/DocMaker.exe" /LANGUAGE French /DOCUMENTATIONPATH .. /OUTPUTPATH "$(PB_SVN)/Build/Documentation"
	explorer "$(PB_SVN)\Build\Documentation"

console:
	pbdocmakerconsole /LANGUAGE French /DOCUMENTATIONPATH .. /OUTPUTPATH "$(PB_SVN)/Build/Documentation"

