XIncludeFile "common.pbi"

Import "atl.lib"
       Api(AtlAdvise, (arg1, arg2, arg3, arg4), 16)
       Api(AtlAxAttachControl, (arg1, arg2, arg3), 12)
       Api(AtlAxCreateControl, (arg1, arg2, arg3, arg4), 16)
       Api(AtlAxCreateControlEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(AtlAxCreateDialog, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(AtlAxDialogBox, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(AtlAxGetControl, (arg1, arg2), 8)
       Api(AtlAxGetHost, (arg1, arg2), 8)
       Api(AtlAxWinInit, (), 0)
       Api(AtlComPtrAssign, (arg1, arg2), 8)
       Api(AtlComQIPtrAssign, (arg1, arg2, arg3), 12)
       Api(AtlCreateTargetDC, (arg1, arg2), 8)
  AnsiWide(AtlDevModeW2, (arg1, arg2), 8)
       Api(AtlFreeMarshalStream, (arg1), 4)
       Api(AtlGetObjectSourceInterface, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(AtlGetVersion, (arg1), 4)
       Api(AtlHiMetricToPixel, (arg1, arg2), 8)
       Api(AtlInternalQueryInterface, (arg1, arg2, arg3, arg4), 16)
       Api(AtlIPersistPropertyBag_Load, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(AtlIPersistPropertyBag_Save, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(AtlIPersistStreamInit_Load, (arg1, arg2, arg3, arg4), 16)
       Api(AtlIPersistStreamInit_Save, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(AtlMarshalPtrInProc, (arg1, arg2, arg3), 12)
       Api(AtlModuleAddCreateWndData, (arg1, arg2, arg3), 12)
       Api(AtlModuleAddTermFunc, (arg1, arg2, arg3), 12)
       Api(AtlModuleExtractCreateWndData, (arg1), 4)
       Api(AtlModuleGetClassObject, (arg1, arg2, arg3, arg4), 16)
       Api(AtlModuleInit, (arg1, arg2, arg3), 12)
       Api(AtlModuleLoadTypeLib, (arg1, arg2, arg3, arg4), 16)
       Api(AtlModuleRegisterClassObjects, (arg1, arg2, arg3), 12)
       Api(AtlModuleRegisterServer, (arg1, arg2, arg3), 12)
       Api(AtlModuleRegisterTypeLib, (arg1, arg2), 8)
  AnsiWide(AtlModuleRegisterWndClassInfo, (arg1, arg2, arg3), 12)
       Api(AtlModuleRevokeClassObjects, (arg1), 4)
       Api(AtlModuleTerm, (arg1), 4)
       Api(AtlModuleUnregisterServer, (arg1, arg2), 8)
       Api(AtlModuleUnregisterServerEx, (arg1, arg2, arg3), 12)
       Api(AtlModuleUnRegisterTypeLib, (arg1, arg2), 8)
       Api(AtlModuleUpdateRegistryFromResourceD, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(AtlPixelToHiMetric, (arg1, arg2), 8)
       Api(AtlRegisterClassCategoriesHelper, (arg1, arg2, arg3), 12)
       Api(AtlSetErrorInfo, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(AtlUnadvise, (arg1, arg2, arg3), 12)
       Api(AtlUnmarshalPtr, (arg1, arg2, arg3), 12)
       Api(AtlWaitWithMessageLoop, (arg1), 4)
EndImport
