XIncludeFile "common.pbi"

Import "comctl32.lib"
       Api(_TrackMouseEvent, (arg1), 4)
       Api(CreateMappedBitmap, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(CreatePropertySheetPage, (arg1), 4)
  AnsiWide(CreateStatusWindow, (arg1, arg2, arg3, arg4), 16)
       Api(CreateToolbar, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(CreateToolbarEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13), 52)
       Api(CreateUpDownControl, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(DestroyPropertySheetPage, (arg1), 4)
       Api(DrawInsert, (arg1, arg2, arg3), 12)
  AnsiWide(DrawStatusText, (arg1, arg2, arg3, arg4), 16)
       Api(FlatSB_EnableScrollBar, (arg1, arg2, arg3), 12)
       Api(FlatSB_GetScrollInfo, (arg1, arg2, arg3), 12)
       Api(FlatSB_GetScrollPos, (arg1, arg2), 8)
       Api(FlatSB_GetScrollProp, (arg1, arg2, arg3), 12)
       Api(FlatSB_GetScrollRange, (arg1, arg2, arg3, arg4), 16)
       Api(FlatSB_SetScrollInfo, (arg1, arg2, arg3, arg4), 16)
       Api(FlatSB_SetScrollPos, (arg1, arg2, arg3, arg4), 16)
       Api(FlatSB_SetScrollProp, (arg1, arg2, arg3, arg4), 16)
       Api(FlatSB_SetScrollRange, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(FlatSB_ShowScrollBar, (arg1, arg2, arg3), 12)
       Api(GetEffectiveClientRect, (arg1, arg2, arg3), 12)
       Api(ImageList_Add, (arg1, arg2, arg3), 12)
       Api(ImageList_AddIcon, (arg1, arg2), 8)
       Api(ImageList_AddMasked, (arg1, arg2, arg3), 12)
       Api(ImageList_BeginDrag, (arg1, arg2, arg3, arg4), 16)
       Api(ImageList_Copy, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ImageList_Create, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ImageList_Destroy, (arg1), 4)
       Api(ImageList_DragEnter, (arg1, arg2, arg3), 12)
       Api(ImageList_DragLeave, (arg1), 4)
       Api(ImageList_DragMove, (arg1, arg2), 8)
       Api(ImageList_DragShowNolock, (arg1), 4)
       Api(ImageList_Draw, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ImageList_DrawEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(ImageList_DrawIndirect, (arg1), 4)
       Api(ImageList_Duplicate, (arg1), 4)
       Api(ImageList_EndDrag, (), 0)
       Api(ImageList_GetBkColor, (arg1), 4)
       Api(ImageList_GetDragImage, (arg1, arg2), 8)
       Api(ImageList_GetIcon, (arg1, arg2, arg3), 12)
       Api(ImageList_GetIconSize, (arg1, arg2, arg3), 12)
       Api(ImageList_GetImageCount, (arg1), 4)
       Api(ImageList_GetImageInfo, (arg1, arg2, arg3), 12)
       Api(ImageList_GetImageRect, (arg1, arg2, arg3), 12)
  AnsiWide(ImageList_LoadImage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ImageList_Merge, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ImageList_Read, (arg1), 4)
       Api(ImageList_Remove, (arg1, arg2), 8)
       Api(ImageList_Replace, (arg1, arg2, arg3, arg4), 16)
       Api(ImageList_ReplaceIcon, (arg1, arg2, arg3), 12)
       Api(ImageList_SetBkColor, (arg1, arg2), 8)
       Api(ImageList_SetDragCursorImage, (arg1, arg2, arg3, arg4), 16)
       Api(ImageList_SetFilter, (arg1, arg2, arg3), 12)
       Api(ImageList_SetIconSize, (arg1, arg2, arg3), 12)
       Api(ImageList_SetImageCount, (arg1, arg2), 8)
       Api(ImageList_SetOverlayImage, (arg1, arg2, arg3), 12)
       Api(ImageList_Write, (arg1, arg2), 8)
       Api(InitCommonControls, (), 0)
       Api(InitCommonControlsEx, (arg1), 4)
       Api(InitializeFlatSB, (arg1), 4)
       Api(LBItemFromPt, (arg1, arg2.q, arg3), 16)
       Api(MakeDragList, (arg1), 4)
       Api(MenuHelp, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(PropertySheet, (arg1), 4)
       Api(ShowHideMenuCtl, (arg1, arg2, arg3), 12)
       Api(UninitializeFlatSB, (arg1), 4)
EndImport
