XIncludeFile "common.pbi"

Import "comdlg32.lib"
       Api(ArrowBtnWndProc, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(ChooseColor, (arg1), 4)
  AnsiWide(ChooseFont, (arg1), 4)
       Api(ColorDlgProc, (arg1, arg2, arg3, arg4), 16)
       Api(CommDlgExtendedError, (), 0)
       Api(dwLBSubclass, (arg1, arg2, arg3, arg4), 16)
       Api(dwOKSubclass, (arg1, arg2, arg3, arg4), 16)
       Api(EditIntegerOnly, (arg1, arg2, arg3, arg4), 16)
       Api(FileOpenDlgProc, (arg1, arg2, arg3, arg4), 16)
       Api(FileSaveDlgProc, (arg1, arg2, arg3, arg4), 16)
       Api(FindReplaceDlgProc, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(FindText, (arg1), 4)
       Api(FontFamilyEnumProc, (arg1, arg2, arg3, arg4), 16)
       Api(FontStyleEnumProc, (arg1, arg2, arg3, arg4), 16)
       Api(FormatCharDlgProc, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetFileTitle, (arg1, arg2, arg3), 12)
  AnsiWide(GetOpenFileName, (arg1), 4)
  AnsiWide(GetSaveFileName, (arg1), 4)
       Api(LoadAlterBitmap, (arg1, arg2, arg3), 12)
  AnsiWide(PageSetupDlg, (arg1), 4)
  AnsiWide(PrintDlg, (arg1), 4)
       Api(PrintDlgProc, (arg1, arg2, arg3, arg4), 16)
       Api(PrintSetupDlgProc, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(ReplaceText, (arg1), 4)
       Api(WantArrows, (arg1, arg2, arg3, arg4), 16)
EndImport
