XIncludeFile "common.pbi"

Import "crypt32.lib"
       Api(CertAddCertificateContextToStore, (arg1, arg2, arg3, arg4), 16)
       Api(CertAddCRLContextToStore, (arg1, arg2, arg3, arg4), 16)
       Api(CertAddCTLContextToStore, (arg1, arg2, arg3, arg4), 16)
       Api(CertAddEncodedCertificateToStore, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(CertAddEncodedCertificateToSystemStore, (arg1, arg2, arg3), 12)
       Api(CertAddEncodedCRLToStore, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CertAddEncodedCTLToStore, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CertAddEnhancedKeyUsageIdentifier, (arg1, arg2), 8)
       Api(CertAddSerializedElementToStore, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(CertAlgIdToOID, (arg1), 4)
       Api(CertCloseStore, (arg1, arg2), 8)
       Api(CertCompareCertificate, (arg1, arg2, arg3), 12)
       Api(CertCompareCertificateName, (arg1, arg2, arg3), 12)
       Api(CertCompareIntegerBlob, (arg1, arg2), 8)
       Api(CertComparePublicKeyInfo, (arg1, arg2, arg3), 12)
       Api(CertCreateCertificateContext, (arg1, arg2, arg3), 12)
       Api(CertCreateCRLContext, (arg1, arg2, arg3), 12)
       Api(CertCreateCTLContext, (arg1, arg2, arg3), 12)
       Api(CertDeleteCertificateFromStore, (arg1), 4)
       Api(CertDeleteCRLFromStore, (arg1), 4)
       Api(CertDeleteCTLFromStore, (arg1), 4)
       Api(CertDuplicateCertificateContext, (arg1), 4)
       Api(CertDuplicateCRLContext, (arg1), 4)
       Api(CertDuplicateCTLContext, (arg1), 4)
       Api(CertDuplicateStore, (arg1), 4)
       Api(CertEnumCertificateContextProperties, (arg1, arg2), 8)
       Api(CertEnumCertificatesInStore, (arg1, arg2), 8)
       Api(CertEnumCRLContextProperties, (arg1, arg2), 8)
       Api(CertEnumCTLContextProperties, (arg1, arg2), 8)
       Api(CertEnumCTLsInStore, (arg1, arg2), 8)
       Api(CertFindAttribute, (arg1, arg2, arg3), 12)
       Api(CertFindCertificateInStore, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CertFindCTLInStore, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CertFindExtension, (arg1, arg2, arg3), 12)
       Api(CertFindRDNAttr, (arg1, arg2), 8)
       Api(CertFindSubjectInCTL, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CertFreeCertificateContext, (arg1), 4)
       Api(CertFreeCRLContext, (arg1), 4)
       Api(CertFreeCTLContext, (arg1), 4)
       Api(CertGetCertificateContextProperty, (arg1, arg2, arg3, arg4), 16)
       Api(CertGetCRLContextProperty, (arg1, arg2, arg3, arg4), 16)
       Api(CertGetCRLFromStore, (arg1, arg2, arg3, arg4), 16)
       Api(CertGetCTLContextProperty, (arg1, arg2, arg3, arg4), 16)
       Api(CertGetEnhancedKeyUsage, (arg1, arg2, arg3, arg4), 16)
       Api(CertGetIntendedKeyUsage, (arg1, arg2, arg3, arg4), 16)
       Api(CertGetIssuerCertificateFromStore, (arg1, arg2, arg3, arg4), 16)
       Api(CertGetSubjectCertificateFromStore, (arg1, arg2, arg3), 12)
       Api(CertIsRDNAttrsInCertificateName, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(CertNameToStr, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CertOIDToAlgId, (arg1), 4)
       Api(CertOpenStore, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(CertOpenSystemStore, (arg1, arg2), 8)
  AnsiWide(CertRDNValueToStr, (arg1, arg2, arg3, arg4), 16)
       Api(CertRemoveEnhancedKeyUsageIdentifier, (arg1, arg2), 8)
       Api(CertSaveStore, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CertSerializeCertificateStoreElement, (arg1, arg2, arg3, arg4), 16)
       Api(CertSerializeCRLStoreElement, (arg1, arg2, arg3, arg4), 16)
       Api(CertSerializeCTLStoreElement, (arg1, arg2, arg3, arg4), 16)
       Api(CertSetCertificateContextProperty, (arg1, arg2, arg3, arg4), 16)
       Api(CertSetCRLContextProperty, (arg1, arg2, arg3, arg4), 16)
       Api(CertSetCTLContextProperty, (arg1, arg2, arg3, arg4), 16)
       Api(CertSetEnhancedKeyUsage, (arg1, arg2), 8)
  AnsiWide(CertStrToName, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CertVerifyCRLRevocation, (arg1, arg2, arg3, arg4), 16)
       Api(CertVerifyCRLTimeValidity, (arg1, arg2), 8)
       Api(CertVerifyCTLUsage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CertVerifyRevocation, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CertVerifySubjectCertificateContext, (arg1, arg2, arg3), 12)
       Api(CertVerifyTimeValidity, (arg1, arg2), 8)
       Api(CertVerifyValidityNesting, (arg1, arg2), 8)
       Api(CreateFileU, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptAcquireContextU, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CryptAllocTls, (), 0)
       Api(CryptDecodeMessage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13), 52)
       Api(CryptDecodeObject, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptDecryptAndVerifyMessageSignature, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(CryptDecryptMessage, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptDetachTls, (arg1), 4)
       Api(CryptEncodeObject, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CryptEncryptMessage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptEnumOIDFunction, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptExportPublicKeyInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CryptExportPublicKeyInfoEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(CryptFormatObject, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(CryptFreeOIDFunctionAddress, (arg1, arg2), 8)
       Api(CryptGetDefaultOIDDllList, (arg1, arg2, arg3, arg4), 16)
       Api(CryptGetDefaultOIDFunctionAddress, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptGetMessageCertificates, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CryptGetMessageSignerCount, (arg1, arg2, arg3), 12)
       Api(CryptGetOIDFunctionAddress, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptGetOIDFunctionValue, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptGetOssGlobal, (arg1), 4)
       Api(CryptGetTls, (arg1), 4)
       Api(CryptHashCertificate, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptHashMessage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(CryptHashPublicKeyInfo, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptHashToBeSigned, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptImportPublicKeyInfo, (arg1, arg2, arg3, arg4), 16)
       Api(CryptImportPublicKeyInfoEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptInitOIDFunctionSet, (arg1, arg2), 8)
       Api(CryptInstallOIDFunctionAddress, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptInstallOssGlobal, (arg1, arg2, arg3), 12)
       Api(CryptLoadSip, (arg1, arg2, arg3), 12)
       Api(CryptMsgCalculateEncodedLength, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptMsgClose, (arg1), 4)
       Api(CryptMsgControl, (arg1, arg2, arg3, arg4), 16)
       Api(CryptMsgCountersign, (arg1, arg2, arg3, arg4), 16)
       Api(CryptMsgCountersignEncoded, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptMsgEncodeAndSignCTL, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptMsgGetAndVerifySigner, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptMsgGetParam, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CryptMsgOpenToDecode, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptMsgOpenToEncode, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptMsgSignCTL, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptMsgUpdate, (arg1, arg2, arg3, arg4), 16)
       Api(CryptMsgVerifyCountersignatureEncoded, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptRegisterDefaultOIDFunction, (arg1, arg2, arg3, arg4), 16)
       Api(CryptRegisterOIDFunction, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CryptSetOIDFunctionValue, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptSetProviderU, (arg1, arg2), 8)
       Api(CryptSetTls, (arg1, arg2), 8)
       Api(CryptSignAndEncodeCertificate, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(CryptSignAndEncryptMessage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(CryptSignCertificate, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(CryptSignHashU, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptSignMessage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptSignMessageWithKey, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CryptSIPRetrieveSubjectGuid, (arg1, arg2, arg3), 12)
       Api(CryptUnregisterDefaultOIDFunction, (arg1, arg2, arg3), 12)
       Api(CryptUnregisterOIDFunction, (arg1, arg2, arg3), 12)
       Api(CryptVerifyCertificateSignature, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CryptVerifyDetachedMessageHash, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(CryptVerifyDetachedMessageSignature, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(CryptVerifyMessageHash, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptVerifyMessageSignature, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CryptVerifyMessageSignatureWithKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CryptVerifySignatureU, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RegCreateKeyExU, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(RegDeleteValueU, (arg1, arg2), 8)
       Api(RegEnumValueU, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(RegQueryInfoKeyU, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(RegQueryValueExU, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RegSetValueExU, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
EndImport
