XIncludeFile "common.pbi"

Import "ctl3d32.lib"
       Api(BtnWndProc3d, (arg1, arg2, arg3, arg4), 16)
       Api(ComboWndProc3d, (arg1, arg2, arg3, arg4), 16)
       Api(Ctl3dAutoSubclass, (arg1), 4)
       Api(Ctl3dAutoSubclassEx, (arg1, arg2), 8)
       Api(Ctl3dColorChange, (), 0)
       Api(Ctl3dCtlColor, (arg1, arg2), 8)
       Api(Ctl3dCtlColorEx, (arg1, arg2, arg3), 12)
       Api(Ctl3dDlgFramePaint, (arg1, arg2, arg3, arg4), 16)
       Api(Ctl3dDlgProc, (arg1, arg2, arg3, arg4), 16)
       Api(Ctl3dEnabled, (), 0)
       Api(Ctl3dGetVer, (), 0)
       Api(Ctl3dIsAutoSubclass, (), 0)
       Api(Ctl3dRegister, (arg1), 4)
       Api(Ctl3dSetStyle, (arg1, arg2, arg3), 12)
       Api(Ctl3dSubclassCtl, (arg1), 4)
       Api(Ctl3dSubclassCtlEx, (arg1, arg2), 8)
       Api(Ctl3dSubclassDlg, (arg1, arg2), 8)
       Api(Ctl3dSubclassDlgEx, (arg1, arg2), 8)
       Api(Ctl3dUnAutoSubclass, (), 0)
       Api(Ctl3dUnregister, (arg1), 4)
       Api(Ctl3dUnsubclassCtl, (arg1), 4)
       Api(Ctl3dWinIniChange, (), 0)
       Api(EditWndProc3d, (arg1, arg2, arg3, arg4), 16)
       Api(ListWndProc3d, (arg1, arg2, arg3, arg4), 16)
       Api(StaticWndProc3d, (arg1, arg2, arg3, arg4), 16)
EndImport
