XIncludeFile "common.pbi"

Import "gdi32.lib"
       Api(AbortDoc, (arg1), 4)
       Api(AbortPath, (arg1), 4)
       Api(AddFontMemResourceEx, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(AddFontResource, (*lpszFilename), 4)
       Api(AngleArc, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(AnimatePalette, (arg1, arg2, arg3, arg4), 16)
       Api(Arc, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(ArcTo, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(BeginPath, (arg1), 4)
       Api(BitBlt, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(CancelDC, (arg1), 4)
       Api(CheckColorsInGamut, (arg1, arg2, arg3, arg4), 16)
       Api(ChoosePixelFormat, (arg1, arg2), 8)
       Api(Chord, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(CloseEnhMetaFile, (arg1), 4)
       Api(CloseFigure, (arg1), 4)
       Api(CloseMetaFile, (arg1), 4)
       Api(ColorMatchToTarget, (arg1, arg2, arg3), 12)
       Api(CombineRgn, (arg1, arg2, arg3, arg4), 16)
       Api(CombineTransform, (arg1, arg2, arg3), 12)
  AnsiWide(CopyEnhMetaFile, (arg1, arg2), 8)
  AnsiWide(CopyMetaFile, (arg1, arg2), 8)
       Api(CreateBitmap, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CreateBitmapIndirect, (arg1), 4)
       Api(CreateBrushIndirect, (arg1), 4)
  AnsiWide(CreateColorSpace, (arg1), 4)
       Api(CreateCompatibleBitmap, (arg1, arg2, arg3), 12)
       Api(CreateCompatibleDC, (arg1), 4)
  AnsiWide(CreateDC, (*lpszDriver, *lpszDevice, lpszOutput, *lpInitData), 16)
       Api(CreateDIBitmap, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CreateDIBPatternBrush, (arg1, arg2), 8)
       Api(CreateDIBPatternBrushPt, (arg1, arg2), 8)
       Api(CreateDIBSection, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CreateDiscardableBitmap, (arg1, arg2, arg3), 12)
       Api(CreateEllipticRgn, (arg1, arg2, arg3, arg4), 16)
       Api(CreateEllipticRgnIndirect, (arg1), 4)
  AnsiWide(CreateEnhMetaFile, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(CreateFont, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14), 56)
  AnsiWide(CreateFontIndirect, (arg1), 4)
       Api(CreateHalftonePalette, (arg1), 4)
       Api(CreateHatchBrush, (arg1, arg2), 8)
  AnsiWide(CreateIC, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(CreateMetaFile, (arg1), 4)
       Api(CreatePalette, (arg1), 4)
       Api(CreatePatternBrush, (arg1), 4)
       Api(CreatePen, (arg1, arg2, arg3), 12)
       Api(CreatePenIndirect, (arg1), 4)
       Api(CreatePolygonRgn, (arg1, arg2, arg3), 12)
       Api(CreatePolyPolygonRgn, (arg1, arg2, arg3, arg4), 16)
       Api(CreateRectRgn, (arg1, arg2, arg3, arg4), 16)
       Api(CreateRectRgnIndirect, (arg1), 4)
       Api(CreateRoundRectRgn, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(CreateScalableFontResource, (arg1, arg2, arg3, arg4), 16)
       Api(CreateSolidBrush, (arg1), 4)
       Api(DeleteColorSpace, (arg1), 4)
       Api(DeleteDC, (arg1), 4)
       Api(DeleteEnhMetaFile, (arg1), 4)
       Api(DeleteMetaFile, (arg1), 4)
       Api(DeleteObject, (arg1), 4)
       Api(DescribePixelFormat, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(DeviceCapabilitiesEx, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(DPtoLP, (arg1, arg2, arg3), 12)
       Api(DrawEscape, (arg1, arg2, arg3, arg4), 16)
       Api(Ellipse, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(EndDoc, (arg1), 4)
       Api(EndPage, (arg1), 4)
       Api(EndPath, (arg1), 4)
       Api(EnumEnhMetaFile, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(EnumFontFamilies, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(EnumFontFamiliesEx, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(EnumFonts, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(EnumICMProfiles, (arg1, arg2, arg3), 12)
       Api(EnumMetaFile, (arg1, arg2, arg3, arg4), 16)
       Api(EnumObjects, (arg1, arg2, arg3, arg4), 16)
       Api(EqualRgn, (arg1, arg2), 8)
       Api(Escape, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ExcludeClipRect, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ExtCreatePen, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ExtCreateRegion, (arg1, arg2, arg3), 12)
       Api(ExtEscape, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ExtFloodFill, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ExtSelectClipRgn, (arg1, arg2, arg3), 12)
  AnsiWide(ExtTextOut, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(FillPath, (arg1), 4)
       Api(FillRgn, (arg1, arg2, arg3), 12)
       Api(FixBrushOrgEx, (arg1, arg2, arg3, arg4), 16)
       Api(FlattenPath, (arg1), 4)
       Api(FloodFill, (arg1, arg2, arg3, arg4), 16)
       Api(FrameRgn, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GdiComment, (arg1, arg2, arg3), 12)
       Api(GdiFlush, (), 0)
       Api(GdiGetBatchLimit, (), 0)
       Api(GdiPlayDCScript, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GdiPlayJournal, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GdiPlayScript, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(GdiSetBatchLimit, (arg1), 4)
       Api(GetArcDirection, (arg1), 4)
       Api(GetAspectRatioFilterEx, (arg1, arg2), 8)
       Api(GetBitmapBits, (arg1, arg2, arg3), 12)
       Api(GetBitmapDimensionEx, (arg1, arg2), 8)
       Api(GetBkColor, (arg1), 4)
       Api(GetBkMode, (arg1), 4)
       Api(GetBoundsRect, (arg1, arg2, arg3), 12)
       Api(GetBrushOrgEx, (arg1, arg2), 8)
  AnsiWide(GetCharABCWidths, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetCharABCWidthsFloat, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetCharacterPlacement, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GetCharWidth, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetCharWidth32, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetCharWidthFloat, (arg1, arg2, arg3, arg4), 16)
       Api(GetClipBox, (arg1, arg2), 8)
       Api(GetClipRgn, (arg1, arg2), 8)
       Api(GetColorAdjustment, (arg1, arg2), 8)
       Api(GetColorSpace, (arg1), 4)
       Api(GetCurrentObject, (arg1, arg2), 8)
       Api(GetCurrentPositionEx, (arg1, arg2), 8)
       Api(GetDCOrgEx, (arg1, arg2), 8)
       Api(GetDeviceCaps, (arg1, arg2), 8)
       Api(GetDeviceGammaRamp, (arg1, arg2), 8)
       Api(GetDIBColorTable, (arg1, arg2, arg3, arg4), 16)
       Api(GetDIBits, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(GetEnhMetaFile, (arg1), 4)
       Api(GetEnhMetaFileBits, (arg1, arg2, arg3), 12)
  AnsiWide(GetEnhMetaFileDescription, (arg1, arg2, arg3), 12)
       Api(GetEnhMetaFileHeader, (arg1, arg2, arg3), 12)
       Api(GetEnhMetaFilePaletteEntries, (arg1, arg2, arg3), 12)
       Api(GetFontData, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetFontLanguageInfo, (arg1), 4)
       Api(GetFontResourceInfo, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetGlyphOutline, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(GetGraphicsMode, (arg1), 4)
  AnsiWide(GetICMProfile, (arg1, arg2, arg3), 12)
  AnsiWide(GetKerningPairs, (arg1, arg2, arg3), 12)
  AnsiWide(GetLogColorSpace, (arg1, arg2, arg3), 12)
       Api(GetMapMode, (arg1), 4)
  AnsiWide(GetMetaFile, (arg1), 4)
       Api(GetMetaFileBitsEx, (arg1, arg2, arg3), 12)
       Api(GetMetaRgn, (arg1, arg2), 8)
       Api(GetMiterLimit, (arg1, arg2), 8)
       Api(GetNearestColor, (arg1, arg2), 8)
       Api(GetNearestPaletteIndex, (arg1, arg2), 8)
  AnsiWide(GetObject, (arg1, arg2, arg3), 12)
       Api(GetObjectType, (arg1), 4)
  AnsiWide(GetOutlineTextMetrics, (arg1, arg2, arg3), 12)
       Api(GetPaletteEntries, (arg1, arg2, arg3, arg4), 16)
       Api(GetPath, (arg1, arg2, arg3, arg4), 16)
       Api(GetPixel, (arg1, arg2, arg3), 12)
       Api(GetPixelFormat, (arg1), 4)
       Api(GetPolyFillMode, (arg1), 4)
       Api(GetRandomRgn, (arg1, arg2, arg3), 12)
       Api(GetRasterizerCaps, (arg1, arg2), 8)
       Api(GetRegionData, (arg1, arg2, arg3), 12)
       Api(GetRelAbs, (arg1, arg2), 8)
       Api(GetRgnBox, (arg1, arg2), 8)
       Api(GetROP2, (arg1), 4)
       Api(GetStockObject, (arg1), 4)
       Api(GetStretchBltMode, (arg1), 4)
       Api(GetSystemPaletteEntries, (arg1, arg2, arg3, arg4), 16)
       Api(GetSystemPaletteUse, (arg1), 4)
       Api(GetTextAlign, (arg1), 4)
       Api(GetTextCharacterExtra, (arg1), 4)
       Api(GetTextCharset, (arg1), 4)
       Api(GetTextColor, (arg1), 4)
  AnsiWide(GetTextExtentExPoint, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(GetTextExtentPoint, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetTextExtentPoint32, (hdc, *lpString, c, lpSize), 16)
  AnsiWide(GetTextFace, (arg1, arg2, arg3), 12)
  AnsiWide(GetTextMetrics, (arg1, arg2), 8)
       Api(GetViewportExtEx, (arg1, arg2), 8)
       Api(GetViewportOrgEx, (arg1, arg2), 8)
       Api(GetWindowExtEx, (arg1, arg2), 8)
       Api(GetWindowOrgEx, (arg1, arg2), 8)
       Api(GetWinMetaFileBits, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetWorldTransform, (arg1, arg2), 8)
       Api(IntersectClipRect, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(InvertRgn, (arg1, arg2), 8)
       Api(LineDDA, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(LineTo, (arg1, arg2, arg3), 12)
       Api(LPtoDP, (arg1, arg2, arg3), 12)
       Api(MaskBlt, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(ModifyWorldTransform, (arg1, arg2, arg3), 12)
       Api(MoveToEx, (arg1, arg2, arg3, arg4), 16)
       Api(OffsetClipRgn, (arg1, arg2, arg3), 12)
       Api(OffsetRgn, (arg1, arg2, arg3), 12)
       Api(OffsetViewportOrgEx, (arg1, arg2, arg3, arg4), 16)
       Api(OffsetWindowOrgEx, (arg1, arg2, arg3, arg4), 16)
       Api(PaintRgn, (arg1, arg2), 8)
       Api(PatBlt, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(PathToRegion, (arg1), 4)
       Api(Pie, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(PlayEnhMetaFile, (arg1, arg2, arg3), 12)
       Api(PlayEnhMetaFileRecord, (arg1, arg2, arg3, arg4), 16)
       Api(PlayMetaFile, (arg1, arg2), 8)
       Api(PlayMetaFileRecord, (arg1, arg2, arg3, arg4), 16)
       Api(PlgBlt, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(PolyBezier, (arg1, arg2, arg3), 12)
       Api(PolyBezierTo, (arg1, arg2, arg3), 12)
       Api(PolyDraw, (arg1, arg2, arg3, arg4), 16)
       Api(Polygon, (arg1, arg2, arg3), 12)
       Api(Polyline, (arg1, arg2, arg3), 12)
       Api(PolylineTo, (arg1, arg2, arg3), 12)
       Api(PolyPolygon, (arg1, arg2, arg3, arg4), 16)
       Api(PolyPolyline, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(PolyTextOut, (arg1, arg2, arg3), 12)
       Api(PtInRegion, (arg1, arg2, arg3), 12)
       Api(PtVisible, (arg1, arg2, arg3), 12)
       Api(RealizePalette, (arg1), 4)
       Api(Rectangle, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RectInRegion, (arg1, arg2), 8)
       Api(RectVisible, (arg1, arg2), 8)
       Api(RemoveFontMemResourceEx, (arg1), 4)
  AnsiWide(RemoveFontResource, (*lpFileName), 4)
  AnsiWide(ResetDC, (arg1, arg2), 8)
       Api(ResizePalette, (arg1, arg2), 8)
       Api(RestoreDC, (arg1, arg2), 8)
       Api(RoundRect, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(SaveDC, (arg1), 4)
       Api(ScaleViewportExtEx, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ScaleWindowExtEx, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(SelectBrushLocal, (arg1, arg2), 8)
       Api(SelectClipPath, (arg1, arg2), 8)
       Api(SelectClipRgn, (arg1, arg2), 8)
       Api(SelectFontLocal, (arg1, arg2), 8)
       Api(SelectObject, (arg1, arg2), 8)
       Api(SelectPalette, (arg1, arg2, arg3), 12)
       Api(SetAbortProc, (arg1, arg2), 8)
       Api(SetArcDirection, (arg1, arg2), 8)
       Api(SetBitmapBits, (arg1, arg2, arg3), 12)
       Api(SetBitmapDimensionEx, (arg1, arg2, arg3, arg4), 16)
       Api(SetBkColor, (arg1, arg2), 8)
       Api(SetBkMode, (arg1, arg2), 8)
       Api(SetBoundsRect, (arg1, arg2, arg3), 12)
       Api(SetBrushOrgEx, (arg1, arg2, arg3, arg4), 16)
       Api(SetColorAdjustment, (arg1, arg2), 8)
       Api(SetColorSpace, (arg1, arg2), 8)
       Api(SetDCBrushColor, (arg1, arg2), 8)
       Api(SetDCPenColor, (arg1, arg2), 8)
       Api(SetDeviceGammaRamp, (arg1, arg2), 8)
       Api(SetDIBColorTable, (arg1, arg2, arg3, arg4), 16)
       Api(SetDIBits, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(SetDIBitsToDevice, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(SetEnhMetaFileBits, (arg1, arg2), 8)
       Api(SetFontEnumeration, (arg1), 4)
       Api(SetGraphicsMode, (arg1, arg2), 8)
       Api(SetICMMode, (arg1, arg2), 8)
  AnsiWide(SetICMProfile, (arg1, arg2), 8)
       Api(SetMapMode, (arg1, arg2), 8)
       Api(SetMapperFlags, (arg1, arg2), 8)
       Api(SetMetaFileBitsEx, (arg1, arg2), 8)
       Api(SetMetaRgn, (arg1), 4)
       Api(SetMiterLimit, (arg1, arg2, arg3), 12)
       Api(SetPaletteEntries, (arg1, arg2, arg3, arg4), 16)
       Api(SetPixel, (arg1, arg2, arg3, arg4), 16)
       Api(SetPixelFormat, (arg1, arg2, arg3), 12)
       Api(SetPixelV, (arg1, arg2, arg3, arg4), 16)
       Api(SetPolyFillMode, (arg1, arg2), 8)
       Api(SetRectRgn, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetRelAbs, (arg1, arg2), 8)
       Api(SetROP2, (arg1, arg2), 8)
       Api(SetStretchBltMode, (arg1, arg2), 8)
       Api(SetSystemPaletteUse, (arg1, arg2), 8)
       Api(SetTextAlign, (arg1, arg2), 8)
       Api(SetTextCharacterExtra, (arg1, arg2), 8)
       Api(SetTextColor, (arg1, arg2), 8)
       Api(SetTextJustification, (arg1, arg2, arg3), 12)
       Api(SetViewportExtEx, (arg1, arg2, arg3, arg4), 16)
       Api(SetViewportOrgEx, (arg1, arg2, arg3, arg4), 16)
       Api(SetWindowExtEx, (arg1, arg2, arg3, arg4), 16)
       Api(SetWindowOrgEx, (arg1, arg2, arg3, arg4), 16)
       Api(SetWinMetaFileBits, (arg1, arg2, arg3, arg4), 16)
       Api(SetWorldTransform, (arg1, arg2), 8)
  AnsiWide(StartDoc, (arg1, arg2), 8)
       Api(StartPage, (arg1), 4)
       Api(StretchBlt, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(StretchDIBits, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13), 52)
       Api(StrokeAndFillPath, (arg1), 4)
       Api(StrokePath, (arg1), 4)
       Api(SwapBuffers, (arg1), 4)
  AnsiWide(TextOut, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(TranslateCharsetInfo, (arg1, arg2, arg3), 12)
       Api(UnrealizeObject, (arg1), 4)
       Api(UpdateColors, (arg1), 4)
       Api(WidenPath, (arg1), 4)
EndImport
