XIncludeFile "common.pbi"

Import "hlink.lib"
       Api(HlinkClone, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(HlinkCreateBrowseContext, (arg1, arg2, arg3), 12)
       Api(HlinkCreateExtensionServices, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(HlinkCreateFromData, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(HlinkCreateFromMoniker, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(HlinkCreateFromString, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(HlinkCreateShortcut, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(HlinkCreateShortcutFromMoniker, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(HlinkCreateShortcutFromString, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(HlinkGetSpecialReference, (arg1, arg2), 8)
       Api(HlinkGetValueFromParams, (arg1, arg2, arg3), 12)
       Api(HlinkIsShortcut, (arg1), 4)
       Api(HlinkNavigate, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(HlinkNavigateToStringReference, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(HlinkOnNavigate, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(HlinkOnRenameDocument, (arg1, arg2, arg3, arg4), 16)
       Api(HlinkParseDisplayName, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(HlinkPreprocessMoniker, (arg1, arg2, arg3), 12)
       Api(HlinkQueryCreateFromData, (arg1), 4)
       Api(HlinkResolveMonikerForData, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(HlinkResolveShortcut, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(HlinkResolveShortcutToMoniker, (arg1, arg2, arg3), 12)
       Api(HlinkResolveShortcutToString, (arg1, arg2, arg3), 12)
       Api(HlinkResolveStringForData, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(HlinkSetSpecialReference, (arg1, arg2), 8)
       Api(HlinkTranslateURL, (arg1, arg2, arg3), 12)
       Api(HlinkUpdateStackItem, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(OleSaveToStreamEx, (arg1, arg2, arg3), 12)
EndImport
