XIncludeFile "common.pbi"

Import "imagehlp.lib"
       Api(BindImage, (arg1, arg2, arg3), 12)
       Api(BindImageEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CheckSumMappedFile, (arg1, arg2, arg3, arg4), 16)
       Api(EnumerateLoadedModules, (arg1, arg2, arg3), 12)
       Api(FindDebugInfoFile, (arg1, arg2, arg3), 12)
       Api(FindExecutableImage, (arg1, arg2, arg3), 12)
       Api(GetImageConfigInformation, (arg1, arg2), 8)
       Api(GetImageUnusedHeaderBytes, (arg1, arg2), 8)
       Api(GetTimestampForLoadedLibrary, (arg1), 4)
       Api(ImageAddCertificate, (arg1, arg2, arg3), 12)
       Api(ImageDirectoryEntryToData, (arg1, arg2, arg3, arg4), 16)
       Api(ImageEnumerateCertificates, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ImageGetCertificateData, (arg1, arg2, arg3, arg4), 16)
       Api(ImageGetCertificateHeader, (arg1, arg2, arg3), 12)
       Api(ImageGetDigestStream, (arg1, arg2, arg3, arg4), 16)
       Api(ImagehlpApiVersion, (), 0)
       Api(ImagehlpApiVersionEx, (arg1), 4)
       Api(ImageLoad, (arg1, arg2), 8)
       Api(ImageNtHeader, (arg1), 4)
       Api(ImageRemoveCertificate, (arg1, arg2), 8)
       Api(ImageRvaToSection, (arg1, arg2, arg3), 12)
       Api(ImageRvaToVa, (arg1, arg2, arg3, arg4), 16)
       Api(ImageUnload, (arg1), 4)
       Api(MakeSureDirectoryPathExists, (arg1), 4)
       Api(MapAndLoad, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(MapDebugInformation, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(MapFileAndCheckSum, (arg1, arg2, arg3), 12)
       Api(MarkImageAsRunFromSwap, (arg1, arg2), 8)
       Api(ReBaseImage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(RemovePrivateCvSymbolic, (arg1, arg2, arg3), 12)
       Api(RemoveRelocations, (arg1), 4)
       Api(SearchTreeForFile, (arg1, arg2, arg3), 12)
       Api(SetImageConfigInformation, (arg1, arg2), 8)
       Api(SplitSymbols, (arg1, arg2, arg3, arg4), 16)
       Api(StackWalk, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(SymCleanup, (arg1), 4)
       Api(SymEnumerateModules, (arg1, arg2, arg3), 12)
       Api(SymEnumerateSymbols, (arg1, arg2, arg3, arg4), 16)
       Api(SymFunctionTableAccess, (arg1, arg2), 8)
       Api(SymGetModuleBase, (arg1, arg2), 8)
       Api(SymGetModuleInfo, (arg1, arg2, arg3), 12)
       Api(SymGetOptions, (), 0)
       Api(SymGetSearchPath, (arg1, arg2, arg3), 12)
       Api(SymGetSymFromAddr, (arg1, arg2, arg3, arg4), 16)
       Api(SymGetSymFromName, (arg1, arg2, arg3), 12)
       Api(SymGetSymNext, (arg1, arg2), 8)
       Api(SymGetSymPrev, (arg1, arg2), 8)
       Api(SymInitialize, (arg1, arg2, arg3), 12)
       Api(SymLoadModule, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(SymRegisterCallback, (arg1, arg2, arg3, arg4), 16)
       Api(SymSetOptions, (arg1), 4)
       Api(SymSetSearchPath, (arg1, arg2), 8)
       Api(SymUnDName, (arg1, arg2, arg3), 12)
       Api(SymUnloadModule, (arg1, arg2), 8)
       Api(UnDecorateSymbolName, (arg1, arg2, arg3, arg4), 16)
       Api(UnMapAndLoad, (arg1), 4)
       Api(UnmapDebugInformation, (arg1), 4)
       Api(UpdateDebugInfoFile, (arg1, arg2, arg3, arg4), 16)
       Api(UpdateDebugInfoFileEx, (arg1, arg2, arg3, arg4, arg5), 20)
EndImport
