XIncludeFile "common.pbi"

Import "imm32.lib"
       Api(ImmAssociateContext, (arg1, arg2), 8)
       Api(ImmAssociateContextEx, (arg1, arg2, arg3), 12)
  AnsiWide(ImmConfigureIME, (arg1, arg2, arg3, arg4), 16)
       Api(ImmCreateContext, (), 0)
       Api(ImmCreateIMCC, (arg1), 4)
       Api(ImmCreateSoftKeyboard, (arg1, arg2, arg3, arg4), 16)
       Api(ImmDestroyContext, (arg1), 4)
       Api(ImmDestroyIMCC, (arg1), 4)
       Api(ImmDestroySoftKeyboard, (arg1), 4)
       Api(ImmDisableIME, (arg1), 4)
       Api(ImmEnumInputContext, (arg1, arg2, arg3), 12)
  AnsiWide(ImmEnumRegisterWord, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(ImmEscape, (arg1, arg2, arg3, arg4), 16)
       Api(ImmGenerateMessage, (arg1), 4)
  AnsiWide(ImmGetCandidateList, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(ImmGetCandidateListCount, (arg1, arg2), 8)
       Api(ImmGetCandidateWindow, (arg1, arg2, arg3), 12)
  AnsiWide(ImmGetCompositionFont, (arg1, arg2), 8)
  AnsiWide(ImmGetCompositionString, (arg1, arg2, arg3, arg4), 16)
       Api(ImmGetCompositionWindow, (arg1, arg2), 8)
       Api(ImmGetContext, (arg1), 4)
  AnsiWide(ImmGetConversionList, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ImmGetConversionStatus, (arg1, arg2, arg3), 12)
       Api(ImmGetDefaultIMEWnd, (arg1), 4)
  AnsiWide(ImmGetDescription, (arg1, arg2, arg3), 12)
  AnsiWide(ImmGetGuideLine, (arg1, arg2, arg3, arg4), 16)
       Api(ImmGetHotKey, (arg1, arg2, arg3, arg4), 16)
       Api(ImmGetIMCCLockCount, (arg1), 4)
       Api(ImmGetIMCCSize, (arg1), 4)
       Api(ImmGetIMCLockCount, (arg1), 4)
  AnsiWide(ImmGetIMEFileName, (arg1, arg2, arg3), 12)
  AnsiWide(ImmGetImeMenuItems, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ImmGetOpenStatus, (arg1), 4)
       Api(ImmGetProperty, (arg1, arg2), 8)
  AnsiWide(ImmGetRegisterWordStyle, (arg1, arg2, arg3), 12)
       Api(ImmGetStatusWindowPos, (arg1, arg2), 8)
       Api(ImmGetVirtualKey, (arg1), 4)
  AnsiWide(ImmInstallIME, (arg1, arg2), 8)
       Api(ImmIsIME, (arg1), 4)
  AnsiWide(ImmIsUIMessage, (arg1, arg2, arg3, arg4), 16)
       Api(ImmLockIMC, (arg1), 4)
       Api(ImmLockIMCC, (arg1), 4)
       Api(ImmNotifyIME, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(ImmRegisterWord, (arg1, arg2, arg3, arg4), 16)
       Api(ImmReleaseContext, (arg1, arg2), 8)
  AnsiWide(ImmRequestMessage, (arg1, arg2, arg3), 12)
       Api(ImmReSizeIMCC, (arg1, arg2), 8)
       Api(ImmSetCandidateWindow, (arg1, arg2), 8)
  AnsiWide(ImmSetCompositionFont, (arg1, arg2), 8)
  AnsiWide(ImmSetCompositionString, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ImmSetCompositionWindow, (arg1, arg2), 8)
       Api(ImmSetConversionStatus, (arg1, arg2, arg3), 12)
       Api(ImmSetHotKey, (arg1, arg2, arg3, arg4), 16)
       Api(ImmSetOpenStatus, (arg1, arg2), 8)
       Api(ImmSetStatusWindowPos, (arg1, arg2), 8)
       Api(ImmShowSoftKeyboard, (arg1, arg2), 8)
       Api(ImmSimulateHotKey, (arg1, arg2), 8)
       Api(ImmUnlockIMC, (arg1), 4)
       Api(ImmUnlockIMCC, (arg1), 4)
  AnsiWide(ImmUnregisterWord, (arg1, arg2, arg3, arg4), 16)
EndImport
