XIncludeFile "common.pbi"

Import "iphlpapi.lib"
       Api(AddIPAddress, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(AllocateAndGetArpEntTableFromStack, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(AllocateAndGetIfTableFromStack, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(AllocateAndGetIpAddrTableFromStack, (arg1, arg2, arg3, arg4), 16)
       Api(AllocateAndGetIpForwardTableFromStack, (arg1, arg2, arg3, arg4), 16)
       Api(AllocateAndGetIpNetTableFromStack, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(AllocateAndGetTcpTableFromStack, (arg1, arg2, arg3, arg4), 16)
       Api(AllocateAndGetUdpTableFromStack, (arg1, arg2, arg3, arg4), 16)
       Api(CreateIpForwardEntry, (arg1), 4)
       Api(CreateIpNetEntry, (arg1), 4)
       Api(CreateProxyArpEntry, (arg1, arg2, arg3), 12)
       Api(DeleteIPAddress, (arg1), 4)
       Api(DeleteIpForwardEntry, (arg1), 4)
       Api(DeleteIpNetEntry, (arg1), 4)
       Api(DeleteProxyArpEntry, (arg1, arg2, arg3), 12)
       Api(FlushIpNetTable, (arg1), 4)
       Api(FlushIpNetTableFromStack, (arg1), 4)
       Api(GetAdapterIndex, (arg1, arg2), 8)
       Api(GetAdaptersInfo, (arg1, arg2), 8)
       Api(GetBestInterface, (arg1, arg2), 8)
       Api(GetBestInterfaceFromStack, (arg1, arg2), 8)
       Api(GetBestRoute, (arg1, arg2, arg3), 12)
       Api(GetBestRouteFromStack, (arg1, arg2, arg3), 12)
       Api(GetFriendlyIfIndex, (arg1), 4)
       Api(GetIcmpStatistics, (arg1), 4)
       Api(GetIcmpStatsFromStack, (arg1), 4)
       Api(GetIfEntry, (arg1), 4)
       Api(GetIfEntryFromStack, (arg1, arg2, arg3), 12)
       Api(GetIfTable, (arg1, arg2, arg3), 12)
       Api(GetIfTableFromStack, (arg1, arg2, arg3, arg4), 16)
       Api(GetInterfaceInfo, (arg1, arg2), 8)
       Api(GetIpAddrTable, (arg1, arg2, arg3), 12)
       Api(GetIpAddrTableFromStack, (arg1, arg2, arg3), 12)
       Api(GetIpForwardTable, (arg1, arg2, arg3), 12)
       Api(GetIpForwardTableFromStack, (arg1, arg2, arg3), 12)
       Api(GetIpNetTable, (arg1, arg2, arg3), 12)
       Api(GetIpNetTableFromStack, (arg1, arg2, arg3, arg4), 16)
       Api(GetIpStatistics, (arg1), 4)
       Api(GetIpStatsFromStack, (arg1), 4)
       Api(GetNetworkParams, (arg1, arg2), 8)
       Api(GetNumberOfInterfaces, (arg1), 4)
       Api(GetPerAdapterInfo, (arg1, arg2, arg3), 12)
       Api(GetRTTAndHopCount, (arg1, arg2, arg3, arg4), 16)
       Api(GetTcpStatistics, (arg1), 4)
       Api(GetTcpStatsFromStack, (arg1), 4)
       Api(GetTcpTable, (arg1, arg2, arg3), 12)
       Api(GetTcpTableFromStack, (arg1, arg2, arg3), 12)
       Api(GetUdpStatistics, (arg1), 4)
       Api(GetUdpStatsFromStack, (arg1), 4)
       Api(GetUdpTable, (arg1, arg2, arg3), 12)
       Api(GetUdpTableFromStack, (arg1, arg2, arg3), 12)
       Api(GetUniDirectionalAdapterInfo, (arg1, arg2), 8)
       Api(InternalCreateIpForwardEntry, (arg1), 4)
       Api(InternalCreateIpNetEntry, (arg1), 4)
       Api(InternalDeleteIpForwardEntry, (arg1), 4)
       Api(InternalDeleteIpNetEntry, (arg1), 4)
       Api(InternalGetIfTable, (arg1, arg2, arg3), 12)
       Api(InternalGetIpAddrTable, (arg1, arg2, arg3), 12)
       Api(InternalGetIpForwardTable, (arg1, arg2, arg3), 12)
       Api(InternalGetIpNetTable, (arg1, arg2, arg3), 12)
       Api(InternalGetTcpTable, (arg1, arg2, arg3), 12)
       Api(InternalGetUdpTable, (arg1, arg2, arg3), 12)
       Api(InternalSetIfEntry, (arg1), 4)
       Api(InternalSetIpForwardEntry, (arg1), 4)
       Api(InternalSetIpNetEntry, (arg1), 4)
       Api(InternalSetIpStats, (arg1), 4)
       Api(InternalSetTcpEntry, (arg1), 4)
       Api(IpHlpDllEntry, (arg1, arg2, arg3), 12)
       Api(IpReleaseAddress, (arg1), 4)
       Api(IpRenewAddress, (arg1), 4)
       Api(IsLocalAddress, (arg1), 4)
       Api(NotifyAddrChange, (arg1, arg2), 8)
       Api(NotifyRouteChange, (arg1, arg2), 8)
       Api(NTPTimeToNTFileTime, (arg1, arg2, arg3), 12)
       Api(NTTimeToNTPTime, (arg1, arg2), 8)
       Api(PfAddFiltersToInterface, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(PfAddGlobalFilterToInterface, (arg1, arg2), 8)
       Api(PfBindInterfaceToIndex, (arg1, arg2), 8)
       Api(PfBindInterfaceToIPAddress, (arg1, arg2, arg3), 12)
       Api(PfCreateInterface, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(PfDeleteInterface, (arg1), 4)
       Api(PfDeleteLog, (), 0)
       Api(PfGetInterfaceStatistics, (arg1, arg2, arg3, arg4), 16)
       Api(PfMakeLog, (arg1), 4)
       Api(PfRebindFilters, (arg1, arg2), 8)
       Api(PfRemoveFilterHandles, (arg1, arg2, arg3), 12)
       Api(PfRemoveFiltersFromInterface, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(PfRemoveGlobalFilterFromInterface, (arg1, arg2), 8)
       Api(PfSetLogBuffer, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(PfTestPacket, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(PfUnBindInterface, (arg1), 4)
       Api(SendARP, (arg1, arg2, arg3, arg4), 16)
       Api(SetAdapterIpAddress, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetIfEntry, (arg1), 4)
       Api(SetIfEntryToStack, (arg1, arg2), 8)
       Api(SetIpForwardEntry, (arg1), 4)
       Api(SetIpForwardEntryToStack, (arg1), 4)
       Api(SetIpNetEntry, (arg1), 4)
       Api(SetIpNetEntryToStack, (arg1, arg2), 8)
       Api(SetIpRouteEntryToStack, (arg1), 4)
       Api(SetIpStatistics, (arg1), 4)
       Api(SetIpStatsToStack, (arg1), 4)
       Api(SetIpTTL, (arg1), 4)
       Api(SetProxyArpEntryToStack, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetTcpEntry, (arg1), 4)
       Api(SetTcpEntryToStack, (arg1), 4)
EndImport
