XIncludeFile "common.pbi"

Import "kernel32.lib"
       Api(_hread, (arg1, arg2, arg3), 12)
       Api(_hwrite, (arg1, arg2, arg3), 12)
       Api(_lclose, (arg1), 4)
       Api(_lcreat, (arg1, arg2), 8)
       Api(_llseek, (arg1, arg2, arg3), 12)
       Api(_lopen, (arg1, arg2), 8)
       Api(_lread, (arg1, arg2, arg3), 12)
       Api(_lwrite, (arg1, arg2, arg3), 12)
  AnsiWide(AddAtom, (arg1), 4)
  AnsiWide(AddConsoleAlias, (arg1, arg2, arg3), 12)
       Api(AllocConsole, (), 0)
       Api(AreFileApisANSI, (), 0)
       Api(BackupRead, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(BackupSeek, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(BackupWrite, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(Beep, (arg1, arg2), 8)
  AnsiWide(BeginUpdateResource, (arg1, arg2), 8)
  AnsiWide(BuildCommDCB, (arg1, arg2), 8)
  AnsiWide(BuildCommDCBAndTimeouts, (arg1, arg2, arg3), 12)
  AnsiWide(CallNamedPipe, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CancelIo, (arg1), 4)
       Api(CancelWaitableTimer, (arg1), 4)
       Api(ClearCommBreak, (arg1), 4)
       Api(ClearCommError, (arg1, arg2, arg3), 12)
       Api(CloseConsoleHandle, (arg1), 4)
       Api(CloseHandle, (arg1), 4)
       Api(CloseProfileUserMapping, (), 0)
       Api(CmdBatNotification, (arg1), 4)
  AnsiWide(CommConfigDialog, (arg1, arg2, arg3), 12)
       Api(CompareFileTime, (arg1, arg2), 8)
  AnsiWide(CompareString, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ConnectNamedPipe, (arg1, arg2), 8)
       Api(ConsoleMenuControl, (arg1, arg2, arg3), 12)
       Api(ContinueDebugEvent, (arg1, arg2, arg3), 12)
       Api(ConvertDefaultLocale, (arg1), 4)
       Api(ConvertThreadToFiber, (arg1), 4)
  AnsiWide(CopyFile, (*arg1, arg2, arg3), 12)
  AnsiWide(CopyFileEx, (*arg1, *arg2, arg3, arg4, arg5, arg6), 24)
       Api(CreateConsoleScreenBuffer, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(CreateDirectory, (*arg1, arg2), 8)
  AnsiWide(CreateDirectoryEx, (*arg1, *arg2, arg3), 12)
  AnsiWide(CreateEvent, (*lpEventAttributes, bManualReset, bInitialState, *lpName), 16)
       Api(CreateFiber, (arg1, arg2, arg3), 12)
  AnsiWide(CreateFile, (*arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(CreateFileMapping, (arg1, arg2, arg3, arg4, arg5, *arg6), 24)
       Api(CreateIoCompletionPort, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(CreateMailslot, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(CreateMutex, (arg1, arg2, *arg3), 12)
  AnsiWide(CreateNamedPipe, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(CreatePipe, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(CreateProcess, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(CreateRemoteThread, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(CreateSemaphore, (arg1, arg2, arg3, arg4), 16)
       Api(CreateTapePartition, (arg1, arg2, arg3, arg4), 16)
       Api(CreateThread, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CreateToolhelp32Snapshot, (arg1, arg2), 8)
       Api(CreateVirtualBuffer, (arg1, arg2, arg3), 12)
  AnsiWide(CreateWaitableTimer, (arg1, arg2, arg3), 12)
       Api(DebugActiveProcess, (arg1), 4)
       Api(DebugBreak, (), 0)
  AnsiWide(DefineDosDevice, (arg1, arg2, arg3), 12)
       Api(DeleteAtom, (arg1), 4)
       Api(DeleteCriticalSection, (arg1), 4)
       Api(DeleteFiber, (arg1), 4)
  AnsiWide(DeleteFile, (*arg1), 4)
       Api(DeviceIoControl, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(DisableThreadLibraryCalls, (arg1), 4)
       Api(DisconnectNamedPipe, (arg1), 4)
       Api(DosDateTimeToFileTime, (arg1, arg2, arg3), 12)
       Api(DuplicateConsoleHandle, (arg1, arg2, arg3, arg4), 16)
       Api(DuplicateHandle, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(EndUpdateResource, (arg1, arg2), 8)
       Api(EnterCriticalSection, (arg1), 4)
  AnsiWide(EnumCalendarInfo, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(EnumDateFormats, (arg1, arg2, arg3), 12)
  AnsiWide(EnumResourceLanguages, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(EnumResourceNames, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(EnumResourceTypes, (arg1, arg2, arg3), 12)
  AnsiWide(EnumSystemCodePages, (arg1, arg2), 8)
  AnsiWide(EnumSystemLocales, (arg1, arg2), 8)
  AnsiWide(EnumTimeFormats, (arg1, arg2, arg3), 12)
       Api(EraseTape, (arg1, arg2, arg3), 12)
       Api(EscapeCommFunction, (arg1, arg2), 8)
       Api(ExitProcess, (arg1), 4)
       Api(ExitThread, (arg1), 4)
       Api(ExitVDM, (arg1, arg2), 8)
  AnsiWide(ExpandEnvironmentStrings, (*arg1, arg2, arg3), 12)
  AnsiWide(ExpungeConsoleCommandHistory, (arg1), 4)
       Api(ExtendVirtualBuffer, (arg1, arg2), 8)
  AnsiWide(FatalAppExit, (arg1, arg2), 8)
       Api(FatalExit, (arg1), 4)
       Api(FileTimeToDosDateTime, (arg1, arg2, arg3), 12)
       Api(FileTimeToLocalFileTime, (arg1, arg2), 8)
       Api(FileTimeToSystemTime, (arg1, arg2), 8)
       Api(FillConsoleOutputAttribute, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(FillConsoleOutputCharacter, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(FindAtom, (arg1), 4)
       Api(FindClose, (arg1), 4)
       Api(FindCloseChangeNotification, (arg1), 4)
  AnsiWide(FindFirstChangeNotification, (arg1, arg2, arg3), 12)
  AnsiWide(FindFirstFile, (*arg1, arg2), 8)
  AnsiWide(FindFirstFileEx, (*arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(FindNextChangeNotification, (arg1), 4)
  AnsiWide(FindNextFile, (arg1, arg2), 8)
  AnsiWide(FindResource, (arg1, arg2, arg3), 12)
  AnsiWide(FindResourceEx, (arg1, arg2, arg3, arg4), 16)
       Api(FlushConsoleInputBuffer, (arg1), 4)
       Api(FlushFileBuffers, (arg1), 4)
       Api(FlushInstructionCache, (arg1, arg2, arg3), 12)
       Api(FlushViewOfFile, (arg1, arg2), 8)
  AnsiWide(FoldString, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(FormatMessage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(FreeConsole, (), 0)
  AnsiWide(FreeEnvironmentStrings, (arg1), 4)
       Api(FreeLibrary, (arg1), 4)
       Api(FreeLibraryAndExitThread, (arg1, arg2), 8)
       Api(FreeResource, (arg1), 4)
       Api(FreeVirtualBuffer, (arg1), 4)
       Api(GenerateConsoleCtrlEvent, (arg1, arg2), 8)
       Api(GetACP, (), 0)
  AnsiWide(GetAtomName, (arg1, arg2, arg3), 12)
  AnsiWide(GetBinaryType, (arg1, arg2), 8)
  AnsiWide(GetCommandLine, (), 0)
       Api(GetCommConfig, (arg1, arg2, arg3), 12)
       Api(GetCommMask, (arg1, arg2), 8)
       Api(GetCommModemStatus, (arg1, arg2), 8)
       Api(GetCommProperties, (arg1, arg2), 8)
       Api(GetCommState, (arg1, arg2), 8)
       Api(GetCommTimeouts, (arg1, arg2), 8)
  AnsiWide(GetCompressedFileSize, (*arg1, arg2), 8)
  AnsiWide(GetComputerName, (arg1, arg2), 8)
  AnsiWide(GetConsoleAlias, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetConsoleAliases, (arg1, arg2, arg3), 12)
  AnsiWide(GetConsoleAliasesLength, (arg1), 4)
  AnsiWide(GetConsoleAliasExes, (arg1, arg2), 8)
  AnsiWide(GetConsoleAliasExesLength, (), 0)
  AnsiWide(GetConsoleCommandHistory, (arg1, arg2, arg3), 12)
  AnsiWide(GetConsoleCommandHistoryLength, (arg1), 4)
       Api(GetConsoleCP, (), 0)
       Api(GetConsoleCursorInfo, (arg1, arg2), 8)
       Api(GetConsoleDisplayMode, (arg1), 4)
       Api(GetConsoleFontInfo, (arg1, arg2, arg3, arg4), 16)
       Api(GetConsoleFontSize, (arg1, arg2), 8)
       Api(GetConsoleHardwareState, (arg1, arg2, arg3), 12)
  AnsiWide(GetConsoleInputExeName, (arg1, arg2), 8)
       Api(GetConsoleInputWaitHandle, (), 0)
  AnsiWide(GetConsoleKeyboardLayoutName, (arg1), 4)
       Api(GetConsoleMode, (arg1, arg2), 8)
       Api(GetConsoleOutputCP, (), 0)
       Api(GetConsoleScreenBufferInfo, (arg1, arg2), 8)
  AnsiWide(GetConsoleTitle, (arg1, arg2), 8)
       Api(GetCPInfo, (arg1, arg2), 8)
  AnsiWide(GetCurrencyFormat, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetCurrentConsoleFont, (arg1, arg2, arg3), 12)
  AnsiWide(GetCurrentDirectory, (arg1, arg2), 8)
       Api(GetCurrentProcess, (), 0)
       Api(GetCurrentProcessId, (), 0)
       Api(GetCurrentThread, (), 0)
       Api(GetCurrentThreadId, (), 0)
  AnsiWide(GetDateFormat, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GetDefaultCommConfig, (arg1, arg2, arg3), 12)
  AnsiWide(GetDiskFreeSpace, (*lpRootPathName, *lpSectorsPerCluster, *lpBytesPerSector, *lpNumberOfFreeClusters, *lpTotalNumberOfClusters), 20)
  AnsiWide(GetDiskFreeSpaceEx, (*lpDirectoryName, *lpFreeBytesAvailable, *lpTotalNumberOfBytes, *lpTotalNumberOfFreeBytes), 16)
  AnsiWide(GetDriveType, (*arg1), 4)
  AnsiWide(GetEnvironmentStrings, (), 0)
  AnsiWide(GetEnvironmentVariable, (*arg1, arg2, arg3), 12)
       Api(GetExitCodeProcess, (arg1, arg2), 8)
       Api(GetExitCodeThread, (arg1, arg2), 8)
  AnsiWide(GetFileAttributes, (*arg1), 4)
  AnsiWide(GetFileAttributesEx, (*arg1, arg2, arg3), 12)
       Api(GetFileInformationByHandle, (arg1, arg2), 8)
       Api(GetFileSize, (arg1, arg2), 8)
       Api(GetFileSizeEx, (arg1, arg2), 8)
       Api(GetFileTime, (arg1, arg2, arg3, arg4), 16)
       Api(GetFileType, (arg1), 4)
  AnsiWide(GetFullPathName, (arg1, arg2, arg3, arg4), 16)
       Api(GetHandleInformation, (arg1, arg2), 8)
       Api(GetLargestConsoleWindowSize, (arg1), 4)
       Api(GetLastError, (), 0)
  AnsiWide(GetLocaleInfo, (arg1, arg2, arg3, arg4), 16)
       Api(GetLocalTime, (arg1), 4)
       Api(GetLogicalDrives, (), 0)
  AnsiWide(GetLogicalDriveStrings, (arg1, arg2), 8)
  AnsiWide(GetLongPathName, (arg1, arg2, arg3), 12)
       Api(GetMailslotInfo, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(GetModuleFileName, (arg1, arg2, arg3), 12)
  AnsiWide(GetModuleHandle, (*arg1), 4)
  AnsiWide(GetNamedPipeHandleState, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(GetNamedPipeInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetNextVDMCommand, (arg1), 4)
  AnsiWide(GetNumberFormat, (arg1, arg2, *arg3, arg4, arg5, arg6), 24)
       Api(GetNumberOfConsoleFonts, (), 0)
       Api(GetNumberOfConsoleInputEvents, (arg1, arg2), 8)
       Api(GetNumberOfConsoleMouseButtons, (arg1), 4)
       Api(GetOEMCP, (), 0)
       Api(GetOverlappedResult, (arg1, arg2, arg3, arg4), 16)
       Api(GetPriorityClass, (arg1), 4)
  AnsiWide(GetPrivateProfileInt, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetPrivateProfileSection, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetPrivateProfileSectionNames, (arg1, arg2, arg3), 12)
  AnsiWide(GetPrivateProfileString, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GetPrivateProfileStruct, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetProcAddress, (hModule, lpProcName), 8)
       Api(GetProcessAffinityMask, (arg1, arg2, arg3), 12)
       Api(GetProcessHeap, (), 0)
       Api(GetProcessHeaps, (arg1, arg2), 8)
       Api(GetProcessPriorityBoost, (arg1, arg2), 8)
       Api(GetProcessShutdownParameters, (arg1, arg2), 8)
       Api(GetProcessTimes, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetProcessVersion, (arg1), 4)
       Api(GetProcessWorkingSetSize, (arg1, arg2, arg3), 12)
  AnsiWide(GetProfileInt, (arg1, arg2, arg3), 12)
  AnsiWide(GetProfileSection, (arg1, arg2, arg3), 12)
  AnsiWide(GetProfileString, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetQueuedCompletionStatus, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(GetShortPathName, (arg1, arg2, arg3), 12)
  AnsiWide(GetStartupInfo, (arg1), 4)
       Api(GetStdHandle, (arg1), 4)
  AnsiWide(GetStringType, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(GetStringTypeEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetSystemDefaultLangID, (), 0)
       Api(GetSystemDefaultLCID, (), 0)
  AnsiWide(GetSystemDirectory, (lpBuffer, uSize), 8)
       Api(GetSystemInfo, (arg1), 4)
       Api(GetSystemPowerStatus, (arg1), 4)
       Api(GetSystemTime, (arg1), 4)
       Api(GetSystemTimeAdjustment, (arg1, arg2, arg3), 12)
       Api(GetSystemTimeAsFileTime, (arg1), 4)
       Api(GetTapeParameters, (arg1, arg2, arg3, arg4), 16)
       Api(GetTapePosition, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetTapeStatus, (arg1), 4)
  AnsiWide(GetTempFileName, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetTempPath, (arg1, arg2), 8)
       Api(GetThreadContext, (arg1, arg2), 8)
       Api(GetThreadLocale, (), 0)
       Api(GetThreadPriority, (arg1), 4)
       Api(GetThreadPriorityBoost, (arg1, arg2), 8)
       Api(GetThreadSelectorEntry, (arg1, arg2, arg3), 12)
       Api(GetThreadTimes, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetTickCount, (), 0)
  AnsiWide(GetTimeFormat, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetTimeZoneInformation, (arg1), 4)
       Api(GetUserDefaultLangID, (), 0)
       Api(GetUserDefaultLCID, (), 0)
       Api(GetVDMCurrentDirectories, (arg1, arg2), 8)
       Api(GetVersion, (), 0)
  AnsiWide(GetVersionEx, (arg1), 4)
  AnsiWide(GetVolumeInformation, (*arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(GetWindowsDirectory, (arg1, arg2), 8)
  AnsiWide(GlobalAddAtom, (arg1), 4)
       Api(GlobalAlloc, (arg1, arg2), 8)
       Api(GlobalCompact, (arg1), 4)
       Api(GlobalDeleteAtom, (arg1), 4)
  AnsiWide(GlobalFindAtom, (arg1), 4)
       Api(GlobalFix, (arg1), 4)
       Api(GlobalFlags, (arg1), 4)
       Api(GlobalFree, (arg1), 4)
  AnsiWide(GlobalGetAtomName, (arg1, arg2, arg3), 12)
       Api(GlobalHandle, (arg1), 4)
       Api(GlobalLock, (arg1), 4)
       Api(GlobalMemoryStatus, (arg1), 4)
       Api(GlobalMemoryStatusEx, (arg1), 4)
       Api(GlobalReAlloc, (arg1, arg2, arg3), 12)
       Api(GlobalSize, (arg1), 4)
       Api(GlobalUnfix, (arg1), 4)
       Api(GlobalUnlock, (arg1), 4)
       Api(GlobalUnWire, (arg1), 4)
       Api(GlobalWire, (arg1), 4)
       Api(Heap32First, (arg1, arg2, arg3), 12)
       Api(Heap32ListFirst, (arg1, arg2), 8)
       Api(Heap32ListNext, (arg1, arg2), 8)
       Api(Heap32Next, (arg1), 4)
       Api(HeapAlloc, (arg1, arg2, arg3), 12)
       Api(HeapCompact, (arg1, arg2), 8)
       Api(HeapCreate, (arg1, arg2, arg3), 12)
       Api(HeapDestroy, (arg1), 4)
       Api(HeapExtend, (arg1, arg2, arg3, arg4), 16)
       Api(HeapFree, (arg1, arg2, arg3), 12)
       Api(HeapLock, (arg1), 4)
       Api(HeapReAlloc, (arg1, arg2, arg3, arg4), 16)
       Api(HeapSize, (arg1, arg2, arg3), 12)
       Api(HeapSummary, (arg1, arg2, arg3), 12)
       Api(HeapUnlock, (arg1), 4)
       Api(HeapUsage, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(HeapValidate, (arg1, arg2, arg3), 12)
       Api(HeapWalk, (arg1, arg2), 8)
       Api(InitAtomTable, (arg1), 4)
       Api(InitializeCriticalSection, (arg1), 4)
       Api(InterlockedCompareExchange, (arg1, arg2, arg3), 12)
       Api(InterlockedDecrement, (arg1), 4)
       Api(InterlockedExchange, (arg1, arg2), 8)
       Api(InterlockedExchangeAdd, (arg1, arg2), 8)
       Api(InterlockedIncrement, (arg1), 4)
       Api(InvalidateConsoleDIBits, (arg1, arg2), 8)
       Api(IsBadCodePtr, (arg1), 4)
       Api(IsBadHugeReadPtr, (arg1, arg2), 8)
       Api(IsBadHugeWritePtr, (arg1, arg2), 8)
       Api(IsBadReadPtr, (arg1, arg2), 8)
  AnsiWide(IsBadStringPtr, (arg1, arg2), 8)
       Api(IsBadWritePtr, (arg1, arg2), 8)
       Api(IsDBCSLeadByte, (arg1), 4)
       Api(IsDBCSLeadByteEx, (arg1, arg2), 8)
       Api(IsDebuggerPresent, (), 0)
       Api(IsProcessorFeaturePresent, (arg1), 4)
       Api(IsValidCodePage, (arg1), 4)
       Api(IsValidLocale, (arg1, arg2), 8)
  AnsiWide(LCMapString, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(LeaveCriticalSection, (arg1), 4)
  AnsiWide(LoadLibrary, (*lpFileName), 4)
  AnsiWide(LoadLibraryEx, (*lpFileName, hFile, dwFlags), 12)
       Api(LoadModule, (arg1, arg2), 8)
       Api(LoadResource, (arg1, arg2), 8)
       Api(LocalAlloc, (arg1, arg2), 8)
       Api(LocalCompact, (arg1), 4)
       Api(LocalFileTimeToFileTime, (arg1, arg2), 8)
       Api(LocalFlags, (arg1), 4)
       Api(LocalFree, (arg1), 4)
       Api(LocalHandle, (arg1), 4)
       Api(LocalLock, (arg1), 4)
       Api(LocalReAlloc, (arg1, arg2, arg3), 12)
       Api(LocalShrink, (arg1, arg2), 8)
       Api(LocalSize, (arg1), 4)
       Api(LocalUnlock, (arg1), 4)
       Api(LockFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(LockFileEx, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(LockResource, (arg1), 4)
  AnsiWide(lstrcat, (arg1, arg2), 8)
  AnsiWide(lstrcmp, (arg1, arg2), 8)
  AnsiWide(lstrcmpi, (arg1, arg2), 8)
  AnsiWide(lstrcpy, (arg1, arg2), 8)
  AnsiWide(lstrcpyn, (arg1, arg2, arg3), 12)
  AnsiWide(lstrlen, (arg1), 4)
       Api(MapViewOfFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(MapViewOfFileEx, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWideWierd(Module32First, (arg1, arg2), 8)  ; Warning, wierd version :)
  AnsiWideWierd(Module32Next, (arg1, arg2), 8)   ; Warning, wierd version :)
  AnsiWide(MoveFile, (*arg1, *arg2), 8)
  AnsiWide(MoveFileEx, (*arg1, *arg2, arg3), 12)
  AnsiWide(MoveFileWithProgress, (*lpExistingFileName, *lpNewFileName, *lpProgressRoutine, lpData.l, dwFlags.l), 20)
       Api(MulDiv, (arg1, arg2, arg3), 12)
       Api(MultiByteToWideChar, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(OpenEvent, (dwDesiredAccess.l, bInheritHandle, *lpName), 12)
       Api(OpenFile, (arg1, arg2, arg3), 12)
  AnsiWide(OpenFileMapping, (dwDesiredAccess.l, bInheritHandle, *lpName), 12)
  AnsiWide(OpenMutex, (arg1, arg2, arg3), 12)
       Api(OpenProcess, (arg1, arg2, arg3), 12)
       Api(OpenProfileUserMapping, (), 0)
  AnsiWide(OpenSemaphore, (arg1, arg2, arg3), 12)
  AnsiWide(OpenWaitableTimer, (arg1, arg2, arg3), 12)
  AnsiWide(OutputDebugString, (arg1), 4)
  AnsiWide(PeekConsoleInput, (arg1, arg2, arg3, arg4), 16)
       Api(PeekNamedPipe, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(PostQueuedCompletionStatus, (arg1, arg2, arg3, arg4), 16)
       Api(PrepareTape, (arg1, arg2, arg3), 12)
  AnsiWideWierd(Process32First, (arg1, arg2), 8) ; Warning, wierd version :)
  AnsiWideWierd(Process32Next, (arg1, arg2), 8)  ; Warning, wierd version :)
       Api(PulseEvent, (arg1), 4)
       Api(PurgeComm, (arg1, arg2), 8)
  AnsiWide(QueryDosDevice, (arg1, arg2, arg3), 12)
       Api(QueryPerformanceCounter, (arg1), 4)
       Api(QueryPerformanceFrequency, (arg1), 4)
       Api(QueryWin31IniFilesMappedToRegistry, (arg1, arg2, arg3, arg4), 16)
       Api(QueueUserAPC, (arg1, arg2, arg3), 12)
       Api(RaiseException, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(ReadConsole, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(ReadConsoleInput, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(ReadConsoleInputEx, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(ReadConsoleOutput, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ReadConsoleOutputAttribute, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(ReadConsoleOutputCharacter, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ReadFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ReadFileEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ReadProcessMemory, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RegisterConsoleVDM, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(RegisterWaitForInputIdle, (arg1), 4)
       Api(RegisterWowBaseHandlers, (arg1), 4)
       Api(RegisterWowExec, (arg1), 4)
       Api(ReleaseMutex, (arg1), 4)
       Api(ReleaseSemaphore, (arg1, arg2, arg3), 12)
  AnsiWide(RemoveDirectory, (*arg1), 4)
       Api(ResetEvent, (arg1), 4)
       Api(ResumeThread, (arg1), 4)
       Api(RtlFillMemory, (arg1, arg2, arg3), 12)
       Api(RtlMoveMemory, (arg1, arg2, arg3), 12)
       Api(RtlUnwind, (arg1, arg2, arg3, arg4), 16)
       Api(RtlZeroMemory, (arg1, arg2), 8)
  AnsiWide(ScrollConsoleScreenBuffer, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SearchPath, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(SetCommBreak, (arg1), 4)
       Api(SetCommConfig, (arg1, arg2, arg3), 12)
       Api(SetCommMask, (arg1, arg2), 8)
       Api(SetCommState, (arg1, arg2), 8)
       Api(SetCommTimeouts, (arg1, arg2), 8)
  AnsiWide(SetComputerName, (arg1), 4)
       Api(SetConsoleActiveScreenBuffer, (arg1), 4)
       Api(SetConsoleCommandHistoryMode, (arg1), 4)
       Api(SetConsoleCP, (arg1), 4)
       Api(SetConsoleCtrlHandler, (arg1, arg2), 8)
       Api(SetConsoleCursor, (arg1, arg2), 8)
       Api(SetConsoleCursorInfo, (arg1, arg2), 8)
       Api(SetConsoleCursorPosition, (arg1, arg2), 8)
       Api(SetConsoleDisplayMode, (arg1, arg2, arg3), 12)
       Api(SetConsoleFont, (arg1, arg2), 8)
       Api(SetConsoleHardwareState, (arg1, arg2, arg3), 12)
       Api(SetConsoleIcon, (arg1), 4)
  AnsiWide(SetConsoleInputExeName, (arg1), 4)
       Api(SetConsoleKeyShortcuts, (arg1, arg2, arg3, arg4), 16)
       Api(SetConsoleMaximumWindowSize, (arg1, arg2), 8)
       Api(SetConsoleMenuClose, (arg1), 4)
       Api(SetConsoleMode, (arg1, arg2), 8)
  AnsiWide(SetConsoleNumberOfCommands, (arg1, arg2), 8)
       Api(SetConsoleOutputCP, (arg1), 4)
       Api(SetConsolePalette, (arg1, arg2, arg3), 12)
       Api(SetConsoleScreenBufferSize, (arg1, arg2), 8)
       Api(SetConsoleTextAttribute, (arg1, arg2), 8)
  AnsiWide(SetConsoleTitle, (arg1), 4)
       Api(SetConsoleWindowInfo, (arg1, arg2, arg3), 12)
  AnsiWide(SetCurrentDirectory, (*lpPathName), 4)
  AnsiWide(SetDefaultCommConfig, (arg1, arg2, arg3), 12)
       Api(SetEndOfFile, (arg1), 4)
  AnsiWide(SetEnvironmentVariable, (*arg1, *arg2), 8)
       Api(SetErrorMode, (arg1), 4)
       Api(SetEvent, (arg1), 4)
       Api(SetFileApisToANSI, (), 0)
       Api(SetFileApisToOEM, (), 0)
  AnsiWide(SetFileAttributes, (*arg1, arg2), 8)
       Api(SetFilePointer, (arg1, arg2, arg3, arg4), 16)
       Api(SetFilePointerEx, (hFile, liDistanceToMove.q, *lpNewFilePointer, dwMoveMethod), 20)
       Api(SetFileTime, (arg1, arg2, arg3, arg4), 16)
       Api(SetHandleCount, (arg1), 4)
       Api(SetHandleInformation, (arg1, arg2, arg3), 12)
       Api(SetLastConsoleEventActive, (), 0)
       Api(SetLastError, (arg1), 4)
  AnsiWide(SetLocaleInfo, (arg1, arg2, arg3), 12)
       Api(SetLocalTime, (arg1), 4)
       Api(SetMailslotInfo, (arg1, arg2), 8)
       Api(SetNamedPipeHandleState, (arg1, arg2, arg3, arg4), 16)
       Api(SetPriorityClass, (arg1, arg2), 8)
       Api(SetProcessAffinityMask, (arg1, arg2), 8)
       Api(SetProcessPriorityBoost, (arg1, arg2), 8)
       Api(SetProcessShutdownParameters, (arg1, arg2), 8)
       Api(SetProcessWorkingSetSize, (arg1, arg2, arg3), 12)
       Api(SetStdHandle, (arg1, arg2), 8)
       Api(SetSystemPowerState, (arg1, arg2), 8)
       Api(SetSystemTime, (arg1), 4)
       Api(SetSystemTimeAdjustment, (arg1, arg2), 8)
       Api(SetTapeParameters, (arg1, arg2, arg3), 12)
       Api(SetTapePosition, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(SetThreadAffinityMask, (arg1, arg2), 8)
       Api(SetThreadContext, (arg1, arg2), 8)
       Api(SetThreadIdealProcessor, (arg1, arg2), 8)
       Api(SetThreadLocale, (arg1), 4)
       Api(SetThreadPriority, (arg1, arg2), 8)
       Api(SetThreadPriorityBoost, (arg1, arg2), 8)
       Api(SetTimeZoneInformation, (arg1), 4)
       Api(SetUnhandledExceptionFilter, (arg1), 4)
       Api(SetupComm, (arg1, arg2, arg3), 12)
       Api(SetVDMCurrentDirectories, (arg1, arg2), 8)
  AnsiWide(SetVolumeLabel, (arg1, arg2), 8)
       Api(SetWaitableTimer, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ShowConsoleCursor, (arg1, arg2), 8)
       Api(SignalObjectAndWait, (arg1, arg2, arg3, arg4), 16)
       Api(SizeofResource, (arg1, arg2), 8)
       Api(Sleep, (arg1), 4)
       Api(SleepEx, (arg1, arg2), 8)
       Api(SuspendThread, (arg1), 4)
       Api(SwitchToFiber, (arg1), 4)
       Api(SwitchToThread, (), 0)
       Api(SystemTimeToFileTime, (arg1, arg2), 8)
       Api(SystemTimeToTzSpecificLocalTime, (arg1, arg2, arg3), 12)
       Api(TerminateProcess, (arg1, arg2), 8)
       Api(TerminateThread, (arg1, arg2), 8)
       Api(Thread32First, (arg1, arg2), 8)
       Api(Thread32Next, (arg1, arg2), 8)
       Api(TlsAlloc, (), 0)
       Api(TlsFree, (arg1), 4)
       Api(TlsGetValue, (arg1), 4)
       Api(TlsSetValue, (arg1, arg2), 8)
       Api(Toolhelp32ReadProcessMemory, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(TransactNamedPipe, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(TransmitCommChar, (arg1, arg2), 8)
       Api(TrimVirtualBuffer, (arg1), 4)
       Api(TryEnterCriticalSection, (arg1), 4)
       Api(UnhandledExceptionFilter, (arg1), 4)
       Api(UnlockFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(UnlockFileEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(UnmapViewOfFile, (arg1), 4)
  AnsiWide(UpdateResource, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(VDMConsoleOperation, (arg1, arg2), 8)
       Api(VDMOperationStarted, (arg1), 4)
       Api(VerifyConsoleIoHandle, (arg1), 4)
  AnsiWide(VerLanguageName, (arg1, arg2, arg3), 12)
       Api(VirtualAlloc, (arg1, arg2, arg3, arg4), 16)
       Api(VirtualAllocEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(VirtualBufferExceptionHandler, (arg1, arg2, arg3), 12)
       Api(VirtualFree, (arg1, arg2, arg3), 12)
       Api(VirtualFreeEx, (arg1, arg2, arg3, arg4), 16)
       Api(VirtualLock, (arg1, arg2), 8)
       Api(VirtualProtect, (arg1, arg2, arg3, arg4), 16)
       Api(VirtualProtectEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(VirtualQuery, (arg1, arg2, arg3), 12)
       Api(VirtualQueryEx, (arg1, arg2, arg3, arg4), 16)
       Api(VirtualUnlock, (arg1, arg2), 8)
       Api(WaitCommEvent, (arg1, arg2, arg3), 12)
       Api(WaitForDebugEvent, (arg1, arg2), 8)
       Api(WaitForMultipleObjects, (arg1, arg2, arg3, arg4), 16)
       Api(WaitForMultipleObjectsEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WaitForSingleObject, (arg1, arg2), 8)
       Api(WaitForSingleObjectEx, (arg1, arg2, arg3), 12)
  AnsiWide(WaitNamedPipe, (arg1, arg2), 8)
       Api(WideCharToMultiByte, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(WinExec, (*lpCmdLine, uCmdShow), 8)
  AnsiWide(WriteConsole, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(WriteConsoleInput, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(WriteConsoleInputVDM, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(WriteConsoleOutput, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WriteConsoleOutputAttribute, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(WriteConsoleOutputCharacter, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WriteFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WriteFileEx, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(WritePrivateProfileSection, (arg1, arg2, arg3), 12)
  AnsiWide(WritePrivateProfileString, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(WritePrivateProfileStruct, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WriteProcessMemory, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(WriteProfileSection, (arg1, arg2), 8)
  AnsiWide(WriteProfileString, (arg1, arg2, arg3), 12)
       Api(WriteTapemark, (arg1, arg2, arg3, arg4), 16)
EndImport
