XIncludeFile "common.pbi"

Import "mapi32.lib"
       Api(BuildDisplayTable, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(CbOfEncoded, (arg1), 4)
       Api(CchOfEncoding, (arg1), 4)
       Api(ChangeIdleRoutine, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CloseIMsgSession, (arg1), 4)
       Api(CreateIProp, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CreateTable, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(DeinitMapiUtil, (), 0)
       Api(DeregisterIdleRoutine, (arg1), 4)
       Api(EnableIdleRoutine, (arg1, arg2), 8)
       Api(EncodeID, (arg1, arg2, arg3), 12)
       Api(FBadColumnSet, (arg1), 4)
       Api(FBadEntryList, (arg1), 4)
       Api(FBadProp, (arg1), 4)
       Api(FBadPropTag, (arg1), 4)
       Api(FBadRestriction, (arg1), 4)
       Api(FBadRglpNameID, (arg1, arg2), 8)
  AnsiWide(FBadRglpsz, (arg1, arg2), 8)
       Api(FBadRow, (arg1), 4)
       Api(FBadRowSet, (arg1), 4)
       Api(FBadSortOrderSet, (arg1), 4)
       Api(FBinFromHex, (arg1, arg2), 8)
       Api(FDecodeID, (arg1, arg2, arg3), 12)
       Api(FEqualNames, (arg1, arg2), 8)
       Api(FPropCompareProp, (arg1, arg2, arg3), 12)
       Api(FPropContainsProp, (arg1, arg2, arg3), 12)
       Api(FPropExists, (arg1, arg2), 8)
       Api(FreePadrlist, (arg1), 4)
       Api(FreeProws, (arg1), 4)
       Api(FtAdcFt, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(FtAddFt, (arg1, arg2, arg3, arg4), 16)
       Api(FtDivFtBogus, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(FtgRegisterIdleRoutine, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(FtMulDw, (arg1, arg2, arg3), 12)
       Api(FtMulDwDw, (arg1, arg2), 8)
       Api(FtNegFt, (arg1, arg2), 8)
       Api(FtSubFt, (arg1, arg2, arg3, arg4), 16)
       Api(GetAttribIMsgOnIStg, (arg1, arg2, arg3), 12)
       Api(GetTnefStreamCodepage, (arg1, arg2, arg3), 12)
       Api(HexFromBin, (arg1, arg2, arg3), 12)
       Api(HrAddColumns, (arg1, arg2, arg3, arg4), 16)
       Api(HrAddColumnsEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(HrAllocAdviseSink, (arg1, arg2, arg3), 12)
       Api(HrComposeEID, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(HrComposeMsgID, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(HrDecomposeEID, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(HrDecomposeMsgID, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(HrDispatchNotifications, (arg1), 4)
       Api(HrEntryIDFromSz, (arg1, arg2, arg3), 12)
       Api(HrGetOneProp, (arg1, arg2, arg3), 12)
       Api(HrIStorageFromStream, (arg1, arg2, arg3, arg4), 16)
       Api(HrQueryAllRows, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(HrSetOneProp, (arg1, arg2), 8)
       Api(HrSzFromEntryID, (arg1, arg2, arg3), 12)
       Api(HrThisThreadAdviseSink, (arg1, arg2), 8)
       Api(HrValidateIPMSubtree, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(HrValidateParameters, (arg1, arg2), 8)
       Api(InstallFilterHook, (arg1), 4)
       Api(IsBadBoundedStringPtr, (arg1, arg2), 8)
       Api(LaunchWizard, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(LPropCompareProp, (arg1, arg2), 8)
       Api(LpValFindProp, (arg1, arg2, arg3), 12)
       Api(MAPIAdminProfiles, (arg1, arg2), 8)
       Api(MAPIAllocateBuffer, (arg1, arg2), 8)
       Api(MAPIAllocateMore, (arg1, arg2, arg3), 12)
       Api(MAPIDeinitIdle, (), 0)
       Api(MAPIFreeBuffer, (arg1), 4)
       Api(MAPIGetDefaultMalloc, (), 0)
       Api(MAPIInitialize, (arg1), 4)
       Api(MAPIInitIdle, (arg1), 4)
       Api(MAPILogonEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(MAPIOpenFormMgr, (arg1, arg2), 8)
       Api(MAPIOpenLocalFormContainer, (arg1), 4)
       Api(MAPIUninitialize, (), 0)
       Api(MapStorageSCode, (arg1), 4)
       Api(MNLS_MultiByteToWideChar, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(MNLS_WideCharToMultiByte, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(OpenIMsgOnIStg, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(OpenIMsgSession, (arg1, arg2, arg3), 12)
       Api(OpenStreamOnFile, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(OpenTnefStream, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(OpenTnefStreamEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(PpropFindProp, (arg1, arg2, arg3), 12)
       Api(PropCopyMore, (arg1, arg2, arg3, arg4), 16)
       Api(RTFSync, (arg1, arg2, arg3), 12)
       Api(ScBinFromHexBounded, (arg1, arg2, arg3), 12)
       Api(ScCopyNotifications, (arg1, arg2, arg3, arg4), 16)
       Api(ScCopyProps, (arg1, arg2, arg3, arg4), 16)
       Api(ScCountNotifications, (arg1, arg2, arg3), 12)
       Api(ScCountProps, (arg1, arg2, arg3), 12)
       Api(ScCreateConversationIndex, (arg1, arg2, arg3, arg4), 16)
       Api(ScDupPropset, (arg1, arg2, arg3, arg4), 16)
       Api(ScGenerateMuid, (arg1), 4)
       Api(ScInitMapiUtil, (arg1), 4)
       Api(ScLocalPathFromUNC, (arg1, arg2, arg3), 12)
       Api(ScRelocNotifications, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ScRelocProps, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ScUNCFromLocalPath, (arg1, arg2, arg3), 12)
       Api(SetAttribIMsgOnIStg, (arg1, arg2, arg3, arg4), 16)
       Api(SwapPlong, (arg1, arg2), 8)
       Api(SwapPword, (arg1, arg2), 8)
       Api(SzFindCh, (arg1, arg2), 8)
       Api(SzFindLastCh, (arg1, arg2), 8)
       Api(SzFindSz, (arg1, arg2), 8)
       Api(UFromSz, (arg1), 4)
       Api(UlAddRef, (arg1), 4)
       Api(UlFromSzHex, (arg1), 4)
       Api(UlPropSize, (arg1), 4)
       Api(UlRelease, (arg1), 4)
       Api(UNKOBJ_COFree, (arg1, arg2), 8)
       Api(UNKOBJ_Free, (arg1, arg2), 8)
       Api(UNKOBJ_FreeRows, (arg1, arg2), 8)
       Api(UNKOBJ_ScAllocate, (arg1, arg2, arg3), 12)
       Api(UNKOBJ_ScAllocateMore, (arg1, arg2, arg3, arg4), 16)
       Api(UNKOBJ_ScCOAllocate, (arg1, arg2, arg3), 12)
       Api(UNKOBJ_ScCOReallocate, (arg1, arg2, arg3), 12)
       Api(UNKOBJ_ScSzFromIdsAlloc, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WrapCompressedRTFStream, (arg1, arg2, arg3), 12)
       Api(WrapProgress, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WrapStoreEntryID, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
EndImport
