XIncludeFile "common.pbi"

Import "mpr.lib"
  AnsiWide(MultinetGetConnectionPerformance, (arg1, arg2), 8)
  AnsiWide(MultinetGetErrorText, (arg1, arg2, arg3, arg4), 16)
       Api(RestoreConnectionA0, (arg1, arg2), 8)
  AnsiWide(WNetAddConnection, (arg1, arg2, arg3), 12)
  AnsiWide(WNetAddConnection2, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(WNetAddConnection3, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(WNetCancelConnection, (arg1, arg2), 8)
  AnsiWide(WNetCancelConnection2, (arg1, arg2, arg3), 12)
       Api(WNetClearConnections, (arg1), 4)
       Api(WNetCloseEnum, (arg1), 4)
       Api(WNetConnectionDialog, (arg1, arg2), 8)
  AnsiWide(WNetConnectionDialog1, (arg1), 4)
       Api(WNetConnectionDialog2, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(WNetDirectoryNotify, (arg1, arg2, arg3), 12)
       Api(WNetDisconnectDialog, (arg1, arg2), 8)
  AnsiWide(WNetDisconnectDialog1, (arg1), 4)
       Api(WNetDisconnectDialog2, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(WNetEnumResource, (arg1, arg2, arg3, arg4), 16)
       Api(WNetFMXEditPerm, (arg1, arg2, arg3), 12)
       Api(WNetFMXGetPermCaps, (arg1), 4)
       Api(WNetFMXGetPermHelp, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(WNetFormatNetworkName, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(WNetGetConnection, (arg1, arg2, arg3), 12)
  AnsiWide(WNetGetConnection2, (arg1, arg2, arg3), 12)
  AnsiWide(WNetGetConnection3, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(WNetGetDirectoryType, (arg1, arg2, arg3), 12)
  AnsiWide(WNetGetLastError, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(WNetGetNetworkInformation, (arg1, arg2), 8)
  AnsiWide(WNetGetPropertyText, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(WNetGetProviderName, (arg1, arg2, arg3), 12)
  AnsiWide(WNetGetProviderType, (arg1, arg2), 8)
  AnsiWide(WNetGetResourceInformation, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(WNetGetResourceParent, (arg1, arg2, arg3), 12)
       Api(WNetGetSearchDialog, (arg1), 4)
  AnsiWide(WNetGetUniversalName, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(WNetGetUser, (arg1, arg2, arg3), 12)
       Api(WNetLogonNotify, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
  AnsiWide(WNetOpenEnum, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WNetPasswordChangeNotify, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(WNetPropertyDialog, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(WNetSetConnection, (arg1, arg2, arg3), 12)
  AnsiWide(WNetSetLastError, (arg1, arg2, arg3), 12)
       Api(WNetSupportGlobalEnum, (arg1), 4)
  AnsiWide(WNetUseConnection, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
EndImport
