XIncludeFile "common.pbi"

Import "msacm32.lib"
  AnsiWide(acmDriverAdd, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(acmDriverClose, (arg1, arg2), 8)
  AnsiWide(acmDriverDetails, (arg1, arg2, arg3), 12)
       Api(acmDriverEnum, (arg1, arg2, arg3), 12)
       Api(acmDriverID, (arg1, arg2, arg3), 12)
       Api(acmDriverMessage, (arg1, arg2, arg3, arg4), 16)
       Api(acmDriverOpen, (arg1, arg2, arg3), 12)
       Api(acmDriverPriority, (arg1, arg2, arg3), 12)
       Api(acmDriverRemove, (arg1, arg2), 8)
  AnsiWide(acmFilterChoose, (arg1), 4)
  AnsiWide(acmFilterDetails, (arg1, arg2, arg3), 12)
  AnsiWide(acmFilterEnum, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(acmFilterTagDetails, (arg1, arg2, arg3), 12)
  AnsiWide(acmFilterTagEnum, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(acmFormatChoose, (arg1), 4)
  AnsiWide(acmFormatDetails, (arg1, arg2, arg3), 12)
  AnsiWide(acmFormatEnum, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(acmFormatSuggest, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(acmFormatTagDetails, (arg1, arg2, arg3), 12)
  AnsiWide(acmFormatTagEnum, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(acmGetVersion, (), 0)
       Api(acmMessage32, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(acmMetrics, (arg1, arg2, arg3), 12)
       Api(acmStreamClose, (arg1, arg2), 8)
       Api(acmStreamConvert, (arg1, arg2, arg3), 12)
       Api(acmStreamMessage, (arg1, arg2, arg3, arg4), 16)
       Api(acmStreamOpen, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(acmStreamPrepareHeader, (arg1, arg2, arg3), 12)
       Api(acmStreamReset, (arg1, arg2), 8)
       Api(acmStreamSize, (arg1, arg2, arg3, arg4), 16)
       Api(acmStreamUnprepareHeader, (arg1, arg2, arg3), 12)
EndImport
