XIncludeFile "common.pbi"

Import "mscms.lib"
  AnsiWide(AssociateColorProfileWithDevice, (arg1, arg2, arg3), 12)
       Api(CheckBitmapBits, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(CheckColors, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CloseColorProfile, (arg1), 4)
  AnsiWide(CreateColorTransform, (arg1, arg2, arg3, arg4), 16)
       Api(CreateDeviceLinkProfile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CreateMultiProfileTransform, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(CreateProfileFromLogColorSpace, (arg1, arg2), 8)
       Api(DeleteColorTransform, (arg1), 4)
  AnsiWide(DisassociateColorProfileFromDevice, (arg1, arg2, arg3), 12)
       Api(DllEntryPoint, (arg1, arg2, arg3), 12)
  AnsiWide(EnumColorProfiles, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(EnumerateMonitors, (arg1, arg2, arg3), 12)
       Api(GenerateCopyFilePaths, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(GetCMMInfo, (arg1, arg2), 8)
  AnsiWide(GetColorDirectory, (arg1, arg2, arg3), 12)
       Api(GetColorProfileElement, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetColorProfileElementTag, (arg1, arg2, arg3), 12)
       Api(GetColorProfileFromHandle, (arg1, arg2, arg3), 12)
       Api(GetColorProfileHeader, (arg1, arg2), 8)
       Api(GetCountColorProfileElements, (arg1, arg2), 8)
       Api(GetPS2ColorRenderingDictionary, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetPS2ColorRenderingIntent, (arg1, arg2, arg3, arg4), 16)
       Api(GetPS2ColorSpaceArray, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GetStandardColorSpaceProfile, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InstallColorProfile, (arg1, arg2), 8)
       Api(IsColorProfileTagPresent, (arg1, arg2, arg3), 12)
       Api(IsColorProfileValid, (arg1, arg2), 8)
  AnsiWide(OpenColorProfile, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RegisterCMM, (arg1, arg2, arg3), 12)
       Api(SelectCMM, (arg1), 4)
       Api(SetColorProfileElement, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetColorProfileElementReference, (arg1, arg2, arg3), 12)
       Api(SetColorProfileElementSize, (arg1, arg2, arg3), 12)
       Api(SetColorProfileHeader, (arg1, arg2), 8)
  AnsiWide(SetStandardColorSpaceProfile, (arg1, arg2, arg3), 12)
       Api(SpoolerCopyFileEvent, (arg1, arg2, arg3), 12)
       Api(TranslateBitmapBits, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(TranslateColors, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(UninstallColorProfile, (arg1, arg2, arg3), 12)
  AnsiWide(UnregisterCMM, (arg1, arg2), 8)
EndImport
