XIncludeFile "common.pbi"

Import "msi.lib"
       Api(MsiCloseAllHandles, (), 0)
       Api(MsiCloseHandle, (arg1), 4)
  AnsiWide(MsiCollectUserInfo, (arg1), 4)
  AnsiWide(MsiConfigureFeature, (arg1, arg2, arg3), 12)
  AnsiWide(MsiConfigureProduct, (arg1, arg2, arg3), 12)
       Api(MsiCreateRecord, (arg1), 4)
  AnsiWide(MsiDatabaseApplyTransform, (arg1, arg2, arg3), 12)
       Api(MsiDatabaseCommit, (arg1), 4)
  AnsiWide(MsiDatabaseExport, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(MsiDatabaseGenerateTransform, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(MsiDatabaseGetPrimaryKeys, (arg1, arg2, arg3), 12)
  AnsiWide(MsiDatabaseImport, (arg1, arg2, arg3), 12)
  AnsiWide(MsiDatabaseIsTablePersistent, (arg1, arg2), 8)
  AnsiWide(MsiDatabaseMerge, (arg1, arg2, arg3), 12)
  AnsiWide(MsiDatabaseOpenView, (arg1, arg2, arg3), 12)
  AnsiWide(MsiDoAction, (arg1, arg2), 8)
  AnsiWide(MsiEnableLog, (arg1, arg2, arg3), 12)
       Api(MsiEnableUIPreview, (arg1, arg2), 8)
  AnsiWide(MsiEnumClients, (arg1, arg2, arg3), 12)
  AnsiWide(MsiEnumComponentQualifiers, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(MsiEnumComponents, (arg1, arg2), 8)
  AnsiWide(MsiEnumFeatures, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(MsiEnumProducts, (arg1, arg2), 8)
  AnsiWide(MsiEvaluateCondition, (arg1, arg2), 8)
  AnsiWide(MsiFormatRecord, (arg1, arg2, arg3, arg4), 16)
       Api(MsiGetActiveDatabase, (arg1), 4)
  AnsiWide(MsiGetComponentState, (arg1, arg2, arg3, arg4), 16)
       Api(MsiGetDatabaseState, (arg1), 4)
  AnsiWide(MsiGetFeatureCost, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(MsiGetFeatureInfo, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(MsiGetFeatureState, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(MsiGetFeatureUsage, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(MsiGetFeatureValidStates, (arg1, arg2, arg3), 12)
       Api(MsiGetLanguage, (arg1), 4)
       Api(MsiGetMode, (arg1, arg2), 8)
  AnsiWide(MsiGetProductCode, (arg1, arg2), 8)
  AnsiWide(MsiGetProductInfo, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(MsiGetProductProperty, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(MsiGetProperty, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(MsiGetSourcePath, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(MsiGetSummaryInformation, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(MsiGetTargetPath, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(MsiGetUserInfo, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(MsiInstallMissingComponent, (arg1, arg2, arg3), 12)
  AnsiWide(MsiInstallMissingFile, (arg1, arg2), 8)
  AnsiWide(MsiInstallProduct, (arg1, arg2), 8)
  AnsiWide(MsiLocateComponent, (arg1, arg2, arg3), 12)
  AnsiWide(MsiOpenDatabase, (arg1, arg2, arg3), 12)
  AnsiWide(MsiOpenPackage, (arg1, arg2), 8)
  AnsiWide(MsiOpenProduct, (arg1, arg2), 8)
  AnsiWide(MsiPreviewBillboard, (arg1, arg2, arg3), 12)
  AnsiWide(MsiPreviewDialog, (arg1, arg2), 8)
       Api(MsiProcessMessage, (arg1, arg2, arg3), 12)
  AnsiWide(MsiProvideComponent, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(MsiProvideQualifiedComponent, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(MsiQueryFeatureState, (arg1, arg2), 8)
  AnsiWide(MsiQueryProductState, (arg1), 4)
       Api(MsiRecordClearData, (arg1), 4)
       Api(MsiRecordDataSize, (arg1, arg2), 8)
       Api(MsiRecordGetFieldCount, (arg1), 4)
       Api(MsiRecordGetInteger, (arg1, arg2), 8)
  AnsiWide(MsiRecordGetString, (arg1, arg2, arg3, arg4), 16)
       Api(MsiRecordIsNull, (arg1, arg2), 8)
       Api(MsiRecordReadStream, (arg1, arg2, arg3, arg4), 16)
       Api(MsiRecordSetInteger, (arg1, arg2, arg3), 12)
  AnsiWide(MsiRecordSetStream, (arg1, arg2, arg3), 12)
  AnsiWide(MsiRecordSetString, (arg1, arg2, arg3), 12)
  AnsiWide(MsiReinstallFeature, (arg1, arg2, arg3), 12)
  AnsiWide(MsiReinstallProduct, (arg1, arg2), 8)
  AnsiWide(MsiSequence, (arg1, arg2, arg3), 12)
  AnsiWide(MsiSetComponentState, (arg1, arg2, arg3), 12)
  AnsiWide(MsiSetExternalUI, (arg1, arg2, arg3), 12)
  AnsiWide(MsiSetFeatureState, (arg1, arg2, arg3), 12)
       Api(MsiSetInstallLevel, (arg1, arg2), 8)
       Api(MsiSetInternalUI, (arg1, arg2), 8)
       Api(MsiSetMode, (arg1, arg2, arg3), 12)
  AnsiWide(MsiSetProperty, (arg1, arg2, arg3), 12)
  AnsiWide(MsiSetTargetPath, (arg1, arg2, arg3), 12)
  AnsiWide(MsiSummaryInfoGetProperty, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(MsiSummaryInfoGetPropertyCount, (arg1, arg2), 8)
       Api(MsiSummaryInfoPersist, (arg1), 4)
  AnsiWide(MsiSummaryInfoSetProperty, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(MsiUseFeature, (arg1, arg2), 8)
  AnsiWide(MsiVerifyPackage, (arg1), 4)
       Api(MsiViewClose, (arg1), 4)
       Api(MsiViewExecute, (arg1, arg2), 8)
       Api(MsiViewFetch, (arg1, arg2), 8)
       Api(MsiViewGetColumnInfo, (arg1, arg2, arg3), 12)
  AnsiWide(MsiViewGetError, (arg1, arg2, arg3), 12)
       Api(MsiViewModify, (arg1, arg2, arg3), 12)
EndImport
