XIncludeFile "common.pbi"

Import "nal.lib"
       Api(AllocNetworkBuffer, (arg1, arg2), 8)
       Api(CancelTransmit, (arg1, arg2), 8)
       Api(ClearStatistics, (arg1), 4)
       Api(CloseNetwork, (arg1, arg2), 8)
       Api(CompactNetworkBuffer, (arg1), 4)
       Api(ContinueCapturing, (arg1), 4)
       Api(DestroyNetworkID, (arg1), 4)
       Api(EnumNetworks, (), 0)
       Api(FreeNetworkBuffer, (arg1), 4)
       Api(GetBufferSize, (arg1), 4)
       Api(GetBufferTimeStamp, (arg1, arg2), 8)
       Api(GetBufferTotalBytesCaptured, (arg1), 4)
       Api(GetBufferTotalFramesCaptured, (arg1), 4)
       Api(GetNetworkBuffer, (arg1), 4)
       Api(GetNetworkCallback, (arg1), 4)
       Api(GetNetworkFrame, (arg1, arg2), 8)
       Api(GetNetworkID, (arg1), 4)
       Api(GetNetworkInfo, (arg1), 4)
       Api(GetNetworkInstanceData, (arg1), 4)
       Api(GetReconnectInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetworkProc, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(OpenNetwork, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(PauseCapturing, (arg1), 4)
       Api(QueryNetworkStatus, (arg1, arg2), 8)
       Api(SetNetworkBuffer, (arg1, arg2), 8)
       Api(SetNetworkCallback, (arg1, arg2), 8)
       Api(SetNetworkFilter, (arg1, arg2, arg3), 12)
       Api(SetNetworkInstanceData, (arg1, arg2), 8)
       Api(SetReconnectInfo, (arg1, arg2, arg3), 12)
       Api(SetupNetwork, (arg1, arg2), 8)
       Api(StartCapturing, (arg1, arg2), 8)
       Api(StationQuery, (arg1, arg2, arg3, arg4), 16)
       Api(StopCapturing, (arg1), 4)
       Api(TransmitQueue, (arg1, arg2), 8)
       Api(TransmitSpecialFrame, (arg1, arg2, arg3, arg4), 16)
EndImport
