XIncludeFile "common.pbi"

Import "netapi32.lib"
       Api(I_BrowserDebugCall, (arg1, arg2, arg3), 12)
       Api(I_BrowserDebugTrace, (arg1, arg2), 8)
       Api(I_BrowserQueryOtherDomains, (arg1, arg2, arg3, arg4), 16)
       Api(I_BrowserQueryStatistics, (arg1, arg2), 8)
       Api(I_BrowserResetNetlogonState, (arg1), 4)
       Api(I_BrowserResetStatistics, (arg1), 4)
       Api(I_BrowserServerEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(I_NetAccountDeltas, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(I_NetAccountSync, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(I_NetDatabaseDeltas, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(I_NetDatabaseRedo, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(I_NetDatabaseSync, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(I_NetDatabaseSync2, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(I_NetGetDCList, (arg1, arg2, arg3, arg4), 16)
       Api(I_NetListCanonicalize, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(I_NetListTraverse, (arg1, arg2, arg3), 12)
       Api(I_NetLogonControl, (arg1, arg2, arg3, arg4), 16)
       Api(I_NetLogonControl2, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(I_NetLogonSamLogoff, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(I_NetLogonSamLogon, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(I_NetLogonUasLogoff, (arg1, arg2, arg3), 12)
       Api(I_NetLogonUasLogon, (arg1, arg2, arg3), 12)
       Api(I_NetNameCanonicalize, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(I_NetNameCompare, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(I_NetNameValidate, (arg1, arg2, arg3, arg4), 16)
       Api(I_NetPathCanonicalize, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(I_NetPathCompare, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(I_NetPathType, (arg1, arg2, arg3, arg4), 16)
       Api(I_NetServerAuthenticate, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(I_NetServerAuthenticate2, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(I_NetServerPasswordSet, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(I_NetServerReqChallenge, (arg1, arg2, arg3, arg4), 16)
       Api(I_NetServerSetServiceBits, (arg1, arg2, arg3, arg4), 16)
       Api(NetAlertRaise, (arg1, arg2, arg3), 12)
       Api(NetAlertRaiseEx, (arg1, arg2, arg3, arg4), 16)
       Api(NetApiBufferAllocate, (arg1, arg2), 8)
       Api(NetApiBufferFree, (arg1), 4)
       Api(NetApiBufferReallocate, (arg1, arg2, arg3), 12)
       Api(NetApiBufferSize, (arg1, arg2), 8)
       Api(NetapipBufferAllocate, (arg1, arg2), 8)
       Api(NetAuditClear, (arg1, arg2, arg3), 12)
       Api(NetAuditRead, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(NetAuditWrite, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(Netbios, (arg1), 4)
       Api(NetBrowserStatisticsGet, (arg1, arg2, arg3), 12)
       Api(NetConfigGet, (arg1, arg2, arg3, arg4), 16)
       Api(NetConfigGetAll, (arg1, arg2, arg3), 12)
       Api(NetConfigSet, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetConnectionEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NetErrorLogClear, (arg1, arg2, arg3), 12)
       Api(NetErrorLogRead, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(NetErrorLogWrite, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NetFileClose, (arg1, arg2), 8)
       Api(NetFileEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(NetFileGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetGetAnyDCName, (arg1, arg2, arg3), 12)
       Api(NetGetDCName, (arg1, arg2, arg3), 12)
       Api(NetGroupAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetGroupAddUser, (arg1, arg2, arg3), 12)
       Api(NetGroupDel, (arg1, arg2), 8)
       Api(NetGroupDelUser, (arg1, arg2, arg3), 12)
       Api(NetGroupEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetGroupGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetGroupGetUsers, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NetGroupSetInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetGroupSetUsers, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetLocalGroupAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetLocalGroupAddMember, (arg1, arg2, arg3), 12)
       Api(NetLocalGroupDel, (arg1, arg2), 8)
       Api(NetLocalGroupDelMember, (arg1, arg2, arg3), 12)
       Api(NetLocalGroupEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetLocalGroupGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetLocalGroupGetMembers, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NetLocalGroupSetInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetLocalGroupSetMembers, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetMessageBufferSend, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetMessageNameAdd, (arg1, arg2), 8)
       Api(NetMessageNameDel, (arg1, arg2), 8)
       Api(NetMessageNameEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetMessageNameGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetpAccessCheckAndAudit, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetpAllocConfigName, (arg1, arg2, arg3, arg4), 16)
       Api(NetpAllocStrFromWStr, (arg1), 4)
       Api(NetpAllocWStrFromStr, (arg1), 4)
       Api(NetpAllocWStrFromWStr, (arg1), 4)
       Api(NetpApiStatusToNtStatus, (arg1), 4)
       Api(NetpAssertFailed, (arg1, arg2, arg3, arg4), 16)
       Api(NetpCloseConfigData, (arg1), 4)
       Api(NetpCopyStringToBuffer, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetpCreateSecurityObject, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NetpDbgDisplayServerInfo, (arg1, arg2), 8)
       Api(NetpDeleteSecurityObject, (arg1), 4)
       Api(NetpGetComputerName, (arg1), 4)
       Api(NetpGetConfigBool, (arg1, arg2, arg3, arg4), 16)
       Api(NetpGetConfigDword, (arg1, arg2, arg3, arg4), 16)
       Api(NetpGetConfigTStrArray, (arg1, arg2, arg3), 12)
       Api(NetpGetConfigValue, (arg1, arg2, arg3), 12)
       Api(NetpGetDomainName, (arg1), 4)
       Api(NetpGetFileSecurity, (arg1, arg2, arg3, arg4), 16)
       Api(NetpGetPrivilege, (arg1, arg2), 8)
       Api(NetpHexDump, (arg1, arg2), 8)
       Api(NetpInitOemString, (arg1, arg2), 8)
       Api(NetpIsRemote, (arg1, arg2, arg3, arg4), 16)
       Api(NetpIsUncComputerNameValid, (arg1), 4)
       Api(NetpLocalTimeZoneOffset, (), 0)
       Api(NetpLogonPutUnicodeString, (arg1, arg2, arg3), 12)
       Api(NetpNetBiosAddName, (arg1, arg2, arg3), 12)
       Api(NetpNetBiosCall, (arg1, arg2, arg3, arg4), 16)
       Api(NetpNetBiosDelName, (arg1, arg2), 8)
       Api(NetpNetBiosGetAdapterNumbers, (arg1, arg2), 8)
       Api(NetpNetBiosHangup, (arg1, arg2), 8)
       Api(NetpNetBiosReceive, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NetpNetBiosReset, (arg1), 4)
       Api(NetpNetBiosSend, (arg1, arg2, arg3, arg4), 16)
       Api(NetpNetBiosStatusToApiStatus, (arg1), 4)
       Api(NetpNtStatusToApiStatus, (arg1), 4)
       Api(NetpOpenConfigData, (arg1, arg2, arg3, arg4), 16)
       Api(NetpPackString, (arg1, arg2, arg3), 12)
       Api(NetpReleasePrivilege, (), 0)
       Api(NetpSetConfigBool, (arg1, arg2, arg3), 12)
       Api(NetpSetConfigDword, (arg1, arg2, arg3), 12)
       Api(NetpSetConfigTStrArray, (arg1, arg2, arg3), 12)
       Api(NetpSetFileSecurity, (arg1, arg2, arg3), 12)
       Api(NetpSmbCheck, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetpStringToNetBiosName, (arg1, arg2, arg3, arg4), 16)
       Api(NetpTStrArrayEntryCount, (arg1), 4)
       Api(NetpwNameCanonicalize, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetpwNameCompare, (arg1, arg2, arg3, arg4), 16)
       Api(NetpwNameValidate, (arg1, arg2, arg3), 12)
       Api(NetpwPathCanonicalize, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NetpwPathCompare, (arg1, arg2, arg3, arg4), 16)
       Api(NetpwPathType, (arg1, arg2, arg3), 12)
       Api(NetRemoteComputerSupports, (arg1, arg2, arg3), 12)
       Api(NetRemoteTOD, (arg1, arg2), 8)
       Api(NetReplExportDirAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetReplExportDirDel, (arg1, arg2), 8)
       Api(NetReplExportDirEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetReplExportDirGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetReplExportDirLock, (arg1, arg2), 8)
       Api(NetReplExportDirSetInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetReplExportDirUnlock, (arg1, arg2, arg3), 12)
       Api(NetReplGetInfo, (arg1, arg2, arg3), 12)
       Api(NetReplImportDirAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetReplImportDirDel, (arg1, arg2), 8)
       Api(NetReplImportDirEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetReplImportDirGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetReplImportDirLock, (arg1, arg2), 8)
       Api(NetReplImportDirUnlock, (arg1, arg2, arg3), 12)
       Api(NetReplSetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplAdapterAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplAdapterDel, (arg1, arg2), 8)
       Api(NetRplAdapterEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetRplBootAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplBootDel, (arg1, arg2, arg3), 12)
       Api(NetRplBootEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetRplClose, (arg1), 4)
       Api(NetRplConfigAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplConfigDel, (arg1, arg2), 8)
       Api(NetRplConfigEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NetRplGetInfo, (arg1, arg2, arg3), 12)
       Api(NetRplOpen, (arg1, arg2), 8)
       Api(NetRplProfileAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplProfileClone, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplProfileDel, (arg1, arg2), 8)
       Api(NetRplProfileEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NetRplProfileGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplProfileSetInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetRplSetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplSetSecurity, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplVendorAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplVendorDel, (arg1, arg2), 8)
       Api(NetRplVendorEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetRplWkstaAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplWkstaClone, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NetRplWkstaDel, (arg1, arg2), 8)
       Api(NetRplWkstaEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NetRplWkstaGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetRplWkstaSetInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetScheduleJobAdd, (arg1, arg2, arg3), 12)
       Api(NetScheduleJobDel, (arg1, arg2, arg3), 12)
       Api(NetScheduleJobEnum, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NetScheduleJobGetInfo, (arg1, arg2, arg3), 12)
       Api(NetServerDiskEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetServerEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(NetServerGetInfo, (arg1, arg2, arg3), 12)
       Api(NetServerSetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetServerTransportAdd, (arg1, arg2, arg3), 12)
       Api(NetServerTransportDel, (arg1, arg2, arg3), 12)
       Api(NetServerTransportEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetServiceControl, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetServiceEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetServiceGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetServiceInstall, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetSessionDel, (arg1, arg2, arg3), 12)
       Api(NetSessionEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(NetSessionGetInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetShareAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetShareCheck, (arg1, arg2, arg3), 12)
       Api(NetShareDel, (arg1, arg2, arg3), 12)
       Api(NetShareDelSticky, (arg1, arg2, arg3), 12)
       Api(NetShareEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetShareEnumSticky, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetShareGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetShareSetInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetStatisticsGet, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetUseAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetUseDel, (arg1, arg2, arg3), 12)
       Api(NetUseEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetUseGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetUserAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetUserDel, (arg1, arg2), 8)
       Api(NetUserEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NetUserGetGroups, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetUserGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetUserGetLocalGroups, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NetUserModalsGet, (arg1, arg2, arg3), 12)
       Api(NetUserModalsSet, (arg1, arg2, arg3, arg4), 16)
       Api(NetUserSetGroups, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetUserSetInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NetWkstaGetInfo, (arg1, arg2, arg3), 12)
       Api(NetWkstaSetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NetWkstaTransportAdd, (arg1, arg2, arg3, arg4), 16)
       Api(NetWkstaTransportDel, (arg1, arg2, arg3), 12)
       Api(NetWkstaTransportEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetWkstaUserEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NetWkstaUserGetInfo, (arg1, arg2, arg3), 12)
       Api(NetWkstaUserSetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(NlBindingAddServerToCache, (arg1), 4)
       Api(NlBindingRemoveServerFromCache, (arg1), 4)
       Api(RxNetAccessAdd, (arg1, arg2, arg3, arg4), 16)
       Api(RxNetAccessDel, (arg1, arg2), 8)
       Api(RxNetAccessEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(RxNetAccessGetInfo, (arg1, arg2, arg3, arg4), 16)
       Api(RxNetAccessGetUserPerms, (arg1, arg2, arg3, arg4), 16)
       Api(RxNetAccessSetInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RxNetServerEnum, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(RxNetUserPasswordSet, (arg1, arg2, arg3, arg4), 16)
EndImport
