XIncludeFile "common.pbi"

Import "ntdll.lib"
       Api(CsrAllocateCaptureBuffer, (arg1, arg2, arg3), 12)
       Api(CsrAllocateCapturePointer, (arg1, arg2, arg3), 12)
       Api(CsrAllocateMessagePointer, (arg1, arg2, arg3), 12)
       Api(CsrCaptureMessageBuffer, (arg1, arg2, arg3, arg4), 16)
       Api(CsrCaptureMessageString, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CsrCaptureTimeout, (arg1, arg2), 8)
       Api(CsrClientCallServer, (arg1, arg2, arg3, arg4), 16)
       Api(CsrClientConnectToServer, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CsrFreeCaptureBuffer, (arg1), 4)
       Api(CsrIdentifyAlertableThread, (), 0)
       Api(CsrNewThread, (), 0)
       Api(CsrProbeForRead, (arg1, arg2, arg3), 12)
       Api(CsrProbeForWrite, (arg1, arg2, arg3), 12)
       Api(CsrSetPriorityClass, (arg1, arg2), 8)
       Api(DbgBreakPoint, (), 0)
       Api(DbgPrompt, (arg1, arg2, arg3), 12)
       Api(DbgSsHandleKmApiMsg, (arg1, arg2), 8)
       Api(DbgSsInitialize, (arg1, arg2, arg3, arg4), 16)
       Api(DbgUiConnectToDbg, (), 0)
       Api(DbgUiContinue, (arg1, arg2), 8)
       Api(DbgUiWaitStateChange, (arg1, arg2), 8)
       Api(DbgUserBreakPoint, (), 0)
       Api(KiRaiseUserExceptionDispatcher, (), 0)
       Api(KiUserApcDispatcher, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(KiUserCallbackDispatcher, (arg1, arg2, arg3), 12)
       Api(KiUserExceptionDispatcher, (arg1, arg2), 8)
       Api(LdrAccessResource, (arg1, arg2, arg3, arg4), 16)
       Api(LdrDisableThreadCalloutsForDll, (arg1), 4)
       Api(LdrEnumResources, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(LdrFindEntryForAddress, (arg1, arg2), 8)
       Api(LdrFindResource_U, (arg1, arg2, arg3, arg4), 16)
       Api(LdrFindResourceDirectory_U, (arg1, arg2, arg3, arg4), 16)
       Api(LdrGetDllHandle, (arg1, arg2, arg3, arg4), 16)
       Api(LdrGetProcedureAddress, (arg1, arg2, arg3, arg4), 16)
       Api(LdrInitializeThunk, (arg1, arg2, arg3, arg4), 16)
       Api(LdrLoadDll, (arg1, arg2, arg3, arg4), 16)
       Api(LdrProcessRelocationBlock, (arg1, arg2, arg3, arg4), 16)
       Api(LdrQueryImageFileExecutionOptions, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(LdrQueryProcessModuleInformation, (arg1, arg2, arg3), 12)
       Api(LdrShutdownProcess, (), 0)
       Api(LdrShutdownThread, (), 0)
       Api(LdrUnloadDll, (arg1), 4)
       Api(LdrVerifyImageMatchesChecksum, (arg1, arg2, arg3, arg4), 16)
       Api(NtAcceptConnectPort, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtAccessCheck, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NtAccessCheckAndAuditAlarm, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(NtAddAtom, (arg1, arg2), 8)
       Api(NtAdjustGroupsToken, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtAdjustPrivilegesToken, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtAlertResumeThread, (arg1, arg2), 8)
       Api(NtAlertThread, (arg1), 4)
       Api(NtAllocateLocallyUniqueId, (arg1), 4)
       Api(NtAllocateUuids, (arg1, arg2, arg3), 12)
       Api(NtAllocateVirtualMemory, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtCallbackReturn, (arg1, arg2, arg3), 12)
       Api(NtCancelIoFile, (arg1, arg2), 8)
       Api(NtCancelTimer, (arg1, arg2), 8)
       Api(NtClearEvent, (arg1), 4)
       Api(NtClose, (arg1), 4)
       Api(NtCloseObjectAuditAlarm, (arg1, arg2, arg3), 12)
       Api(NtCompleteConnectPort, (arg1), 4)
       Api(NtConnectPort, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NtContinue, (arg1, arg2), 8)
       Api(NtCreateChannel, (arg1, arg2), 8)
       Api(NtCreateDirectoryObject, (arg1, arg2, arg3), 12)
       Api(NtCreateEvent, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtCreateEventPair, (arg1, arg2, arg3), 12)
       Api(NtCreateFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(NtCreateIoCompletion, (arg1, arg2, arg3, arg4), 16)
       Api(NtCreateKey, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NtCreateMailslotFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NtCreateMutant, (arg1, arg2, arg3, arg4), 16)
       Api(NtCreateNamedPipeFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14), 56)
       Api(NtCreatePagingFile, (arg1, arg2, arg3, arg4), 16)
       Api(NtCreatePort, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtCreateProcess, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NtCreateProfile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(NtCreateSection, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NtCreateSemaphore, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtCreateSymbolicLinkObject, (arg1, arg2, arg3, arg4), 16)
       Api(NtCreateThread, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(NtCreateTimer, (arg1, arg2, arg3, arg4), 16)
       Api(NtCreateToken, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13), 52)
       Api(NtCurrentTeb, (), 0)
       Api(NtDelayExecution, (arg1, arg2), 8)
       Api(NtDeleteAtom, (arg1), 4)
       Api(NtDeleteFile, (arg1), 4)
       Api(NtDeleteKey, (arg1), 4)
       Api(NtDeleteObjectAuditAlarm, (arg1, arg2, arg3), 12)
       Api(NtDeleteValueKey, (arg1, arg2), 8)
       Api(NtDeviceIoControlFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(NtDisplayString, (arg1), 4)
       Api(NtDuplicateObject, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NtDuplicateToken, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtEnumerateKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtEnumerateValueKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtExtendSection, (arg1, arg2), 8)
       Api(NtFindAtom, (arg1, arg2), 8)
       Api(NtFlushBuffersFile, (arg1, arg2), 8)
       Api(NtFlushInstructionCache, (arg1, arg2, arg3), 12)
       Api(NtFlushKey, (arg1), 4)
       Api(NtFlushVirtualMemory, (arg1, arg2, arg3, arg4), 16)
       Api(NtFlushWriteBuffer, (), 0)
       Api(NtFreeVirtualMemory, (arg1, arg2, arg3, arg4), 16)
       Api(NtFsControlFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(NtGetContextThread, (arg1, arg2), 8)
       Api(NtGetPlugPlayEvent, (arg1, arg2, arg3, arg4), 16)
       Api(NtGetTickCount, (), 0)
       Api(NtImpersonateClientOfPort, (arg1, arg2), 8)
       Api(NtImpersonateThread, (arg1, arg2, arg3), 12)
       Api(NtInitializeRegistry, (arg1), 4)
       Api(NtListenChannel, (arg1, arg2), 8)
       Api(NtListenPort, (arg1, arg2), 8)
       Api(NtLoadDriver, (arg1), 4)
       Api(NtLoadKey, (arg1, arg2), 8)
       Api(NtLoadKey2, (arg1, arg2, arg3), 12)
       Api(NtLockFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(NtLockVirtualMemory, (arg1, arg2, arg3, arg4), 16)
       Api(NtMakeTemporaryObject, (arg1), 4)
       Api(NtMapViewOfSection, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(NtNotifyChangeDirectoryFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(NtNotifyChangeKey, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(NtOpenChannel, (arg1, arg2), 8)
       Api(NtOpenDirectoryObject, (arg1, arg2, arg3), 12)
       Api(NtOpenEvent, (arg1, arg2, arg3), 12)
       Api(NtOpenEventPair, (arg1, arg2, arg3), 12)
       Api(NtOpenFile, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtOpenIoCompletion, (arg1, arg2, arg3), 12)
       Api(NtOpenKey, (arg1, arg2, arg3), 12)
       Api(NtOpenMutant, (arg1, arg2, arg3), 12)
       Api(NtOpenObjectAuditAlarm, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(NtOpenProcess, (arg1, arg2, arg3, arg4), 16)
       Api(NtOpenProcessToken, (arg1, arg2, arg3), 12)
       Api(NtOpenSection, (arg1, arg2, arg3), 12)
       Api(NtOpenSemaphore, (arg1, arg2, arg3), 12)
       Api(NtOpenSymbolicLinkObject, (arg1, arg2, arg3), 12)
       Api(NtOpenThread, (arg1, arg2, arg3, arg4), 16)
       Api(NtOpenThreadToken, (arg1, arg2, arg3, arg4), 16)
       Api(NtOpenTimer, (arg1, arg2, arg3), 12)
       Api(NtPlugPlayControl, (arg1, arg2, arg3, arg4), 16)
       Api(NtPrivilegeCheck, (arg1, arg2, arg3), 12)
       Api(NtPrivilegedServiceAuditAlarm, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtPrivilegeObjectAuditAlarm, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtProtectVirtualMemory, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtPulseEvent, (arg1, arg2), 8)
       Api(NtQueryAttributesFile, (arg1, arg2), 8)
       Api(NtQueryDefaultLocale, (arg1, arg2), 8)
       Api(NtQueryDirectoryFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(NtQueryDirectoryObject, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NtQueryEaFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(NtQueryEvent, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryFullAttributesFile, (arg1, arg2), 8)
       Api(NtQueryInformationAtom, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryInformationFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryInformationPort, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryInformationProcess, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryInformationThread, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryInformationToken, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryIntervalProfile, (arg1, arg2), 8)
       Api(NtQueryIoCompletion, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryKey, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryMultipleValueKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtQueryMutant, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryObject, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryOleDirectoryFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(NtQueryPerformanceCounter, (arg1, arg2), 8)
       Api(NtQuerySection, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQuerySecurityObject, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQuerySemaphore, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQuerySymbolicLinkObject, (arg1, arg2, arg3), 12)
       Api(NtQuerySystemEnvironmentValue, (arg1, arg2, arg3, arg4), 16)
       Api(NtQuerySystemInformation, (arg1, arg2, arg3, arg4), 16)
       Api(NtQuerySystemTime, (arg1), 4)
       Api(NtQueryTimer, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueryTimerResolution, (arg1, arg2, arg3), 12)
       Api(NtQueryValueKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtQueryVirtualMemory, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtQueryVolumeInformationFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtQueueApcThread, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtRaiseException, (arg1, arg2, arg3), 12)
       Api(NtRaiseHardError, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtReadFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(NtReadRequestData, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtReadVirtualMemory, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtRegisterThreadTerminatePort, (arg1), 4)
       Api(NtReleaseMutant, (arg1, arg2), 8)
       Api(NtReleaseSemaphore, (arg1, arg2, arg3), 12)
       Api(NtRemoveIoCompletion, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtReplaceKey, (arg1, arg2, arg3), 12)
       Api(NtReplyPort, (arg1, arg2), 8)
       Api(NtReplyWaitReceivePort, (arg1, arg2, arg3, arg4), 16)
       Api(NtReplyWaitReplyPort, (arg1, arg2), 8)
       Api(NtReplyWaitSendChannel, (arg1, arg2, arg3), 12)
       Api(NtRequestPort, (arg1, arg2), 8)
       Api(NtRequestWaitReplyPort, (arg1, arg2, arg3), 12)
       Api(NtResetEvent, (arg1, arg2), 8)
       Api(NtRestoreKey, (arg1, arg2, arg3), 12)
       Api(NtResumeThread, (arg1, arg2), 8)
       Api(NtSaveKey, (arg1, arg2), 8)
       Api(NtSendWaitReplyChannel, (arg1, arg2, arg3, arg4), 16)
       Api(NtSetContextChannel, (arg1), 4)
       Api(NtSetContextThread, (arg1, arg2), 8)
       Api(NtSetDefaultHardErrorPort, (arg1), 4)
       Api(NtSetDefaultLocale, (arg1, arg2), 8)
       Api(NtSetEaFile, (arg1, arg2, arg3, arg4), 16)
       Api(NtSetEvent, (arg1, arg2), 8)
       Api(NtSetHighEventPair, (arg1), 4)
       Api(NtSetHighWaitLowEventPair, (arg1), 4)
       Api(NtSetHighWaitLowThread, (), 0)
       Api(NtSetInformationFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtSetInformationKey, (arg1, arg2, arg3, arg4), 16)
       Api(NtSetInformationObject, (arg1, arg2, arg3, arg4), 16)
       Api(NtSetInformationProcess, (arg1, arg2, arg3, arg4), 16)
       Api(NtSetInformationThread, (arg1, arg2, arg3, arg4), 16)
       Api(NtSetInformationToken, (arg1, arg2, arg3, arg4), 16)
       Api(NtSetIntervalProfile, (arg1, arg2), 8)
       Api(NtSetIoCompletion, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtSetLdtEntries, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtSetLowEventPair, (arg1), 4)
       Api(NtSetLowWaitHighEventPair, (arg1), 4)
       Api(NtSetLowWaitHighThread, (), 0)
       Api(NtSetSecurityObject, (arg1, arg2, arg3), 12)
       Api(NtSetSystemEnvironmentValue, (arg1, arg2), 8)
       Api(NtSetSystemInformation, (arg1, arg2, arg3), 12)
       Api(NtSetSystemPowerState, (arg1, arg2, arg3), 12)
       Api(NtSetSystemTime, (arg1, arg2), 8)
       Api(NtSetTimer, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(NtSetTimerResolution, (arg1, arg2, arg3), 12)
       Api(NtSetValueKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtSetVolumeInformationFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtShutdownSystem, (arg1), 4)
       Api(NtSignalAndWaitForSingleObject, (arg1, arg2, arg3, arg4), 16)
       Api(NtStartProfile, (arg1), 4)
       Api(NtStopProfile, (arg1), 4)
       Api(NtSuspendThread, (arg1, arg2), 8)
       Api(NtSystemDebugControl, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtTerminateProcess, (arg1, arg2), 8)
       Api(NtTerminateThread, (arg1, arg2), 8)
       Api(NtTestAlert, (), 0)
       Api(NtUnloadDriver, (arg1), 4)
       Api(NtUnloadKey, (arg1), 4)
       Api(NtUnlockFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtUnlockVirtualMemory, (arg1, arg2, arg3, arg4), 16)
       Api(NtUnmapViewOfSection, (arg1, arg2), 8)
       Api(NtVdmControl, (arg1, arg2), 8)
       Api(NtW32Call, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtWaitForMultipleObjects, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtWaitForSingleObject, (arg1, arg2, arg3), 12)
       Api(NtWaitHighEventPair, (arg1), 4)
       Api(NtWaitLowEventPair, (arg1), 4)
       Api(NtWriteFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(NtWriteRequestData, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NtWriteVirtualMemory, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NtYieldExecution, (), 0)
       Api(PfxFindPrefix, (arg1, arg2), 8)
       Api(PfxInitialize, (arg1), 4)
       Api(PfxInsertPrefix, (arg1, arg2, arg3), 12)
       Api(PfxRemovePrefix, (arg1, arg2), 8)
       Api(RtlAbortRXact, (arg1), 4)
       Api(RtlAbsoluteToSelfRelativeSD, (arg1, arg2, arg3), 12)
       Api(RtlAcquirePebLock, (), 0)
       Api(RtlAcquireResourceExclusive, (arg1, arg2), 8)
       Api(RtlAcquireResourceShared, (arg1, arg2), 8)
       Api(RtlAddAccessAllowedAce, (arg1, arg2, arg3, arg4), 16)
       Api(RtlAddAccessDeniedAce, (arg1, arg2, arg3, arg4), 16)
       Api(RtlAddAce, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlAddActionToRXact, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlAddAtomToAtomTable, (arg1, arg2, arg3), 12)
       Api(RtlAddAttributeActionToRXact, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(RtlAddAuditAccessAce, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlAddCompoundAce, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlAdjustPrivilege, (arg1, arg2, arg3, arg4), 16)
       Api(RtlAllocateAndInitializeSid, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(RtlAllocateHandle, (arg1, arg2), 8)
       Api(RtlAllocateHeap, (arg1, arg2, arg3), 12)
       Api(RtlAnsiCharToUnicodeChar, (arg1), 4)
       Api(RtlAnsiStringToUnicodeSize, (arg1), 4)
       Api(RtlAnsiStringToUnicodeString, (arg1, arg2, arg3), 12)
       Api(RtlAppendAsciizToString, (arg1, arg2), 8)
       Api(RtlAppendStringToString, (arg1, arg2), 8)
       Api(RtlAppendUnicodeStringToString, (arg1, arg2), 8)
       Api(RtlAppendUnicodeToString, (arg1, arg2), 8)
       Api(RtlApplyRXact, (arg1), 4)
       Api(RtlApplyRXactNoFlush, (arg1), 4)
       Api(RtlAreAllAccessesGranted, (arg1, arg2), 8)
       Api(RtlAreAnyAccessesGranted, (arg1, arg2), 8)
       Api(RtlAreBitsClear, (arg1, arg2, arg3), 12)
       Api(RtlAreBitsSet, (arg1, arg2, arg3), 12)
       Api(RtlAssert, (arg1, arg2, arg3, arg4), 16)
       Api(RtlCaptureStackBackTrace, (arg1, arg2, arg3, arg4), 16)
       Api(RtlCharToInteger, (arg1, arg2, arg3), 12)
       Api(RtlCheckRegistryKey, (arg1, arg2), 8)
       Api(RtlClearAllBits, (arg1), 4)
       Api(RtlClearBits, (arg1, arg2, arg3), 12)
       Api(RtlClosePropertySet, (arg1), 4)
       Api(RtlCompactHeap, (arg1, arg2), 8)
       Api(RtlCompareMemory, (arg1, arg2, arg3), 12)
       Api(RtlCompareMemoryUlong, (arg1, arg2, arg3), 12)
       Api(RtlCompareString, (arg1, arg2, arg3), 12)
       Api(RtlCompareUnicodeString, (arg1, arg2, arg3), 12)
       Api(RtlCompressBuffer, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(RtlConsoleMultiByteToUnicodeN, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlConvertExclusiveToShared, (arg1), 4)
       Api(RtlConvertLongToLargeInteger, (arg1), 4)
       Api(RtlConvertSharedToExclusive, (arg1), 4)
       Api(RtlConvertSidToUnicodeString, (arg1, arg2, arg3), 12)
       Api(RtlConvertUiListToApiList, (arg1, arg2, arg3), 12)
       Api(RtlConvertUlongToLargeInteger, (arg1), 4)
       Api(RtlCopyLuid, (arg1, arg2), 8)
       Api(RtlCopyLuidAndAttributesArray, (arg1, arg2, arg3), 12)
       Api(RtlCopySecurityDescriptor, (arg1, arg2), 8)
       Api(RtlCopySid, (arg1, arg2, arg3), 12)
       Api(RtlCopySidAndAttributesArray, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(RtlCopyString, (arg1, arg2), 8)
       Api(RtlCopyUnicodeString, (arg1, arg2), 8)
       Api(RtlCreateAcl, (arg1, arg2, arg3), 12)
       Api(RtlCreateAndSetSD, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlCreateAtomTable, (arg1, arg2), 8)
       Api(RtlCreateEnvironment, (arg1, arg2), 8)
       Api(RtlCreateHeap, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlCreateProcessParameters, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(RtlCreatePropertySet, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(RtlCreateQueryDebugBuffer, (arg1, arg2), 8)
       Api(RtlCreateRegistryKey, (arg1, arg2), 8)
       Api(RtlCreateSecurityDescriptor, (arg1, arg2), 8)
       Api(RtlCreateTagHeap, (arg1, arg2, arg3, arg4), 16)
       Api(RtlCreateUnicodeString, (arg1, arg2), 8)
       Api(RtlCreateUnicodeStringFromAsciiz, (arg1, arg2), 8)
       Api(RtlCreateUserProcess, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(RtlCreateUserSecurityObject, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(RtlCreateUserThread, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(RtlCustomCPToUnicodeN, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlCutoverTimeToSystemTime, (arg1, arg2, arg3, arg4), 16)
       Api(RtlDecompressBuffer, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlDecompressFragment, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(RtlDelete, (arg1), 4)
       Api(RtlDeleteAce, (arg1, arg2), 8)
       Api(RtlDeleteAtomFromAtomTable, (arg1, arg2), 8)
       Api(RtlDeleteCriticalSection, (arg1), 4)
       Api(RtlDeleteElementGenericTable, (arg1, arg2), 8)
       Api(RtlDeleteNoSplay, (arg1, arg2), 8)
       Api(RtlDeleteRegistryValue, (arg1, arg2, arg3), 12)
       Api(RtlDeleteResource, (arg1), 4)
       Api(RtlDeleteSecurityObject, (arg1), 4)
       Api(RtlDeNormalizeProcessParams, (arg1), 4)
       Api(RtlDestroyAtomTable, (arg1), 4)
       Api(RtlDestroyEnvironment, (arg1), 4)
       Api(RtlDestroyHandleTable, (arg1), 4)
       Api(RtlDestroyHeap, (arg1), 4)
       Api(RtlDestroyProcessParameters, (arg1), 4)
       Api(RtlDestroyQueryDebugBuffer, (arg1), 4)
       Api(RtlDetermineDosPathNameType_U, (arg1), 4)
       Api(RtlDoesFileExists_U, (arg1), 4)
       Api(RtlDosPathNameToNtPathName_U, (arg1, arg2, arg3, arg4), 16)
       Api(RtlDosSearchPath_U, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlDowncaseUnicodeString, (arg1, arg2, arg3), 12)
       Api(RtlDumpResource, (arg1), 4)
       Api(RtlEmptyAtomTable, (arg1, arg2), 8)
       Api(RtlEnlargedIntegerMultiply, (arg1, arg2), 8)
       Api(RtlEnlargedUnsignedDivide, (arg1, arg2, arg3, arg4), 16)
       Api(RtlEnlargedUnsignedMultiply, (arg1, arg2), 8)
       Api(RtlEnterCriticalSection, (arg1), 4)
       Api(RtlEnumerateGenericTable, (arg1, arg2), 8)
       Api(RtlEnumerateGenericTableWithoutSplaying, (arg1, arg2), 8)
       Api(RtlEnumerateProperties, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlEnumProcessHeaps, (arg1, arg2), 8)
       Api(RtlEqualComputerName, (arg1, arg2), 8)
       Api(RtlEqualDomainName, (arg1, arg2), 8)
       Api(RtlEqualLuid, (arg1, arg2), 8)
       Api(RtlEqualPrefixSid, (arg1, arg2), 8)
       Api(RtlEqualSid, (arg1, arg2), 8)
       Api(RtlEqualString, (arg1, arg2, arg3), 12)
       Api(RtlEqualUnicodeString, (arg1, arg2, arg3), 12)
       Api(RtlEraseUnicodeString, (arg1), 4)
       Api(RtlExpandEnvironmentStrings_U, (arg1, arg2, arg3, arg4), 16)
       Api(RtlExtendedIntegerMultiply, (arg1, arg2, arg3), 12)
       Api(RtlExtendedLargeIntegerDivide, (arg1, arg2, arg3, arg4), 16)
       Api(RtlExtendedMagicDivide, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlExtendHeap, (arg1, arg2, arg3, arg4), 16)
       Api(RtlFillMemoryUlong, (arg1, arg2, arg3), 12)
       Api(RtlFindClearBits, (arg1, arg2, arg3), 12)
       Api(RtlFindClearBitsAndSet, (arg1, arg2, arg3), 12)
       Api(RtlFindLongestRunClear, (arg1, arg2), 8)
       Api(RtlFindLongestRunSet, (arg1, arg2), 8)
       Api(RtlFindMessage, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlFindSetBits, (arg1, arg2, arg3), 12)
       Api(RtlFindSetBitsAndClear, (arg1, arg2, arg3), 12)
       Api(RtlFirstFreeAce, (arg1, arg2), 8)
       Api(RtlFlushPropertySet, (arg1), 4)
       Api(RtlFormatCurrentUserKeyPath, (arg1), 4)
       Api(RtlFormatMessage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(RtlFreeAnsiString, (arg1), 4)
       Api(RtlFreeHandle, (arg1, arg2), 8)
       Api(RtlFreeHeap, (arg1, arg2, arg3), 12)
       Api(RtlFreeOemString, (arg1), 4)
       Api(RtlFreeSid, (arg1), 4)
       Api(RtlFreeUnicodeString, (arg1), 4)
       Api(RtlFreeUserThreadStack, (arg1, arg2), 8)
       Api(RtlGenerate8dot3Name, (arg1, arg2, arg3, arg4), 16)
       Api(RtlGetAce, (arg1, arg2, arg3), 12)
       Api(RtlGetCallersAddress, (arg1, arg2), 8)
       Api(RtlGetCompressionWorkSpaceSize, (arg1, arg2, arg3), 12)
       Api(RtlGetControlSecurityDescriptor, (arg1, arg2, arg3), 12)
       Api(RtlGetCurrentDirectory_U, (arg1, arg2), 8)
       Api(RtlGetDaclSecurityDescriptor, (arg1, arg2, arg3, arg4), 16)
       Api(RtlGetElementGenericTable, (arg1, arg2), 8)
       Api(RtlGetFullPathName_U, (arg1, arg2, arg3, arg4), 16)
       Api(RtlGetGroupSecurityDescriptor, (arg1, arg2, arg3), 12)
       Api(RtlGetLongestNtPathLength, (), 0)
       Api(RtlGetNtGlobalFlags, (), 0)
       Api(RtlGetNtProductType, (arg1), 4)
       Api(RtlGetOwnerSecurityDescriptor, (arg1, arg2, arg3), 12)
       Api(RtlGetProcessHeaps, (arg1, arg2), 8)
       Api(RtlGetSaclSecurityDescriptor, (arg1, arg2, arg3, arg4), 16)
       Api(RtlGetUserInfoHeap, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlGuidToPropertySetName, (arg1, arg2), 8)
       Api(RtlIdentifierAuthoritySid, (arg1), 4)
       Api(RtlImageDirectoryEntryToData, (arg1, arg2, arg3, arg4), 16)
       Api(RtlImageNtHeader, (arg1), 4)
       Api(RtlImageRvaToSection, (arg1, arg2, arg3), 12)
       Api(RtlImageRvaToVa, (arg1, arg2, arg3, arg4), 16)
       Api(RtlImpersonateSelf, (arg1), 4)
       Api(RtlInitAnsiString, (arg1, arg2), 8)
       Api(RtlInitCodePageTable, (arg1, arg2), 8)
       Api(RtlInitializeAtomPackage, (arg1), 4)
       Api(RtlInitializeBitMap, (arg1, arg2, arg3), 12)
       Api(RtlInitializeContext, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlInitializeCriticalSection, (arg1), 4)
       Api(RtlInitializeGenericTable, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlInitializeHandleTable, (arg1, arg2, arg3), 12)
       Api(RtlInitializeResource, (arg1), 4)
       Api(RtlInitializeRXact, (arg1, arg2, arg3), 12)
       Api(RtlInitializeSid, (arg1, arg2, arg3), 12)
       Api(RtlInitNlsTables, (arg1, arg2, arg3, arg4), 16)
       Api(RtlInitString, (arg1, arg2), 8)
       Api(RtlInitUnicodeString, (arg1, arg2), 8)
       Api(RtlInsertElementGenericTable, (arg1, arg2, arg3, arg4), 16)
       Api(RtlIntegerToChar, (arg1, arg2, arg3, arg4), 16)
       Api(RtlIntegerToUnicodeString, (arg1, arg2, arg3), 12)
       Api(RtlIsDosDeviceName_U, (arg1), 4)
       Api(RtlIsGenericTableEmpty, (arg1), 4)
       Api(RtlIsNameLegalDOS8Dot3, (arg1, arg2, arg3), 12)
       Api(RtlIsTextUnicode, (arg1, arg2, arg3), 12)
       Api(RtlIsValidHandle, (arg1, arg2), 8)
       Api(RtlIsValidIndexHandle, (arg1, arg2, arg3), 12)
       Api(RtlLargeIntegerAdd, (arg1, arg2, arg3, arg4), 16)
       Api(RtlLargeIntegerArithmeticShift, (arg1, arg2, arg3), 12)
       Api(RtlLargeIntegerDivide, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlLargeIntegerNegate, (arg1, arg2), 8)
       Api(RtlLargeIntegerShiftLeft, (arg1, arg2, arg3), 12)
       Api(RtlLargeIntegerShiftRight, (arg1, arg2, arg3), 12)
       Api(RtlLargeIntegerSubtract, (arg1, arg2, arg3, arg4), 16)
       Api(RtlLargeIntegerToChar, (arg1, arg2, arg3, arg4), 16)
       Api(RtlLeaveCriticalSection, (arg1), 4)
       Api(RtlLengthRequiredSid, (arg1), 4)
       Api(RtlLengthSecurityDescriptor, (arg1), 4)
       Api(RtlLengthSid, (arg1), 4)
       Api(RtlLocalTimeToSystemTime, (arg1, arg2), 8)
       Api(RtlLockHeap, (arg1), 4)
       Api(RtlLookupAtomInAtomTable, (arg1, arg2, arg3), 12)
       Api(RtlLookupElementGenericTable, (arg1, arg2), 8)
       Api(RtlMakeSelfRelativeSD, (arg1, arg2, arg3), 12)
       Api(RtlMapGenericMask, (arg1, arg2), 8)
       Api(RtlMultiByteToUnicodeN, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlMultiByteToUnicodeSize, (arg1, arg2, arg3), 12)
       Api(RtlNewInstanceSecurityObject, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(RtlNewSecurityGrantedAccess, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlNewSecurityObject, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlNormalizeProcessParams, (arg1), 4)
       Api(RtlNtStatusToDosError, (arg1), 4)
       Api(RtlNumberGenericTableElements, (arg1), 4)
       Api(RtlNumberOfClearBits, (arg1), 4)
       Api(RtlNumberOfSetBits, (arg1), 4)
       Api(RtlOemStringToUnicodeSize, (arg1), 4)
       Api(RtlOemStringToUnicodeString, (arg1, arg2, arg3), 12)
       Api(RtlOemToUnicodeN, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlOpenCurrentUser, (arg1, arg2), 8)
       Api(RtlPcToFileHeader, (arg1, arg2), 8)
       Api(RtlPinAtomInAtomTable, (arg1, arg2), 8)
       Api(RtlpNtCreateKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlpNtEnumerateSubKey, (arg1, arg2, arg3, arg4), 16)
       Api(RtlpNtMakeTemporaryKey, (arg1), 4)
       Api(RtlpNtOpenKey, (arg1, arg2, arg3, arg4), 16)
       Api(RtlpNtQueryValueKey, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlpNtSetValueKey, (arg1, arg2, arg3, arg4), 16)
       Api(RtlPrefixString, (arg1, arg2, arg3), 12)
       Api(RtlPrefixUnicodeString, (arg1, arg2, arg3), 12)
       Api(RtlPropertySetNameToGuid, (arg1, arg2, arg3), 12)
       Api(RtlProtectHeap, (arg1, arg2), 8)
       Api(RtlpUnWaitCriticalSection, (arg1), 4)
       Api(RtlpWaitForCriticalSection, (arg1), 4)
       Api(RtlQueryAtomInAtomTable, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlQueryEnvironmentVariable_U, (arg1, arg2, arg3), 12)
       Api(RtlQueryInformationAcl, (arg1, arg2, arg3, arg4), 16)
       Api(RtlQueryProcessBackTraceInformation, (arg1), 4)
       Api(RtlQueryProcessDebugInformation, (arg1, arg2, arg3), 12)
       Api(RtlQueryProcessHeapInformation, (arg1), 4)
       Api(RtlQueryProcessLockInformation, (arg1), 4)
       Api(RtlQueryProperties, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(RtlQueryPropertyNames, (arg1, arg2, arg3, arg4), 16)
       Api(RtlQueryPropertySet, (arg1, arg2), 8)
       Api(RtlQueryRegistryValues, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlQuerySecurityObject, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlQueryTagHeap, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlQueryTimeZoneInformation, (arg1), 4)
       Api(RtlRaiseException, (arg1), 4)
       Api(RtlRaiseStatus, (arg1), 4)
       Api(RtlRandom, (arg1), 4)
       Api(RtlReAllocateHeap, (arg1, arg2, arg3, arg4), 16)
       Api(RtlRealPredecessor, (arg1), 4)
       Api(RtlRealSuccessor, (arg1), 4)
       Api(RtlReleasePebLock, (), 0)
       Api(RtlReleaseResource, (arg1), 4)
       Api(RtlRemoteCall, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(RtlResetRtlTranslations, (arg1), 4)
       Api(RtlRunDecodeUnicodeString, (arg1, arg2), 8)
       Api(RtlRunEncodeUnicodeString, (arg1, arg2), 8)
       Api(RtlSecondsSince1970ToTime, (arg1, arg2), 8)
       Api(RtlSecondsSince1980ToTime, (arg1, arg2), 8)
       Api(RtlSelfRelativeToAbsoluteSD, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(RtlSetAllBits, (arg1), 4)
       Api(RtlSetAttributesSecurityDescriptor, (arg1, arg2, arg3), 12)
       Api(RtlSetBits, (arg1, arg2, arg3), 12)
       Api(RtlSetCurrentDirectory_U, (arg1), 4)
       Api(RtlSetCurrentEnvironment, (arg1, arg2), 8)
       Api(RtlSetDaclSecurityDescriptor, (arg1, arg2, arg3, arg4), 16)
       Api(RtlSetEnvironmentVariable, (arg1, arg2, arg3), 12)
       Api(RtlSetGroupSecurityDescriptor, (arg1, arg2, arg3), 12)
       Api(RtlSetInformationAcl, (arg1, arg2, arg3, arg4), 16)
       Api(RtlSetOwnerSecurityDescriptor, (arg1, arg2, arg3), 12)
       Api(RtlSetProperties, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(RtlSetPropertyNames, (arg1, arg2, arg3, arg4), 16)
       Api(RtlSetPropertySetClassId, (arg1, arg2), 8)
       Api(RtlSetSaclSecurityDescriptor, (arg1, arg2, arg3, arg4), 16)
       Api(RtlSetSecurityObject, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlSetTimeZoneInformation, (arg1), 4)
       Api(RtlSetUnicodeCallouts, (arg1), 4)
       Api(RtlSetUserFlagsHeap, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlSetUserValueHeap, (arg1, arg2, arg3, arg4), 16)
       Api(RtlSizeHeap, (arg1, arg2, arg3), 12)
       Api(RtlSplay, (arg1), 4)
       Api(RtlStartRXact, (arg1), 4)
       Api(RtlSubAuthorityCountSid, (arg1), 4)
       Api(RtlSubAuthoritySid, (arg1, arg2), 8)
       Api(RtlSubtreePredecessor, (arg1), 4)
       Api(RtlSubtreeSuccessor, (arg1), 4)
       Api(RtlSystemTimeToLocalTime, (arg1, arg2), 8)
       Api(RtlTimeFieldsToTime, (arg1, arg2), 8)
       Api(RtlTimeToElapsedTimeFields, (arg1, arg2), 8)
       Api(RtlTimeToSecondsSince1970, (arg1, arg2), 8)
       Api(RtlTimeToSecondsSince1980, (arg1, arg2), 8)
       Api(RtlTimeToTimeFields, (arg1, arg2), 8)
       Api(RtlTryEnterCriticalSection, (arg1), 4)
       Api(RtlUnicodeStringToAnsiSize, (arg1), 4)
       Api(RtlUnicodeStringToAnsiString, (arg1, arg2, arg3), 12)
       Api(RtlUnicodeStringToCountedOemString, (arg1, arg2, arg3), 12)
       Api(RtlUnicodeStringToInteger, (arg1, arg2, arg3), 12)
       Api(RtlUnicodeStringToOemSize, (arg1), 4)
       Api(RtlUnicodeStringToOemString, (arg1, arg2, arg3), 12)
       Api(RtlUnicodeToCustomCPN, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlUnicodeToMultiByteN, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlUnicodeToMultiByteSize, (arg1, arg2, arg3), 12)
       Api(RtlUnicodeToOemN, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlUniform, (arg1), 4)
       Api(RtlUnlockHeap, (arg1), 4)
       Api(RtlUpcaseUnicodeChar, (arg1), 4)
       Api(RtlUpcaseUnicodeString, (arg1, arg2, arg3), 12)
       Api(RtlUpcaseUnicodeStringToAnsiString, (arg1, arg2, arg3), 12)
       Api(RtlUpcaseUnicodeStringToCountedOemString, (arg1, arg2, arg3), 12)
       Api(RtlUpcaseUnicodeStringToOemString, (arg1, arg2, arg3), 12)
       Api(RtlUpcaseUnicodeToCustomCPN, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlUpcaseUnicodeToMultiByteN, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlUpcaseUnicodeToOemN, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RtlUpperChar, (arg1), 4)
       Api(RtlUpperString, (arg1, arg2), 8)
       Api(RtlUsageHeap, (arg1, arg2, arg3), 12)
       Api(RtlValidAcl, (arg1), 4)
       Api(RtlValidateHeap, (arg1, arg2, arg3), 12)
       Api(RtlValidateProcessHeaps, (), 0)
       Api(RtlValidSecurityDescriptor, (arg1), 4)
       Api(RtlValidSid, (arg1), 4)
       Api(RtlWalkHeap, (arg1, arg2), 8)
       Api(RtlWriteRegistryValue, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RtlxAnsiStringToUnicodeSize, (arg1), 4)
       Api(RtlxOemStringToUnicodeSize, (arg1), 4)
       Api(RtlxUnicodeStringToAnsiSize, (arg1), 4)
       Api(RtlxUnicodeStringToOemSize, (arg1), 4)
       Api(RtlZeroHeap, (arg1, arg2), 8)
       Api(ZwAcceptConnectPort, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwAccessCheck, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(ZwAccessCheckAndAuditAlarm, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(ZwAddAtom, (arg1, arg2), 8)
       Api(ZwAdjustGroupsToken, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwAdjustPrivilegesToken, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwAlertResumeThread, (arg1, arg2), 8)
       Api(ZwAlertThread, (arg1), 4)
       Api(ZwAllocateLocallyUniqueId, (arg1), 4)
       Api(ZwAllocateUuids, (arg1, arg2, arg3), 12)
       Api(ZwAllocateVirtualMemory, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwCallbackReturn, (arg1, arg2, arg3), 12)
       Api(ZwCancelIoFile, (arg1, arg2), 8)
       Api(ZwCancelTimer, (arg1, arg2), 8)
       Api(ZwClearEvent, (arg1), 4)
       Api(ZwClose, (arg1), 4)
       Api(ZwCloseObjectAuditAlarm, (arg1, arg2, arg3), 12)
       Api(ZwCompleteConnectPort, (arg1), 4)
       Api(ZwConnectPort, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(ZwContinue, (arg1, arg2), 8)
       Api(ZwCreateChannel, (arg1, arg2), 8)
       Api(ZwCreateDirectoryObject, (arg1, arg2, arg3), 12)
       Api(ZwCreateEvent, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwCreateEventPair, (arg1, arg2, arg3), 12)
       Api(ZwCreateFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(ZwCreateIoCompletion, (arg1, arg2, arg3, arg4), 16)
       Api(ZwCreateKey, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ZwCreateMailslotFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(ZwCreateMutant, (arg1, arg2, arg3, arg4), 16)
       Api(ZwCreateNamedPipeFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14), 56)
       Api(ZwCreatePagingFile, (arg1, arg2, arg3, arg4), 16)
       Api(ZwCreatePort, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwCreateProcess, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(ZwCreateProfile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(ZwCreateSection, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ZwCreateSemaphore, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwCreateSymbolicLinkObject, (arg1, arg2, arg3, arg4), 16)
       Api(ZwCreateThread, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(ZwCreateTimer, (arg1, arg2, arg3, arg4), 16)
       Api(ZwCreateToken, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13), 52)
       Api(ZwDelayExecution, (arg1, arg2), 8)
       Api(ZwDeleteAtom, (arg1), 4)
       Api(ZwDeleteFile, (arg1), 4)
       Api(ZwDeleteKey, (arg1), 4)
       Api(ZwDeleteObjectAuditAlarm, (arg1, arg2, arg3), 12)
       Api(ZwDeleteValueKey, (arg1, arg2), 8)
       Api(ZwDeviceIoControlFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(ZwDisplayString, (arg1), 4)
       Api(ZwDuplicateObject, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ZwDuplicateToken, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwEnumerateKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwEnumerateValueKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwExtendSection, (arg1, arg2), 8)
       Api(ZwFindAtom, (arg1, arg2), 8)
       Api(ZwFlushBuffersFile, (arg1, arg2), 8)
       Api(ZwFlushInstructionCache, (arg1, arg2, arg3), 12)
       Api(ZwFlushKey, (arg1), 4)
       Api(ZwFlushVirtualMemory, (arg1, arg2, arg3, arg4), 16)
       Api(ZwFlushWriteBuffer, (), 0)
       Api(ZwFreeVirtualMemory, (arg1, arg2, arg3, arg4), 16)
       Api(ZwFsControlFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(ZwGetContextThread, (arg1, arg2), 8)
       Api(ZwGetPlugPlayEvent, (arg1, arg2, arg3, arg4), 16)
       Api(ZwGetTickCount, (), 0)
       Api(ZwImpersonateClientOfPort, (arg1, arg2), 8)
       Api(ZwImpersonateThread, (arg1, arg2, arg3), 12)
       Api(ZwInitializeRegistry, (arg1), 4)
       Api(ZwListenChannel, (arg1, arg2), 8)
       Api(ZwListenPort, (arg1, arg2), 8)
       Api(ZwLoadDriver, (arg1), 4)
       Api(ZwLoadKey, (arg1, arg2), 8)
       Api(ZwLoadKey2, (arg1, arg2, arg3), 12)
       Api(ZwLockFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(ZwLockVirtualMemory, (arg1, arg2, arg3, arg4), 16)
       Api(ZwMakeTemporaryObject, (arg1), 4)
       Api(ZwMapViewOfSection, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(ZwNotifyChangeDirectoryFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(ZwNotifyChangeKey, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(ZwOpenChannel, (arg1, arg2), 8)
       Api(ZwOpenDirectoryObject, (arg1, arg2, arg3), 12)
       Api(ZwOpenEvent, (arg1, arg2, arg3), 12)
       Api(ZwOpenEventPair, (arg1, arg2, arg3), 12)
       Api(ZwOpenFile, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwOpenIoCompletion, (arg1, arg2, arg3), 12)
       Api(ZwOpenKey, (arg1, arg2, arg3), 12)
       Api(ZwOpenMutant, (arg1, arg2, arg3), 12)
       Api(ZwOpenObjectAuditAlarm, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(ZwOpenProcess, (arg1, arg2, arg3, arg4), 16)
       Api(ZwOpenProcessToken, (arg1, arg2, arg3), 12)
       Api(ZwOpenSection, (arg1, arg2, arg3), 12)
       Api(ZwOpenSemaphore, (arg1, arg2, arg3), 12)
       Api(ZwOpenSymbolicLinkObject, (arg1, arg2, arg3), 12)
       Api(ZwOpenThread, (arg1, arg2, arg3, arg4), 16)
       Api(ZwOpenThreadToken, (arg1, arg2, arg3, arg4), 16)
       Api(ZwOpenTimer, (arg1, arg2, arg3), 12)
       Api(ZwPlugPlayControl, (arg1, arg2, arg3, arg4), 16)
       Api(ZwPrivilegeCheck, (arg1, arg2, arg3), 12)
       Api(ZwPrivilegedServiceAuditAlarm, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwPrivilegeObjectAuditAlarm, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwProtectVirtualMemory, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwPulseEvent, (arg1, arg2), 8)
       Api(ZwQueryAttributesFile, (arg1, arg2), 8)
       Api(ZwQueryDefaultLocale, (arg1, arg2), 8)
       Api(ZwQueryDirectoryFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(ZwQueryDirectoryObject, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ZwQueryEaFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(ZwQueryEvent, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryFullAttributesFile, (arg1, arg2), 8)
       Api(ZwQueryInformationAtom, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryInformationFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryInformationPort, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryInformationProcess, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryInformationThread, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryInformationToken, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryIntervalProfile, (arg1, arg2), 8)
       Api(ZwQueryIoCompletion, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryKey, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryMultipleValueKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwQueryMutant, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryObject, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryOleDirectoryFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(ZwQueryPerformanceCounter, (arg1, arg2), 8)
       Api(ZwQuerySection, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQuerySecurityObject, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQuerySemaphore, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQuerySymbolicLinkObject, (arg1, arg2, arg3), 12)
       Api(ZwQuerySystemEnvironmentValue, (arg1, arg2, arg3, arg4), 16)
       Api(ZwQuerySystemInformation, (arg1, arg2, arg3, arg4), 16)
       Api(ZwQuerySystemTime, (arg1), 4)
       Api(ZwQueryTimer, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueryTimerResolution, (arg1, arg2, arg3), 12)
       Api(ZwQueryValueKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwQueryVirtualMemory, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwQueryVolumeInformationFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwQueueApcThread, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwRaiseException, (arg1, arg2, arg3), 12)
       Api(ZwRaiseHardError, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwReadFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(ZwReadRequestData, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwReadVirtualMemory, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwRegisterThreadTerminatePort, (arg1), 4)
       Api(ZwReleaseMutant, (arg1, arg2), 8)
       Api(ZwReleaseSemaphore, (arg1, arg2, arg3), 12)
       Api(ZwRemoveIoCompletion, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwReplaceKey, (arg1, arg2, arg3), 12)
       Api(ZwReplyPort, (arg1, arg2), 8)
       Api(ZwReplyWaitReceivePort, (arg1, arg2, arg3, arg4), 16)
       Api(ZwReplyWaitReplyPort, (arg1, arg2), 8)
       Api(ZwReplyWaitSendChannel, (arg1, arg2, arg3), 12)
       Api(ZwRequestPort, (arg1, arg2), 8)
       Api(ZwRequestWaitReplyPort, (arg1, arg2, arg3), 12)
       Api(ZwResetEvent, (arg1, arg2), 8)
       Api(ZwRestoreKey, (arg1, arg2, arg3), 12)
       Api(ZwResumeThread, (arg1, arg2), 8)
       Api(ZwSaveKey, (arg1, arg2), 8)
       Api(ZwSendWaitReplyChannel, (arg1, arg2, arg3, arg4), 16)
       Api(ZwSetContextChannel, (arg1), 4)
       Api(ZwSetContextThread, (arg1, arg2), 8)
       Api(ZwSetDefaultHardErrorPort, (arg1), 4)
       Api(ZwSetDefaultLocale, (arg1, arg2), 8)
       Api(ZwSetEaFile, (arg1, arg2, arg3, arg4), 16)
       Api(ZwSetEvent, (arg1, arg2), 8)
       Api(ZwSetHighEventPair, (arg1), 4)
       Api(ZwSetHighWaitLowEventPair, (arg1), 4)
       Api(ZwSetHighWaitLowThread, (), 0)
       Api(ZwSetInformationFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwSetInformationKey, (arg1, arg2, arg3, arg4), 16)
       Api(ZwSetInformationObject, (arg1, arg2, arg3, arg4), 16)
       Api(ZwSetInformationProcess, (arg1, arg2, arg3, arg4), 16)
       Api(ZwSetInformationThread, (arg1, arg2, arg3, arg4), 16)
       Api(ZwSetInformationToken, (arg1, arg2, arg3, arg4), 16)
       Api(ZwSetIntervalProfile, (arg1, arg2), 8)
       Api(ZwSetIoCompletion, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwSetLdtEntries, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwSetLowEventPair, (arg1), 4)
       Api(ZwSetLowWaitHighEventPair, (arg1), 4)
       Api(ZwSetLowWaitHighThread, (), 0)
       Api(ZwSetSecurityObject, (arg1, arg2, arg3), 12)
       Api(ZwSetSystemEnvironmentValue, (arg1, arg2), 8)
       Api(ZwSetSystemInformation, (arg1, arg2, arg3), 12)
       Api(ZwSetSystemPowerState, (arg1, arg2, arg3), 12)
       Api(ZwSetSystemTime, (arg1, arg2), 8)
       Api(ZwSetTimer, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ZwSetTimerResolution, (arg1, arg2, arg3), 12)
       Api(ZwSetValueKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwSetVolumeInformationFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwShutdownSystem, (arg1), 4)
       Api(ZwSignalAndWaitForSingleObject, (arg1, arg2, arg3, arg4), 16)
       Api(ZwStartProfile, (arg1), 4)
       Api(ZwStopProfile, (arg1), 4)
       Api(ZwSuspendThread, (arg1, arg2), 8)
       Api(ZwSystemDebugControl, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwTerminateProcess, (arg1, arg2), 8)
       Api(ZwTerminateThread, (arg1, arg2), 8)
       Api(ZwTestAlert, (), 0)
       Api(ZwUnloadDriver, (arg1), 4)
       Api(ZwUnloadKey, (arg1), 4)
       Api(ZwUnlockFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwUnlockVirtualMemory, (arg1, arg2, arg3, arg4), 16)
       Api(ZwUnmapViewOfSection, (arg1, arg2), 8)
       Api(ZwVdmControl, (arg1, arg2), 8)
       Api(ZwW32Call, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwWaitForMultipleObjects, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwWaitForSingleObject, (arg1, arg2, arg3), 12)
       Api(ZwWaitHighEventPair, (arg1), 4)
       Api(ZwWaitLowEventPair, (arg1), 4)
       Api(ZwWriteFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(ZwWriteRequestData, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ZwWriteVirtualMemory, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ZwYieldExecution, (), 0)
EndImport
