XIncludeFile "common.pbi"

Import "ntmsapi.lib"
       Api(AccessNtmsLibraryDoor, (arg1, arg2, arg3), 12)
       Api(AddNtmsMediaType, (arg1, arg2, arg3), 12)
       Api(AllocateNtmsMedia, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CancelNtmsLibraryRequest, (arg1, arg2), 8)
       Api(CancelNtmsOperatorRequest, (arg1, arg2), 8)
       Api(ChangeNtmsMediaType, (arg1, arg2, arg3), 12)
       Api(CleanNtmsDrive, (arg1, arg2), 8)
       Api(CloseNtmsNotification, (arg1), 4)
       Api(CloseNtmsSession, (arg1), 4)
  AnsiWide(CreateNtmsMedia, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(CreateNtmsMediaPool, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(DeallocateNtmsMedia, (arg1, arg2, arg3), 12)
       Api(DecommissionNtmsMedia, (arg1, arg2), 8)
       Api(DeleteNtmsDrive, (arg1, arg2), 8)
       Api(DeleteNtmsLibrary, (arg1, arg2), 8)
       Api(DeleteNtmsMedia, (arg1, arg2), 8)
       Api(DeleteNtmsMediaPool, (arg1, arg2), 8)
       Api(DeleteNtmsMediaType, (arg1, arg2, arg3), 12)
       Api(DeleteNtmsRequests, (arg1, arg2, arg3, arg4), 16)
       Api(DisableNtmsObject, (arg1, arg2, arg3), 12)
       Api(DismountNtmsDrive, (arg1, arg2), 8)
       Api(DismountNtmsMedia, (arg1, arg2, arg3, arg4), 16)
       Api(EjectNtmsCleaner, (arg1, arg2, arg3, arg4), 16)
       Api(EjectNtmsMedia, (arg1, arg2, arg3, arg4), 16)
       Api(EnableNtmsObject, (arg1, arg2, arg3), 12)
       Api(EnumerateNtmsObject, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ExportNtmsDatabase, (arg1), 4)
  AnsiWide(GetNtmsMediaPoolName, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetNtmsObjectAttribute, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GetNtmsObjectInformation, (arg1, arg2, arg3), 12)
       Api(GetNtmsObjectSecurity, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(GetNtmsRequestOrder, (arg1, arg2, arg3), 12)
       Api(ImportNtmsDatabase, (arg1), 4)
       Api(InjectNtmsCleaner, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(InjectNtmsMedia, (arg1, arg2, arg3, arg4), 16)
       Api(InventoryNtmsLibrary, (arg1, arg2, arg3), 12)
       Api(MountNtmsMedia, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(MoveToNtmsMediaPool, (arg1, arg2, arg3), 12)
       Api(OpenNtmsNotification, (arg1, arg2), 8)
  AnsiWide(OpenNtmsSession, (arg1, arg2, arg3), 12)
       Api(ReleaseNtmsCleanerSlot, (arg1, arg2), 8)
       Api(ReserveNtmsCleanerSlot, (arg1, arg2, arg3), 12)
       Api(SatisfyNtmsOperatorRequest, (arg1, arg2), 8)
       Api(SetNtmsMediaComplete, (arg1, arg2), 8)
  AnsiWide(SetNtmsObjectAttribute, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetNtmsObjectInformation, (arg1, arg2, arg3), 12)
       Api(SetNtmsObjectSecurity, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetNtmsRequestOrder, (arg1, arg2, arg3), 12)
  AnsiWide(SubmitNtmsOperatorRequest, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(SwapNtmsMedia, (arg1, arg2, arg3), 12)
       Api(UpdateNtmsOmidInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WaitForNtmsNotification, (arg1, arg2, arg3), 12)
       Api(WaitForNtmsOperatorRequest, (arg1, arg2, arg3), 12)
EndImport
