XIncludeFile "common.pbi"

Import "odbccp32.lib"
           Api(AboutDlg, (arg1, arg2, arg3, arg4), 16)
           Api(AddDriverDlg, (arg1, arg2, arg3, arg4), 16)
           Api(AddDSourceDlg, (arg1, arg2, arg3, arg4), 16)
           Api(AdvancedDlg, (arg1, arg2, arg3, arg4), 16)
           Api(CommDlgHook, (arg1, arg2, arg3, arg4), 16)
           Api(CopyFileDlg, (arg1, arg2, arg3, arg4), 16)
           Api(CPlApplet, (arg1, arg2, arg3, arg4), 16)
           Api(DDEDlg, (arg1, arg2, arg3, arg4), 16)
           Api(DriversDlg, (arg1, arg2, arg3, arg4), 16)
           Api(InstallDlg, (arg1, arg2, arg3, arg4), 16)
           Api(MainDlg, (arg1, arg2, arg3, arg4), 16)
           Api(OptionsDlg, (arg1, arg2, arg3, arg4), 16)
           Api(SelectTransDlg, (arg1, arg2, arg3, arg4), 16)
 AnsiWideWierd(SQLConfigDataSource, (arg1, arg2, arg3, arg4), 16)  ; No 'A' posfix in Ascii (but 'W' postfix in unicode)
 AnsiWideWierd(SQLConfigDriver, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
 AnsiWideWierd(SQLCreateDataSource, (arg1, arg2), 8)
 AnsiWideWierd(SQLGetAvailableDrivers, (arg1, arg2, arg3, arg4), 16)
 AnsiWideWierd(SQLGetInstalledDrivers, (arg1, arg2, arg3), 12)
 AnsiWideWierd(SQLGetPrivateProfileString, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
 AnsiWideWierd(SQLGetTranslator, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
 AnsiWideWierd(SQLInstallDriver, (arg1, arg2, arg3, arg4, arg5), 20)
 AnsiWideWierd(SQLInstallDriverEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
 AnsiWideWierd(SQLInstallDriverManager, (arg1, arg2, arg3), 12)
 AnsiWideWierd(SQLInstallerError, (arg1, arg2, arg3, arg4, arg5), 20)
 AnsiWideWierd(SQLInstallODBC, (arg1, arg2, arg3, arg4), 16)
 AnsiWideWierd(SQLInstallTranslator, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
 AnsiWideWierd(SQLInstallTranslatorEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
           Api(SQLManageDataSources, (arg1), 4)
           Api(SQLRemoveDefaultDataSource, (), 0)
 AnsiWideWierd(SQLRemoveDriver, (arg1, arg2, arg3), 12)
          Api(SQLRemoveDriverManager, (arg1), 4)
 AnsiWideWierd(SQLRemoveDSNFromIni, (arg1), 4)
          Api(SQLRemoveTranslator, (arg1, arg2), 8)
 AnsiWideWierd(SQLValidDSN, (arg1), 4)
 AnsiWideWierd(SQLWriteDSNToIni, (arg1, arg2), 8)
 AnsiWideWierd(SQLWritePrivateProfileString, (arg1, arg2, arg3, arg4), 16)
          Api(UpdateDlg, (arg1, arg2, arg3, arg4), 16)
          Api(VersionsDlg, (arg1, arg2, arg3, arg4), 16)
EndImport
