XIncludeFile "common.pbi"

Import "ole32.lib"
       Api(BindMoniker, (arg1, arg2, arg3, arg4), 16)
       Api(CLIPFORMAT_UserFree, (arg1, arg2), 8)
       Api(CLIPFORMAT_UserMarshal, (arg1, arg2, arg3), 12)
       Api(CLIPFORMAT_UserSize, (arg1, arg2, arg3), 12)
       Api(CLIPFORMAT_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(CLSIDFromProgID, (arg1, arg2), 8)
       Api(CLSIDFromString, (arg1, arg2), 8)
       Api(CoAddRefServerProcess, (), 0)
       Api(CoBuildVersion, (), 0)
       Api(CoCopyProxy, (arg1, arg2), 8)
       Api(CoCreateFreeThreadedMarshaler, (arg1, arg2), 8)
       Api(CoCreateGuid, (arg1), 4)
       Api(CoCreateInstance, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CoCreateInstanceEx, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CoDisconnectObject, (arg1, arg2), 8)
       Api(CoDosDateTimeToFileTime, (arg1, arg2, arg3), 12)
       Api(CoFileTimeNow, (arg1), 4)
       Api(CoFileTimeToDosDateTime, (arg1, arg2, arg3), 12)
       Api(CoFreeAllLibraries, (), 0)
       Api(CoFreeLibrary, (arg1), 4)
       Api(CoFreeUnusedLibraries, (), 0)
       Api(CoGetCallContext, (arg1, arg2), 8)
       Api(CoGetCallerTID, (arg1), 4)
       Api(CoGetClassObject, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CoGetCurrentLogicalThreadId, (arg1), 4)
       Api(CoGetCurrentProcess, (), 0)
       Api(CoGetInstanceFromFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(CoGetInstanceFromIStorage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CoGetInterfaceAndReleaseStream, (arg1, arg2, arg3), 12)
       Api(CoGetMalloc, (arg1, arg2), 8)
       Api(CoGetMarshalSizeMax, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CoGetObject, (arg1, arg2, arg3, arg4), 16)
       Api(CoGetPSClsid, (arg1, arg2), 8)
       Api(CoGetStandardMarshal, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CoGetState, (arg1), 4)
       Api(CoGetTIDFromIPID, (arg1), 4)
       Api(CoGetTreatAsClass, (arg1, arg2), 8)
       Api(CoImpersonateClient, (), 0)
       Api(CoInitialize, (arg1), 4)
       Api(CoInitializeEx, (arg1, arg2), 8)
       Api(CoInitializeSecurity, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(CoIsHandlerConnected, (arg1), 4)
       Api(CoIsOle1Class, (arg1), 4)
       Api(CoLoadLibrary, (arg1, arg2), 8)
       Api(CoLockObjectExternal, (arg1, arg2, arg3), 12)
       Api(CoMarshalHresult, (arg1, arg2), 8)
       Api(CoMarshalInterface, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CoMarshalInterThreadInterfaceInStream, (arg1, arg2, arg3), 12)
       Api(CoQueryAuthenticationServices, (arg1, arg2), 8)
       Api(CoQueryClientBlanket, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CoQueryProxyBlanket, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(CoQueryReleaseObject, (arg1), 4)
       Api(CoRegisterChannelHook, (arg1, arg2), 8)
       Api(CoRegisterClassObject, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CoRegisterMallocSpy, (arg1), 4)
       Api(CoRegisterMessageFilter, (arg1, arg2), 8)
       Api(CoRegisterPSClsid, (arg1, arg2), 8)
       Api(CoReleaseMarshalData, (arg1), 4)
       Api(CoReleaseServerProcess, (), 0)
       Api(CoResumeClassObjects, (), 0)
       Api(CoRevertToSelf, (), 0)
       Api(CoRevokeClassObject, (arg1), 4)
       Api(CoRevokeMallocSpy, (), 0)
       Api(CoSetProxyBlanket, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(CoSetState, (arg1), 4)
       Api(CoSuspendClassObjects, (), 0)
       Api(CoSwitchCallContext, (arg1, arg2), 8)
       Api(CoTaskMemAlloc, (arg1), 4)
       Api(CoTaskMemFree, (arg1), 4)
       Api(CoTaskMemRealloc, (arg1, arg2), 8)
       Api(CoTreatAsClass, (arg1, arg2), 8)
       Api(CoUninitialize, (), 0)
       Api(CoUnmarshalHresult, (arg1, arg2), 8)
       Api(CoUnmarshalInterface, (arg1, arg2, arg3), 12)
       Api(CreateAntiMoniker, (arg1), 4)
       Api(CreateBindCtx, (arg1, arg2), 8)
       Api(CreateClassMoniker, (arg1, arg2), 8)
       Api(CreateDataAdviseHolder, (arg1), 4)
       Api(CreateDataCache, (arg1, arg2, arg3, arg4), 16)
       Api(CreateFileMoniker, (arg1, arg2), 8)
       Api(CreateGenericComposite, (arg1, arg2, arg3), 12)
       Api(CreateILockBytesOnHGlobal, (arg1, arg2, arg3), 12)
       Api(CreateItemMoniker, (arg1, arg2, arg3), 12)
       Api(CreateOleAdviseHolder, (arg1), 4)
       Api(CreatePointerMoniker, (arg1, arg2), 8)
       Api(CreateStreamOnHGlobal, (arg1, arg2, arg3), 12)
       Api(DllDebugObjectRPCHook, (arg1, arg2), 8)
       Api(DoDragDrop, (arg1, arg2, arg3, arg4), 16)
       Api(EnableHookObject, (arg1, arg2), 8)
       Api(FreePropVariantArray, (arg1, arg2), 8)
       Api(GetClassFile, (arg1, arg2), 8)
       Api(GetConvertStg, (arg1), 4)
       Api(GetDocumentBitStg, (arg1), 4)
       Api(GetHGlobalFromILockBytes, (arg1, arg2), 8)
       Api(GetHGlobalFromStream, (arg1, arg2), 8)
       Api(GetHookInterface, (arg1), 4)
       Api(GetRunningObjectTable, (arg1, arg2), 8)
       Api(HACCEL_UserFree, (arg1, arg2), 8)
       Api(HACCEL_UserMarshal, (arg1, arg2, arg3), 12)
       Api(HACCEL_UserSize, (arg1, arg2, arg3), 12)
       Api(HACCEL_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(HBITMAP_UserFree, (arg1, arg2), 8)
       Api(HBITMAP_UserMarshal, (arg1, arg2, arg3), 12)
       Api(HBITMAP_UserSize, (arg1, arg2, arg3), 12)
       Api(HBITMAP_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(HBRUSH_UserFree, (arg1, arg2), 8)
       Api(HBRUSH_UserMarshal, (arg1, arg2, arg3), 12)
       Api(HBRUSH_UserSize, (arg1, arg2, arg3), 12)
       Api(HBRUSH_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(HENHMETAFILE_UserFree, (arg1, arg2), 8)
       Api(HENHMETAFILE_UserMarshal, (arg1, arg2, arg3), 12)
       Api(HENHMETAFILE_UserSize, (arg1, arg2, arg3), 12)
       Api(HENHMETAFILE_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(HGLOBAL_UserFree, (arg1, arg2), 8)
       Api(HGLOBAL_UserMarshal, (arg1, arg2, arg3), 12)
       Api(HGLOBAL_UserSize, (arg1, arg2, arg3), 12)
       Api(HGLOBAL_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(HMENU_UserFree, (arg1, arg2), 8)
       Api(HMENU_UserMarshal, (arg1, arg2, arg3), 12)
       Api(HMENU_UserSize, (arg1, arg2, arg3), 12)
       Api(HMENU_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(HMETAFILE_UserFree, (arg1, arg2), 8)
       Api(HMETAFILE_UserMarshal, (arg1, arg2, arg3), 12)
       Api(HMETAFILE_UserSize, (arg1, arg2, arg3), 12)
       Api(HMETAFILE_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(HMETAFILEPICT_UserFree, (arg1, arg2), 8)
       Api(HMETAFILEPICT_UserMarshal, (arg1, arg2, arg3), 12)
       Api(HMETAFILEPICT_UserSize, (arg1, arg2, arg3), 12)
       Api(HMETAFILEPICT_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(HPALETTE_UserFree, (arg1, arg2), 8)
       Api(HPALETTE_UserMarshal, (arg1, arg2, arg3), 12)
       Api(HPALETTE_UserSize, (arg1, arg2, arg3), 12)
       Api(HPALETTE_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(HWND_UserFree, (arg1, arg2), 8)
       Api(HWND_UserMarshal, (arg1, arg2, arg3), 12)
       Api(HWND_UserSize, (arg1, arg2, arg3), 12)
       Api(HWND_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(IIDFromString, (arg1, arg2), 8)
       Api(IsAccelerator, (arg1, arg2, arg3, arg4), 16)
       Api(IsEqualGUID, (arg1, arg2), 8)
       Api(IsValidIid, (arg1), 4)
       Api(IsValidInterface, (arg1), 4)
       Api(IsValidPtrIn, (arg1, arg2), 8)
       Api(IsValidPtrOut, (arg1, arg2), 8)
       Api(MkParseDisplayName, (arg1, arg2, arg3, arg4), 16)
       Api(MonikerCommonPrefixWith, (arg1, arg2, arg3), 12)
       Api(MonikerRelativePathTo, (arg1, arg2, arg3, arg4), 16)
       Api(OleBuildVersion, (), 0)
       Api(OleConvertIStorageToOLESTREAM, (arg1, arg2), 8)
       Api(OleConvertIStorageToOLESTREAMEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(OleConvertOLESTREAMToIStorage, (arg1, arg2, arg3), 12)
       Api(OleConvertOLESTREAMToIStorageEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(OleCreate, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(OleCreateDefaultHandler, (arg1, arg2, arg3, arg4), 16)
       Api(OleCreateEmbeddingHelper, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(OleCreateEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(OleCreateFromData, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(OleCreateFromDataEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(OleCreateFromFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(OleCreateFromFileEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13), 52)
       Api(OleCreateLink, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(OleCreateLinkEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(OleCreateLinkFromData, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(OleCreateLinkFromDataEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(OleCreateLinkToFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(OleCreateLinkToFileEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(OleCreateMenuDescriptor, (arg1, arg2), 8)
       Api(OleCreateStaticFromData, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(OleDestroyMenuDescriptor, (arg1), 4)
       Api(OleDoAutoConvert, (arg1, arg2), 8)
       Api(OleDraw, (arg1, arg2, arg3, arg4), 16)
       Api(OleDuplicateData, (arg1, arg2, arg3), 12)
       Api(OleFlushClipboard, (), 0)
       Api(OleGetAutoConvert, (arg1, arg2), 8)
       Api(OleGetClipboard, (arg1), 4)
       Api(OleGetIconOfClass, (arg1, arg2, arg3), 12)
       Api(OleGetIconOfFile, (arg1, arg2), 8)
       Api(OleInitialize, (arg1), 4)
       Api(OleIsCurrentClipboard, (arg1), 4)
       Api(OleIsRunning, (arg1), 4)
       Api(OleLoad, (arg1, arg2, arg3, arg4), 16)
       Api(OleLoadFromStream, (arg1, arg2, arg3), 12)
       Api(OleLockRunning, (arg1, arg2, arg3), 12)
       Api(OleMetafilePictFromIconAndLabel, (arg1, arg2, arg3, arg4), 16)
       Api(OleNoteObjectVisible, (arg1, arg2), 8)
       Api(OleQueryCreateFromData, (arg1), 4)
       Api(OleQueryLinkFromData, (arg1), 4)
       Api(OleRegEnumFormatEtc, (arg1, arg2, arg3), 12)
       Api(OleRegEnumVerbs, (arg1, arg2), 8)
       Api(OleRegGetMiscStatus, (arg1, arg2, arg3), 12)
       Api(OleRegGetUserType, (arg1, arg2, arg3), 12)
       Api(OleRun, (arg1), 4)
       Api(OleSave, (arg1, arg2, arg3), 12)
       Api(OleSaveToStream, (arg1, arg2), 8)
       Api(OleSetAutoConvert, (arg1, arg2), 8)
       Api(OleSetClipboard, (arg1), 4)
       Api(OleSetContainedObject, (arg1, arg2), 8)
       Api(OleSetMenuDescriptor, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(OleTranslateAccelerator, (arg1, arg2, arg3), 12)
       Api(OleUninitialize, (), 0)
       Api(OpenOrCreateStream, (arg1, arg2, arg3), 12)
       Api(ProgIDFromCLSID, (arg1, arg2), 8)
       Api(PropSysAllocString, (arg1), 4)
       Api(PropSysFreeString, (arg1), 4)
       Api(PropVariantClear, (arg1), 4)
       Api(PropVariantCopy, (arg1, arg2), 8)
       Api(ReadClassStg, (arg1, arg2), 8)
       Api(ReadClassStm, (arg1, arg2), 8)
       Api(ReadFmtUserTypeStg, (arg1, arg2, arg3), 12)
       Api(ReadOleStg, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ReadStringStream, (arg1, arg2), 8)
       Api(RegisterDragDrop, (arg1, arg2), 8)
       Api(ReleaseStgMedium, (arg1), 4)
       Api(RevokeDragDrop, (arg1), 4)
       Api(SetConvertStg, (arg1, arg2), 8)
       Api(SetDocumentBitStg, (arg1, arg2), 8)
       Api(SNB_UserFree, (arg1, arg2), 8)
       Api(SNB_UserMarshal, (arg1, arg2, arg3), 12)
       Api(SNB_UserSize, (arg1, arg2, arg3), 12)
       Api(SNB_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(StgCreateDocfile, (arg1, arg2, arg3, arg4), 16)
       Api(StgCreateDocfileOnILockBytes, (arg1, arg2, arg3, arg4), 16)
       Api(StgGetIFillLockBytesOnFile, (arg1, arg2), 8)
       Api(StgGetIFillLockBytesOnILockBytes, (arg1, arg2), 8)
       Api(StgIsStorageFile, (arg1), 4)
       Api(StgIsStorageILockBytes, (arg1), 4)
       Api(STGMEDIUM_UserFree, (arg1, arg2), 8)
       Api(STGMEDIUM_UserMarshal, (arg1, arg2, arg3), 12)
       Api(STGMEDIUM_UserSize, (arg1, arg2, arg3), 12)
       Api(STGMEDIUM_UserUnmarshal, (arg1, arg2, arg3), 12)
       Api(StgOpenAsyncDocfileOnIFillLockBytes, (arg1, arg2, arg3, arg4), 16)
       Api(StgOpenStorage, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(StgOpenStorageOnILockBytes, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(StgSetTimes, (arg1, arg2, arg3, arg4), 16)
       Api(StringFromCLSID, (arg1, arg2), 8)
       Api(StringFromGUID2, (arg1, arg2, arg3), 12)
       Api(StringFromIID, (arg1, arg2), 8)
       Api(UpdateDCOMSettings, (), 0)
       Api(UtConvertDvtd16toDvtd32, (arg1, arg2, arg3), 12)
       Api(UtConvertDvtd32toDvtd16, (arg1, arg2, arg3), 12)
       Api(UtGetDvtd16Info, (arg1, arg2), 8)
       Api(UtGetDvtd32Info, (arg1, arg2), 8)
       Api(WriteClassStg, (arg1, arg2), 8)
       Api(WriteClassStm, (arg1, arg2), 8)
       Api(WriteFmtUserTypeStg, (arg1, arg2, arg3), 12)
       Api(WriteOleStg, (arg1, arg2, arg3, arg4), 16)
       Api(WriteStringStream, (arg1, arg2), 8)
EndImport
