XIncludeFile "common.pbi"

Import "penwin32.lib"
       Api(AddInksetInterval, (arg1, arg2), 8)
       Api(AddPenDataHRC, (arg1, arg2), 8)
       Api(AddPenInputHRC, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(AddPointsPenData, (arg1, arg2, arg3, arg4), 16)
       Api(AddWordsHWL, (arg1, arg2, arg3), 12)
       Api(BoundingRectFromPoints, (arg1, arg2, arg3), 12)
       Api(CharacterToSymbol, (arg1, arg2, arg3), 12)
       Api(CompressPenData, (arg1, arg2, arg3), 12)
       Api(ConfigHREC, (arg1, arg2, arg3, arg4), 16)
       Api(CorrectWriting, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(CreateCompatibleHRC, (arg1, arg2), 8)
       Api(CreateHWL, (arg1, arg2, arg3, arg4), 16)
       Api(CreateInkset, (arg1), 4)
       Api(CreateInksetHRCRESULT, (arg1, arg2, arg3), 12)
       Api(CreatePenDataEx, (arg1, arg2, arg3, arg4), 16)
       Api(CreatePenDataHRC, (arg1), 4)
       Api(CreatePenDataRegion, (arg1, arg2), 8)
       Api(DestroyHRC, (arg1), 4)
       Api(DestroyHRCRESULT, (arg1), 4)
       Api(DestroyHWL, (arg1), 4)
       Api(DestroyInkset, (arg1), 4)
       Api(DestroyPenData, (arg1), 4)
       Api(DoDefaultPenInput, (arg1, arg2), 8)
       Api(DPtoTP, (arg1, arg2), 8)
       Api(DrawPenDataEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(DuplicatePenData, (arg1, arg2), 8)
       Api(EnableGestureSetHRC, (arg1, arg2, arg3), 12)
       Api(EnableSystemDictionaryHRC, (arg1, arg2), 8)
       Api(EndPenInputHRC, (arg1), 4)
       Api(ExtractPenDataPoints, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ExtractPenDataStrokes, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetAlphabetHRC, (arg1, arg2, arg3), 12)
       Api(GetAlphabetPriorityHRC, (arg1, arg2, arg3), 12)
       Api(GetAlternateWordsHRCRESULT, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetBoxMappingHRCRESULT, (arg1, arg2, arg3, arg4), 16)
       Api(GetBoxResultsHRC, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetGuideHRC, (arg1, arg2, arg3), 12)
       Api(GetHotspotsHRCRESULT, (arg1, arg2, arg3, arg4), 16)
       Api(GetHRECFromHRC, (arg1), 4)
       Api(GetInksetInterval, (arg1, arg2, arg3), 12)
       Api(GetInksetIntervalCount, (arg1), 4)
       Api(GetInternationalHRC, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetMaxResultsHRC, (arg1), 4)
       Api(GetPenAppFlags, (), 0)
       Api(GetPenAsyncState, (arg1), 4)
       Api(GetPenDataAttributes, (arg1, arg2, arg3), 12)
       Api(GetPenDataInfo, (arg1, arg2, arg3, arg4), 16)
       Api(GetPenInput, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetPenMiscInfo, (arg1, arg2), 8)
       Api(GetPointsFromPenData, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetResultsHRC, (arg1, arg2, arg3, arg4), 16)
       Api(GetStrokeAttributes, (arg1, arg2, arg3, arg4), 16)
       Api(GetStrokeTableAttributes, (arg1, arg2, arg3, arg4), 16)
       Api(GetSymbolCountHRCRESULT, (arg1), 4)
       Api(GetSymbolsHRCRESULT, (arg1, arg2, arg3, arg4), 16)
       Api(GetVersionPenWin, (), 0)
       Api(GetWordlistCoercionHRC, (arg1), 4)
       Api(GetWordlistHRC, (arg1, arg2), 8)
       Api(HitTestPenData, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(InsertPenData, (arg1, arg2, arg3), 12)
       Api(InsertPenDataPoints, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(InsertPenDataStroke, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(InstallRecognizer, (arg1), 4)
       Api(IsPenEvent, (arg1, arg2), 8)
       Api(MetricScalePenData, (arg1, arg2), 8)
       Api(OffsetPenData, (arg1, arg2, arg3), 12)
       Api(PeekPenInput, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(PenDataFromBuffer, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(PenDataToBuffer, (arg1, arg2, arg3, arg4), 16)
       Api(ProcessHRC, (arg1, arg2), 8)
       Api(ReadHWL, (arg1, arg2), 8)
       Api(RedisplayPenData, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RemovePenDataStrokes, (arg1, arg2, arg3), 12)
       Api(ResizePenData, (arg1, arg2), 8)
       Api(SetAlphabetHRC, (arg1, arg2, arg3), 12)
       Api(SetAlphabetPriorityHRC, (arg1, arg2, arg3), 12)
       Api(SetBoxAlphabetHRC, (arg1, arg2, arg3), 12)
       Api(SetGuideHRC, (arg1, arg2, arg3), 12)
       Api(SetInternationalHRC, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetMaxResultsHRC, (arg1, arg2), 8)
       Api(SetPenAppFlags, (arg1, arg2), 8)
       Api(SetPenMiscInfo, (arg1, arg2), 8)
       Api(SetResultsHookHREC, (arg1, arg2), 8)
       Api(SetStrokeAttributes, (arg1, arg2, arg3, arg4), 16)
       Api(SetStrokeTableAttributes, (arg1, arg2, arg3, arg4), 16)
       Api(SetWordlistCoercionHRC, (arg1, arg2), 8)
       Api(SetWordlistHRC, (arg1, arg2), 8)
       Api(StartInking, (arg1, arg2, arg3), 12)
       Api(StartPenInput, (arg1, arg2, arg3, arg4), 16)
       Api(StopInking, (arg1), 4)
       Api(StopPenInput, (arg1, arg2, arg3), 12)
       Api(SymbolToCharacter, (arg1, arg2, arg3, arg4), 16)
       Api(TargetPoints, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(TPtoDP, (arg1, arg2), 8)
       Api(TrainHREC, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(TrimPenData, (arg1, arg2, arg3), 12)
       Api(UnhookResultsHookHREC, (arg1, arg2), 8)
       Api(UninstallRecognizer, (arg1), 4)
       Api(WriteHWL, (arg1, arg2), 8)
EndImport
