XIncludeFile "common.pbi"

Import "rasapi32.lib"
       Api(DDMGetPhonebookInfo, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(RasAutodialAddressToNetwork, (arg1, arg2, arg3), 12)
       Api(RasAutodialEntryToNetwork, (arg1, arg2, arg3), 12)
  AnsiWide(RasConnectionNotification, (arg1, arg2, arg3), 12)
  AnsiWide(RasCreatePhonebookEntry, (arg1, arg2), 8)
  AnsiWide(RasDeleteEntry, (arg1, arg2), 8)
  AnsiWide(RasDial, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RasDialWow, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(RasEditPhonebookEntry, (arg1, arg2, arg3), 12)
  AnsiWide(RasEnumAutodialAddresses, (arg1, arg2, arg3), 12)
  AnsiWide(RasEnumConnections, (arg1, arg2, arg3), 12)
       Api(RasEnumConnectionsWow, (arg1, arg2, arg3), 12)
  AnsiWide(RasEnumDevices, (arg1, arg2, arg3), 12)
  AnsiWide(RasEnumEntries, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RasEnumEntriesWow, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(RasGetAutodialAddress, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(RasGetAutodialEnable, (arg1, arg2), 8)
  AnsiWide(RasGetAutodialParam, (arg1, arg2, arg3), 12)
       Api(RasGetConnectResponse, (arg1, arg2), 8)
  AnsiWide(RasGetConnectStatus, (arg1, arg2), 8)
       Api(RasGetConnectStatusWow, (arg1, arg2), 8)
  AnsiWide(RasGetCountryInfo, (arg1, arg2), 8)
  AnsiWide(RasGetCredentials, (arg1, arg2, arg3), 12)
  AnsiWide(RasGetEntryDialParams, (arg1, arg2, arg3), 12)
  AnsiWide(RasGetEntryProperties, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(RasGetErrorString, (arg1, arg2, arg3), 12)
       Api(RasGetErrorStringWow, (arg1, arg2, arg3), 12)
       Api(RasGetHport, (arg1), 4)
  AnsiWide(RasGetProjectionInfo, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RasGetSubEntryHandle, (arg1, arg2, arg3), 12)
  AnsiWide(RasGetSubEntryProperties, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(RasHangUp, (arg1), 4)
       Api(RasHangUpWow, (arg1), 4)
       Api(RasIsRouterConnection, (arg1), 4)
  AnsiWide(RasRenameEntry, (arg1, arg2, arg3), 12)
  AnsiWide(RasSetAutodialAddress, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(RasSetAutodialEnable, (arg1, arg2), 8)
  AnsiWide(RasSetAutodialParam, (arg1, arg2, arg3), 12)
  AnsiWide(RasSetCredentials, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RasSetEntryDialParams, (arg1, arg2, arg3), 12)
  AnsiWide(RasSetEntryProperties, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RasSetOldPassword, (arg1, arg2), 8)
  AnsiWide(RasSetSubEntryProperties, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(RasValidateEntryName, (arg1, arg2), 8)
EndImport
