XIncludeFile "common.pbi"

Import "resutils.lib"
       Api(ClusWorkerCheckTerminate, (arg1), 4)
       Api(ClusWorkerCreate, (arg1, arg2, arg3), 12)
       Api(ClusWorkerStart, (arg1), 4)
       Api(ClusWorkerTerminate, (arg1), 4)
       Api(ResUtilAddUnknownProperties, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ResUtilCreateDirectoryTree, (arg1), 4)
       Api(ResUtilDupParameterBlock, (arg1, arg2, arg3), 12)
       Api(ResUtilDupString, (arg1), 4)
       Api(ResUtilEnumPrivateProperties, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ResUtilEnumProperties, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ResUtilEnumResources, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilExpandEnvironmentStrings, (arg1), 4)
       Api(ResUtilFindBinaryProperty, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ResUtilFindDependentDiskResourceDriveLetter, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilFindDwordProperty, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilFindExpandedSzProperty, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilFindExpandSzProperty, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilFindLongProperty, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilFindMultiSzProperty, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ResUtilFindSzProperty, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilFreeEnvironment, (arg1), 4)
       Api(ResUtilFreeParameterBlock, (arg1, arg2, arg3), 12)
       Api(ResUtilGetAllProperties, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ResUtilGetBinaryProperty, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ResUtilGetBinaryValue, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilGetDwordProperty, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ResUtilGetDwordValue, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilGetEnvironmentWithNetName, (arg1), 4)
       Api(ResUtilGetMultiSzProperty, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ResUtilGetPrivateProperties, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ResUtilGetProperties, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ResUtilGetPropertiesToParameterBlock, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ResUtilGetProperty, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilGetPropertySize, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilGetResourceDependency, (arg1, arg2), 8)
       Api(ResUtilGetResourceDependencyByClass, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilGetResourceDependencyByName, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilGetResourceDependentIPAddressProps, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ResUtilGetResourceNameDependency, (arg1, arg2), 8)
       Api(ResUtilGetSzProperty, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ResUtilGetSzValue, (arg1, arg2), 8)
       Api(ResUtilIsPathValid, (arg1), 4)
       Api(ResUtilIsResourceClassEqual, (arg1, arg2), 8)
       Api(ResUtilPropertyListFromParameterBlock, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ResUtilResourcesEqual, (arg1, arg2), 8)
       Api(ResUtilResourceTypesEqual, (arg1, arg2), 8)
       Api(ResUtilSetBinaryValue, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ResUtilSetDwordValue, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilSetExpandSzValue, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilSetMultiSzValue, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ResUtilSetPrivatePropertyList, (arg1, arg2, arg3), 12)
       Api(ResUtilSetPropertyParameterBlock, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ResUtilSetPropertyParameterBlockEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(ResUtilSetPropertyTable, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ResUtilSetPropertyTableEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(ResUtilSetResourceServiceEnvironment, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilSetResourceServiceStartParameters, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ResUtilSetSzValue, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilSetUnknownProperties, (arg1, arg2, arg3, arg4), 16)
       Api(ResUtilStartResourceService, (arg1, arg2), 8)
       Api(ResUtilStopResourceService, (arg1), 4)
       Api(ResUtilStopService, (arg1), 4)
       Api(ResUtilVerifyPrivatePropertyList, (arg1, arg2), 8)
       Api(ResUtilVerifyPropertyTable, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ResUtilVerifyResourceService, (arg1), 4)
       Api(ResUtilVerifyService, (arg1), 4)
EndImport
