XIncludeFile "common.pbi"

Import "rpcns4.lib"
       Api(I_GetDefaultEntrySyntax, (), 0)
       Api(I_RpcNsGetBuffer, (arg1), 4)
       Api(I_RpcNsRaiseException, (arg1, arg2), 8)
       Api(I_RpcNsSendReceive, (arg1, arg2), 8)
       Api(I_RpcReBindBuffer, (arg1), 4)
  AnsiWide(RpcNsBindingExport, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(RpcNsBindingImportBegin, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RpcNsBindingImportDone, (arg1), 4)
       Api(RpcNsBindingImportNext, (arg1, arg2), 8)
  AnsiWide(RpcNsBindingLookupBegin, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RpcNsBindingLookupDone, (arg1), 4)
       Api(RpcNsBindingLookupNext, (arg1, arg2), 8)
       Api(RpcNsBindingSelect, (arg1, arg2), 8)
  AnsiWide(RpcNsBindingUnexport, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RpcNsEntryExpandName, (arg1, arg2, arg3), 12)
  AnsiWide(RpcNsEntryObjectInqBegin, (arg1, arg2, arg3), 12)
       Api(RpcNsEntryObjectInqDone, (arg1), 4)
       Api(RpcNsEntryObjectInqNext, (arg1, arg2), 8)
  AnsiWide(RpcNsGroupDelete, (arg1, arg2), 8)
  AnsiWide(RpcNsGroupMbrAdd, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RpcNsGroupMbrInqBegin, (arg1, arg2, arg3, arg4), 16)
       Api(RpcNsGroupMbrInqDone, (arg1), 4)
  AnsiWide(RpcNsGroupMbrInqNext, (arg1, arg2), 8)
  AnsiWide(RpcNsGroupMbrRemove, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RpcNsMgmtBindingUnexport, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(RpcNsMgmtEntryCreate, (arg1, arg2), 8)
  AnsiWide(RpcNsMgmtEntryDelete, (arg1, arg2), 8)
  AnsiWide(RpcNsMgmtEntryInqIfIds, (arg1, arg2, arg3), 12)
       Api(RpcNsMgmtHandleSetExpAge, (arg1, arg2), 8)
       Api(RpcNsMgmtInqExpAge, (arg1), 4)
       Api(RpcNsMgmtSetExpAge, (arg1), 4)
  AnsiWide(RpcNsProfileDelete, (arg1, arg2), 8)
  AnsiWide(RpcNsProfileEltAdd, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(RpcNsProfileEltInqBegin, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(RpcNsProfileEltInqDone, (arg1), 4)
  AnsiWide(RpcNsProfileEltInqNext, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(RpcNsProfileEltRemove, (arg1, arg2, arg3, arg4, arg5), 20)
EndImport
