XIncludeFile "common.pbi"

Import "rpcrt4.lib"
       Api(char_array_from_ndr, (arg1, arg2, arg3, arg4), 16)
       Api(char_from_ndr, (arg1, arg2), 8)
       Api(CStdStubBuffer_AddRef, (arg1), 4)
       Api(CStdStubBuffer_Connect, (arg1, arg2), 8)
       Api(CStdStubBuffer_CountRefs, (arg1), 4)
       Api(CStdStubBuffer_DebugServerQueryInterface, (arg1, arg2), 8)
       Api(CStdStubBuffer_DebugServerRelease, (arg1, arg2), 8)
       Api(CStdStubBuffer_Disconnect, (arg1), 4)
       Api(CStdStubBuffer_Invoke, (arg1, arg2, arg3), 12)
       Api(CStdStubBuffer_IsIIDSupported, (arg1, arg2), 8)
       Api(CStdStubBuffer_QueryInterface, (arg1, arg2, arg3), 12)
       Api(data_from_ndr, (arg1, arg2, arg3, arg4), 16)
       Api(data_into_ndr, (arg1, arg2, arg3, arg4), 16)
       Api(data_size_ndr, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(DceErrorInqText, (arg1, arg2), 8)
       Api(double_array_from_ndr, (arg1, arg2, arg3, arg4), 16)
       Api(double_from_ndr, (arg1, arg2), 8)
       Api(enum_from_ndr, (arg1, arg2), 8)
       Api(float_array_from_ndr, (arg1, arg2, arg3, arg4), 16)
       Api(float_from_ndr, (arg1, arg2), 8)
       Api(GlobalMutexClearExternal, (), 0)
       Api(GlobalMutexRequestExternal, (), 0)
       Api(I_RpcAbortAsyncCall, (arg1, arg2), 8)
       Api(I_RpcAllocate, (arg1), 4)
       Api(I_RpcAsyncAbortCall, (arg1, arg2), 8)
       Api(I_RpcAsyncSetHandle, (arg1, arg2), 8)
       Api(I_RpcBindingCopy, (arg1, arg2), 8)
       Api(I_RpcBindingInqConnId, (arg1, arg2, arg3), 12)
  AnsiWide(I_RpcBindingInqDynamicEndpoint, (arg1, arg2), 8)
       Api(I_RpcBindingInqTransportType, (arg1, arg2), 8)
       Api(I_RpcBindingIsClientLocal, (arg1, arg2), 8)
       Api(I_RpcClearMutex, (arg1), 4)
       Api(I_RpcConnectionInqSockBuffSize, (arg1, arg2), 8)
       Api(I_RpcConnectionSetSockBuffSize, (arg1, arg2), 8)
       Api(I_RpcDeleteMutex, (arg1), 4)
       Api(I_RpcFree, (arg1), 4)
       Api(I_RpcFreeBuffer, (arg1), 4)
       Api(I_RpcFreePipeBuffer, (arg1), 4)
       Api(I_RpcGetAssociationContext, (arg1, arg2), 8)
       Api(I_RpcGetBuffer, (arg1), 4)
       Api(I_RpcGetBufferWithObject, (arg1, arg2), 8)
       Api(I_RpcGetCurrentCallHandle, (), 0)
       Api(I_RpcGetExtendedError, (), 0)
       Api(I_RpcGetServerContextList, (arg1), 4)
       Api(I_RpcIfInqTransferSyntaxes, (arg1, arg2, arg3, arg4), 16)
       Api(I_RpcLogEvent, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(I_RpcMapWin32Status, (arg1), 4)
       Api(I_RpcMonitorAssociation, (arg1, arg2, arg3), 12)
  AnsiWide(I_RpcNsBindingSetEntryName, (arg1, arg2, arg3), 12)
       Api(I_RpcNsInterfaceExported, (arg1, arg2, arg3), 12)
       Api(I_RpcNsInterfaceUnexported, (arg1, arg2, arg3), 12)
       Api(I_RpcParseSecurity, (arg1, arg2), 8)
       Api(I_RpcPauseExecution, (arg1), 4)
       Api(I_RpcReallocPipeBuffer, (arg1, arg2), 8)
       Api(I_RpcReceive, (arg1, arg2), 8)
       Api(I_RpcRequestMutex, (arg1), 4)
       Api(I_RpcSend, (arg1), 4)
       Api(I_RpcSendReceive, (arg1), 4)
       Api(I_RpcServerAllocateIpPort, (arg1, arg2), 8)
       Api(I_RpcServerInqTransportType, (arg1), 4)
       Api(I_RpcServerRegisterForwardFunction, (arg1), 4)
  AnsiWide(I_RpcServerUseProtseq2, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(I_RpcServerUseProtseqEp2, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(I_RpcSetAsyncHandle, (arg1, arg2), 8)
       Api(I_RpcSetServerContextList, (arg1, arg2), 8)
       Api(I_RpcSsDontSerializeContext, (), 0)
       Api(I_RpcStopMonitorAssociation, (arg1), 4)
       Api(I_RpcTransConnectionAllocatePacket, (arg1, arg2), 8)
       Api(I_RpcTransConnectionFreePacket, (arg1, arg2), 8)
       Api(I_RpcTransConnectionReallocPacket, (arg1, arg2, arg3, arg4), 16)
       Api(I_RpcTransDatagramAllocate, (arg1, arg2, arg3, arg4), 16)
       Api(I_RpcTransDatagramAllocate2, (arg1, arg2, arg3, arg4), 16)
       Api(I_RpcTransDatagramFree, (arg1, arg2, arg3), 12)
       Api(I_RpcTransGetThreadEvent, (), 0)
       Api(I_RpcTransIoCancelled, (arg1, arg2), 8)
       Api(I_RpcTransProtectThread, (), 0)
       Api(I_RpcTransServerNewConnection, (arg1), 4)
       Api(I_RpcTransUnprotectThread, (arg1), 4)
       Api(I_UuidCreate, (arg1), 4)
       Api(IUnknown_AddRef_Proxy, (arg1), 4)
       Api(IUnknown_QueryInterface_Proxy, (arg1, arg2, arg3), 12)
       Api(IUnknown_Release_Proxy, (arg1), 4)
       Api(long_array_from_ndr, (arg1, arg2, arg3, arg4), 16)
       Api(long_from_ndr, (arg1, arg2), 8)
       Api(long_from_ndr_temp, (arg1, arg2, arg3), 12)
       Api(MesBufferHandleReset, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(MesDecodeBufferHandleCreate, (arg1, arg2, arg3), 12)
       Api(MesDecodeIncrementalHandleCreate, (arg1, arg2, arg3), 12)
       Api(MesEncodeDynBufferHandleCreate, (arg1, arg2, arg3), 12)
       Api(MesEncodeFixedBufferHandleCreate, (arg1, arg2, arg3, arg4), 16)
       Api(MesEncodeIncrementalHandleCreate, (arg1, arg2, arg3, arg4), 16)
       Api(MesHandleFree, (arg1), 4)
       Api(MesIncrementalHandleReset, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(MesInqProcEncodingId, (arg1, arg2, arg3), 12)
       Api(MIDL_wchar_strcpy, (arg1, arg2), 8)
       Api(MIDL_wchar_strlen, (arg1), 4)
       Api(NdrAllocate, (arg1, arg2), 8)
       Api(NdrAsyncServerCall, (arg1), 4)
       Api(NdrAsyncStubCall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrByteCountPointerBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrByteCountPointerFree, (arg1, arg2, arg3), 12)
       Api(NdrByteCountPointerMarshall, (arg1, arg2, arg3), 12)
       Api(NdrByteCountPointerUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NDRCContextBinding, (arg1), 4)
       Api(NDRCContextMarshall, (arg1, arg2), 8)
       Api(NDRCContextUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrClearOutParameters, (arg1, arg2, arg3), 12)
       Api(NdrClientContextMarshall, (arg1, arg2, arg3), 12)
       Api(NdrClientContextUnmarshall, (arg1, arg2, arg3), 12)
       Api(NdrClientInitialize, (arg1, arg2, arg3, arg4), 16)
       Api(NdrClientInitializeNew, (arg1, arg2, arg3, arg4), 16)
       Api(NdrComplexArrayBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrComplexArrayFree, (arg1, arg2, arg3), 12)
       Api(NdrComplexArrayMarshall, (arg1, arg2, arg3), 12)
       Api(NdrComplexArrayMemorySize, (arg1, arg2), 8)
       Api(NdrComplexArrayUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrComplexStructBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrComplexStructFree, (arg1, arg2, arg3), 12)
       Api(NdrComplexStructMarshall, (arg1, arg2, arg3), 12)
       Api(NdrComplexStructMemorySize, (arg1, arg2), 8)
       Api(NdrComplexStructUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrConformantArrayBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrConformantArrayFree, (arg1, arg2, arg3), 12)
       Api(NdrConformantArrayMarshall, (arg1, arg2, arg3), 12)
       Api(NdrConformantArrayMemorySize, (arg1, arg2), 8)
       Api(NdrConformantArrayUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrConformantStringBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrConformantStringMarshall, (arg1, arg2, arg3), 12)
       Api(NdrConformantStringMemorySize, (arg1, arg2), 8)
       Api(NdrConformantStringUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrConformantStructBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrConformantStructFree, (arg1, arg2, arg3), 12)
       Api(NdrConformantStructMarshall, (arg1, arg2, arg3), 12)
       Api(NdrConformantStructMemorySize, (arg1, arg2), 8)
       Api(NdrConformantStructUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrConformantVaryingArrayBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrConformantVaryingArrayFree, (arg1, arg2, arg3), 12)
       Api(NdrConformantVaryingArrayMarshall, (arg1, arg2, arg3), 12)
       Api(NdrConformantVaryingArrayMemorySize, (arg1, arg2), 8)
       Api(NdrConformantVaryingArrayUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrConformantVaryingStructBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrConformantVaryingStructFree, (arg1, arg2, arg3), 12)
       Api(NdrConformantVaryingStructMarshall, (arg1, arg2, arg3), 12)
       Api(NdrConformantVaryingStructMemorySize, (arg1, arg2), 8)
       Api(NdrConformantVaryingStructUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrContextHandleInitialize, (arg1, arg2), 8)
       Api(NdrContextHandleSize, (arg1, arg2, arg3), 12)
       Api(NdrConvert, (arg1, arg2), 8)
       Api(NdrConvert2, (arg1, arg2, arg3), 12)
       Api(NDRcopy, (arg1, arg2, arg3), 12)
       Api(NdrCorrelationFree, (arg1), 4)
       Api(NdrCorrelationInitialize, (arg1, arg2, arg3, arg4), 16)
       Api(NdrCorrelationPass, (arg1), 4)
       Api(NdrCStdStubBuffer2_Release, (arg1, arg2), 8)
       Api(NdrCStdStubBuffer_Release, (arg1, arg2), 8)
       Api(NdrDcomAsyncStubCall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrDllCanUnloadNow, (arg1), 4)
       Api(NdrDllGetClassObject, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NdrDllRegisterProxy, (arg1, arg2, arg3), 12)
       Api(NdrDllUnregisterProxy, (arg1, arg2, arg3), 12)
       Api(NdrEncapsulatedUnionBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrEncapsulatedUnionFree, (arg1, arg2, arg3), 12)
       Api(NdrEncapsulatedUnionMarshall, (arg1, arg2, arg3), 12)
       Api(NdrEncapsulatedUnionMemorySize, (arg1, arg2), 8)
       Api(NdrEncapsulatedUnionUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrFixedArrayBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrFixedArrayFree, (arg1, arg2, arg3), 12)
       Api(NdrFixedArrayMarshall, (arg1, arg2, arg3), 12)
       Api(NdrFixedArrayMemorySize, (arg1, arg2), 8)
       Api(NdrFixedArrayUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrFullPointerFree, (arg1, arg2), 8)
       Api(NdrFullPointerInsertRefId, (arg1, arg2, arg3), 12)
       Api(NdrFullPointerQueryPointer, (arg1, arg2, arg3, arg4), 16)
       Api(NdrFullPointerQueryRefId, (arg1, arg2, arg3, arg4), 16)
       Api(NdrFullPointerXlatFree, (arg1), 4)
       Api(NdrFullPointerXlatInit, (arg1, arg2), 8)
       Api(NdrGetBuffer, (arg1, arg2, arg3), 12)
       Api(NdrGetDcomProtocolVersion, (arg1, arg2), 8)
       Api(NdrGetPartialBuffer, (arg1), 4)
       Api(NdrGetPipeBuffer, (arg1, arg2, arg3), 12)
       Api(NdrHardStructBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrHardStructFree, (arg1, arg2, arg3), 12)
       Api(NdrHardStructMarshall, (arg1, arg2, arg3), 12)
       Api(NdrHardStructMemorySize, (arg1, arg2), 8)
       Api(NdrHardStructUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrInterfacePointerBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrInterfacePointerFree, (arg1, arg2, arg3), 12)
       Api(NdrInterfacePointerMarshall, (arg1, arg2, arg3), 12)
       Api(NdrInterfacePointerMemorySize, (arg1, arg2), 8)
       Api(NdrInterfacePointerUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrIsAppDoneWithPipes, (arg1), 4)
       Api(NdrMapCommAndFaultStatus, (arg1, arg2, arg3, arg4), 16)
       Api(NdrMarkNextActivePipe, (arg1), 4)
       Api(NdrMesSimpleTypeAlignSize, (arg1), 4)
       Api(NdrMesSimpleTypeDecode, (arg1, arg2, arg3), 12)
       Api(NdrMesSimpleTypeEncode, (arg1, arg2, arg3, arg4), 16)
       Api(NdrMesTypeAlignSize, (arg1, arg2, arg3, arg4), 16)
       Api(NdrMesTypeDecode, (arg1, arg2, arg3, arg4), 16)
       Api(NdrMesTypeEncode, (arg1, arg2, arg3, arg4), 16)
       Api(NdrNonConformantStringBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrNonConformantStringMarshall, (arg1, arg2, arg3), 12)
       Api(NdrNonConformantStringMemorySize, (arg1, arg2), 8)
       Api(NdrNonConformantStringUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrNonEncapsulatedUnionBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrNonEncapsulatedUnionFree, (arg1, arg2, arg3), 12)
       Api(NdrNonEncapsulatedUnionMarshall, (arg1, arg2, arg3), 12)
       Api(NdrNonEncapsulatedUnionMemorySize, (arg1, arg2), 8)
       Api(NdrNonEncapsulatedUnionUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrNsGetBuffer, (arg1, arg2, arg3), 12)
       Api(NdrNsSendReceive, (arg1, arg2, arg3), 12)
       Api(NdrOleAllocate, (arg1), 4)
       Api(NdrOleFree, (arg1), 4)
       Api(NdrPipePull, (arg1, arg2, arg3, arg4), 16)
       Api(NdrPipePush, (arg1, arg2, arg3), 12)
       Api(NdrPipesDone, (arg1), 4)
       Api(NdrPipeSendReceive, (arg1, arg2), 8)
       Api(NdrPipesInitialize, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NdrPointerBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrPointerFree, (arg1, arg2, arg3), 12)
       Api(NdrPointerMarshall, (arg1, arg2, arg3), 12)
       Api(NdrPointerMemorySize, (arg1, arg2), 8)
       Api(NdrPointerUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrProxyErrorHandler, (arg1), 4)
       Api(NdrProxyFreeBuffer, (arg1, arg2), 8)
       Api(NdrProxyGetBuffer, (arg1, arg2), 8)
       Api(NdrProxyInitialize, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NdrProxySendReceive, (arg1, arg2), 8)
       Api(NdrpSetRpcSsDefaults, (arg1, arg2), 8)
       Api(NdrRangeUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrRpcSmClientAllocate, (arg1), 4)
       Api(NdrRpcSmClientFree, (arg1), 4)
       Api(NdrRpcSmSetClientToOsf, (arg1), 4)
       Api(NdrRpcSsDefaultAllocate, (arg1), 4)
       Api(NdrRpcSsDefaultFree, (arg1), 4)
       Api(NdrRpcSsDisableAllocate, (arg1), 4)
       Api(NdrRpcSsEnableAllocate, (arg1), 4)
       Api(NDRSContextMarshall, (arg1, arg2, arg3), 12)
       Api(NDRSContextMarshall2, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NDRSContextMarshallEx, (arg1, arg2, arg3, arg4), 16)
       Api(NDRSContextUnmarshall, (arg1, arg2), 8)
       Api(NDRSContextUnmarshall2, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NDRSContextUnmarshallEx, (arg1, arg2, arg3), 12)
       Api(NdrSendReceive, (arg1, arg2), 8)
       Api(NdrServerCall, (arg1), 4)
       Api(NdrServerCall2, (arg1), 4)
       Api(NdrServerContextMarshall, (arg1, arg2, arg3), 12)
       Api(NdrServerContextNewMarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrServerContextNewUnmarshall, (arg1, arg2), 8)
       Api(NdrServerContextUnmarshall, (arg1), 4)
       Api(NdrServerInitialize, (arg1, arg2, arg3), 12)
       Api(NdrServerInitializeMarshall, (arg1, arg2), 8)
       Api(NdrServerInitializeNew, (arg1, arg2, arg3), 12)
       Api(NdrServerInitializePartial, (arg1, arg2, arg3, arg4), 16)
       Api(NdrServerInitializeUnmarshall, (arg1, arg2, arg3), 12)
       Api(NdrServerMarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrServerUnmarshall, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(NdrSimpleStructBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrSimpleStructFree, (arg1, arg2, arg3), 12)
       Api(NdrSimpleStructMarshall, (arg1, arg2, arg3), 12)
       Api(NdrSimpleStructMemorySize, (arg1, arg2), 8)
       Api(NdrSimpleStructUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrSimpleTypeMarshall, (arg1, arg2, arg3), 12)
       Api(NdrSimpleTypeUnmarshall, (arg1, arg2, arg3), 12)
       Api(NdrStubCall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrStubCall2, (arg1, arg2, arg3, arg4), 16)
       Api(NdrStubForwardingFunction, (arg1, arg2, arg3, arg4), 16)
       Api(NdrStubGetBuffer, (arg1, arg2, arg3), 12)
       Api(NdrStubInitialize, (arg1, arg2, arg3, arg4), 16)
       Api(NdrStubInitializeMarshall, (arg1, arg2, arg3), 12)
       Api(NdrUserMarshalBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrUserMarshalFree, (arg1, arg2, arg3), 12)
       Api(NdrUserMarshalMarshall, (arg1, arg2, arg3), 12)
       Api(NdrUserMarshalMemorySize, (arg1, arg2), 8)
       Api(NdrUserMarshalSimpleTypeConvert, (arg1, arg2, arg3), 12)
       Api(NdrUserMarshalUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrVaryingArrayBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrVaryingArrayFree, (arg1, arg2, arg3), 12)
       Api(NdrVaryingArrayMarshall, (arg1, arg2, arg3), 12)
       Api(NdrVaryingArrayMemorySize, (arg1, arg2), 8)
       Api(NdrVaryingArrayUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(NdrXmitOrRepAsBufferSize, (arg1, arg2, arg3), 12)
       Api(NdrXmitOrRepAsFree, (arg1, arg2, arg3), 12)
       Api(NdrXmitOrRepAsMarshall, (arg1, arg2, arg3), 12)
       Api(NdrXmitOrRepAsMemorySize, (arg1, arg2), 8)
       Api(NdrXmitOrRepAsUnmarshall, (arg1, arg2, arg3, arg4), 16)
       Api(RpcAbortAsyncCall, (arg1, arg2), 8)
       Api(RpcAsyncAbortCall, (arg1, arg2), 8)
       Api(RpcAsyncCancelCall, (arg1, arg2), 8)
       Api(RpcAsyncCompleteCall, (arg1, arg2), 8)
       Api(RpcAsyncGetCallStatus, (arg1), 4)
       Api(RpcAsyncInitializeHandle, (arg1, arg2), 8)
       Api(RpcAsyncRegisterInfo, (arg1), 4)
       Api(RpcBindingCopy, (arg1, arg2), 8)
       Api(RpcBindingFree, (arg1), 4)
  AnsiWide(RpcBindingFromStringBinding, (arg1, arg2), 8)
  AnsiWide(RpcBindingInqAuthClient, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(RpcBindingInqAuthClientEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(RpcBindingInqAuthInfo, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(RpcBindingInqAuthInfoEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(RpcBindingInqObject, (arg1, arg2), 8)
       Api(RpcBindingInqOption, (arg1, arg2, arg3), 12)
       Api(RpcBindingReset, (arg1), 4)
       Api(RpcBindingServerFromClient, (arg1, arg2), 8)
  AnsiWide(RpcBindingSetAuthInfo, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(RpcBindingSetAuthInfoEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(RpcBindingSetObject, (arg1, arg2), 8)
       Api(RpcBindingSetOption, (arg1, arg2, arg3), 12)
  AnsiWide(RpcBindingToStringBinding, (arg1, arg2), 8)
       Api(RpcBindingVectorFree, (arg1), 4)
       Api(RpcCancelAsyncCall, (arg1, arg2), 8)
       Api(RpcCancelThread, (arg1), 4)
       Api(RpcCancelThreadEx, (arg1, arg2), 8)
       Api(RpcCompleteAsyncCall, (arg1, arg2), 8)
  AnsiWide(RpcEpRegister, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RpcEpRegisterNoReplace, (arg1, arg2, arg3, arg4), 16)
       Api(RpcEpResolveBinding, (arg1, arg2), 8)
       Api(RpcEpUnregister, (arg1, arg2, arg3), 12)
       Api(RpcGetAsyncCallStatus, (arg1), 4)
       Api(RpcIfIdVectorFree, (arg1), 4)
       Api(RpcIfInqId, (arg1, arg2), 8)
       Api(RpcImpersonateClient, (arg1), 4)
       Api(RpcInitializeAsyncHandle, (arg1, arg2), 8)
       Api(RpcMgmtEnableIdleCleanup, (), 0)
       Api(RpcMgmtEpEltInqBegin, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RpcMgmtEpEltInqDone, (arg1), 4)
  AnsiWide(RpcMgmtEpEltInqNext, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RpcMgmtEpUnregister, (arg1, arg2, arg3, arg4), 16)
       Api(RpcMgmtInqComTimeout, (arg1, arg2), 8)
       Api(RpcMgmtInqDefaultProtectLevel, (arg1, arg2), 8)
       Api(RpcMgmtInqIfIds, (arg1, arg2), 8)
  AnsiWide(RpcMgmtInqServerPrincName, (arg1, arg2, arg3), 12)
       Api(RpcMgmtInqStats, (arg1, arg2), 8)
       Api(RpcMgmtIsServerListening, (arg1), 4)
       Api(RpcMgmtSetAuthorizationFn, (arg1), 4)
       Api(RpcMgmtSetCancelTimeout, (arg1), 4)
       Api(RpcMgmtSetComTimeout, (arg1, arg2), 8)
       Api(RpcMgmtSetServerStackSize, (arg1), 4)
       Api(RpcMgmtStatsVectorFree, (arg1), 4)
       Api(RpcMgmtStopServerListening, (arg1), 4)
  AnsiWide(RpcNetworkInqProtseqs, (arg1), 4)
  AnsiWide(RpcNetworkIsProtseqValid, (arg1), 4)
  AnsiWide(RpcNsBindingInqEntryName, (arg1, arg2, arg3), 12)
       Api(RpcObjectInqType, (arg1, arg2), 8)
       Api(RpcObjectSetInqFn, (arg1), 4)
       Api(RpcObjectSetType, (arg1, arg2), 8)
  AnsiWide(RpcProtseqVectorFree, (arg1), 4)
       Api(RpcRaiseException, (arg1), 4)
       Api(RpcRegisterAsyncInfo, (arg1), 4)
       Api(RpcRevertToSelf, (), 0)
       Api(RpcRevertToSelfEx, (arg1), 4)
       Api(RpcServerInqBindings, (arg1), 4)
  AnsiWide(RpcServerInqDefaultPrincName, (arg1, arg2), 8)
       Api(RpcServerInqIf, (arg1, arg2, arg3), 12)
       Api(RpcServerListen, (arg1, arg2, arg3), 12)
  AnsiWide(RpcServerRegisterAuthInfo, (arg1, arg2, arg3, arg4), 16)
       Api(RpcServerRegisterIf, (arg1, arg2, arg3), 12)
       Api(RpcServerRegisterIf2, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(RpcServerRegisterIfEx, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(RpcServerTestCancel, (arg1), 4)
       Api(RpcServerUnregisterIf, (arg1, arg2, arg3), 12)
       Api(RpcServerUseAllProtseqs, (arg1, arg2), 8)
       Api(RpcServerUseAllProtseqsEx, (arg1, arg2, arg3), 12)
       Api(RpcServerUseAllProtseqsIf, (arg1, arg2, arg3), 12)
       Api(RpcServerUseAllProtseqsIfEx, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RpcServerUseProtseq, (arg1, arg2, arg3), 12)
  AnsiWide(RpcServerUseProtseqEp, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RpcServerUseProtseqEpEx, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(RpcServerUseProtseqEx, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RpcServerUseProtseqIf, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RpcServerUseProtseqIfEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RpcSmAllocate, (arg1, arg2), 8)
       Api(RpcSmClientFree, (arg1), 4)
       Api(RpcSmDestroyClientContext, (arg1), 4)
       Api(RpcSmDisableAllocate, (), 0)
       Api(RpcSmEnableAllocate, (), 0)
       Api(RpcSmFree, (arg1), 4)
       Api(RpcSmGetThreadHandle, (arg1), 4)
       Api(RpcSmSetClientAllocFree, (arg1, arg2), 8)
       Api(RpcSmSetThreadHandle, (arg1), 4)
       Api(RpcSmSwapClientAllocFree, (arg1, arg2, arg3, arg4), 16)
       Api(RpcSsAllocate, (arg1), 4)
       Api(RpcSsDestroyClientContext, (arg1), 4)
       Api(RpcSsDisableAllocate, (), 0)
       Api(RpcSsDontSerializeContext, (), 0)
       Api(RpcSsEnableAllocate, (), 0)
       Api(RpcSsFree, (arg1), 4)
       Api(RpcSsGetContextBinding, (arg1, arg2), 8)
       Api(RpcSsGetThreadHandle, (), 0)
       Api(RpcSsSetClientAllocFree, (arg1, arg2), 8)
       Api(RpcSsSetThreadHandle, (arg1), 4)
       Api(RpcSsSwapClientAllocFree, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RpcStringBindingCompose, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(RpcStringBindingParse, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(RpcStringFree, (arg1), 4)
       Api(RpcTestCancel, (), 0)
       Api(short_array_from_ndr, (arg1, arg2, arg3, arg4), 16)
       Api(short_from_ndr, (arg1, arg2), 8)
       Api(short_from_ndr_temp, (arg1, arg2, arg3), 12)
       Api(TowerConstruct, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(TowerExplode, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(tree_into_ndr, (arg1, arg2, arg3, arg4), 16)
       Api(tree_peek_ndr, (arg1, arg2, arg3, arg4), 16)
       Api(tree_size_ndr, (arg1, arg2, arg3, arg4), 16)
       Api(UuidCompare, (arg1, arg2, arg3), 12)
       Api(UuidCreate, (arg1), 4)
       Api(UuidCreateNil, (arg1), 4)
       Api(UuidCreateSequential, (arg1), 4)
       Api(UuidEqual, (arg1, arg2, arg3), 12)
  AnsiWide(UuidFromString, (arg1, arg2), 8)
       Api(UuidHash, (arg1, arg2), 8)
       Api(UuidIsNil, (arg1, arg2), 8)
  AnsiWide(UuidToString, (arg1, arg2), 8)
EndImport
