XIncludeFile "common.pbi"

Import "secur32.lib"
       Api(AcceptSecurityContext, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
  AnsiWide(AcquireCredentialsHandle, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
  AnsiWide(AddCredentials, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(AddSecurityPackage, (arg1, arg2), 8)
       Api(ApplyControlToken, (arg1, arg2), 8)
       Api(CompleteAuthToken, (arg1, arg2), 8)
       Api(DecryptMessage, (arg1, arg2, arg3, arg4), 16)
       Api(DeleteSecurityContext, (arg1), 4)
  AnsiWide(DeleteSecurityPackage, (arg1), 4)
       Api(EncryptMessage, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(EnumerateSecurityPackages, (arg1, arg2), 8)
       Api(ExportSecurityContext, (arg1, arg2, arg3, arg4), 16)
       Api(FreeContextBuffer, (arg1), 4)
       Api(FreeCredentialsHandle, (arg1), 4)
  AnsiWide(GetComputerObjectName, (arg1, arg2, arg3), 12)
  AnsiWide(GetUserNameEx, (arg1, arg2, arg3), 12)
       Api(ImpersonateSecurityContext, (arg1), 4)
  AnsiWide(ImportSecurityContext, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InitializeSecurityContext, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
  AnsiWide(InitSecurityInterface, (), 0)
       Api(LsaCallAuthenticationPackage, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(LsaConnectUntrusted, (arg1), 4)
       Api(LsaDeregisterLogonProcess, (arg1), 4)
       Api(LsaFreeReturnBuffer, (arg1), 4)
       Api(LsaLogonUser, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14), 56)
       Api(LsaLookupAuthenticationPackage, (arg1, arg2, arg3), 12)
       Api(LsaRegisterLogonProcess, (arg1, arg2, arg3), 12)
       Api(LsaRegisterPolicyChangeNotification, (arg1, arg2), 8)
       Api(LsaUnregisterPolicyChangeNotification, (arg1, arg2), 8)
       Api(MakeSignature, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(QueryContextAttributes, (arg1, arg2, arg3), 12)
  AnsiWide(QueryCredentialsAttributes, (arg1, arg2, arg3), 12)
       Api(QuerySecurityContextToken, (arg1, arg2), 8)
  AnsiWide(QuerySecurityPackageInfo, (arg1, arg2), 8)
       Api(RevertSecurityContext, (arg1), 4)
       Api(SaslAcceptSecurityContext, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
  AnsiWide(SaslEnumerateProfiles, (arg1, arg2), 8)
  AnsiWide(SaslGetProfilePackage, (arg1, arg2), 8)
  AnsiWide(SaslIdentifyPackage, (arg1, arg2), 8)
  AnsiWide(SaslInitializeSecurityContext, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(SealMessage, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(TranslateName, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(UnsealMessage, (arg1, arg2, arg3, arg4), 16)
       Api(VerifySignature, (arg1, arg2, arg3, arg4), 16)
EndImport
