XIncludeFile "common.pbi"

Import "setupapi.lib"
       Api(AddTagToGroupOrderListEntry, (arg1, arg2, arg3), 12)
       Api(AppendStringToMultiSz, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(AssertFail, (arg1, arg2, arg3), 12)
       Api(CaptureAndConvertAnsiArg, (arg1, arg2), 8)
       Api(CaptureStringArg, (arg1, arg2), 8)
       Api(CenterWindowRelativeToParent, (arg1), 4)
       Api(ConcatenatePaths, (arg1, arg2, arg3, arg4), 16)
       Api(DestroyTextFileReadBuffer, (arg1), 4)
       Api(DoesUserHavePrivilege, (arg1), 4)
       Api(DuplicateString, (arg1), 4)
       Api(EnablePrivilege, (arg1, arg2), 8)
       Api(ExtensionPropSheetPageProc, (arg1, arg2, arg3), 12)
       Api(FileExists, (arg1, arg2), 8)
       Api(FreeStringArray, (arg1, arg2), 8)
       Api(GetNewInfName, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetSetFileTimestamp, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetVersionInfoFromImage, (arg1, arg2, arg3), 12)
       Api(InfIsFromOemLocation, (arg1), 4)
  AnsiWide(InstallHinfSection, (arg1, arg2, arg3, arg4), 16)
       Api(InstallStop, (arg1), 4)
       Api(LookUpStringInTable, (arg1, arg2, arg3), 12)
       Api(MemoryInitialize, (arg1), 4)
       Api(MultiByteToUnicode, (arg1, arg2), 8)
       Api(MyFree, (arg1), 4)
       Api(MyGetFileTitle, (arg1), 4)
       Api(MyMalloc, (arg1), 4)
       Api(MyRealloc, (arg1, arg2), 8)
       Api(OpenAndMapFileForRead, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(OutOfMemory, (arg1), 4)
       Api(QueryMultiSzValueToArray, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(QueryRegistryValue, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ReadAsciiOrUnicodeTextFile, (arg1, arg2), 8)
       Api(RegistryDelnode, (arg1, arg2), 8)
       Api(RetreiveFileSecurity, (arg1, arg2), 8)
       Api(RetrieveServiceConfig, (arg1, arg2), 8)
       Api(SetArrayToMultiSzValue, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupAddToSourceList, (arg1, arg2), 8)
       Api(SetupCancelTemporarySourceList, (), 0)
       Api(SetupCloseFileQueue, (arg1), 4)
       Api(SetupCloseInfFile, (arg1), 4)
  AnsiWide(SetupCommitFileQueue, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupCopyError, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
  AnsiWide(SetupDecompressOrCopyFile, (arg1, arg2, arg3), 12)
  AnsiWide(SetupDefaultQueueCallback, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupDeleteError, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetupDiAskForOEMDisk, (arg1, arg2), 8)
       Api(SetupDiBuildClassInfoList, (arg1, arg2, arg3, arg4), 16)
       Api(SetupDiBuildDriverInfoList, (arg1, arg2, arg3), 12)
       Api(SetupDiCallClassInstaller, (arg1, arg2, arg3), 12)
       Api(SetupDiCancelDriverInfoSearch, (arg1), 4)
       Api(SetupDiChangeState, (arg1, arg2), 8)
  AnsiWide(SetupDiClassGuidsFromName, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupDiClassNameFromGuid, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupDiCreateDeviceInfo, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(SetupDiCreateDeviceInfoList, (arg1, arg2), 8)
  AnsiWide(SetupDiCreateDevRegKey, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(SetupDiDeleteDeviceInfo, (arg1, arg2), 8)
       Api(SetupDiDeleteDevRegKey, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetupDiDestroyClassImageList, (arg1), 4)
       Api(SetupDiDestroyDeviceInfoList, (arg1), 4)
       Api(SetupDiDestroyDriverInfoList, (arg1, arg2, arg3), 12)
       ; Api(SetupDiDrawMiniIcon, (arg1, arg2.RECT, arg3, arg4, arg5), 28) ; It ask a rect as second parameter and we don't support that
       Api(SetupDiEnumDeviceInfo, (arg1, arg2, arg3), 12)
       Api(SetupDiEnumDeviceInterfaces, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupDiEnumDriverInfo, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupDiGetActualSectionToInstall, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(SetupDiGetClassBitmapIndex, (arg1, arg2), 8)
  AnsiWide(SetupDiGetClassDescription, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupDiGetClassDevPropertySheets, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetupDiGetClassDevs, (*ClassGuid, *Enumerator, hwndParent, Flags), 16)
       Api(SetupDiGetClassImageIndex, (arg1, arg2, arg3), 12)
       Api(SetupDiGetClassImageList, (arg1), 4)
  AnsiWide(SetupDiGetClassInstallParams, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetupDiGetDeviceInfoListClass, (arg1, arg2), 8)
  AnsiWide(SetupDiGetDeviceInstallParams, (arg1, arg2, arg3), 12)
  AnsiWide(SetupDiGetDeviceInstanceId, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupDiGetDeviceInterfaceDetail, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetupDiGetDeviceRegistryProperty, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(SetupDiGetDriverInfoDetail, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetupDiGetDriverInstallParams, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupDiGetHwProfileFriendlyName, (arg1, arg2, arg3, arg4), 16)
       Api(SetupDiGetHwProfileList, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupDiGetINFClass, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetupDiGetSelectedDevice, (arg1, arg2), 8)
  AnsiWide(SetupDiGetSelectedDriver, (arg1, arg2, arg3), 12)
       Api(SetupDiGetWizardPage, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupDiInstallClass, (arg1, arg2, arg3, arg4), 16)
       Api(SetupDiInstallDevice, (arg1, arg2), 8)
       Api(SetupDiInstallDriverFiles, (arg1, arg2), 8)
       Api(SetupDiLoadClassIcon, (arg1, arg2, arg3), 12)
       Api(SetupDiMoveDuplicateDevice, (arg1, arg2), 8)
       Api(SetupDiOpenClassRegKey, (arg1, arg2), 8)
  AnsiWide(SetupDiOpenDeviceInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetupDiOpenDevRegKey, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(SetupDiRegisterDeviceInfo, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(SetupDiRemoveDevice, (arg1, arg2), 8)
       Api(SetupDiSelectDevice, (arg1, arg2), 8)
       Api(SetupDiSelectOEMDrv, (arg1, arg2, arg3), 12)
  AnsiWide(SetupDiSetClassInstallParams, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupDiSetDeviceInstallParams, (arg1, arg2, arg3), 12)
  AnsiWide(SetupDiSetDeviceRegistryProperty, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupDiSetDriverInstallParams, (arg1, arg2, arg3, arg4), 16)
       Api(SetupDiSetSelectedDevice, (arg1, arg2), 8)
  AnsiWide(SetupDiSetSelectedDriver, (arg1, arg2, arg3), 12)
  AnsiWide(SetupFindFirstLine, (arg1, arg2, arg3, arg4), 16)
       Api(SetupFindNextLine, (arg1, arg2), 8)
  AnsiWide(SetupFindNextMatchLine, (arg1, arg2, arg3), 12)
  AnsiWide(SetupFreeSourceList, (arg1, arg2), 8)
       Api(SetupGetBinaryField, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetupGetFieldCount, (arg1), 4)
  AnsiWide(SetupGetFileCompressionInfo, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupGetInfFileList, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupGetInfInformation, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetupGetIntField, (arg1, arg2, arg3), 12)
  AnsiWide(SetupGetLineByIndex, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupGetLineCount, (arg1, arg2), 8)
  AnsiWide(SetupGetLineText, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(SetupGetMultiSzField, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupGetSourceFileLocation, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(SetupGetSourceFileSize, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetupGetSourceInfo, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetupGetStringField, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupGetTargetPath, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(SetupInitDefaultQueueCallback, (arg1), 4)
       Api(SetupInitDefaultQueueCallbackEx, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupInitializeFileLog, (arg1, arg2), 8)
  AnsiWide(SetupInstallFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(SetupInstallFileEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
  AnsiWide(SetupInstallFilesFromInfSection, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetupInstallFromInfSection, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
  AnsiWide(SetupInstallServicesFromInfSection, (arg1, arg2, arg3), 12)
  AnsiWide(SetupIterateCabinet, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupLogFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
  AnsiWide(SetupOpenAppendInfFile, (arg1, arg2, arg3), 12)
       Api(SetupOpenFileQueue, (), 0)
  AnsiWide(SetupOpenInfFile, (arg1, arg2, arg3, arg4), 16)
       Api(SetupOpenMasterInf, (), 0)
  AnsiWide(SetupPromptForDisk, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(SetupPromptReboot, (arg1, arg2, arg3), 12)
  AnsiWide(SetupQueryFileLog, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(SetupQueryInfFileInformation, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupQueryInfVersionInformation, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetupQuerySourceList, (arg1, arg2, arg3), 12)
  AnsiWide(SetupQueueCopy, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
  AnsiWide(SetupQueueCopySection, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetupQueueDefaultCopy, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetupQueueDelete, (arg1, arg2, arg3), 12)
  AnsiWide(SetupQueueDeleteSection, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupQueueRename, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetupQueueRenameSection, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetupRemoveFileLogEntry, (arg1, arg2, arg3), 12)
  AnsiWide(SetupRemoveFromSourceList, (arg1, arg2), 8)
  AnsiWide(SetupRenameError, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetupScanFileQueue, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SetupSetDirectoryId, (arg1, arg2, arg3), 12)
  AnsiWide(SetupSetPlatformPathOverride, (arg1), 4)
  AnsiWide(SetupSetSourceList, (arg1, arg2, arg3), 12)
       Api(SetupTermDefaultQueueCallback, (arg1), 4)
       Api(SetupTerminateFileLog, (arg1), 4)
       Api(ShouldDeviceBeExcluded, (arg1, arg2, arg3), 12)
       Api(StampFileSecurity, (arg1, arg2), 8)
       Api(StringTableAddString, (arg1, arg2, arg3), 12)
       Api(StringTableDestroy, (arg1), 4)
       Api(StringTableDuplicate, (arg1), 4)
       Api(StringTableInitialize, (), 0)
       Api(StringTableLookUpString, (arg1, arg2, arg3), 12)
       Api(StringTableStringFromId, (arg1, arg2), 8)
       Api(StringTableTrim, (arg1), 4)
       Api(TakeOwnershipOfFile, (arg1), 4)
       Api(UnicodeToMultiByte, (arg1, arg2), 8)
       Api(UnmapAndCloseFile, (arg1, arg2, arg3), 12)
EndImport
