XIncludeFile "common.pbi"

Import "shell32.lib"
       Api(CallCPLEntry16, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(CheckEscapes, (arg1, arg2), 8)
       Api(Control_FillCache_RunDLL, (arg1, arg2, arg3, arg4), 16)
       Api(Control_RunDLL, (arg1, arg2, arg3, arg4), 16)
       Api(DAD_AutoScroll, (arg1, arg2, arg3), 12)
       Api(DAD_DragEnterEx, (arg1, pt.q), 12)
       Api(DAD_DragLeave, (), 0)
       Api(DAD_DragMove, (pt.q), 8)
       Api(DAD_ShowDragImage, (arg1), 4)
  AnsiWide(DoEnvironmentSubst, (arg1, arg2), 8)
       Api(DragAcceptFiles, (arg1, arg2), 8)
       Api(DragFinish, (arg1), 4)
  AnsiWide(DragQueryFile, (arg1, arg2, arg3, arg4), 16)
       Api(DragQueryPoint, (arg1, arg2), 8)
       Api(DriveType, (arg1), 4)
       Api(DuplicateIcon, (arg1, arg2), 8)
  AnsiWide(ExtractAssociatedIcon, (arg1, arg2, arg3), 12)
  AnsiWide(ExtractAssociatedIconEx, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(ExtractIcon, (hInst, *lpszExeFileName, nIconIndex), 12)
  AnsiWide(ExtractIconEx, (*lpszFile, nIconIndex, *phiconLarge, *phiconSmall, nIcons), 20)
  AnsiWide(ExtractIconResInfo, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(FindExecutable, (arg1, arg2, arg3), 12)
       Api(FindExeDlgProc, (arg1, arg2, arg3, arg4), 16)
       Api(FreeIconList, (arg1, arg2), 8)
       Api(GetFileNameFromBrowse, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ILAppendID, (arg1, arg2, arg3), 12)
       Api(ILClone, (arg1), 4)
       Api(ILCloneFirst, (arg1), 4)
       Api(ILCombine, (arg1, arg2), 8)
       Api(ILCreateFromPath, (arg1), 4)
       Api(ILFindChild, (arg1, arg2), 8)
       Api(ILFindLastID, (arg1), 4)
       Api(ILFree, (arg1), 4)
       Api(ILGetNext, (arg1), 4)
       Api(ILGetSize, (arg1), 4)
       Api(ILIsEqual, (arg1, arg2), 8)
       Api(ILIsParent, (arg1, arg2, arg3), 12)
       Api(ILLoadFromStream, (arg1, arg2), 8)
       Api(ILRemoveLastID, (arg1), 4)
       Api(ILSaveToStream, (arg1, arg2), 8)
  AnsiWide(InternalExtractIconList, (arg1, arg2, arg3), 12)
       Api(IsLFNDrive, (arg1), 4)
       Api(IsNetDrive, (arg1), 4)
       Api(IsUserAnAdmin, (), 0)
  AnsiWide(OpenAs_RunDLL, (arg1, arg2, arg3, arg4), 16)
       Api(OpenRegStream, (arg1, arg2, arg3, arg4), 16)
       Api(PathCleanupSpec, (arg1, arg2), 8)
       Api(PathGetShortPath, (arg1), 4)
       Api(PathIsExe, (arg1), 4)
       Api(PathMakeUniqueName, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(PathProcessCommand, (arg1, arg2, arg3, arg4), 16)
       Api(PathQualify, (arg1), 4)
       Api(PathResolve, (arg1, arg2, arg3), 12)
       Api(PathYetAnotherMakeUniqueName, (arg1, arg2, arg3, arg4), 16)
       Api(PickIconDlg, (arg1, arg2, arg3, arg4), 16)
       Api(PifMgr_CloseProperties, (arg1, arg2), 8)
       Api(PifMgr_GetProperties, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(PifMgr_OpenProperties, (arg1, arg2, arg3, arg4), 16)
       Api(PifMgr_SetProperties, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(PrintersGetCommand_RunDLL, (arg1, arg2, arg3, arg4), 16)
       Api(ReadCabinetState, (arg1, arg2), 8)
       Api(RealDriveType, (arg1, arg2), 8)
  AnsiWide(RealShellExecute, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
  AnsiWide(RealShellExecuteEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
       Api(RegenerateUserEnvironment, (arg1, arg2), 8)
       Api(RestartDialog, (arg1, arg2, arg3), 12)
       Api(SHAddFromPropSheetExtArray, (arg1, arg2, arg3), 12)
       Api(SHAddToRecentDocs, (arg1, arg2), 8)
       Api(SHAlloc, (arg1), 4)
       Api(SHAllocShared, (arg1, arg2, arg3), 12)
       Api(SHAppBarMessage, (arg1, arg2), 8)
  AnsiWide(SHBrowseForFolder, (arg1), 4)
       Api(SHChangeNotification_Lock, (arg1, arg2, arg3, arg4), 16)
       Api(SHChangeNotification_Unlock, (arg1), 4)
       Api(SHChangeNotify, (arg1, arg2, arg3, arg4), 16)
       Api(SHChangeNotifyDeregister, (arg1), 4)
       Api(SHChangeNotifyRegister, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(SHCloneSpecialIDList, (arg1, arg2, arg3), 12)
       Api(SHCLSIDFromString, (arg1, arg2), 8)
       Api(SHCoCreateInstance, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SHCreateDirectory, (arg1, arg2), 8)
       Api(SHCreatePropSheetExtArray, (arg1, arg2, arg3), 12)
       Api(SHCreateShellFolderViewEx, (arg1, arg2), 8)
       Api(SHCreateStdEnumFmtEtc, (arg1, arg2, arg3), 12)
       Api(SHDestroyPropSheetExtArray, (arg1), 4)
       Api(SHDoDragDrop, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SheChangeDir, (arg1), 4)
  AnsiWide(SheChangeDirEx, (arg1), 4)
  AnsiWide(SheFullPath, (arg1, arg2, arg3), 12)
       Api(SheGetCurDrive, (), 0)
  AnsiWide(SheGetDir, (arg1, arg2), 8)
       Api(Shell_GetCachedImageIndex, (arg1, arg2, arg3), 12)
       Api(Shell_GetImageLists, (arg1, arg2), 8)
       Api(Shell_MergeMenus, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(Shell_NotifyIcon, (arg1, arg2), 8)
  AnsiWide(ShellAbout, (arg1, *arg2, *arg3, arg4), 16)
  AnsiWide(ShellExecute, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(ShellExecuteEx, (arg1), 4)
       Api(ShellHookProc, (arg1, arg2, arg3), 12)
  AnsiWide(SheRemoveQuotes, (arg1), 4)
       Api(SheSetCurDrive, (arg1), 4)
  AnsiWide(SheShortenPath, (arg1, arg2), 8)
  AnsiWide(SHFileOperation, (arg1), 4)
       Api(SHFind_InitMenuPopup, (arg1, arg2, arg3, arg4), 16)
       Api(SHFindFiles, (arg1, arg2), 8)
       Api(SHFlushClipboard, (), 0)
       Api(SHFormatDrive, (arg1, arg2, arg3, arg4), 16)
       Api(SHFree, (arg1), 4)
       Api(SHFreeNameMappings, (arg1), 4)
       Api(SHFreeShared, (arg1, arg2), 8)
  AnsiWide(SHGetDataFromIDList, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SHGetDesktopFolder, (arg1), 4)
  AnsiWide(SHGetFileInfo, (*arg1, arg2, arg3, arg4, arg5), 20)
       Api(SHGetFolderLocation, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SHGetInstanceExplorer, (arg1), 4)
       Api(SHGetMalloc, (arg1), 4)
  AnsiWide(SHGetNewLinkInfo, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SHGetPathFromIDList, (arg1, arg2), 8)
       Api(SHGetRealIDL, (arg1, arg2, arg3), 12)
       Api(SHGetSetSettings, (arg1, arg2, arg3), 12)
       Api(SHGetSpecialFolderLocation, (arg1, arg2, arg3), 12)
  AnsiWide(SHGetSpecialFolderPath, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SHHelpShortcuts_RunDLL, (arg1, arg2, arg3, arg4), 16)
       Api(SHILCreateFromPath, (arg1, arg2, arg3), 12)
       Api(SHLoadInProc, (arg1), 4)
       Api(SHLoadOLE, (arg1), 4)
       Api(SHLockShared, (arg1, arg2), 8)
       Api(SHMapPIDLToSystemImageListIndex, (arg1, arg2, arg3), 12)
       Api(SHObjectProperties, (arg1, arg2, arg3, arg4), 16)
       Api(SHReplaceFromPropSheetExtArray, (arg1, arg2, arg3, arg4), 16)
       Api(SHRestricted, (arg1), 4)
       Api(SHRunControlPanel, (arg1, arg2), 8)
       Api(SHSetInstanceExplorer, (arg1), 4)
       Api(SHShellFolderView_Message, (arg1, arg2, arg3), 12)
       Api(SHSimpleIDListFromPath, (arg1), 4)
       Api(SHUnlockShared, (arg1), 4)
       Api(SHUpdateRecycleBinIcon, (), 0)
       Api(SHValidateUNC, (arg1, arg2, arg3), 12)
       Api(SignalFileOpen, (arg1), 4)
  AnsiWide(StrChr, (arg1, arg2), 8)
  AnsiWide(StrChrI, (arg1, arg2), 8)
  AnsiWide(StrCmpN, (arg1, arg2, arg3), 12)
  AnsiWide(StrCmpNI, (arg1, arg2, arg3), 12)
  AnsiWide(StrCpyN, (arg1, arg2, arg3), 12)
  AnsiWide(StrNCmp, (arg1, arg2, arg3), 12)
  AnsiWide(StrNCmpI, (arg1, arg2, arg3), 12)
  AnsiWide(StrNCpy, (arg1, arg2, arg3), 12)
  AnsiWide(StrRChr, (arg1, arg2, arg3), 12)
  AnsiWide(StrRChrI, (arg1, arg2, arg3), 12)
  AnsiWide(StrRStr, (arg1, arg2, arg3), 12)
  AnsiWide(StrRStrI, (arg1, arg2, arg3), 12)
  AnsiWide(StrStr, (arg1, arg2), 8)
  AnsiWide(StrStrI, (arg1, arg2), 8)
       Api(Win32DeleteFile, (arg1), 4)
       Api(WOWShellExecute, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(WriteCabinetState, (arg1), 4)
EndImport
