XIncludeFile "common.pbi"

Import "snmpapi.lib"
       Api(SnmpSvcAddrIsIpx, (arg1, arg2, arg3), 12)
       Api(SnmpSvcAddrToSocket, (arg1, arg2), 8)
       Api(SnmpSvcBufRevAndCpy, (arg1, arg2, arg3), 12)
       Api(SnmpSvcBufRevInPlace, (arg1, arg2), 8)
       Api(SnmpSvcDecodeMessage, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SnmpSvcEncodeMessage, (arg1, arg2, arg3, arg4), 16)
       Api(SnmpSvcGenerateAuthFailTrap, (arg1), 4)
       Api(SnmpSvcGenerateColdStartTrap, (arg1), 4)
       Api(SnmpSvcGenerateLinkDownTrap, (arg1, arg2), 8)
       Api(SnmpSvcGenerateLinkUpTrap, (arg1, arg2), 8)
       Api(SnmpSvcGenerateTrap, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SnmpSvcGenerateWarmStartTrap, (arg1), 4)
       Api(SnmpSvcGetUptime, (), 0)
       Api(SnmpSvcInitUptime, (), 0)
       Api(SnmpSvcReleaseMessage, (arg1), 4)
       Api(SnmpSvcReportEvent, (arg1, arg2, arg3, arg4), 16)
       Api(SnmpSvcSetLogLevel, (arg1), 4)
       Api(SnmpSvcSetLogType, (arg1), 4)
       Api(SnmpUtilAnsiToUnicode, (arg1, arg2, arg3), 12)
  AnsiWide(SnmpUtilIdsTo, (arg1, arg2), 8)
       Api(SnmpUtilMemAlloc, (arg1), 4)
       Api(SnmpUtilMemFree, (arg1), 4)
       Api(SnmpUtilMemReAlloc, (arg1, arg2), 8)
       Api(SnmpUtilOidAppend, (arg1, arg2), 8)
       Api(SnmpUtilOidCmp, (arg1, arg2), 8)
       Api(SnmpUtilOidCpy, (arg1, arg2), 8)
       Api(SnmpUtilOidFree, (arg1), 4)
       Api(SnmpUtilOidNCmp, (arg1, arg2, arg3), 12)
  AnsiWide(SnmpUtilOidTo, (arg1), 4)
       Api(SnmpUtilPrintAsnAny, (arg1), 4)
       Api(SnmpUtilPrintOid, (arg1), 4)
       Api(SnmpUtilUnicodeToAnsi, (arg1, arg2, arg3), 12)
       Api(SnmpUtilVarBindCpy, (arg1, arg2), 8)
       Api(SnmpUtilVarBindFree, (arg1), 4)
       Api(SnmpUtilVarBindListCpy, (arg1, arg2), 8)
       Api(SnmpUtilVarBindListFree, (arg1), 4)
EndImport
