XIncludeFile "common.pbi"

Import "tapi32.lib"
       Api(GetTheFunctionPtr, (arg1, arg2), 8)
       Api(lineAccept, (arg1, arg2, arg3), 12)
  AnsiWide(lineAddProvider, (arg1, arg2, arg3), 12)
       Api(lineAddToConference, (arg1, arg2), 8)
       Api(lineAgentSpecific, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(lineAnswer, (arg1, arg2, arg3), 12)
  AnsiWide(lineBlindTransfer, (arg1, arg2, arg3), 12)
       Api(lineClose, (arg1), 4)
       Api(lineCompleteCall, (arg1, arg2, arg3, arg4), 16)
       Api(lineCompleteTransfer, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(lineConfigDialog, (arg1, arg2, arg3), 12)
  AnsiWide(lineConfigDialogEdit, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(lineConfigProvider, (arg1, arg2), 8)
       Api(lineDeallocateCall, (arg1), 4)
       Api(lineDevSpecific, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(lineDevSpecificFeature, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(lineDial, (arg1, arg2, arg3), 12)
       Api(lineDrop, (arg1, arg2, arg3), 12)
  AnsiWide(lineForward, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(lineGatherDigits, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(lineGenerateDigits, (arg1, arg2, arg3, arg4), 16)
       Api(lineGenerateTone, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(lineGetAddressCaps, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(lineGetAddressID, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(lineGetAddressStatus, (arg1, arg2, arg3), 12)
  AnsiWide(lineGetAgentActivityList, (arg1, arg2, arg3), 12)
  AnsiWide(lineGetAgentCaps, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(lineGetAgentGroupList, (arg1, arg2, arg3), 12)
  AnsiWide(lineGetAgentStatus, (arg1, arg2, arg3), 12)
  AnsiWide(lineGetAppPriority, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(lineGetCallInfo, (arg1, arg2), 8)
       Api(lineGetCallStatus, (arg1, arg2), 8)
       Api(lineGetConfRelatedCalls, (arg1, arg2), 8)
  AnsiWide(lineGetCountry, (arg1, arg2, arg3), 12)
  AnsiWide(lineGetDevCaps, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(lineGetDevConfig, (arg1, arg2, arg3), 12)
  AnsiWide(lineGetIcon, (arg1, arg2, arg3), 12)
  AnsiWide(lineGetID, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(lineGetLineDevStatus, (arg1, arg2), 8)
       Api(lineGetMessage, (arg1, arg2, arg3), 12)
       Api(lineGetNewCalls, (arg1, arg2, arg3, arg4), 16)
       Api(lineGetNumRings, (arg1, arg2, arg3), 12)
  AnsiWide(lineGetProviderList, (arg1, arg2), 8)
  AnsiWide(lineGetRequest, (arg1, arg2, arg3), 12)
       Api(lineGetStatusMessages, (arg1, arg2, arg3), 12)
  AnsiWide(lineGetTranslateCaps, (arg1, arg2, arg3), 12)
  AnsiWide(lineHandoff, (arg1, arg2, arg3), 12)
       Api(lineHold, (arg1), 4)
       Api(lineInitialize, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(lineInitializeEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(lineMakeCall, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(lineMonitorDigits, (arg1, arg2), 8)
       Api(lineMonitorMedia, (arg1, arg2), 8)
       Api(lineMonitorTones, (arg1, arg2, arg3), 12)
       Api(lineNegotiateAPIVersion, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(lineNegotiateExtVersion, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(lineOpen, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
  AnsiWide(linePark, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(linePickup, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(linePrepareAddToConference, (arg1, arg2, arg3), 12)
       Api(lineProxyMessage, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(lineProxyResponse, (arg1, arg2, arg3), 12)
  AnsiWide(lineRedirect, (arg1, arg2, arg3), 12)
       Api(lineRegisterRequestRecipient, (arg1, arg2, arg3, arg4), 16)
       Api(lineReleaseUserUserInfo, (arg1), 4)
       Api(lineRemoveFromConference, (arg1), 4)
       Api(lineRemoveProvider, (arg1, arg2), 8)
       Api(lineSecureCall, (arg1), 4)
       Api(lineSendUserUserInfo, (arg1, arg2, arg3), 12)
       Api(lineSetAgentActivity, (arg1, arg2, arg3), 12)
       Api(lineSetAgentGroup, (arg1, arg2, arg3), 12)
       Api(lineSetAgentState, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(lineSetAppPriority, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(lineSetAppSpecific, (arg1, arg2), 8)
       Api(lineSetCallData, (arg1, arg2, arg3), 12)
       Api(lineSetCallParams, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(lineSetCallPrivilege, (arg1, arg2), 8)
       Api(lineSetCallQualityOfService, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(lineSetCallTreatment, (arg1, arg2), 8)
       Api(lineSetCurrentLocation, (arg1, arg2), 8)
  AnsiWide(lineSetDevConfig, (arg1, arg2, arg3, arg4), 16)
       Api(lineSetLineDevStatus, (arg1, arg2, arg3), 12)
       Api(lineSetMediaControl, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
       Api(lineSetMediaMode, (arg1, arg2), 8)
       Api(lineSetNumRings, (arg1, arg2, arg3), 12)
       Api(lineSetStatusMessages, (arg1, arg2, arg3), 12)
       Api(lineSetTerminal, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(lineSetTollList, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(lineSetupConference, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(lineSetupTransfer, (arg1, arg2, arg3), 12)
       Api(lineShutdown, (arg1), 4)
       Api(lineSwapHold, (arg1, arg2), 8)
  AnsiWide(lineTranslateAddress, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(lineTranslateDialog, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(lineUncompleteCall, (arg1, arg2), 8)
       Api(lineUnhold, (arg1), 4)
  AnsiWide(lineUnpark, (arg1, arg2, arg3, arg4), 16)
       Api(phoneClose, (arg1), 4)
  AnsiWide(phoneConfigDialog, (arg1, arg2, arg3), 12)
       Api(phoneDevSpecific, (arg1, arg2, arg3), 12)
  AnsiWide(phoneGetButtonInfo, (arg1, arg2, arg3), 12)
       Api(phoneGetData, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(phoneGetDevCaps, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(phoneGetDisplay, (arg1, arg2), 8)
       Api(phoneGetGain, (arg1, arg2, arg3), 12)
       Api(phoneGetHookSwitch, (arg1, arg2), 8)
  AnsiWide(phoneGetIcon, (arg1, arg2, arg3), 12)
  AnsiWide(phoneGetID, (arg1, arg2, arg3), 12)
       Api(phoneGetLamp, (arg1, arg2, arg3), 12)
       Api(phoneGetMessage, (arg1, arg2, arg3), 12)
       Api(phoneGetRing, (arg1, arg2, arg3), 12)
  AnsiWide(phoneGetStatus, (arg1, arg2), 8)
       Api(phoneGetStatusMessages, (arg1, arg2, arg3, arg4), 16)
       Api(phoneGetVolume, (arg1, arg2, arg3), 12)
       Api(phoneInitialize, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(phoneInitializeEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(phoneNegotiateAPIVersion, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(phoneNegotiateExtVersion, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(phoneOpen, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(phoneSetButtonInfo, (arg1, arg2, arg3), 12)
       Api(phoneSetData, (arg1, arg2, arg3, arg4), 16)
       Api(phoneSetDisplay, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(phoneSetGain, (arg1, arg2, arg3), 12)
       Api(phoneSetHookSwitch, (arg1, arg2, arg3), 12)
       Api(phoneSetLamp, (arg1, arg2, arg3), 12)
       Api(phoneSetRing, (arg1, arg2, arg3), 12)
       Api(phoneSetStatusMessages, (arg1, arg2, arg3, arg4), 16)
       Api(phoneSetVolume, (arg1, arg2, arg3), 12)
       Api(phoneShutdown, (arg1), 4)
  AnsiWide(tapiGetLocationInfo, (arg1, arg2), 8)
       Api(tapiRequestDrop, (arg1, arg2), 8)
  AnsiWide(tapiRequestMakeCall, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(tapiRequestMediaCall, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
EndImport
