XIncludeFile "common.pbi"

Import "urlmon.lib"
       Api(BindAsyncMoniker, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CoGetClassObjectFromURL, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(CreateAsyncBindCtx, (arg1, arg2, arg3, arg4), 16)
       Api(CreateBindProtocol, (arg1, arg2), 8)
       Api(CreateFormatEnumerator, (arg1, arg2, arg3), 12)
       Api(CreateURLMoniker, (arg1, arg2, arg3), 12)
       Api(Extract, (arg1, arg2), 8)
       Api(FindMediaType, (arg1, arg2), 8)
       Api(FindMediaTypeClass, (arg1, arg2, arg3, arg4), 16)
       Api(GetClassFileOrMime, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(GetClassURL, (arg1, arg2), 8)
       Api(HlinkGoBack, (arg1), 4)
       Api(HlinkGoForward, (arg1), 4)
       Api(HlinkNavigateMoniker, (arg1, arg2), 8)
       Api(HlinkNavigateString, (arg1, arg2), 8)
       Api(HlinkSimpleNavigateToMoniker, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(HlinkSimpleNavigateToString, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(IsAsyncMoniker, (arg1), 4)
       Api(IsValidURL, (arg1, arg2, arg3), 12)
       Api(MkParseDisplayNameEx, (arg1, arg2, arg3, arg4), 16)
       Api(RegisterBindStatusCallback, (arg1, arg2, arg3, arg4), 16)
       Api(RegisterFormatEnumerator, (arg1, arg2, arg3), 12)
       Api(RegisterMediaTypeClass, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RegisterMediaTypes, (arg1, arg2, arg3), 12)
       Api(RevokeBindStatusCallback, (arg1, arg2), 8)
       Api(RevokeFormatEnumerator, (arg1, arg2), 8)
  AnsiWide(URLDownload, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(URLDownloadToCacheFile, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(URLDownloadToFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(UrlMkBuildVersion, (), 0)
       Api(UrlMkSetSessionOption, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(URLOpenBlockingStream, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(URLOpenPullStream, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(URLOpenStream, (arg1, arg2, arg3, arg4), 16)
EndImport
