XIncludeFile "common.pbi"

Import "userenv.lib"
  AnsiWide(AddDesktopItem, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(AddItem, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(ApplyGroupPolicy, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(ApplySystemPolicy, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(CopyProfileDirectory, (arg1, arg2, arg3), 12)
  AnsiWide(CopyProfileDirectoryEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CreateEnvironmentBlock, (arg1, arg2, arg3), 12)
  AnsiWide(CreateGroup, (arg1, arg2), 8)
  AnsiWide(CreateLinkFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
  AnsiWide(CreateUserProfile, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(DeleteDesktopItem, (arg1, arg2), 8)
  AnsiWide(DeleteGroup, (arg1, arg2), 8)
  AnsiWide(DeleteItem, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(DeleteLinkFile, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(DeleteProfile, (arg1, arg2, arg3), 12)
       Api(DestroyEnvironmentBlock, (arg1), 4)
       Api(EnterCriticalPolicySection, (arg1), 4)
  AnsiWide(ExpandEnvironmentStringsForUser, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(FreeGPOList, (arg1), 4)
  AnsiWide(GetAllUsersProfileDirectory, (arg1, arg2), 8)
  AnsiWide(GetAppliedGPOList, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(GetDefaultUserProfileDirectory, (arg1, arg2), 8)
  AnsiWide(GetGPOList, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GetProfilesDirectory, (arg1, arg2), 8)
       Api(GetProfileType, (arg1), 4)
  AnsiWide(GetSystemTempDirectory, (arg1, arg2), 8)
  AnsiWide(GetUserProfileDirectory, (arg1, arg2, arg3), 12)
       Api(InitializeProfiles, (arg1), 4)
       Api(LeaveCriticalPolicySection, (arg1), 4)
  AnsiWide(LoadUserProfile, (arg1, arg2), 8)
       Api(MigrateNT4ToNT5, (), 0)
       Api(ProcessGroupPolicyCompleted, (arg1, arg2, arg3), 12)
       Api(RefreshPolicy, (arg1), 4)
       Api(RegisterGPNotification, (arg1, arg2), 8)
       Api(ResetUserSpecialFolderPaths, (), 0)
       Api(ShutdownGPOProcessing, (arg1), 4)
       Api(UnloadUserProfile, (arg1, arg2), 8)
       Api(UnregisterGPNotification, (arg1), 4)
EndImport
