XIncludeFile "common.pbi"

Import "user32.lib"
       Api(ActivateKeyboardLayout, (arg1, arg2), 8)
       Api(AdjustWindowRect, (arg1, arg2, arg3), 12)
       Api(AdjustWindowRectEx, (arg1, arg2, arg3, arg4), 16)
       Api(AllowSetForegroundWindow, (arg1), 4)
       Api(AnimateWindow, (arg1, arg2, arg3), 12)
       Api(AnyPopup, (), 0)
  AnsiWide(AppendMenu, (hMenu, uFlags, uIDNewItem, lpNewItem), 16)
       Api(ArrangeIconicWindows, (arg1), 4)
       Api(AttachThreadInput, (arg1, arg2, arg3), 12)
       Api(BeginDeferWindowPos, (arg1), 4)
       Api(BeginPaint, (arg1, arg2), 8)
       Api(BlockInput, (arg1), 4)
       Api(BringWindowToTop, (arg1), 4)
  AnsiWide(BroadcastSystemMessage, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(CallMsgFilter, (arg1, arg2), 8)
       Api(CallNextHookEx, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(CallWindowProc, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CascadeChildWindows, (arg1, arg2), 8)
       Api(CascadeWindows, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ChangeClipboardChain, (arg1, arg2), 8)
  AnsiWide(ChangeDisplaySettings, (arg1, arg2), 8)
  AnsiWide(ChangeDisplaySettingsEx, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(ChangeMenu, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ChangeWindowMessageFilter, (arg1, arg2), 8)
  AnsiWide(CharLower, (arg1), 4)
  AnsiWide(CharLowerBuff, (arg1, arg2), 8)
  AnsiWide(CharNext, (arg1), 4)
  AnsiWide(CharNextEx, (arg1, arg2, arg3), 12)
  AnsiWide(CharPrev, (arg1, arg2), 8)
  AnsiWide(CharPrevEx, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(CharToOem, (arg1, arg2), 8)
  AnsiWide(CharToOemBuff, (arg1, arg2, arg3), 12)
  AnsiWide(CharUpper, (arg1), 4)
  AnsiWide(CharUpperBuff, (arg1, arg2), 8)
       Api(CheckDlgButton, (arg1, arg2, arg3), 12)
       Api(CheckMenuItem, (arg1, arg2, arg3), 12)
       Api(CheckMenuRadioItem, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CheckRadioButton, (arg1, arg2, arg3, arg4), 16)
       Api(ChildWindowFromPoint, (arg1, arg2.q), 12)
       Api(ChildWindowFromPointEx, (arg1, arg2.q, arg3), 16)
       Api(ClientToScreen, (arg1, arg2), 8)
       Api(ClipCursor, (arg1), 4)
       Api(CloseClipboard, (), 0)
       Api(CloseDesktop, (arg1), 4)
       Api(CloseWindow, (arg1), 4)
       Api(CloseWindowStation, (arg1), 4)
  AnsiWide(CopyAcceleratorTable, (arg1, arg2, arg3), 12)
       Api(CopyIcon, (arg1), 4)
       Api(CopyImage, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CopyRect, (arg1, arg2), 8)
       Api(CountClipboardFormats, (), 0)
  AnsiWide(CreateAcceleratorTable, (arg1, arg2), 8)
       Api(CreateCaret, (arg1, arg2, arg3, arg4), 16)
       Api(CreateCursor, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(CreateDesktop, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(CreateDialogIndirectParam, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(CreateDialogParam, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CreateIcon, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CreateIconFromResource, (arg1, arg2, arg3, arg4), 16)
       Api(CreateIconFromResourceEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(CreateIconIndirect, (arg1), 4)
  AnsiWide(CreateMDIWindow, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(CreateMenu, (), 0)
       Api(CreatePopupMenu, (), 0)
  AnsiWide(CreateWindowEx, (arg1, *arg2, *arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), 48)
  AnsiWide(CreateWindowStation, (arg1, arg2, arg3, arg4), 16)
       Api(DdeAbandonTransaction, (arg1, arg2, arg3), 12)
       Api(DdeAccessData, (arg1, arg2), 8)
       Api(DdeAddData, (arg1, arg2, arg3, arg4), 16)
       Api(DdeClientTransaction, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(DdeCmpStringHandles, (arg1, arg2), 8)
       Api(DdeConnect, (arg1, arg2, arg3, arg4), 16)
       Api(DdeConnectList, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(DdeCreateDataHandle, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(DdeCreateStringHandle, (arg1, arg2, arg3), 12)
       Api(DdeDisconnect, (arg1), 4)
       Api(DdeDisconnectList, (arg1), 4)
       Api(DdeEnableCallback, (arg1, arg2, arg3), 12)
       Api(DdeFreeDataHandle, (arg1), 4)
       Api(DdeFreeStringHandle, (arg1, arg2), 8)
       Api(DdeGetData, (arg1, arg2, arg3, arg4), 16)
       Api(DdeGetLastError, (arg1), 4)
       Api(DdeImpersonateClient, (arg1), 4)
  AnsiWide(DdeInitialize, (arg1, arg2, arg3, arg4), 16)
       Api(DdeKeepStringHandle, (arg1, arg2), 8)
       Api(DdeNameService, (arg1, arg2, arg3, arg4), 16)
       Api(DdePostAdvise, (arg1, arg2, arg3), 12)
       Api(DdeQueryConvInfo, (arg1, arg2, arg3), 12)
       Api(DdeQueryNextServer, (arg1, arg2), 8)
  AnsiWide(DdeQueryString, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(DdeReconnect, (arg1), 4)
       Api(DdeSetQualityOfService, (arg1, arg2, arg3), 12)
       Api(DdeSetUserHandle, (arg1, arg2, arg3), 12)
       Api(DdeUnaccessData, (arg1), 4)
       Api(DdeUninitialize, (arg1), 4)
  AnsiWide(DefDlgProc, (arg1, arg2, arg3, arg4), 16)
       Api(DeferWindowPos, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(DefFrameProc, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(DefMDIChildProc, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(DefWindowProc, (arg1, arg2, arg3, arg4), 16)
       Api(DeleteMenu, (arg1, arg2, arg3), 12)
       Api(DestroyAcceleratorTable, (arg1), 4)
       Api(DestroyCaret, (), 0)
       Api(DestroyCursor, (arg1), 4)
       Api(DestroyIcon, (arg1), 4)
       Api(DestroyMenu, (arg1), 4)
       Api(DestroyWindow, (arg1), 4)
  AnsiWide(DialogBoxIndirectParam, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(DialogBoxParam, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(DispatchMessage, (arg1), 4)
  AnsiWide(DlgDirList, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(DlgDirListComboBox, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(DlgDirSelectComboBoxEx, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(DlgDirSelectEx, (arg1, arg2, arg3, arg4), 16)
       Api(DragDetect, (arg1, pt.q), 12)
       Api(DragObject, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(DrawAnimatedRects, (arg1, arg2, arg3, arg4), 16)
       Api(DrawCaption, (arg1, arg2, arg3, arg4), 16)
       Api(DrawEdge, (arg1, arg2, arg3, arg4), 16)
       Api(DrawFocusRect, (arg1, arg2), 8)
       Api(DrawFrame, (arg1, arg2, arg3, arg4), 16)
       Api(DrawFrameControl, (arg1, arg2, arg3, arg4), 16)
       Api(DrawIcon, (arg1, arg2, arg3, arg4), 16)
       Api(DrawIconEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(DrawMenuBar, (arg1), 4)
  AnsiWide(DrawState, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
  AnsiWide(DrawText, (hDC, lpchText, nCount, lpRect, uFormat), 20)
  AnsiWide(DrawTextEx, (arg1, *arg2, arg3, arg4, arg5, arg6), 24)
       Api(EditWndProc, (arg1, arg2, arg3, arg4), 16)
       Api(EmptyClipboard, (), 0)
       Api(EnableMenuItem, .l(arg1, arg2, arg3), 12)
       Api(EnableScrollBar, (arg1, arg2, arg3), 12)
       Api(EnableWindow, (arg1, arg2), 8)
       Api(EndDeferWindowPos, (arg1), 4)
       Api(EndDialog, (arg1, arg2), 8)
       Api(EndMenu, (), 0)
       Api(EndPaint, (arg1, arg2), 8)
       Api(EnumChildWindows, (arg1, arg2, arg3), 12)
       Api(EnumClipboardFormats, (arg1), 4)
  AnsiWide(EnumDesktops, (arg1, arg2, arg3), 12)
       Api(EnumDesktopWindows, (arg1, arg2, arg3), 12)
  AnsiWide(EnumDisplayDevices, (arg1, arg2, arg3, arg4), 16)
       Api(EnumDisplayMonitors, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(EnumDisplaySettings, (arg1, arg2, arg3), 12)
  AnsiWide(EnumDisplaySettingsEx, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(EnumProps, (arg1, arg2), 8)
  AnsiWide(EnumPropsEx, (arg1, arg2, arg3), 12)
       Api(EnumThreadWindows, (arg1, arg2, arg3), 12)
       Api(EnumWindows, (arg1, arg2), 8)
  AnsiWide(EnumWindowStations, (arg1, arg2), 8)
       Api(EqualRect, (arg1, arg2), 8)
       Api(ExcludeUpdateRgn, (arg1, arg2), 8)
       Api(ExitWindowsEx, (arg1, arg2), 8)
       Api(FillRect, (arg1, arg2, arg3), 12)
  AnsiWide(FindWindow, (*lpClassName, *lpWindowName), 8)
  AnsiWide(FindWindowEx, (hwndParent, hwndChildAfter, *lpszClass, *lpszWindow), 16)
       Api(FlashWindow, (arg1, arg2), 8)
       Api(FlashWindowEx, (arg1), 4)
       Api(FrameRect, (arg1, arg2, arg3), 12)
       Api(FreeDDElParam, (arg1, arg2), 8)
       Api(GetActiveWindow, (), 0)
  AnsiWide(GetAltTabInfo, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetAncestor, (arg1, arg2), 8)
       Api(GetAsyncKeyState, (arg1), 4)
       Api(GetCapture, (), 0)
       Api(GetCaretBlinkTime, (), 0)
       Api(GetCaretPos, (arg1), 4)
  AnsiWide(GetClassInfo, (arg1, arg2, arg3), 12)
  AnsiWide(GetClassInfoEx, (arg1, arg2, arg3), 12)
  AnsiWide(GetClassLong, (arg1, arg2), 8)
  AnsiWide(GetClassLongPtr, (arg1, arg2), 8)
  AnsiWide(GetClassName, (arg1, arg2, arg3), 12)
       Api(GetClassWord, (arg1, arg2), 8)
       Api(GetClientRect, (arg1, arg2), 8)
       Api(GetClipboardData, (arg1), 4)
  AnsiWide(GetClipboardFormatName, (arg1, arg2, arg3), 12)
       Api(GetClipboardOwner, (), 0)
       Api(GetClipboardSequenceNumber, (), 0)
       Api(GetClipboardViewer, (), 0)
       Api(GetClipCursor, (arg1), 4)
       Api(GetComboBoxInfo, (arg1, arg2), 8)
       Api(GetCursor, (), 0)
       Api(GetCursorInfo, (arg1), 4)
       Api(GetCursorPos, (arg1), 4)
       Api(GetDC, (arg1), 4)
       Api(GetDCEx, (arg1, arg2, arg3), 12)
       Api(GetDesktopWindow, (), 0)
       Api(GetDialogBaseUnits, (), 0)
       Api(GetDlgCtrlID, (arg1), 4)
       Api(GetDlgItem, (arg1, arg2), 8)
       Api(GetDlgItemInt, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetDlgItemText, (arg1, arg2, arg3, arg4), 16)
       Api(GetDoubleClickTime, (), 0)
       Api(GetFocus, (), 0)
       Api(GetForegroundWindow, (), 0)
       Api(GetGuiResources, (arg1, arg2), 8)
       Api(GetGUIThreadInfo, (arg1, arg2), 8)
       Api(GetIconInfo, (arg1, arg2), 8)
       Api(GetInputDesktop, (), 0)
       Api(GetInputState, (), 0)
       Api(GetKBCodePage, (), 0)
       Api(GetKeyboardLayout, (arg1), 4)
       Api(GetKeyboardLayoutList, (arg1, arg2), 8)
  AnsiWide(GetKeyboardLayoutName, (arg1), 4)
       Api(GetKeyboardState, (arg1), 4)
       Api(GetKeyboardType, (arg1), 4)
  AnsiWide(GetKeyNameText, (lParam, lpString, cchSize), 12)
       Api(GetKeyState, (arg1), 4)
       Api(GetLastActivePopup, (arg1), 4)
       Api(GetLastInputInfo, (arg1), 4)
       Api(GetListBoxInfo, (arg1), 4)
       Api(GetMenu, (arg1), 4)
       Api(GetMenuBarInfo, (arg1, arg2, arg3, arg4), 16)
       Api(GetMenuCheckMarkDimensions, (), 0)
       Api(GetMenuContextHelpId, (arg1), 4)
       Api(GetMenuDefaultItem, (arg1, arg2, arg3), 12)
       Api(GetMenuInfo, (arg1, arg2), 8)
       Api(GetMenuItemCount, (arg1), 4)
       Api(GetMenuItemID, (arg1, arg2), 8)
  AnsiWide(GetMenuItemInfo, (arg1, arg2, arg3, arg4), 16)
       Api(GetMenuItemRect, (arg1, arg2, arg3, arg4), 16)
       Api(GetMenuState, (arg1, arg2, arg3), 12)
  AnsiWide(GetMenuString, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(GetMessage, (arg1, arg2, arg3, arg4), 16)
       Api(GetMessageExtraInfo, (), 0)
       Api(GetMessagePos, (), 0)
       Api(GetMessageTime, (), 0)
  AnsiWide(GetMonitorInfo, (arg1, arg2), 8)
       Api(GetMouseMovePointsEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetNextDlgGroupItem, (arg1, arg2, arg3), 12)
       Api(GetNextDlgTabItem, (arg1, arg2, arg3), 12)
       Api(GetOpenClipboardWindow, (), 0)
       Api(GetParent, (arg1), 4)
       Api(GetPriorityClipboardFormat, (arg1, arg2), 8)
       Api(GetProcessDefaultLayout, (arg1), 4)
       Api(GetProcessWindowStation, (), 0)
  AnsiWide(GetProp, (arg1, *arg2), 8)
       Api(GetQueueStatus, (arg1), 4)
       Api(GetScrollBarInfo, (arg1, arg2, arg3), 12)
       Api(GetScrollInfo, (arg1, arg2, arg3), 12)
       Api(GetScrollPos, (arg1, arg2), 8)
       Api(GetScrollRange, (arg1, arg2, arg3, arg4), 16)
       Api(GetShellWindow, (), 0)
       Api(GetSubMenu, (arg1, arg2), 8)
       Api(GetSysColor, (arg1), 4)
       Api(GetSysColorBrush, (arg1), 4)
       Api(GetSystemMenu, (arg1, arg2), 8)
       Api(GetSystemMetrics, (arg1), 4)
  AnsiWide(GetTabbedTextExtent, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetThreadDesktop, (arg1), 4)
       Api(GetTitleBarInfo, (arg1, arg2), 8)
       Api(GetTopWindow, (arg1), 4)
       Api(GetUpdateRect, (arg1, arg2, arg3), 12)
       Api(GetUpdateRgn, (arg1, arg2, arg3), 12)
  AnsiWide(GetUserObjectInformation, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetUserObjectSecurity, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetWindow, (arg1, arg2), 8)
       Api(GetWindowContextHelpId, (arg1), 4)
       Api(GetWindowDC, (arg1), 4)
       Api(GetWindowInfo, (arg1, arg2), 8)
  AnsiWide(GetWindowLong, (arg1, arg2), 8)
  AnsiWide(GetWindowLongPtr, (arg1, arg2), 8)
  AnsiWide(GetWindowModuleFileName, (arg1, arg2, arg3), 12)
       Api(GetWindowPlacement, (arg1, arg2), 8)
       Api(GetWindowRect, (arg1, arg2), 8)
       Api(GetWindowRgn, (arg1, arg2), 8)
  AnsiWide(GetWindowText, (arg1, arg2, arg3), 12)
  AnsiWide(GetWindowTextLength, (arg1), 4)
       Api(GetWindowThreadProcessId, (arg1, arg2), 8)
       Api(GetWindowWord, (arg1, arg2), 8)
  AnsiWide(GrayString, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 = 9, arg9 = 10), 36)
       Api(HideCaret, (arg1), 4)
       Api(HiliteMenuItem, (arg1, arg2, arg3, arg4), 16)
       Api(ImpersonateDdeClientWindow, (arg1, arg2), 8)
  AnsiWide(IMPGetIME, (arg1, arg2), 8)
  AnsiWide(IMPQueryIME, (arg1), 4)
  AnsiWide(IMPSetIME, (arg1, arg2), 8)
       Api(InflateRect, (arg1, arg2, arg3), 12)
       Api(InSendMessage, (), 0)
       Api(InSendMessageEx, (arg1), 4)
  AnsiWide(InsertMenu, (hMenu, uPosition, uFlags, uIDNewItem, lpNewItem), 20)
  AnsiWide(InsertMenuItem, (arg1, arg2, arg3, arg4), 16)
       Api(IntersectRect, (arg1, arg2, arg3), 12)
       Api(InvalidateRect, (arg1, arg2, arg3), 12)
       Api(InvalidateRgn, (arg1, arg2, arg3), 12)
       Api(InvertRect, (arg1, arg2), 8)
  AnsiWide(IsCharAlpha, (arg1), 4)
  AnsiWide(IsCharAlphaNumeric, (arg1), 4)
  AnsiWide(IsCharLower, (arg1), 4)
  AnsiWide(IsCharUpper, (arg1), 4)
       Api(IsChild, (arg1, arg2), 8)
       Api(IsClipboardFormatAvailable, (arg1), 4)
  AnsiWide(IsDialogMessage, (arg1, arg2), 8)
       Api(IsDlgButtonChecked, (arg1, arg2), 8)
       Api(IsIconic, (arg1), 4)
       Api(IsMenu, (arg1), 4)
       Api(IsRectEmpty, (arg1), 4)
       Api(IsWindow, (arg1), 4)
       Api(IsWindowEnabled, (arg1), 4)
       Api(IsWindowUnicode, (arg1), 4)
       Api(IsWindowVisible, (arg1), 4)
       Api(IsZoomed, (arg1), 4)
       Api(keybd_event, (arg1, arg2, arg3, arg4), 16)
       Api(KillTimer, (arg1, arg2), 8)
  AnsiWide(LoadAccelerators, (arg1, arg2), 8)
  AnsiWide(LoadBitmap, (arg1, arg2), 8)
  AnsiWide(LoadCursor, (arg1, arg2), 8)
  AnsiWide(LoadCursorFromFile, (arg1), 4)
  AnsiWide(LoadIcon, (arg1, arg2), 8)
  AnsiWide(LoadImage, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(LoadKeyboardLayout, (arg1, arg2), 8)
  AnsiWide(LoadMenu, (arg1, arg2), 8)
  AnsiWide(LoadMenuIndirect, (arg1), 4)
  AnsiWide(LoadString, (arg1, arg2, arg3, arg4), 16)
       Api(LockSetForegroundWindow, (arg1), 4)
       Api(LockWindowUpdate, (arg1), 4)
       Api(LockWorkStation, (), 0)
       Api(LookupIconIdFromDirectory, (arg1, arg2), 8)
       Api(LookupIconIdFromDirectoryEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(MapDialogRect, (arg1, arg2), 8)
  AnsiWide(MapVirtualKey, (arg1, arg2), 8)
  AnsiWide(MapVirtualKeyEx, (arg1, arg2, arg3), 12)
       Api(MapWindowPoints, (arg1, arg2, arg3, arg4), 16)
       Api(MenuItemFromPoint, (arg1, arg2, arg3.q), 16)
       Api(MessageBeep, (arg1), 4)
  AnsiWide(MessageBox, (hWnd, *lpText, *lpCaption, uType), 16)
  AnsiWide(MessageBoxEx, (hWnd, *lpText, *lpCaption, uType, wLanguageId), 20)
  AnsiWide(MessageBoxIndirect, (lpMsgBoxParams), 4)
  AnsiWide(ModifyMenu, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(MonitorFromPoint, (arg1.q, arg2), 12)
       Api(MonitorFromRect, (arg1, arg2), 8)
       Api(MonitorFromWindow, (arg1, arg2), 8)
       Api(mouse_event, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(MoveWindow, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(MsgWaitForMultipleObjects, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(MsgWaitForMultipleObjectsEx, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NotifyWinEvent, (arg1, arg2, arg3, arg4), 16)
       Api(OemKeyScan, (arg1), 4)
  AnsiWide(OemToChar, (arg1, arg2), 8)
  AnsiWide(OemToCharBuff, (arg1, arg2, arg3), 12)
       Api(OffsetRect, (arg1, arg2, arg3), 12)
       Api(OpenClipboard, (arg1), 4)
  AnsiWide(OpenDesktop, (arg1, arg2, arg3, arg4), 16)
       Api(OpenIcon, (arg1), 4)
       Api(OpenInputDesktop, (arg1, arg2, arg3), 12)
  AnsiWide(OpenWindowStation, (arg1, arg2, arg3), 12)
       Api(PackDDElParam, (arg1, arg2, arg3), 12)
       Api(PaintDesktop, (arg1), 4)
  AnsiWide(PeekMessage, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(PostMessage, (arg1, arg2, arg3, arg4), 16)
       Api(PostQuitMessage, (arg1), 4)
  AnsiWide(PostThreadMessage, (arg1, arg2, arg3, arg4), 16)
       Api(PtInRect, (arg1, arg2.q), 12)
       Api(RealChildWindowFromPoint, (arg1, arg2.q), 12)
  AnsiWide(RealGetWindowClass, (arg1, arg2, arg3), 12)
       Api(RedrawWindow, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RegisterClass, (arg1), 4)
  AnsiWide(RegisterClassEx, (arg1), 4)
  AnsiWide(RegisterClipboardFormat, (arg1), 4)
  AnsiWide(RegisterDeviceNotification, (arg1, arg2, arg3), 12)
       Api(RegisterHotKey, (arg1, arg2, arg3, arg4), 16)
       Api(RegisterShellHookWindow, (arg1), 4)
  AnsiWide(RegisterWindowMessage, (*arg1), 4)
       Api(ReleaseCapture, (), 0)
       Api(ReleaseDC, (arg1, arg2), 8)
       Api(RemoveMenu, (arg1, arg2, arg3), 12)
  AnsiWide(RemoveProp, (arg1, *arg2), 8)
       Api(ReplyMessage, (arg1), 4)
       Api(ReuseDDElParam, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ScreenToClient, (arg1, arg2), 8)
       Api(ScrollDC, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ScrollWindow, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ScrollWindowEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(SendDlgItemMessage, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SendIMEMessageEx, (arg1, arg2), 8)
       Api(SendInput, (arg1, arg2, arg3), 12)
  AnsiWide(SendMessage, (hWnd, Msg, wParam, lParam), 16)
  AnsiWide(SendMessageCallback, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(SendMessageTimeout, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(SendNotifyMessage, (arg1, arg2, arg3, arg4), 16)
       Api(SetActiveWindow, (arg1), 4)
       Api(SetCapture, (arg1), 4)
       Api(SetCaretBlinkTime, (arg1), 4)
       Api(SetCaretPos, (arg1, arg2), 8)
  AnsiWide(SetClassLong, (arg1, arg2, arg3), 12)
  AnsiWide(SetClassLongPtr, (arg1, arg2, arg3), 12)
       Api(SetClassWord, (arg1, arg2, arg3), 12)
       Api(SetClipboardData, (arg1, arg2), 8)
       Api(SetClipboardViewer, (arg1), 4)
       Api(SetCursor, (arg1), 4)
       Api(SetCursorPos, (arg1, arg2), 8)
       Api(SetDebugErrorLevel, (arg1), 4)
       Api(SetDeskWallpaper, (arg1), 4)
       Api(SetDlgItemInt, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetDlgItemText, (arg1, arg2, arg3), 12)
       Api(SetDoubleClickTime, (arg1), 4)
       Api(SetFocus, (arg1), 4)
       Api(SetForegroundWindow, (arg1), 4)
       Api(SetKeyboardState, (arg1), 4)
       Api(SetLastErrorEx, (arg1, arg2), 8)
       Api(SetLayeredWindowAttributes, (arg1, arg2, arg3, arg4), 16)
       Api(SetMenu, (arg1, arg2), 8)
       Api(SetMenuContextHelpId, (arg1, arg2), 8)
       Api(SetMenuDefaultItem, (arg1, arg2, arg3), 12)
       Api(SetMenuInfo, (arg1, arg2), 8)
       Api(SetMenuItemBitmaps, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetMenuItemInfo, (arg1, arg2, arg3, arg4), 16)
       Api(SetMessageExtraInfo, (arg1), 4)
       Api(SetMessageQueue, (arg1), 4)
       Api(SetParent, (arg1, arg2), 8)
       Api(SetProcessDefaultLayout, (arg1), 4)
       Api(SetProcessWindowStation, (arg1), 4)
  AnsiWide(SetProp, (arg1, arg2, arg3), 12)
       Api(SetRect, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetRectEmpty, (arg1), 4)
       Api(SetScrollInfo, (arg1, arg2, arg3, arg4), 16)
       Api(SetScrollPos, (arg1, arg2, arg3, arg4), 16)
       Api(SetScrollRange, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(SetShellWindow, (arg1), 4)
       Api(SetSysColors, (arg1, arg2, arg3), 12)
       Api(SetSystemCursor, (arg1, arg2), 8)
       Api(SetThreadDesktop, (arg1), 4)
       Api(SetTimer, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetUserObjectInformation, (arg1, arg2, arg3, arg4), 16)
       Api(SetUserObjectSecurity, (arg1, arg2, arg3), 12)
       Api(SetWindowContextHelpId, (arg1, arg2), 8)
  AnsiWide(SetWindowLong, (arg1, arg2, arg3), 12)
  AnsiWide(SetWindowLongPtr, (arg1, arg2, arg3), 12)
       Api(SetWindowPlacement, (arg1, arg2), 8)
       Api(SetWindowPos, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(SetWindowRgn, (arg1, arg2, arg3), 12)
  AnsiWide(SetWindowsHook, (arg1, arg2), 8)
  AnsiWide(SetWindowsHookEx, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetWindowText, (arg1, *arg2), 8)
       Api(SetWindowWord, (arg1, arg2, arg3), 12)
       Api(SetWinEventHook, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(ShowCaret, (arg1), 4)
       Api(ShowCursor, .l(arg1), 4)
       Api(ShowOwnedPopups, (arg1, arg2), 8)
       Api(ShowScrollBar, (arg1, arg2, arg3), 12)
       Api(ShowWindow, (arg1, arg2), 8)
       Api(ShowWindowAsync, (arg1, arg2), 8)
       Api(SubtractRect, (arg1, arg2, arg3), 12)
       Api(SwapMouseButton, (arg1), 4)
       Api(SwitchDesktop, (arg1), 4)
  AnsiWide(SystemParametersInfo, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(TabbedTextOut, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(TileChildWindows, (arg1, arg2), 8)
       Api(TileWindows, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ToAscii, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ToAsciiEx, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ToUnicode, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ToUnicodeEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(TrackMouseEvent, (arg1), 4)
       Api(TrackPopupMenu, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(TrackPopupMenuEx, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(TranslateAccelerator, (arg1, arg2, arg3), 12)
       Api(TranslateMDISysAccel, (arg1, arg2), 8)
       Api(TranslateMessage, (arg1), 4)
       Api(UnhookWindowsHook, (arg1, arg2), 8)
       Api(UnhookWindowsHookEx, (arg1), 4)
       Api(UnhookWinEvent, (arg1), 4)
       Api(UnionRect, (arg1, arg2, arg3), 12)
       Api(UnloadKeyboardLayout, (arg1), 4)
       Api(UnpackDDElParam, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(UnregisterClass, (arg1, arg2), 8)
       Api(UnregisterDeviceNotification, (arg1), 4)
       Api(UnregisterHotKey, (arg1, arg2), 8)
       Api(UpdateLayeredWindow, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(UpdateWindow, (arg1), 4)
       Api(UserHandleGrantAccess, (arg1, arg2, arg3), 12)
       Api(ValidateRect, (arg1, arg2), 8)
       Api(ValidateRgn, (arg1, arg2), 8)
  AnsiWide(VkKeyScan, (arg1), 4)
  AnsiWide(VkKeyScanEx, (arg1, arg2), 8)
       Api(WaitForInputIdle, (arg1, arg2), 8)
       Api(WaitMessage, (), 0)
       Api(Win32PoolAllocationStats, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(WindowFromDC, (arg1), 4)
       Api(WindowFromPoint, (arg1.q), 8)
  AnsiWide(WinHelp, (arg1, arg2, arg3, arg4), 16)
       Api(WINNLSEnableIME, (arg1, arg2), 8)
       Api(WINNLSGetEnableStatus, (arg1), 4)
       Api(WINNLSGetIMEHotkey, (arg1), 4)
  AnsiWide(wsprintf, (arg1, arg2, arg3), 12)
  AnsiWide(wvsprintf, (arg1, arg2, arg3), 12)
       Api(DefRawInputProc, (*paRawInput, nInput.l, cbSizeHeader.l), 12)
       Api(GetRawInputBuffer, (*pData, *pcbSize, cbSizeHeader.l), 12)
       Api(GetRawInputData, (hRawInput, uiCommand.l, *pData, *pcbSize, cbSizeHeader.l), 20)
       Api(GetRawInputDeviceInfo, (hDevice, uiCommand.l, *pData, *pcbSize), 16)
       Api(GetRawInputDeviceList, (*pRawInputDeviceList, *puiNumDevices, cbSize.l), 12)
       Api(GetRegisteredRawInputDevices, (*pRawInputDevices, *puiNumDevices, cbSize.l), 12)
       Api(RegisterRawInputDevices, (*pRawInputDevices, uiNumDevices.l, cbSize.l), 12)
EndImport
