XIncludeFile "common.pbi"

Import "uxtheme.lib"
       Api(CloseThemeData, (arg1), 4)
       Api(DrawThemeBackground, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(DrawThemeBackgroundEx, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(DrawThemeEdge, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(DrawThemeIcon, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(DrawThemeParentBackground, (arg1, arg2, arg3), 12)
       Api(DrawThemeText, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(EnableThemeDialogTexture, (arg1, arg2), 8)
       Api(EnableTheming, (arg1), 4)
       Api(GetCurrentThemeName, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetThemeAppProperties, (), 0)
       Api(GetThemeBackgroundContentRect, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetThemeBackgroundExtent, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetThemeBackgroundRegion, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetThemeBool, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetThemeColor, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetThemeDocumentationProperty, (arg1, arg2, arg3, arg4), 16)
       Api(GetThemeEnumValue, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetThemeFilename, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetThemeFont, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetThemeInt, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetThemeIntList, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetThemeMargins, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(GetThemeMetric, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetThemePartSize, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(GetThemePosition, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetThemePropertyOrigin, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetThemeRect, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetThemeString, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GetThemeSysBool, (arg1, arg2), 8)
       Api(GetThemeSysColor, (arg1, arg2), 8)
       Api(GetThemeSysColorBrush, (arg1, arg2), 8)
       Api(GetThemeSysFont, (arg1, arg2, arg3), 12)
       Api(GetThemeSysInt, (arg1, arg2, arg3), 12)
       Api(GetThemeSysSize, (arg1, arg2), 8)
       Api(GetThemeSysString, (arg1, arg2, arg3, arg4), 16)
       Api(GetThemeTextExtent, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), 36)
       Api(GetThemeTextMetrics, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GetWindowTheme, (arg1), 4)
       Api(HitTestThemeBackground, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, pt.q, arg9), 40)
       Api(IsAppThemed, (), 0)
       Api(IsThemeActive, (), 0)
       Api(IsThemeBackgroundPartiallyTransparent, (arg1, arg2, arg3), 12)
       Api(IsThemeDialogTextureEnabled, (arg1), 4)
       Api(IsThemePartDefined, (arg1, arg2, arg3), 12)
       Api(OpenThemeData, (arg1, arg2), 8)
       Api(SetThemeAppProperties, (arg1), 4)
       Api(SetWindowTheme, (arg1, arg2, arg3), 12)
EndImport
