XIncludeFile "common.pbi"

Import "wininet.lib"
  AnsiWide(CommitUrlCacheEntry, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), 44)
  AnsiWide(CreateUrlCacheContainer, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(CreateUrlCacheEntry, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(CreateUrlCacheGroup, (arg1, arg2), 8)
       Api(DeleteIE3Cache, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(DeleteUrlCacheContainer, (arg1, arg2), 8)
  AnsiWide(DeleteUrlCacheEntry, (arg1), 4)
       Api(DeleteUrlCacheGroup, (arg1.q, arg2, arg3), 16)
       Api(DoConnectoidsExist, (), 0)
  AnsiWide(ExportCookieFile, (arg1, arg2), 8)
       Api(FindCloseUrlCache, (arg1), 4)
  AnsiWide(FindFirstUrlCacheContainer, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(FindFirstUrlCacheEntry, (arg1, arg2, arg3), 12)
  AnsiWide(FindFirstUrlCacheEntryEx, (arg1, arg2, arg3, arg4.q, arg5, arg6, arg7, arg8, arg9), 40)
       Api(FindFirstUrlCacheGroup, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(FindNextUrlCacheContainer, (arg1, arg2, arg3), 12)
  AnsiWide(FindNextUrlCacheEntry, (arg1, arg2, arg3), 12)
  AnsiWide(FindNextUrlCacheEntryEx, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(FindNextUrlCacheGroup, (arg1, arg2, arg3), 12)
  AnsiWide(FreeUrlCacheSpace, (arg1, arg2, arg3), 12)
  AnsiWide(FtpCommand, (arg1, arg2, arg3, *arg4, arg5, arg6), 24)
  AnsiWide(FtpCreateDirectory, (arg1, *arg2), 8)
  AnsiWide(FtpDeleteFile, (arg1, *arg2), 8)
  AnsiWide(FtpFindFirstFile, (arg1, *arg2, arg3, arg4, arg5), 20)
  AnsiWide(FtpGetCurrentDirectory, (arg1, arg2, arg3), 12)
  AnsiWide(FtpGetFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(FtpGetFileEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(FtpGetFileSize, (arg1, arg2), 8)
  AnsiWide(FtpOpenFile, (arg1, *arg2, arg3, arg4, arg5), 20)
  AnsiWide(FtpPutFile, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(FtpPutFileEx, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(FtpRemoveDirectory, (arg1, *arg2), 8)
  AnsiWide(FtpRenameFile, (arg1, *arg2, *arg3), 12)
  AnsiWide(FtpSetCurrentDirectory, (arg1, *arg2), 8)
  AnsiWide(GetDiskInfo, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(GetUrlCacheConfigInfo, (arg1, arg2, arg3), 12)
  AnsiWide(GetUrlCacheEntryInfo, (arg1, arg2, arg3), 12)
  AnsiWide(GetUrlCacheEntryInfoEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(GetUrlCacheGroupAttribute, (arg1.q, arg2, arg3, arg4, arg5, arg6), 28)
       Api(GetUrlCacheHeaderData, (arg1, arg2), 8)
  AnsiWide(GopherCreateLocator, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(GopherFindFirstFile, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GopherGetAttribute, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(GopherGetLocatorType, (arg1, arg2), 8)
  AnsiWide(GopherOpenFile, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(HttpAddRequestHeaders, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(HttpCheckDavCompliance, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(HttpEndRequest, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(HttpOpenRequest, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(HttpQueryInfo, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(HttpSendRequest, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(HttpSendRequestEx, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(ImportCookieFile, (arg1), 4)
       Api(IncrementUrlCacheHeaderData, (arg1, arg2), 8)
  AnsiWide(InternetAlgIdToString, (arg1, arg2, arg3, arg4), 16)
       Api(InternetAttemptConnect, (arg1), 4)
       Api(InternetAutodial, (arg1, arg2), 8)
       Api(InternetAutodialCallback, (arg1, arg2), 8)
       Api(InternetAutodialHangup, (arg1), 4)
  AnsiWide(InternetCanonicalizeUrl, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetCheckConnection, (arg1, arg2, arg3), 12)
       Api(InternetCloseHandle, (arg1), 4)
  AnsiWide(InternetCombineUrl, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(InternetConfirmZoneCrossing, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetConnect, (arg1, *arg2, arg3, *arg4, *arg5, arg6, arg7, arg8), 32)
  AnsiWide(InternetCrackUrl, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetCreateUrl, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetDial, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(InternetErrorDlg, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(InternetFindNextFile, (arg1, arg2), 8)
       Api(InternetFortezzaCommand, (arg1, arg2, arg3), 12)
  AnsiWide(InternetGetCertByURL, (arg1, arg2, arg3), 12)
       Api(InternetGetConnectedState, (arg1, arg2), 8)
  AnsiWide(InternetGetConnectedStateEx, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetGetCookie, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetGetLastResponseInfo, (arg1, arg2, arg3), 12)
  AnsiWide(InternetGoOnline, (arg1, arg2, arg3), 12)
       Api(InternetHangUp, (arg1, arg2), 8)
       Api(InternetLockRequestFile, (arg1, arg2), 8)
  AnsiWide(InternetOpen, (*arg1, arg2, *arg3, *arg4, arg5), 20)
  AnsiWide(InternetOpenUrl, (arg1, *arg2, *arg3, arg4, arg5, arg6), 24)
       Api(InternetQueryDataAvailable, (arg1, arg2, arg3, arg4), 16)
       Api(InternetQueryFortezzaStatus, (arg1, arg2), 8)
  AnsiWide(InternetQueryOption, (arg1, arg2, arg3, arg4), 16)
       Api(InternetReadFile, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetReadFileEx, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetSecurityProtocolToString, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetSetCookie, (arg1, arg2, arg3), 12)
  AnsiWide(InternetSetDialState, (arg1, arg2, arg3), 12)
       Api(InternetSetFilePointer, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(InternetSetOption, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetSetOptionEx, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(InternetSetStatusCallback, (arg1, arg2), 8)
  AnsiWide(InternetShowSecurityInfoByURL, (arg1, arg2), 8)
  AnsiWide(InternetTimeFromSystemTime, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetTimeToSystemTime, (arg1, arg2, arg3), 12)
       Api(InternetUnlockRequestFile, (arg1), 4)
       Api(InternetWriteFile, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(InternetWriteFileEx, (arg1, arg2, arg3, arg4), 16)
       Api(IsHostInProxyBypassList, (arg1, arg2, arg3), 12)
  AnsiWide(IsUrlCacheEntryExpired, (arg1, arg2, arg3), 12)
       Api(LoadUrlCacheContent, (), 0)
       Api(ParseX509EncodedCertificateForListBoxEntry, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(PerformOperationOverUrlCache, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(ReadUrlCacheEntryStream, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RegisterUrlCacheNotification, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(ResumeSuspendedDownload, (arg1, arg2), 8)
  AnsiWide(RetrieveUrlCacheEntryFile, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(RetrieveUrlCacheEntryStream, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(RunOnceUrlCache, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetUrlCacheConfigInfo, (arg1, arg2), 8)
  AnsiWide(SetUrlCacheEntryGroup, (arg1, arg2, arg3.q, arg4, arg5, arg6), 28)
  AnsiWide(SetUrlCacheEntryInfo, (arg1, arg2, arg3), 12)
  AnsiWide(SetUrlCacheGroupAttribute, (arg1.q, arg2, arg3, arg4, arg5), 24)
       Api(SetUrlCacheHeaderData, (arg1, arg2), 8)
       Api(ShowClientAuthCerts, (arg1), 4)
       Api(ShowSecurityInfo, (arg1, arg2), 8)
       Api(ShowX509EncodedCertificate, (arg1, arg2, arg3), 12)
  AnsiWide(UnlockUrlCacheEntryFile, (arg1, arg2), 8)
       Api(UnlockUrlCacheEntryStream, (arg1, arg2), 8)
       Api(UpdateUrlCacheContentPath, (arg1), 4)
EndImport
