XIncludeFile "common.pbi"

Import "winmm.lib"
       Api(aux32Message, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(auxGetDevCaps, (arg1, arg2, arg3), 12)
       Api(auxGetNumDevs, (), 0)
       Api(auxGetVolume, (arg1, arg2), 8)
       Api(auxOutMessage, (arg1, arg2, arg3, arg4), 16)
       Api(auxSetVolume, (arg1, arg2), 8)
       Api(CloseDriver, (arg1, arg2, arg3), 12)
       Api(DefDriverProc, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(DriverCallback, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(DrvGetModuleHandle, (arg1), 4)
       Api(GetDriverModuleHandle, (arg1), 4)
       Api(joy32Message, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(joyConfigChanged, (arg1), 4)
  AnsiWide(joyGetDevCaps, (arg1, arg2, arg3), 12)
       Api(joyGetNumDevs, (), 0)
       Api(joyGetPos, (arg1, arg2), 8)
       Api(joyGetPosEx, (arg1, arg2), 8)
       Api(joyGetThreshold, (arg1, arg2), 8)
       Api(joyReleaseCapture, (arg1), 4)
       Api(joySetCapture, (arg1, arg2, arg3, arg4), 16)
       Api(joySetThreshold, (arg1, arg2), 8)
       Api(mci32Message, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(mciDriverNotify, (arg1, arg2, arg3), 12)
       Api(mciDriverYield, (arg1), 4)
       Api(mciExecute, (arg1), 4)
       Api(mciFreeCommandResource, (arg1), 4)
       Api(mciGetCreatorTask, (arg1), 4)
  AnsiWide(mciGetDeviceID, (arg1), 4)
  AnsiWide(mciGetDeviceIDFromElementID, (arg1, arg2), 8)
       Api(mciGetDriverData, (arg1), 4)
  AnsiWide(mciGetErrorString, (arg1, arg2, arg3), 12)
       Api(mciGetYieldProc, (arg1, arg2), 8)
       Api(mciLoadCommandResource, (arg1, arg2, arg3), 12)
  AnsiWide(mciSendCommand, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(mciSendString, (arg1, arg2, arg3, arg4), 16)
       Api(mciSetDriverData, (arg1, arg2), 8)
       Api(mciSetYieldProc, (arg1, arg2, arg3), 12)
       Api(mid32Message, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(midiConnect, (arg1, arg2, arg3), 12)
       Api(midiDisconnect, (arg1, arg2, arg3), 12)
       Api(midiInAddBuffer, (arg1, arg2, arg3), 12)
       Api(midiInClose, (arg1), 4)
  AnsiWide(midiInGetDevCaps, (arg1, arg2, arg3), 12)
  AnsiWide(midiInGetErrorText, (arg1, arg2, arg3), 12)
       Api(midiInGetID, (arg1, arg2), 8)
       Api(midiInGetNumDevs, (), 0)
       Api(midiInMessage, (arg1, arg2, arg3, arg4), 16)
       Api(midiInOpen, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(midiInPrepareHeader, (arg1, arg2, arg3), 12)
       Api(midiInReset, (arg1), 4)
       Api(midiInStart, (arg1), 4)
       Api(midiInStop, (arg1), 4)
       Api(midiInUnprepareHeader, (arg1, arg2, arg3), 12)
       Api(midiOutCacheDrumPatches, (arg1, arg2, arg3, arg4), 16)
       Api(midiOutCachePatches, (arg1, arg2, arg3, arg4), 16)
       Api(midiOutClose, (arg1), 4)
  AnsiWide(midiOutGetDevCaps, (arg1, arg2, arg3), 12)
  AnsiWide(midiOutGetErrorText, (arg1, arg2, arg3), 12)
       Api(midiOutGetID, (arg1, arg2), 8)
       Api(midiOutGetNumDevs, (), 0)
       Api(midiOutGetVolume, (arg1, arg2), 8)
       Api(midiOutLongMsg, (arg1, arg2, arg3), 12)
       Api(midiOutMessage, (arg1, arg2, arg3, arg4), 16)
       Api(midiOutOpen, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(midiOutPrepareHeader, (arg1, arg2, arg3), 12)
       Api(midiOutReset, (arg1), 4)
       Api(midiOutSetVolume, (arg1, arg2), 8)
       Api(midiOutShortMsg, (arg1, arg2), 8)
       Api(midiOutUnprepareHeader, (arg1, arg2, arg3), 12)
       Api(midiStreamClose, (arg1), 4)
       Api(midiStreamOpen, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(midiStreamOut, (arg1, arg2, arg3), 12)
       Api(midiStreamPause, (arg1), 4)
       Api(midiStreamPosition, (arg1, arg2, arg3), 12)
       Api(midiStreamProperty, (arg1, arg2, arg3), 12)
       Api(midiStreamRestart, (arg1), 4)
       Api(midiStreamStop, (arg1), 4)
       Api(MigrateAllDrivers, (), 0)
       Api(MigrateMidiUser, (), 0)
       Api(MigrateSoundEvents, (), 0)
       Api(mixerClose, (arg1), 4)
  AnsiWide(mixerGetControlDetails, (arg1, arg2, arg3), 12)
  AnsiWide(mixerGetDevCaps, (arg1, arg2, arg3), 12)
       Api(mixerGetID, (arg1, arg2, arg3), 12)
  AnsiWide(mixerGetLineControls, (arg1, arg2, arg3), 12)
  AnsiWide(mixerGetLineInfo, (arg1, arg2, arg3), 12)
       Api(mixerGetNumDevs, (), 0)
       Api(mixerMessage, (arg1, arg2, arg3, arg4), 16)
       Api(mixerOpen, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(mixerSetControlDetails, (arg1, arg2, arg3), 12)
       Api(mmDrvInstall, (arg1, arg2, arg3, arg4), 16)
       Api(mmGetCurrentTask, (), 0)
       Api(mmioAdvance, (arg1, arg2, arg3), 12)
       Api(mmioAscend, (arg1, arg2, arg3), 12)
       Api(mmioClose, (arg1, arg2), 8)
       Api(mmioCreateChunk, (arg1, arg2, arg3), 12)
       Api(mmioDescend, (arg1, arg2, arg3, arg4), 16)
       Api(mmioFlush, (arg1, arg2), 8)
       Api(mmioGetInfo, (arg1, arg2, arg3), 12)
  AnsiWide(mmioInstallIOProc, (arg1, arg2, arg3), 12)
  AnsiWide(mmioOpen, (arg1, arg2, arg3), 12)
       Api(mmioRead, (arg1, arg2, arg3), 12)
  AnsiWide(mmioRename, (arg1, arg2, arg3, arg4), 16)
       Api(mmioSeek, (arg1, arg2, arg3), 12)
       Api(mmioSendMessage, (arg1, arg2, arg3, arg4), 16)
       Api(mmioSetBuffer, (arg1, arg2, arg3, arg4), 16)
       Api(mmioSetInfo, (arg1, arg2, arg3), 12)
  AnsiWide(mmioStringToFOURCC, (arg1, arg2), 8)
       Api(mmioWrite, (arg1, arg2, arg3), 12)
       Api(mmsystemGetVersion, (), 0)
       Api(mmTaskBlock, (arg1), 4)
       Api(mmTaskCreate, (arg1, arg2, arg3), 12)
       Api(mmTaskSignal, (arg1), 4)
       Api(mmTaskYield, (), 0)
       Api(mod32Message, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(mxd32Message, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(NotifyCallbackData, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(OpenDriver, (arg1, arg2, arg3), 12)
  AnsiWide(PlaySound, (arg1, arg2, arg3), 12)
       Api(SendDriverMessage, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(sndPlaySound, (*arg1, arg2), 8)
       Api(tid32Message, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(timeBeginPeriod, (arg1), 4)
       Api(timeEndPeriod, (arg1), 4)
       Api(timeGetDevCaps, (arg1, arg2), 8)
       Api(timeGetSystemTime, (arg1, arg2), 8)
       Api(timeGetTime, (), 0)
       Api(timeKillEvent, (arg1), 4)
       Api(timeSetEvent, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(waveInAddBuffer, (arg1, arg2, arg3), 12)
       Api(waveInClose, (arg1), 4)
  AnsiWide(waveInGetDevCaps, (arg1, arg2, arg3), 12)
  AnsiWide(waveInGetErrorText, (arg1, arg2, arg3), 12)
       Api(waveInGetID, (arg1, arg2), 8)
       Api(waveInGetNumDevs, (), 0)
       Api(waveInGetPosition, (arg1, arg2, arg3), 12)
       Api(waveInMessage, (arg1, arg2, arg3, arg4), 16)
       Api(waveInOpen, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(waveInPrepareHeader, (arg1, arg2, arg3), 12)
       Api(waveInReset, (arg1), 4)
       Api(waveInStart, (arg1), 4)
       Api(waveInStop, (arg1), 4)
       Api(waveInUnprepareHeader, (arg1, arg2, arg3), 12)
       Api(waveOutBreakLoop, (arg1), 4)
       Api(waveOutClose, (arg1), 4)
  AnsiWide(waveOutGetDevCaps, (arg1, arg2, arg3), 12)
  AnsiWide(waveOutGetErrorText, (arg1, arg2, arg3), 12)
       Api(waveOutGetID, (arg1, arg2), 8)
       Api(waveOutGetNumDevs, (), 0)
       Api(waveOutGetPitch, (arg1, arg2), 8)
       Api(waveOutGetPlaybackRate, (arg1, arg2), 8)
       Api(waveOutGetPosition, (arg1, arg2, arg3), 12)
       Api(waveOutGetVolume, (arg1, arg2), 8)
       Api(waveOutMessage, (arg1, arg2, arg3, arg4), 16)
       Api(waveOutOpen, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(waveOutPause, (arg1), 4)
       Api(waveOutPrepareHeader, (arg1, arg2, arg3), 12)
       Api(waveOutReset, (arg1), 4)
       Api(waveOutRestart, (arg1), 4)
       Api(waveOutSetPitch, (arg1, arg2), 8)
       Api(waveOutSetPlaybackRate, (arg1, arg2), 8)
       Api(waveOutSetVolume, (arg1, arg2), 8)
       Api(waveOutUnprepareHeader, (arg1, arg2, arg3), 12)
       Api(waveOutWrite, (arg1, arg2, arg3), 12)
       Api(wid32Message, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(winmmDbgOut, (), 0)
       Api(winmmSetDebugLevel, (arg1), 4)
       Api(wod32Message, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WOW32DriverCallback, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(WOW32ResolveMultiMediaHandle, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(WOWAppExit, (arg1), 4)
EndImport
