XIncludeFile "common.pbi"

Import "winspool.lib"
       Api(AbortPrinter, (arg1), 4)
  AnsiWide(AddForm, (arg1, arg2, arg3), 12)
  AnsiWide(AddJob, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(AddMonitor, (arg1, arg2, arg3), 12)
  AnsiWide(AddPort, (arg1, arg2, arg3), 12)
  AnsiWide(AddPrinter, (arg1, arg2, arg3), 12)
  AnsiWide(AddPrinterConnection, (arg1), 4)
  AnsiWide(AddPrinterDriver, (arg1, arg2, arg3), 12)
  AnsiWide(AddPrintProcessor, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(AddPrintProvidor, (arg1, arg2, arg3), 12)
  AnsiWide(AdvancedDocumentProperties, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(ClosePrinter, (arg1), 4)
  AnsiWide(ConfigurePort, (arg1, arg2, arg3), 12)
       Api(ConnectToPrinterDlg, (arg1, arg2), 8)
       Api(CreatePrinterIC, (arg1, arg2), 8)
  AnsiWide(DeleteForm, (arg1, arg2), 8)
  AnsiWide(DeleteMonitor, (arg1, arg2, arg3), 12)
  AnsiWide(DeletePort, (arg1, arg2, arg3), 12)
       Api(DeletePrinter, (arg1), 4)
  AnsiWide(DeletePrinterConnection, (arg1), 4)
  AnsiWide(DeletePrinterDriver, (arg1, arg2, arg3), 12)
       Api(DeletePrinterIC, (arg1), 4)
  AnsiWide(DeletePrintProcessor, (arg1, arg2, arg3), 12)
  AnsiWide(DeletePrintProvidor, (arg1, arg2, arg3), 12)
  AnsiWide(DeviceCapabilities, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(DocumentProperties, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(EndDocPrinter, (arg1), 4)
       Api(EndPagePrinter, (arg1), 4)
  AnsiWide(EnumForms, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(EnumJobs, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(EnumMonitors, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(EnumPorts, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(EnumPrinterDrivers, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(EnumPrinters, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(EnumPrintProcessorDatatypes, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
  AnsiWide(EnumPrintProcessors, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(FindClosePrinterChangeNotification, (arg1), 4)
       Api(FindFirstPrinterChangeNotification, (arg1, arg2, arg3, arg4), 16)
       Api(FindNextPrinterChangeNotification, (arg1, arg2, arg3, arg4), 16)
       Api(FreePrinterNotifyInfo, (arg1), 4)
  AnsiWide(GetForm, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GetJob, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GetPrinter, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(GetPrinterData, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GetPrinterDriver, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GetPrinterDriverDirectory, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(GetPrintProcessorDirectory, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(OpenPrinter, (arg1, arg2, arg3), 12)
       Api(PlayGdiScriptOnPrinterIC, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
  AnsiWide(PrinterMessageBox, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(PrinterProperties, (arg1, arg2), 8)
       Api(ReadPrinter, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(ResetPrinter, (arg1, arg2), 8)
       Api(ScheduleJob, (arg1, arg2), 8)
  AnsiWide(SetForm, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetJob, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(SetPrinter, (arg1, arg2, arg3, arg4), 16)
  AnsiWide(SetPrinterData, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(StartDocPrinter, (arg1, arg2, arg3), 12)
       Api(StartPagePrinter, (arg1), 4)
       Api(WritePrinter, (arg1, arg2, arg3, arg4), 16)
EndImport
