XIncludeFile "common.pbi"

Import "wsock32.lib"
       Api(__WSAFDIsSet, (arg1, arg2), 8)
       Api(accept, (arg1, arg2, arg3), 12)
       Api(AcceptEx, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
       Api(bind, (arg1, arg2, arg3), 12)
       Api(closesocket, (arg1), 4)
       Api(connect, (arg1, arg2, arg3), 12)
       Api(dn_expand, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(EnumProtocols, (arg1, arg2, arg3), 12)
       Api(GetAcceptExSockaddrs, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), 32)
  AnsiWide(GetAddressByName, (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), 40)
       Api(gethostbyaddr, (arg1, arg2, arg3), 12)
       Api(gethostbyname, (arg1), 4)
       Api(gethostname, (arg1, arg2), 8)
  AnsiWide(GetNameByType, (arg1, arg2, arg3), 12)
       Api(getnetbyname, (arg1), 4)
       Api(getpeername, (arg1, arg2, arg3), 12)
       Api(getprotobyname, (arg1), 4)
       Api(getprotobynumber, (arg1), 4)
       Api(getservbyname, (arg1, arg2), 8)
       Api(getservbyport, (arg1, arg2), 8)
  AnsiWide(GetService, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(getsockname, (arg1, arg2, arg3), 12)
       Api(getsockopt, (arg1, arg2, arg3, arg4, arg5), 20)
  AnsiWide(GetTypeByName, (arg1, arg2), 8)
       Api(GETXBYYSP_gethostbyaddr, (arg1, arg2, arg3), 12)
       Api(GETXBYYSP_gethostbyname, (arg1), 4)
       Api(GETXBYYSP_gethostname, (arg1, arg2), 8)
       Api(GETXBYYSP_getprotobyname, (arg1), 4)
       Api(GETXBYYSP_getprotobynumber, (arg1), 4)
       Api(GETXBYYSP_getservbyname, (arg1, arg2), 8)
       Api(GETXBYYSP_getservbyport, (arg1, arg2), 8)
       Api(GETXBYYSP_WSAAsyncGetHostByAddr, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(GETXBYYSP_WSAAsyncGetHostByName, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GETXBYYSP_WSAAsyncGetProtoByName, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GETXBYYSP_WSAAsyncGetProtoByNumber, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(GETXBYYSP_WSAAsyncGetServByName, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GETXBYYSP_WSAAsyncGetServByPort, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(GETXBYYSP_WSACancelAsyncRequest, (arg1), 4)
       Api(htonl, (arg1), 4)
       Api(htons, (arg1), 4)
       Api(inet_addr, (arg1), 4)
       Api(inet_network, (arg1), 4)
       Api(inet_ntoa, (arg1), 4)
       Api(ioctlsocket, (arg1, arg2, arg3), 12)
       Api(listen, (arg1, arg2), 8)
       Api(MigrateWinsockConfiguration, (arg1, arg2, arg3), 12)
       Api(NPLoadNameSpaces, (arg1, arg2, arg3), 12)
       Api(NSPStartup, (arg1, arg2), 8)
       Api(ntohl, (arg1), 4)
       Api(ntohs, (arg1), 4)
       Api(rcmd, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(recv, (arg1, arg2, arg3, arg4), 16)
       Api(recvfrom, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(rexec, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(rresvport, (arg1), 4)
       Api(s_perror, (arg1, arg2), 8)
       Api(select, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(send, (arg1, arg2, arg3, arg4), 16)
       Api(sendto, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(sethostname, (arg1, arg2), 8)
  AnsiWide(SetService, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(setsockopt, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(shutdown, (arg1, arg2), 8)
       Api(socket, (arg1, arg2, arg3), 12)
       Api(TransmitFile, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(WSAAsyncGetHostByAddr, (arg1, arg2, arg3, arg4, arg5, arg6, arg7), 28)
       Api(WSAAsyncGetHostByName, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WSAAsyncGetProtoByName, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WSAAsyncGetProtoByNumber, (arg1, arg2, arg3, arg4, arg5), 20)
       Api(WSAAsyncGetServByName, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(WSAAsyncGetServByPort, (arg1, arg2, arg3, arg4, arg5, arg6), 24)
       Api(WSAAsyncSelect, (arg1, arg2, arg3, arg4), 16)
       Api(WSACancelAsyncRequest, (arg1), 4)
       Api(WSACancelBlockingCall, (), 0)
       Api(WSACleanup, (), 0)
       Api(WSAGetLastError, (), 0)
       Api(WSAIsBlocking, (), 0)
       Api(WSApSetPostRoutine, (arg1), 4)
       Api(WSARecvEx, (arg1, arg2, arg3, arg4), 16)
       Api(WSASetBlockingHook, (arg1), 4)
       Api(WSASetLastError, (arg1), 4)
       Api(WSAStartup, (arg1, arg2), 8)
       Api(WSAUnhookBlockingHook, (), 0)
       Api(WSCRegisterWS2, (arg1, arg2), 8)
EndImport
